Repository kubesphere/console, pull requests merged in 2019-12, with the labels that each got.

#23 test: Add e2e tests
  cypress.json
  cypress/integration/clusters/accounts/index.spec.js
  cypress/integration/clusters/clusterroles/index.spec.js
  cypress/integration/clusters/projects/index.spec.js
  cypress/integration/clusters/storageclasses/detail.spec.js
  cypress/integration/clusters/storageclasses/index.spec.js
  cypress/integration/clusters/workspaces/index.spec.js
  cypress/integration/projects/deployments/detail.spec.js
  cypress/integration/projects/deployments/index.spec.js
  cypress/integration/workspaces/devops.spec.js
  cypress/integration/workspaces/members.spec.js
  cypress/integration/workspaces/projects.spec.js
  cypress/integration/workspaces/repos.spec.js
  package.json
  src/components/Base/Panel/index.jsx
  src/components/Modals/Delete/index.jsx
  src/core/index.js
  src/pages/projects/containers/Deployments/Detail/index.jsx
  yarn.lock
Labels: testing

#25 chore: Add docker development scripts
  .dockerignore
  Makefile
  README.md
  docker-compose.builder.yaml
  docker-compose.yaml
  docs/development-with-docker.md
  package.json
  scripts/webpack.dev.js
Labels: size/L

#29 fix: fix pipeline not update when parameters changed
  src/stores/devops/pipelines.js
Labels: approved, lgtm, size/M

#30 fix: fix create image builder failed when used special charactors
  src/components/Forms/CICDs/paramsModal.jsx
  src/stores/s2i/builder.js
Labels: approved, lgtm, size/XS

#34 fix download b2i file error
  server/config.yaml
  server/proxy.js
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageSearch/index.jsx
  src/locales/zh/devops.js
Labels: approved, lgtm, size/M

#40 Update readme
  README.md
  docs/access-backend.md
Labels: approved, documentation, lgtm, size/S

#36 fix(container-terminal): component crash when ws error before term init
  src/components/Modals/ContianerTerminal/index.jsx
  src/components/Modals/KubeCtl/index.jsx
  src/components/Terminal/terminal.jsx
  src/stores/terminal.js
Labels: approved, lgtm, size/M

#37 fix: create b2i service when push image to private image repo bug
  src/components/Forms/ImageBuilder/B2IForm/index.jsx
  src/components/Forms/ImageBuilder/S2IForm/index.jsx
  src/stores/service.js
Labels: approved, lgtm, size/M

#44 Update dev doc
  README.md
  docs/access-backend.md
  docs/development-with-docker.md
Labels: approved, documentation, lgtm, size/S

#45 fix filled wrong default-value when edit hpa
  src/pages/devops/components/Pipeline/Card/detail.jsx
  src/stores/devops/pipelines.js
  src/utils/devops.js
  src/utils/devops.test.js
  src/utils/object.mapper.js
Labels: approved, lgtm, size/M

#50 fix: Fix detail page actions
  src/pages/clusters/containers/MonitoringCenter/Alerting/Policy/Detail/index.jsx
  src/pages/clusters/containers/Roles/Detail/index.jsx
  src/pages/devops/containers/Cridential/detail/index.jsx
  src/pages/projects/containers/Routes/Detail/index.jsx
  src/pages/projects/containers/Services/Detail/index.jsx
  src/pages/projects/containers/StatefulSets/Detail/index.jsx
Labels: approved, bug, lgtm, size/S

#52 refactor: use base64 format in mail config api
  src/stores/notification/mailService.js
Labels: approved, lgtm, size/XS

#46 chore: Update webpack to resolve serialize-javascript security warning
  package.json
  yarn.lock
Labels: approved, size/L

#53 chore: Update github actions
  .github/workflows/clear.yaml
  .github/workflows/main.yaml
Labels: approved

#54 update: Update ace editor
  package.json
  scripts/webpack.dev.js
  scripts/webpack.e2e.js
  scripts/webpack.prod.js
  src/components/Base/CodeEditor/AceEditor.jsx
  yarn.lock
Labels: approved, lgtm, size/M

#55 fix: miss sort filter in log query api
  src/components/Modals/LogSearch/Logging/Detail/index.jsx
  src/components/Modals/LogSearch/Logging/Detail/index.scss
  src/stores/logging/query.js
Labels: approved, lgtm, size/S

#63 fix: sort pipeline steps error
  src/pages/devops/components/Pipeline/StepsEditor/index.jsx
Labels: approved, lgtm, size/XS

#58 fix: Fix pod schedule page styles error
  src/components/Base/Text/index.jsx
  src/components/Cards/Volumes/Item.jsx
  src/components/Cards/Volumes/index.scss
  src/pages/projects/containers/Pods/Detail/ScheduleInfo/index.jsx
  src/pages/projects/containers/Pods/Detail/ScheduleInfo/index.scss
Labels: approved, lgtm, size/M

#66 fix: Replace footer actions with confirm for sub forms in edit-template
  src/components/Base/Card/index.jsx
  src/components/Base/CodeEditor/index.jsx
  src/components/Forms/Base/Confirm/index.jsx
  src/components/Forms/Base/Confirm/index.scss
  src/components/Graph/index.jsx
  src/components/Modals/Edit/Form/index.jsx
  src/components/Modals/Edit/Form/index.scss
  src/components/Modals/Edit/Form/wrapper.jsx
  src/core/containers/Base/Detail/index.jsx
  src/core/index.js
  src/core/layouts/Detail/index.jsx
  src/locales/zh/base.js
  src/pages/apps/components/Lists/AuditRecord/index.jsx
  src/pages/clusters/containers/Workspaces/index.jsx
  src/pages/devops/containers/Pipelines/Detail/PipeLine/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Sider/branch-sider.jsx
  src/pages/devops/containers/Pipelines/Detail/Sider/pipeline-sider.jsx
  src/pages/devops/containers/layout.jsx
  src/pages/projects/components/Cards/ImageRunRecord/Item/index.jsx
  src/pages/projects/containers/Applications/Detail/TrafficManangement/index.jsx
  src/pages/projects/containers/Deployments/Detail/RevisionControl/index.jsx
  src/pages/projects/containers/GrayRelease/Jobs/index.jsx
  src/pages/projects/containers/ImageBuilder/Detail/index.jsx
  src/pages/projects/containers/layout.jsx
  src/pages/workspaces/containers/layout.jsx
Labels: approved, lgtm, size/L
