Repository kubesphere/console, pull requests merged in 2020-01, with the labels that each got.

#68 fix: Fix resource limit compare error
  src/components/Inputs/ResourceLimit/index.jsx
Labels: approved, lgtm, size/XS

#73 fix: add pipeline new status
  src/locales/zh/cicd.js
  src/pages/devops/components/PipelineStatus/card.jsx
  src/pages/devops/components/Status/index.scss
  src/utils/status.js
Labels: approved, lgtm, size/S

#71 fix: show empty card instead of container log if container is creating
  server/libs/request.base.js
  src/components/Modals/ContainerLog/index.jsx
  src/pages/projects/containers/Pods/Containers/Logs.jsx
  src/utils/request.js
Labels: approved, lgtm, size/M

#70 fix: Fix workload select
  src/components/Forms/Service/ServiceSettings/SelectorsInput/index.jsx
  src/components/Forms/Service/ServiceSettings/SelectorsInput/index.scss
  src/components/Forms/Service/ServiceSettings/WorkloadSelect/index.jsx
  src/components/Forms/Service/ServiceSettings/WorkloadSelect/index.scss
  src/components/Forms/Workload/VolumeSettings/index.jsx
  src/pages/clusters/containers/MonitoringCenter/Monitoring/Cluster/Overview/index.jsx
Labels: approved, lgtm, size/M

#74 fix: delete selected item failed when list update
  src/stores/base.js
Labels: approved, lgtm, size/XS

#78 fix(docker): docker miss application property when the pod have
  src/stores/container.js
Labels: approved, lgtm, size/XS

#76 feat: Support init containers in workload create
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerList/Card.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerList/index.jsx
  src/components/Forms/Workload/ContainerSettings/index.jsx
  src/locales/zh/workload.js
Labels: approved, enhancement, lgtm, size/L

#75 update: Update container probe parameters
  src/components/Forms/Workload/ContainerSettings/ContainerForm/HealthChecker/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ProbeForm/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ProbeInput/index.scss
  src/locales/en/workload.js
  src/locales/zh/workload.js
Labels: approved, enhancement, lgtm

#72 update: Add security context for pod and container
  src/components/Base/Alert/index.jsx
  src/components/Base/CheckableText/index.jsx
  src/components/Base/CheckableText/index.scss
  src/components/Base/index.js
  src/components/Forms/Workload/ContainerSettings/ContainerForm/SecurityContext/AccessControl/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/SecurityContext/AccessControl/index.scss
  src/components/Forms/Workload/ContainerSettings/ContainerForm/SecurityContext/Capabilities/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/SecurityContext/Capabilities/index.scss
  src/components/Forms/Workload/ContainerSettings/ContainerForm/SecurityContext/SELinuxOptions/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/SecurityContext/SELinuxOptions/index.scss
  src/components/Forms/Workload/ContainerSettings/ContainerForm/SecurityContext/UserGroup/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/SecurityContext/UserGroup/index.scss
  src/components/Forms/Workload/ContainerSettings/ContainerForm/SecurityContext/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/SecurityContext/index.scss
  src/components/Forms/Workload/ContainerSettings/ContainerForm/index.jsx
  src/components/Forms/Workload/ContainerSettings/PodSecurityContext/index.jsx
  src/components/Forms/Workload/ContainerSettings/PodSecurityContext/index.scss
  src/components/Forms/Workload/ContainerSettings/index.jsx
  src/locales/en/base.js
  src/locales/en/workload.js
  src/locales/zh/base.js
  src/locales/zh/workload.js
Labels: approved, enhancement, lgtm, size/XL

#69 fix: Fix app service protocol error
  src/pages/projects/components/Cards/AppComponents/Item.jsx
Labels: approved, lgtm, size/XS

#80 fix/lose-default-interval-in-monitor-resource-page
  src/pages/clusters/containers/MonitoringCenter/Monitoring/Resource/Usage/Physical/index.jsx
  src/pages/clusters/containers/MonitoringCenter/Monitoring/Resource/Usage/Virtual/index.jsx
Labels: approved, lgtm, size/XS

#81 refactor: change default image features value
  src/utils/constants.js
Labels: approved, lgtm, size/XS

#84 fix: Fix workspace search order
  src/pages/clusters/containers/Workspaces/index.jsx
Labels: approved, lgtm, size/XS

#87 chore: Update workflow
  .github/workflows/main.yaml
Labels: approved, size/XS

#86 fix: filter s2i system roles
  src/stores/role.js
Labels: approved, lgtm, size/XS

#79 refactor: use -1 for infinity
  src/stores/base.js
Labels: approved, lgtm, size/XS

#91 fix: pipeline branch list wrong total number
  src/stores/devops/pipelines.js
Labels: approved, lgtm, size/XS

#96 Fix/volume status filter no work
  src/pages/projects/containers/Volumes/index.jsx
  src/stores/role.js
  src/utils/constants.js
Labels: approved, lgtm, size/S

#99 fix: Fix helm values yaml loading
  src/components/Forms/AppTemplate/index.jsx
  src/pages/appStore/containers/App/index.jsx
  src/pages/apps/components/Forms/AppDeploy/index.jsx
  src/pages/apps/containers/Templates/Detail/index.jsx
  src/utils/app.js
Labels: approved, lgtm, size/M

#95 fix: check token validate before request send
  server/controllers/session.js
  src/utils/request.js
Labels: approved, lgtm, size/S

#97 fix: Fix statefulset service edit if serviceName is empty
  src/pages/projects/containers/StatefulSets/Detail/ResourceStatus.jsx
  src/stores/workload/resource.js
Labels: approved, lgtm, size/S

#98 update: Update ingress gateway tips and workload counts
  src/components/Tables/Base/index.scss
  src/core/containers/Base/List/index.jsx
  src/pages/projects/containers/CronJobs/index.jsx
  src/pages/projects/containers/Jobs/index.jsx
  src/pages/projects/containers/Routes/index.jsx
  src/pages/projects/containers/Routes/index.scss
  src/pages/projects/containers/Workloads/Base.jsx
  src/pages/projects/containers/Workloads/index.jsx
  src/scss/lego.custom.scss
  src/stores/workload/index.js
Labels: approved, lgtm, size/L

#100 fix: volume detail page report 404 when dependent storage class deleted
  src/locales/en/storage.js
  src/locales/zh/storage.js
  src/pages/clusters/containers/Infrastructure/StorageClasses/Detail/index.jsx
  src/pages/clusters/containers/Infrastructure/StorageClasses/index.jsx
  src/pages/projects/containers/Volumes/Detail/index.jsx
  src/utils/object.mapper.js
Labels: approved, lgtm, size/M

#102 fix: Fix service base info form no apps show
  src/components/Forms/Service/BaseInfo/index.jsx
Labels: approved, lgtm, size/XS

#101 update: Update default language to english
  server/components/locale.js
  server/config.yaml
  src/core/i18n.js
  src/utils/index.js
  src/utils/index.test.js
Labels: approved, lgtm, size/S

#106 fix: correct s2i deployment status text
  src/locales/zh/s2i.js
  src/utils/constants.js
Labels: approved, lgtm, size/XS

#107 fix: fix image registry url judgement
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageSearch/DropdownContent.jsx
Labels: approved, lgtm, size/XS
