Repository kubesphere/console, pull requests merged in 2020-07, with the labels that each got.

#533 fix: Fix project create modal clusters select
  src/actions/project.js
  src/components/Modals/ProjectCreate/index.jsx
  src/locales/zh/project.js
Labels: approved, kind/bug, size/L

#534 correct workspace role description
  src/locales/en/role.js
  src/locales/zh/role.js
Labels: approved, area/documentation, lgtm

#535 fix: Fix ingress host with aws lb
  src/components/Forms/Route/RouteRules/RuleForm/index.jsx
  src/pages/clusters/actions/cluster.js
  src/pages/projects/components/Modals/CreateApp/Routes/RuleForm/index.jsx
  src/pages/projects/components/Modals/CreateApp/index.jsx
  src/utils/object.mapper.js
Labels: approved, kind/bug, size/M

#537 fix: Fix project create not refresh
  src/pages/workspaces/containers/Projects/index.jsx
Labels: approved, kind/bug, size/XS

#538 fix: Sort role templates by aliasName
  src/components/Modals/EditAuthorization/CheckItem.jsx
  src/components/Modals/EditAuthorization/index.jsx
  src/components/Modals/EditAuthorization/index.scss
Labels: approved, kind/bug, size/S

#539 fix: Show only fedmanaged workspaces in cluster visibility
  src/pages/clusters/actions/cluster.js
  src/pages/clusters/components/Modals/ClusterVisibility/index.jsx
  src/pages/clusters/containers/Visibility/index.jsx
Labels: approved, kind/bug, size/S

#527 Standardize word capitalizaion and fix typo
  src/locales/en/devops.js
  src/locales/en/workload.js
  src/locales/zh/cicd.js
Labels: approved, kind/documentation, lgtm, size/XS

#542 fix: Fix prob input issues
  src/components/Forms/Workload/ContainerSettings/ContainerForm/HealthChecker/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ProbeForm/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ProbeInput/index.jsx
  src/components/Forms/Workload/ContainerSettings/index.jsx
Labels: approved, kind/bug, size/S

#543 chore: Update access backend doc
  docs/access-backend.md
Labels: approved, kind/documentation, lgtm, size/S

#546 chore: Update base dev image
  docker-compose.builder.yaml
  docker-compose.yaml
Labels: approved, kind/bug, lgtm, size/XS

#551 fix:Fix empty form display in pipeline
  src/pages/devops/containers/Pipelines/index.jsx
Labels: approved, lgtm, size/XS

#550 Minor punctuation and typo fix
  src/locales/en/role.js
  src/locales/en/storage.js
  src/locales/en/workload.js
  src/locales/zh/role.js
  src/locales/zh/workload.js
Labels: approved, kind/documentation, lgtm, size/S

#552 fix: Fix project create error
  src/locales/en/cluster.js
  src/locales/en/workspace.js
  src/locales/zh/workspace.js
  src/pages/clusters/containers/Clusters/index.jsx
  src/pages/workspaces/components/ResourceTable/index.jsx
  src/pages/workspaces/containers/Clusters/index.jsx
  src/pages/workspaces/containers/Overview/ResourceUsage/index.jsx
  src/pages/workspaces/containers/Overview/UsageRanking/index.jsx
  src/stores/project.js
Labels: approved, kind/bug, lgtm, size/M

#573 fix: Fix federated namespace operations
  src/actions/project.js
  src/components/HOCs/withList.js
  src/components/Modals/ProjectCreate/index.jsx
  src/components/Tables/Base/index.jsx
  src/locales/zh/cluster.js
  src/locales/zh/project.js
  src/pages/clusters/containers/Monitor/Resource/Ranking/Project/Table/index.jsx
  src/pages/fedprojects/containers/Deployments/index.jsx
  src/pages/workspaces/containers/FedProjects/index.jsx
  src/pages/workspaces/containers/Projects/index.jsx
  src/stores/cluster/index.js
  src/stores/federated.list.js
  src/stores/project.js
  src/utils/constants.js
  src/utils/object.mapper.js
Labels: approved, kind/bug, lgtm, size/L

#563 fix: Clear the filter in the table after selecting the project
  src/pages/clusters/components/ResourceTable/index.jsx
Labels: approved, kind/bug, lgtm, size/XS

#575 fix: Fix statfulset createc in cluster
  src/actions/workload.js
Labels: approved, kind/bug, lgtm, size/S

#576 fix: Fix log search in single cluster mode.
  src/components/Modals/AuditingSearch/Auditing/Detail/index.jsx
  src/components/Modals/AuditingSearch/Auditing/Home/index.jsx
  src/components/Modals/EventSearch/Event/Detail/index.jsx
  src/components/Modals/EventSearch/Event/Home/index.jsx
  src/components/Modals/LogSearch/Logging/Home/index.jsx
  src/components/Modals/LogSearch/Logging/Search/index.jsx
Labels: approved, kind/bug, lgtm, size/L

#557 Add multicluster tip UI and fix log collection wording
  src/locales/en/project.js
Labels: approved, kind/documentation, lgtm, size/XS

#577 fix:Fix the url returned to the previous page in the network strategy
  src/pages/projects/containers/Network/Policies/Detail/index.jsx
Labels: approved, kind/bug, lgtm, size/XS

#579 fix: Fix some issues
  src/actions/project.js
  src/components/Cards/Containers/EnvVariables/index.jsx
  src/components/Forms/Workload/VolumeSettings/MountConfig/index.jsx
  src/components/Forms/Workload/VolumeSettings/index.jsx
  src/components/Modals/Create/Code/index.jsx
  src/core/containers/Base/Detail/EnvVariables/index.jsx
  src/pages/clusters/containers/Workload/Jobs/index.jsx
  src/stores/monitoring/base.js
  src/stores/workload/env.js
  src/utils/object.mapper.js
Labels: approved, kind/bug, lgtm, size/M

#580 fix: Fix statefulset edit config template
  src/actions/workload.js
  src/components/Forms/CronJob/BaseInfo/index.jsx
  src/components/Forms/Service/BaseInfo/index.jsx
  src/components/Forms/Workload/BaseInfo/index.jsx
  src/pages/projects/components/Modals/ConfigTemplate/config.js
  src/utils/yaml.js
Labels: approved, kind/bug, lgtm, size/M

#581 Chore: Update cluster locales
  src/locales/en/cluster.js
  src/locales/zh/cluster.js
Labels: approved, lgtm, size/S

#582 fix: Fix federated resources create and list status
  server/config.yaml
  src/actions/project.js
  src/components/Base/Indicator/index.scss
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/index.jsx
  src/components/Forms/Workload/ContainerSettings/index.jsx
  src/components/Forms/Workload/VolumeSettings/MountConfig/index.jsx
  src/components/Forms/Workload/VolumeSettings/index.jsx
  src/components/Tables/Base/Empty/index.scss
  src/locales/en/role.js
  src/locales/en/secret.js
  src/locales/zh/project.js
  src/locales/zh/role.js
  src/pages/fedprojects/containers/Applications/index.jsx
  src/pages/fedprojects/containers/BaseInfo/index.jsx
  src/pages/fedprojects/containers/ConfigMaps/index.jsx
  src/pages/fedprojects/containers/Deployments/index.jsx
  src/pages/fedprojects/containers/Routes/index.jsx
  src/pages/fedprojects/containers/Secrets/index.jsx
  src/pages/fedprojects/containers/Services/index.jsx
  src/pages/fedprojects/containers/StatefulSets/index.jsx
  src/pages/fedprojects/containers/Volumes/index.jsx
  src/utils/constants.js
  src/utils/object.mapper.js
Labels: approved, kind/bug, lgtm, size/L

#587 fix: Fix cluster info
  src/components/Clusters/ClusterTitle/index.jsx
  src/locales/en/base.js
  src/locales/zh/application.js
  src/locales/zh/base.js
  src/locales/zh/cluster.js
  src/locales/zh/workload.js
  src/pages/clusters/containers/BaseInfo/index.scss
  src/pages/clusters/containers/Clusters/AddCluster/BaseInfo/index.jsx
Labels: approved, kind/bug, lgtm, size/M

#590 update: Update op application API
  src/actions/openpitrix.js
  src/pages/projects/containers/Applications/OPApps.jsx
  src/pages/projects/containers/Overview/Applications/index.jsx
  src/stores/openpitrix/app.js
  src/stores/openpitrix/application.js
Labels: approved, kind/api-change, lgtm, size/M

#600 fix: Fix some issues
  server/config.yaml
  src/actions/resource.delete.js
  src/actions/service.js
  src/components/Cards/RankTable/NodeTable/index.jsx
  src/components/Forms/Service/AdvanceSettings/Metadata/index.jsx
  src/components/Forms/Service/AdvanceSettings/index.jsx
  src/components/Forms/Service/BaseInfo/index.jsx
  src/components/Forms/Service/ContainerSetting/ContainerForm/index.jsx
  src/components/Forms/Service/ContainerSetting/ContainerSetting/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/Ports/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/index.jsx
  src/components/Inputs/ContainerServicePort/index.jsx
  src/components/Inputs/ServicePort/index.jsx
  src/components/Modals/ProjectSelect/index.jsx
  src/locales/zh/role.js
  src/pages/access/containers/Workspaces/index.jsx
  src/pages/clusters/containers/BaseInfo/index.jsx
  src/pages/fedprojects/containers/Deployments/index.jsx
  src/pages/fedprojects/containers/Services/Detail/ServiceAccess/ClusterService/index.jsx
  src/pages/fedprojects/containers/Services/Detail/ServiceAccess/index.jsx
  src/pages/fedprojects/containers/Services/index.jsx
  src/pages/projects/components/Modals/ServiceCreate/index.jsx
  src/pages/projects/components/Modals/ServiceGatewaySetting/index.jsx
  src/pages/workspaces/components/Modals/WorkspaceSelect/index.jsx
  src/pages/workspaces/components/Selector/index.jsx
  src/utils/cluster.js
Labels: approved, kind/bug, lgtm, size/L

#616 fix: Fix project create redirect
  server/config.yaml
  src/actions/project.js
  src/components/Modals/EditAuthorization/constants.js
  src/locales/en/role.js
  src/locales/zh/role.js
  src/pages/workspaces/containers/BaseInfo/index.jsx
  src/pages/workspaces/containers/FedProjects/index.jsx
  src/pages/workspaces/containers/Projects/index.jsx
Labels: approved, kind/bug, lgtm, size/M

#619 fix: Fix some issues
  src/components/Forms/CronJob/BaseInfo/index.jsx
  src/components/Forms/Route/AdvanceSettings/Metadata/index.jsx
  src/components/Forms/Route/RouteRules/RuleList/index.jsx
  src/components/Forms/Service/AdvanceSettings/Metadata/index.jsx
  src/components/Forms/Service/BaseInfo/index.jsx
  src/components/Forms/Volume/AdvanceSettings/Metadata/index.jsx
  src/components/Forms/Workload/AdvanceSettings/Metadata/index.jsx
  src/components/Forms/Workload/BaseInfo/index.jsx
  src/components/HOCs/withList.js
  src/components/Modals/Create/Code/index.jsx
  src/components/Modals/Create/index.jsx
  src/components/Modals/Delete/index.scss
  src/core/containers/Base/Detail/Page/index.scss
  src/pages/fedprojects/containers/Applications/index.jsx
  src/pages/fedprojects/containers/ConfigMaps/index.jsx
  src/pages/fedprojects/containers/Deployments/index.jsx
  src/pages/fedprojects/containers/Routes/index.jsx
  src/pages/fedprojects/containers/Secrets/index.jsx
  src/pages/fedprojects/containers/Services/index.jsx
  src/pages/fedprojects/containers/StatefulSets/index.jsx
  src/pages/fedprojects/containers/Volumes/index.jsx
  src/pages/workspaces/containers/FedProjects/index.jsx
  src/stores/federated.js
  src/stores/federated.list.js
  src/utils/constants.js
Labels: approved, kind/bug, lgtm, size/L

#620 fix: Fix workspace manager edit
  src/pages/workspaces/components/Modals/EditBasicInfo/index.jsx
Labels: approved, kind/bug, lgtm, size/XS

#627 fix: Fix project create validation
  src/components/Inputs/ProjectSelect/index.jsx
  src/components/Modals/ProjectCreate/index.jsx
  src/pages/clusters/containers/Nodes/Detail/index.jsx
  src/pages/clusters/containers/Workload/Deployments/index.jsx
  src/pages/clusters/containers/Workload/Pods/index.jsx
  src/pages/projects/containers/Volumes/Detail/index.jsx
Labels: approved, kind/bug, lgtm, size/M

#631 fix: add cluster param to getCrumb
  src/stores/devops/base.js
  src/stores/devops/pipelines.js
Labels: approved, lgtm, size/S

#634 fix: Fix 404 redirect if resource not found
  src/pages/devops/containers/layout.jsx
  src/pages/fedprojects/containers/Routes/Detail/ResourceStatus/Rule/index.jsx
  src/pages/projects/App.jsx
  src/pages/projects/containers/CronJobs/index.jsx
  src/stores/cluster/index.js
  src/stores/workload/env.js
  src/stores/workspace.js
Labels: approved, kind/bug, lgtm, size/M

#635 fix: Disable multi cluster resource selection in cluster.
  src/actions/openpitrix.js
  src/pages/clusters/containers/ConfigMaps/index.jsx
  src/pages/clusters/containers/Secrets/index.jsx
  src/pages/clusters/containers/Storage/Volumes/index.jsx
  src/pages/clusters/containers/Workload/Deployments/index.jsx
  src/pages/clusters/containers/Workload/Routes/index.jsx
  src/pages/clusters/containers/Workload/Services/index.jsx
  src/pages/clusters/containers/Workload/StatefulSets/index.jsx
  src/pages/projects/components/Modals/RepoApp/Apps/index.jsx
  src/pages/workspaces/containers/Apps/index.jsx
Labels: approved, kind/bug, lgtm, size/M

#637 fix: Fix Credential role
  src/pages/devops/containers/Credential/detail/index.jsx
Labels: approved, lgtm, size/S

#639 fix: Fix devops 404 error
  src/pages/devops/containers/layout.jsx
Labels: approved, kind/bug, lgtm, size/XS

#606 Fix login page and role desc en wording
  server/controllers/session.js
  server/controllers/view.js
  server/locales/en.properties
  server/locales/zh.properties
  src/locales/en/role.js
  src/stores/devops/scm.js
Labels: approved, kind/documentation, lgtm, size/M

#645 fix: Fix custom monitor with cluster prefix
  src/pages/projects/containers/CustomMonitoring/CreateDashborad/index.jsx
  src/pages/projects/containers/CustomMonitoring/index.jsx
  src/stores/customMonitorDashboard.js
  src/stores/monitoring/custom/monitor.js
  src/stores/monitoring/custom/template.js
Labels: approved, kind/bug, lgtm, size/M

#642 fix: Fix workload mount volume readonly
  src/components/Forms/Workload/VolumeSettings/AddExistVolumes/index.jsx
  src/components/Forms/Workload/VolumeSettings/index.jsx
Labels: approved, kind/bug, lgtm, size/XS

#643 fix: Fix authorized users list
  src/pages/access/containers/Roles/Detail/AuthorizedUsers/index.jsx
  src/pages/access/containers/Roles/Detail/AuthorizedUsers/index.scss
Labels: approved, kind/bug, lgtm, size/M

#644 fix: Fix workload volume name edit error
  src/components/Forms/Workload/VolumeSettings/AddTemporary/index.jsx
  src/components/Forms/Workload/VolumeSettings/index.jsx
Labels: approved, kind/bug, lgtm, size/S

#646 fix: Fix api in custom monitor detail
  src/pages/projects/containers/CustomMonitoring/EditDashborad/index.jsx
  src/pages/projects/containers/CustomMonitoring/index.jsx
Labels: approved, kind/bug, lgtm, size/XS

#649 Capitalization fix and minor wording adjustment
  src/components/Forms/LoggingCollection/Status/index.jsx
  src/components/Modals/EditAuthorization/constants.js
  src/locales/en/logging.js
  src/locales/zh/app.js
  src/locales/zh/project.js
  src/locales/zh/role.js
  src/pages/apps/containers/Store/Detail/AuditRecord/index.jsx
  src/pages/fedprojects/containers/AdvancedSettings/LogCollection/index.jsx
  src/pages/projects/containers/AdvancedSettings/LogCollection/index.jsx
Labels: approved, kind/documentation, lgtm, size/M

#651 fix: Fix network policy rule displays error && validate rules
  src/components/Modals/Network/Policies/IpBlock.jsx
  src/pages/projects/containers/Network/Policies/RuleInfo/index.jsx
Labels: approved, kind/bug, lgtm, size/M

#653 Add role identifier desc and fix role creation wording
  src/locales/en/role.js
  src/locales/en/user.js
  src/locales/zh/role.js
Labels: approved, kind/documentation, lgtm, size/S

#652 fix: Fix link in project ranking table.
  src/components/Base/Avatar/index.scss
  src/pages/clusters/containers/Monitor/Resource/Ranking/Project/Table/index.jsx
  src/pages/clusters/containers/Monitor/Resource/Ranking/Project/index.jsx
  src/pages/clusters/containers/Monitor/Resource/routes.js
  src/pages/workspaces/containers/Overview/UsageRanking/index.jsx
Labels: approved, kind/bug, lgtm, size/M

#661 fix: Using PUT instead of PATCH when update yaml
  src/actions/resource.edit.js
Labels: approved, kind/bug, lgtm, size/XS

#655 fix: Fix some bugs in App template
  src/actions/openpitrix.js
  src/locales/zh/app.js
  src/pages/appStore/components/AppInfo/ImageSlider/index.jsx
  src/pages/appStore/components/AppInfo/index.jsx
  src/pages/appStore/components/AppList/index.jsx
  src/pages/appStore/containers/Home/index.jsx
  src/pages/apps/components/Cards/ScreenshotsEdit/index.jsx
  src/pages/apps/components/Modals/AppEdit/index.jsx
  src/pages/workspaces/containers/Apps/Detail/index.jsx
  src/pages/workspaces/containers/Apps/index.jsx
  src/stores/openpitrix/app.js
Labels: approved, kind/bug, lgtm, size/L

#660 update: Update alerting rule metrics
  src/configs/alerting/metrics/workload.js
Labels: approved, lgtm, size/S

#663 fix: Fix labels mission in statfulset create
  src/utils/constants.js
Labels: approved, kind/bug, lgtm, size/XS

#656 Chore: Update platform settings since the log collector in under clus…
  src/locales/en/base.js
  src/locales/zh/base.js
Labels: approved, lgtm, size/XS

#664 fix: Hide custom columns if no hideableColumns
  src/components/Tables/Base/index.jsx
Labels: approved, kind/bug, lgtm, size/XS

#668 fix: Disable remove system-workspace in cluster visibility
  src/pages/clusters/components/Modals/ClusterVisibility/index.jsx
Labels: approved, kind/bug, lgtm, size/XS

#669 fix: Fix daemonset ready pods
  src/pages/projects/components/WorkloadStatus/index.jsx
  src/utils/status.js
  src/utils/workload.js
Labels: approved, kind/bug, lgtm, size/XS

#670 fix: Fix project members enable actions
  src/pages/projects/containers/Members/index.jsx
Labels: approved, kind/bug, lgtm, size/XS

#671 fix replica deployment wording
  src/components/Forms/Workload/ContainerSettings/PodAffinity/index.jsx
  src/locales/zh/workload.js
Labels: approved, kind/documentation, lgtm, size/S

#667 feat: optimize network policy rule direction default status
  src/components/Modals/Network/Policies/IpBlock.jsx
  src/components/Modals/Network/Policies/index.scss
  src/locales/en/network.js
  src/locales/zh/network.js
  src/pages/projects/containers/Network/Policies/RuleInfo/index.jsx
Labels: approved, kind/feature, lgtm, size/M

#674 fix: Fix check item action in EditAuthorization
  src/components/Modals/EditAuthorization/CheckItem.jsx
  src/pages/projects/components/Modals/RollBack/index.jsx
Labels: approved, kind/bug, lgtm, size/S

#676 fix: Fix delete initContainer in ContainerSettings
  src/components/Forms/Workload/ContainerSettings/ContainerList/Card.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerList/index.jsx
  src/components/Forms/Workload/ContainerSettings/index.jsx
Labels: approved, kind/bug, lgtm, size/M

#679 Chore(cn): minor update
  src/locales/zh/cluster.js
Labels: approved, lgtm, size/XS

#682 fix: Fix repo delete
  src/stores/openpitrix/repo.js
Labels: approved, kind/bug, lgtm, size/XS

#680 fix: Fix network policy some bugs
  src/pages/clusters/containers/Network/Policies/index.jsx
  src/pages/projects/containers/Network/Policies/Detail/Viewer/index.jsx
Labels: approved, kind/bug, lgtm, size/S

#677 fix: Fix multicluster resources
  src/components/Forms/Workload/ClusterDiffSettings/ClustersMapper/index.jsx
  src/components/Forms/Workload/ClusterDiffSettings/index.jsx
  src/components/Forms/Workload/ContainerSettings/ClusterReplicasControl/index.jsx
  src/components/Forms/Workload/ContainerSettings/index.jsx
  src/pages/fedprojects/components/ClusterWorkloadStatus/index.jsx
  src/pages/fedprojects/components/FedWorkloadStatus/index.jsx
  src/pages/fedprojects/containers/Deployments/Detail/ResourceStatus/index.jsx
  src/pages/fedprojects/containers/Deployments/Detail/index.jsx
  src/pages/fedprojects/containers/Deployments/index.jsx
  src/pages/fedprojects/containers/Services/Detail/ResourceStatus/index.jsx
  src/pages/fedprojects/containers/Services/Detail/ServiceAccess/index.jsx
  src/pages/fedprojects/containers/Services/Detail/index.jsx
  src/pages/fedprojects/containers/Services/index.jsx
  src/pages/fedprojects/containers/StatefulSets/Detail/index.jsx
  src/pages/fedprojects/containers/StatefulSets/index.jsx
  src/pages/projects/components/Modals/ServiceDelete/index.jsx
  src/pages/projects/components/Modals/WorkloadDelete/index.jsx
Labels: approved, kind/bug, lgtm, size/L

#681 fix: Fix cluster resource create mission namespace
  src/actions/configmap.js
  src/actions/secret.js
  src/actions/service.js
  src/components/Forms/Service/ServiceSettings/SelectorsInput/index.jsx
  src/components/Forms/Service/ServiceSettings/WorkloadSelect/index.jsx
  src/pages/clusters/containers/ConfigMaps/index.jsx
  src/pages/clusters/containers/Secrets/index.jsx
  src/pages/clusters/containers/Workload/Services/index.jsx
Labels: approved, lgtm, size/M

#683 fix: Fix some issues
  src/components/Forms/Workload/VolumeSettings/MountConfig/index.jsx
  src/locales/en/app.js
  src/locales/zh/app.js
  src/pages/devops/containers/Credential/credentialModal.jsx
Labels: approved, kind/api-change, lgtm, size/M

#678 fix: Fix name description
  src/locales/en/application.js
  src/locales/en/base.js
  src/locales/en/service.js
  src/locales/en/workload.js
  src/locales/zh/application.js
  src/locales/zh/base.js
  src/locales/zh/workload.js
Labels: approved, kind/bug, lgtm, size/M

#686 fix: Fix cluster replicas control
  src/components/Forms/Workload/ContainerSettings/ClusterReplicasControl/index.jsx
Labels: approved, kind/bug, lgtm, size/XS

#689 fix: Fix workspace clusters select
  server/config.yaml
  src/components/Clusters/ClusterTitle/index.jsx
  src/components/Forms/AppDeploy/BasicInfo/Placement/index.jsx
  src/components/Modals/DevOpsCreate/index.jsx
  src/components/Modals/ProjectCreate/index.jsx
  src/components/Modals/ProjectCreate/index.scss
  src/locales/zh/service.js
  src/locales/zh/workload.js
  src/pages/clusters/components/StatusReason/index.jsx
  src/pages/workspaces/components/ResourceTable/ClusterSelect/index.jsx
  src/pages/workspaces/containers/BaseInfo/index.jsx
  src/pages/workspaces/containers/DevOps/index.jsx
  src/pages/workspaces/containers/Overview/Clusters/Card.jsx
  src/pages/workspaces/containers/Overview/Clusters/index.jsx
  src/pages/workspaces/containers/Overview/Clusters/index.scss
  src/pages/workspaces/containers/Overview/ResourceUsage/Physical/index.jsx
  src/pages/workspaces/containers/Overview/ResourceUsage/Virtual/index.jsx
  src/pages/workspaces/containers/Overview/ResourceUsage/Virtual/index.scss
  src/pages/workspaces/containers/Overview/ResourceUsage/index.jsx
  src/pages/workspaces/containers/Overview/ResourceUsage/index.scss
  src/pages/workspaces/containers/Overview/UsageRanking/index.jsx
  src/pages/workspaces/containers/Overview/index.jsx
  src/pages/workspaces/containers/Projects/index.jsx
  src/pages/workspaces/routes/index.js
  src/pages/workspaces/routes/overview.js
  src/stores/workspace.js
Labels: approved, lgtm, size/XL

#690 fix: Fix network policy search
  src/pages/clusters/containers/Network/Policies/index.jsx
Labels: approved, kind/bug, lgtm, size/XS

#691 fix persistentvolumeclaims not found
  src/components/Base/TextArea/index.jsx
  src/stores/container.js
Labels: approved, kind/bug, lgtm, size/S

#693 add : Add tc folder. update: Modify tc language options.
  server/config.yaml
  src/core/i18n.js
  src/locales/tc/alerting.js
  src/locales/tc/app.js
  src/locales/tc/app_repo.js
  src/locales/tc/app_store.js
  src/locales/tc/app_template.js
  src/locales/tc/application.js
  src/locales/tc/base.js
  src/locales/tc/cicd.js
  src/locales/tc/cluster.js
  src/locales/tc/component.js
  src/locales/tc/configmap.js
  src/locales/tc/crd.js
  src/locales/tc/dashboard.js
  src/locales/tc/devops.js
  src/locales/tc/grayrelease.js
  src/locales/tc/index.js
  src/locales/tc/ingress.js
  src/locales/tc/logging.js
  src/locales/tc/mail.js
  src/locales/tc/monitoring.js
  src/locales/tc/network.js
  src/locales/tc/nodes.js
  src/locales/tc/project.js
  src/locales/tc/ranking.js
  src/locales/tc/role.js
  src/locales/tc/s2i.js
  src/locales/tc/secret.js
  src/locales/tc/service.js
  src/locales/tc/settings.js
  src/locales/tc/sort_rank.js
  src/locales/tc/storage.js
  src/locales/tc/terminal.js
  src/locales/tc/user.js
  src/locales/tc/version.js
  src/locales/tc/workload.js
  src/locales/tc/workspace.js
Labels: approved, kind/documentation, lgtm, size/XXL

#695 fix: Fix the branch doesn't change in ParamsModal of the pipeline page
  src/components/Forms/CICDs/paramsModal.jsx
  src/pages/devops/containers/Credential/detail/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Artifacts/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Sider/branch-sider.jsx
  src/pages/devops/containers/Pipelines/index.jsx
  src/stores/devops/pipelines.js
Labels: approved, lgtm, size/L

#696 fix: Fix the ParamsModal has mounted should not request data
  src/components/Forms/CICDs/paramsModal.jsx
Labels: approved, kind/bug, lgtm, size/XS

#697 update: Update ui for host cluster
  src/actions/configmap.js
  src/actions/federated.js
  src/actions/imagebuilder.js
  src/actions/router.js
  src/actions/service.js
  src/components/Cards/Pods/index.scss
  src/components/Clusters/ClusterTitle/index.jsx
  src/components/Modals/DevOpsCreate/index.jsx
  src/components/Modals/FedProjectCreate/index.jsx
  src/components/Modals/Monitoring/ApplicationResource/index.jsx
  src/components/Modals/ProjectSelect/index.jsx
  src/locales/en/cluster.js
  src/locales/zh/cluster.js
  src/pages/clusters/components/Modals/ClusterVisibility/index.jsx
  src/pages/clusters/components/Modals/ClusterVisibility/index.scss
  src/pages/clusters/containers/Clusters/index.jsx
  src/pages/fedprojects/containers/BaseInfo/index.jsx
  src/pages/workspaces/components/Modals/WorkspaceCreate/ClusterSettings/ClusterSelect/index.jsx
  src/pages/workspaces/containers/FedProjects/index.jsx
  src/stores/project.js
  src/utils/object.mapper.js
Labels: approved, kind/bug, lgtm, size/L

#702 fix: Fix monitoring custom range query
  src/components/Cards/Monitoring/Controller/TimeSelector/Range/Custom.jsx
Labels: approved, kind/bug, lgtm, size/XS

#699 fix: Fix project resources search by app
  src/components/Modals/ProjectSelect/index.jsx
  src/locales/zh/base.js
  src/pages/devops/containers/Pipelines/Detail/Sider/pipeline-sider.jsx
  src/pages/devops/containers/Pipelines/Detail/Sider/runs-sider.jsx
  src/pages/fedprojects/containers/Deployments/Detail/index.jsx
  src/pages/fedprojects/containers/Routes/Detail/index.jsx
  src/pages/fedprojects/containers/Routes/index.jsx
  src/pages/fedprojects/containers/Services/index.jsx
  src/pages/fedprojects/containers/StatefulSets/Detail/index.jsx
  src/pages/fedprojects/containers/StatefulSets/index.jsx
  src/pages/projects/containers/DaemonSets/Detail/index.jsx
  src/pages/projects/containers/DaemonSets/index.jsx
  src/pages/projects/containers/Deployments/Detail/index.jsx
  src/pages/projects/containers/Deployments/index.jsx
  src/pages/projects/containers/Pods/Containers/Detail.jsx
  src/pages/projects/containers/Pods/Detail/index.jsx
  src/pages/projects/containers/Pods/index.jsx
  src/pages/projects/containers/Routes/Detail/index.jsx
  src/pages/projects/containers/Routes/index.jsx
  src/pages/projects/containers/Services/Detail/index.jsx
  src/pages/projects/containers/Services/index.jsx
  src/pages/projects/containers/StatefulSets/Detail/index.jsx
  src/pages/projects/containers/StatefulSets/index.jsx
  src/pages/workspaces/containers/FedProjects/index.jsx
  src/stores/base.js
  src/utils/object.mapper.js
Labels: approved, kind/bug, lgtm, size/L

#701 fix: Fix federated application create and version
  src/locales/zh/application.js
  src/pages/fedprojects/containers/Applications/Detail/AppComponents/Components/index.jsx
  src/pages/fedprojects/containers/Applications/Detail/AppComponents/Components/index.scss
  src/pages/fedprojects/containers/Applications/Detail/index.jsx
  src/pages/fedprojects/containers/Applications/index.jsx
  src/pages/projects/components/Modals/CreateApp/BaseInfo/index.jsx
Labels: approved, kind/bug, lgtm, size/M

#704 update: Update locales
  src/locales/en/role.js
  src/locales/tc/role.js
  src/locales/zh/role.js
  src/pages/access/containers/Roles/Detail/AuthorizedUsers/index.jsx
Labels: approved, kind/documentation, lgtm, size/S

#705 Fix some issures in deployment and s2ibuilders
  src/pages/projects/components/Cards/ImageRunRecord/Item/index.jsx
  src/pages/projects/components/Modals/HPA/index.jsx
  src/utils/object.mapper.js
  src/utils/workload.js
Labels: approved, lgtm, size/S

#706 fix: Fix snapshots fetching in volume create
  src/components/Forms/Volume/VolumeSettings/SnapshotForm/index.jsx
  src/components/Forms/Volume/VolumeSettings/index.jsx
Labels: approved, kind/bug, lgtm, size/S

#709 fix: Fix workload hpa settings
  src/pages/projects/components/Cards/HPA/index.jsx
  src/pages/projects/components/Modals/HPA/index.jsx
  src/pages/projects/containers/Deployments/Detail/ResourceStatus/index.jsx
  src/pages/projects/containers/Deployments/Detail/index.jsx
  src/utils/object.mapper.js
Labels: approved, kind/bug, lgtm, size/M

#707 chore: Fix missing lint
  src/locales/en/alerting.js
  src/locales/en/app_repo.js
  src/locales/en/cicd.js
  src/locales/en/grayrelease.js
  src/locales/en/mail.js
  src/locales/en/version.js
  src/locales/tc/s2i.js
  src/locales/zh/cicd.js
  src/locales/zh/s2i.js
Labels: approved, kind/documentation, lgtm, size/M

#712 fix: Fix application ingress
  src/locales/tc/application.js
  src/locales/zh/application.js
  src/pages/fedprojects/containers/Applications/Detail/AppIngresses/Ingresses/index.jsx
  src/pages/fedprojects/containers/Applications/Detail/Tracing/index.jsx
  src/pages/fedprojects/containers/Applications/index.jsx
  src/pages/projects/components/Modals/CreateApp/Routes/RuleList/index.jsx
  src/pages/projects/components/Modals/ServiceDelete/index.jsx
  src/pages/projects/components/Modals/WorkloadDelete/index.jsx
  src/pages/projects/containers/Applications/CRDApps.jsx
  src/pages/workspaces/containers/BaseInfo/index.jsx
  src/pages/workspaces/containers/FedProjects/index.jsx
Labels: approved, kind/bug, lgtm, size/M

#713 fix: Add cluster to the selected mirror apis in deployment
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
  src/stores/container.js
Labels: approved, kind/bug, lgtm, size/M

#719 chore: Fix typo
  src/pages/workspaces/containers/BaseInfo/index.jsx
Labels: approved, kind/bug, size/XS

#714 update: Update tc locales, the cicd.js part has been translated.
  src/locales/tc/cicd.js
Labels: approved, lgtm, size/L

#720 fix: Fix detail navs module control
  src/core/containers/Base/Detail/Page/index.jsx
  src/pages/projects/containers/Applications/CRDAppDetail/routes.js
  src/pages/projects/containers/Applications/OPAppDetail/AppTemplate/index.jsx
  src/pages/workspaces/containers/Members/Detail/routes.js
Labels: approved, kind/bug, lgtm, size/M

#721 fix: Fix issues of self provisioner
  src/locales/zh/role.js
  src/pages/access/containers/Workspaces/index.jsx
  src/pages/projects/containers/BaseInfo/index.jsx
  src/pages/projects/containers/CustomMonitoring/index.jsx
  src/pages/workspaces/containers/Projects/index.jsx
  src/stores/project.js
Labels: approved, kind/bug, lgtm, size/M

#722 fix: Fix app upgrade
  src/pages/projects/containers/Applications/OPAppDetail/AppTemplate/index.jsx
  src/stores/openpitrix/application.js
Labels: approved, kind/bug, lgtm, size/XS

#723 fix: Fix language switch error
  src/core/i18n.js
Labels: approved, kind/bug, lgtm, size/S

#725 fix: Fix workspace projects permission check
  src/pages/workspaces/containers/DevOps/index.jsx
  src/pages/workspaces/containers/Projects/index.jsx
Labels: approved, kind/bug, lgtm, size/XS

#730 fix: Fix application description
  src/locales/en/application.js
  src/pages/projects/components/Modals/CreateApp/BaseInfo/index.jsx
Labels: approved, kind/bug, lgtm, size/XS

#731 fix: Remove role's batch delete operation
  src/components/Cards/ProjectQuota/QuotaItem/index.scss
  src/components/Inputs/ContainerPort/index.jsx
  src/pages/access/containers/Roles/index.jsx
  src/pages/clusters/containers/Roles/index.jsx
  src/pages/devops/containers/Roles/index.jsx
  src/pages/fedprojects/containers/QuotaManage/ResourceQuota/QuotaItem/index.scss
  src/pages/projects/containers/Roles/index.jsx
  src/pages/workspaces/containers/Roles/index.jsx
Labels: approved, kind/bug, lgtm, size/S

#735 fix: Fix related resource not found tip
  src/pages/fedprojects/containers/Services/Detail/ResourceStatus/index.jsx
  src/pages/fedprojects/containers/StatefulSets/Detail/ResourceStatus.jsx
  src/pages/projects/containers/Services/Detail/ResourceStatus/index.jsx
Labels: approved, kind/bug, lgtm, size/S

#726 fix: Fix captcha style in login page
  server/public/login.css
  server/views/login.html
Labels: approved, kind/bug, lgtm, size/XS

#739 fix: Fix workspace overview page cluster switch
  src/components/Cards/Monitoring/Controller/index.scss
  src/components/Modals/Monitoring/ApplicationResource/index.jsx
  src/pages/clusters/containers/Monitor/Resource/Usage/Physical/index.jsx
  src/pages/clusters/containers/Monitor/Resource/Usage/Virtual/index.jsx
  src/pages/workspaces/containers/Overview/ResourceUsage/Physical/index.jsx
  src/pages/workspaces/containers/Overview/ResourceUsage/Virtual/index.jsx
  src/pages/workspaces/containers/Overview/ResourceUsage/index.jsx
  src/pages/workspaces/containers/Overview/UsageRanking/index.jsx
Labels: approved, kind/bug, lgtm, size/L

#737 fix: Configmap and secret mount interface do not displays read-write
  src/components/Forms/CICDs/paramsModal.jsx
  src/components/Forms/Workload/VolumeSettings/MountConfig/index.jsx
  src/components/Inputs/MountInput/Item.jsx
  src/components/Inputs/MountInput/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
  src/pages/devops/containers/Pipelines/index.jsx
  src/stores/devops/pipelines.js
Labels: approved, lgtm, size/M

#743 fix: Fix workload ports missing when update replicas
  src/pages/fedprojects/containers/Deployments/Detail/ResourceStatus/index.jsx
  src/pages/fedprojects/containers/StatefulSets/Detail/ServiceCard/index.jsx
Labels: approved, kind/bug, lgtm, size/M

#741 add tips link
  src/components/Cards/Banner/Tip.jsx
  src/locales/tc/network.js
  src/locales/zh/network.js
Labels: approved, lgtm, size/XS

#738 fix description limit
  src/components/Base/TextArea/index.jsx
  src/components/Modals/AppRepoCreate/index.jsx
  src/components/Modals/DevOpsCreate/index.jsx
  src/components/Modals/DevOpsEdit/index.jsx
  src/components/Modals/EditBasicInfo/index.jsx
  src/pages/devops/components/Modals/DevOpsEdit/index.jsx
  src/pages/projects/components/Modals/AppEdit/index.jsx
  src/pages/workspaces/components/Modals/EditBasicInfo/index.jsx
  src/pages/workspaces/components/Modals/WorkspaceCreate/BaseInfo/index.jsx
Labels: approved, kind/bug, lgtm, size/L

#734 Add loc for workload deletion
  src/locales/en/workload.js
  src/locales/tc/workload.js
  src/locales/zh/workload.js
  src/pages/projects/components/Modals/WorkloadDelete/index.jsx
Labels: approved, kind/documentation, lgtm, size/XS

#744 fix: Show workspace default manager when create and edit
  src/pages/workspaces/components/Modals/EditBasicInfo/index.jsx
  src/pages/workspaces/components/Modals/WorkspaceCreate/BaseInfo/index.jsx
Labels: approved, kind/bug, lgtm, size/S

#745 fix: Fix successThreshold for liveness and startup prob
  src/components/Forms/Workload/ContainerSettings/ContainerForm/HealthChecker/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ProbeForm/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ProbeInput/index.jsx
  src/locales/tc/workload.js
  src/locales/zh/workload.js
Labels: approved, kind/bug, lgtm, size/S

#672 fix: Fix user modify password
  src/actions/user.js
  src/components/Modals/ModifyPassword/index.jsx
  src/components/Modals/UserSetting/PasswordSetting/index.jsx
  src/components/Modals/UserSetting/index.jsx
  src/stores/federated.js
  src/stores/user.js
Labels: approved, kind/bug, lgtm, size/M

#746 Chore(locales): En wording adjustment
  src/components/Forms/GrayRelease/PolicyConfig/Bluegreen/index.jsx
  src/components/Layout/LoginInfo/index.jsx
  src/locales/en/application.js
  src/locales/en/base.js
  src/locales/en/cluster.js
  src/locales/tc/cluster.js
  src/locales/tc/devops.js
  src/locales/tc/grayrelease.js
  src/locales/tc/workload.js
  src/locales/zh/cluster.js
  src/locales/zh/devops.js
  src/locales/zh/grayrelease.js
  src/pages/devops/containers/BaseInfo/index.jsx
Labels: approved, kind/documentation, lgtm, size/M

#752 fix: Fix some issues
  src/components/Cards/RankTable/NodeTable/index.jsx
  src/components/Forms/Service/AdvanceSettings/Metadata/index.jsx
  src/components/Forms/StorageClass/StorageClassSettings/index.jsx
  src/components/Forms/Volume/VolumeSettings/SnapshotForm/index.jsx
  src/components/Forms/Workload/ContainerSettings/UpdateStrategy/index.jsx
  src/components/Forms/Workload/ContainerSettings/index.jsx
  src/components/Modals/FedProjectCreate/index.jsx
  src/components/Modals/ProjectCreate/index.jsx
  src/locales/en/workload.js
  src/locales/tc/ranking.js
  src/locales/tc/workload.js
  src/locales/zh/ranking.js
  src/locales/zh/workload.js
Labels: approved, kind/bug, lgtm, size/L

#753 fix: Remove quota item hover cursor
  src/pages/projects/containers/BaseInfo/ResourceQuota/QuotaItem/index.scss
Labels: approved, kind/bug, lgtm, size/XS

#742 chore: Update en locales
  server/locales/en.properties
  src/components/Forms/GrayRelease/Components/index.jsx
  src/locales/en/alerting.js
  src/locales/en/app.js
  src/locales/en/app_repo.js
  src/locales/en/app_store.js
  src/locales/en/app_template.js
  src/locales/en/application.js
  src/locales/en/base.js
  src/locales/en/cicd.js
  src/locales/en/cluster.js
  src/locales/en/component.js
  src/locales/en/configmap.js
  src/locales/en/crd.js
  src/locales/en/dashboard.js
  src/locales/en/devops.js
  src/locales/en/grayrelease.js
  src/locales/en/ingress.js
  src/locales/en/logging.js
  src/locales/en/mail.js
  src/locales/en/monitoring.js
  src/locales/en/network.js
  src/locales/en/nodes.js
  src/locales/en/project.js
  src/locales/en/role.js
  src/locales/en/s2i.js
  src/locales/en/secret.js
  src/locales/en/service.js
  src/locales/en/settings.js
  src/locales/en/storage.js
  src/locales/en/terminal.js
  src/locales/en/user.js
  src/locales/en/version.js
  src/locales/en/workload.js
  src/locales/en/workspace.js
  src/locales/tc/grayrelease.js
  src/locales/zh/grayrelease.js
Labels: approved, lgtm, size/XXL

#754 fix: Fix service name description
  src/locales/en/service.js
  src/locales/zh/service.js
Labels: approved, kind/bug, lgtm, size/XS

#756 fix: Fix workload edit config template error
  src/components/Cards/Containers/Ports/index.jsx
  src/components/EditForms/Workload/UpdateStrategy/index.jsx
  src/components/Forms/Workload/ContainerSettings/UpdateStrategy/index.jsx
  src/components/Forms/Workload/VolumeSettings/VolumeList/Card.jsx
  src/components/Forms/Workload/VolumeSettings/index.jsx
  src/components/HOCs/withList.js
  src/locales/en/workload.js
  src/locales/tc/workload.js
  src/locales/zh/workload.js
  src/pages/projects/containers/CronJobs/Detail/index.jsx
  src/pages/projects/containers/DaemonSets/Detail/index.jsx
  src/pages/projects/containers/Deployments/Detail/index.jsx
  src/pages/projects/containers/Services/Detail/index.jsx
  src/pages/projects/containers/StatefulSets/Detail/index.jsx
Labels: approved, kind/bug, lgtm, size/L

#758 fix: Fix user settings error
  src/actions/user.js
  src/components/Modals/UserSetting/index.jsx
Labels: approved, kind/bug, lgtm, size/S

#759 fix: Fix service workload select modal
  src/components/Forms/Service/ServiceSettings/SelectorsInput/index.jsx
  src/components/Forms/Service/ServiceSettings/WorkloadSelect/index.jsx
  src/components/Forms/Service/ServiceSettings/index.jsx
Labels: approved, kind/bug, lgtm, size/XS

#760 fix: Fix workload ports without name
  src/components/Cards/Containers/Ports/index.jsx
Labels: approved, kind/bug, lgtm, size/XS

#761 fix: Fix workload prob card missing startUp probe
  src/components/Cards/Containers/Item.jsx
  src/locales/en/workload.js
  src/locales/tc/workload.js
  src/locales/zh/workload.js
  src/pages/projects/components/Cards/ContainerTemplate/Item.jsx
  src/pages/projects/components/Cards/Probe/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#762 fix: Fix the build image still exists in the build image list when deleting the service
  src/pages/projects/components/Modals/ServiceDelete/index.jsx
  src/utils/object.mapper.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#764 fix: Update workload's spec.selector.matchLabels when labels change
  .eslintrc.js
  src/components/Forms/AppDeploy/BasicInfo/Placement/index.jsx
  src/components/Forms/AppDeploy/BasicInfo/index.jsx
  src/components/Forms/Workload/AdvanceSettings/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#765 fix: Fix the query in the build mirror list has not taken effect
  src/pages/projects/containers/ImageBuilder/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/XS

#766 fix: Fix service edit error
  src/components/Cards/Pods/index.jsx
  src/components/Forms/Service/ServiceSettings/index.jsx
  src/locales/zh/service.js
  src/pages/clusters/containers/Nodes/Detail/index.jsx
  src/pages/clusters/containers/Nodes/index.jsx
  src/pages/projects/components/Modals/ServiceDelete/index.jsx
  src/pages/projects/containers/Services/Detail/ResourceStatus/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#767 fix: Remove the status bar in the pipeline list
  src/pages/devops/containers/Pipelines/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/S

#769 fix: Fix workload error status display
  src/actions/project.js
  src/components/Forms/Project/AdvanceSettings/index.jsx
  src/components/Forms/Project/AdvanceSettings/index.scss
  src/components/Forms/Project/BaseInfo/index.jsx
  src/components/Forms/Service/ContainerSetting/ContainerSetting/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerList/Card.jsx
  src/components/Inputs/ResourceLimit/index.jsx
  src/components/Modals/AuditingSearch/Auditing/Home/index.scss
  src/components/Modals/EditBasicInfo/index.jsx
  src/components/Modals/LogSearch/Logging/Home/index.scss
  src/components/Modals/LogSearch/Logging/Search/index.scss
  src/components/Modals/QuotaEdit/index.jsx
  src/components/ToggleView/index.jsx
  src/locales/en/mail.js
  src/locales/en/workload.js
  src/locales/tc/mail.js
  src/locales/tc/workload.js
  src/locales/zh/mail.js
  src/locales/zh/workload.js
  src/pages/clusters/containers/Workload/CronJobs/index.jsx
  src/pages/clusters/containers/Workload/DaemonSets/index.jsx
  src/pages/clusters/containers/Workload/Deployments/index.jsx
  src/pages/clusters/containers/Workload/Jobs/index.jsx
  src/pages/clusters/containers/Workload/StatefulSets/index.jsx
  src/pages/fedprojects/components/ClusterWorkloadStatus/Cluster.jsx
  src/pages/fedprojects/components/ClusterWorkloadStatus/index.jsx
  src/pages/fedprojects/components/ClusterWorkloadStatus/index.scss
  src/pages/fedprojects/components/FedWorkloadStatus/index.jsx
  src/pages/fedprojects/containers/Deployments/Detail/ResourceStatus/index.jsx
  src/pages/fedprojects/containers/Deployments/index.jsx
  src/pages/fedprojects/containers/QuotaManage/ResourceQuota/QuotaItem/index.jsx
  src/pages/fedprojects/containers/QuotaManage/ResourceQuota/index.jsx
  src/pages/fedprojects/containers/Secrets/index.jsx
  src/pages/fedprojects/containers/StatefulSets/index.jsx
  src/pages/projects/components/StatusReason/index.jsx
  src/pages/projects/containers/ConfigMaps/Detail/index.jsx
  src/pages/projects/containers/CronJobs/index.jsx
  src/pages/projects/containers/DaemonSets/index.jsx
  src/pages/projects/containers/Deployments/index.jsx
  src/pages/projects/containers/Jobs/index.jsx
  src/pages/projects/containers/Secrets/Detail/index.jsx
  src/pages/projects/containers/StatefulSets/index.jsx
  src/pages/projects/containers/Volumes/Detail/index.jsx
  src/stores/notification/mailService.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#771 fix: Add try catch wrapper for atob
  src/components/Forms/Secret/SecretSettings/Base64Wrapper/index.jsx
  src/components/Forms/Secret/SecretSettings/DataForm/index.jsx
  src/components/Forms/Secret/SecretSettings/DataList/index.jsx
  src/stores/workload/env.js
  src/utils/app.js
  src/utils/index.js
  src/utils/object.mapper.js
Labels: approved, lgtm

#770 update: Update resource description length limit
  src/components/Forms/AlertingPolicy/BaseInfo/index.jsx
  src/components/Forms/AppDeploy/BasicInfo/index.jsx
  src/components/Forms/CronJob/BaseInfo/index.jsx
  src/components/Forms/Dashboard/BaseInfo/index.jsx
  src/components/Forms/GrayRelease/BaseInfo/index.jsx
  src/components/Forms/Service/BaseInfo/index.jsx
  src/components/Forms/StorageClass/BaseInfo/index.jsx
  src/components/Forms/VolumeSnapshot/BaseInfo/index.jsx
  src/components/Forms/Workload/BaseInfo/index.jsx
  src/components/Modals/AppRepoCreate/index.jsx
  src/components/Modals/DevOpsCreate/index.jsx
  src/components/Modals/DevOpsEdit/index.jsx
  src/components/Modals/EditBasicInfo/index.jsx
  src/components/Modals/FedProjectCreate/index.jsx
  src/components/Modals/ProjectCreate/index.jsx
  src/components/Modals/RoleCreate/index.jsx
  src/components/Modals/UserCreate/index.jsx
  src/locales/en/application.js
  src/locales/en/base.js
  src/locales/tc/application.js
  src/locales/tc/base.js
  src/locales/zh/application.js
  src/locales/zh/base.js
  src/pages/clusters/components/Modals/EditBasicInfo/index.jsx
  src/pages/clusters/containers/Clusters/AddCluster/BaseInfo/index.jsx
  src/pages/devops/components/Modals/DevOpsEdit/index.jsx
  src/pages/devops/containers/Credential/credentialModal.jsx
  src/pages/projects/components/Modals/AppEdit/index.jsx
  src/pages/projects/components/Modals/CreateApp/BaseInfo/index.jsx
  src/pages/workspaces/components/Modals/EditBasicInfo/index.jsx
  src/pages/workspaces/components/Modals/WorkspaceCreate/BaseInfo/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#774 fix: Fix federated project baseinfo edit
  src/pages/fedprojects/containers/BaseInfo/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#777 fix: Fix federated project create
  src/components/Modals/FedProjectCreate/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#776 fix: Fix the bug that the advance setting is empty in the image build when created
  src/actions/imagebuilder.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#772 chore: Update Dockerfile for non-root user
  Dockerfile
  Dockerfile.arm64
  docker-compose.builder.yaml
  docker-compose.yaml
  docker-run
  docs/CONTRIBUTING.md
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/M

#778 fix: Fix job rerun api error
  src/pages/clusters/containers/Workload/Jobs/index.jsx
  src/pages/projects/containers/Jobs/index.jsx
  src/stores/workload/index.js
Labels: approved, dco-signoff: yes, kind/api-change, kind/bug, lgtm, size/S

#779 fix: Fix cluster nodes filter by role
  src/stores/node.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#781 style: Fix gateway settings style in federated project
  src/pages/fedprojects/containers/AdvancedSettings/InternetAccess/Access/index.scss
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#783 update: Update tc locale, has completed to node.js and modified typo
  src/locales/tc/app.js
  src/locales/tc/cluster.js
  src/locales/tc/devops.js
  src/locales/tc/grayrelease.js
  src/locales/tc/ingress.js
  src/locales/tc/logging.js
  src/locales/tc/mail.js
  src/locales/tc/monitoring.js
  src/locales/tc/network.js
  src/locales/tc/nodes.js
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#785 fix: Fix servicemesh settings in federated project
  src/locales/zh/workload.js
  src/pages/fedprojects/App.jsx
  src/pages/fedprojects/containers/AdvancedSettings/InternetAccess/Access/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#780 chore: Update locales
  src/locales/tc/project.js
  src/locales/zh/project.js
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/XS

#786 fix: Fix pods cards in multicluster project
  src/components/Cards/ContainerLog/index.jsx
  src/components/Cards/Pods/index.jsx
  src/pages/fedprojects/containers/Deployments/Detail/ResourceStatus/index.jsx
  src/pages/fedprojects/containers/Services/Detail/ResourceStatus/index.jsx
  src/pages/projects/containers/Pods/Detail/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#727 fix: Fix workspace network isolation in single cluster mode
  src/actions/workspace.js
  src/components/Base/Indicator/index.scss
  src/locales/tc/base.js
  src/locales/zh/workspace.js
  src/pages/workspaces/components/Modals/WorkspaceCreate/BaseInfo/index.jsx
  src/pages/workspaces/containers/BaseInfo/index.jsx
  src/pages/workspaces/containers/BaseInfo/index.scss
  src/utils/object.mapper.js
Labels: approved, kind/bug, lgtm, size/M

#789 fix: Fix single cluster mail settings
  src/stores/notification/mailService.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#791 fix: Fix some issues in the image build
  src/pages/projects/components/Cards/ImageBuilderLastRun/index.jsx
  src/pages/projects/containers/ImageBuilder/Detail/Environment/index.jsx
  src/pages/projects/containers/ImageBuilder/Detail/Events/index.jsx
  src/pages/projects/containers/ImageBuilder/Detail/ResourceStatus/index.jsx
  src/pages/projects/containers/ImageBuilder/Detail/index.jsx
  src/stores/s2i/builder.js
  src/stores/workload/env.js
Labels: approved, dco-signoff: yes, lgtm, size/M

#792 fix: Fix multi-cluster resource detail page in cluster management
  src/components/Cards/Pods/index.jsx
  src/locales/en/project.js
  src/locales/tc/project.js
  src/locales/zh/project.js
  src/pages/clusters/containers/ConfigMaps/index.jsx
  src/pages/clusters/containers/Secrets/index.jsx
  src/pages/clusters/containers/Storage/Volumes/index.jsx
  src/pages/clusters/containers/Workload/Deployments/index.jsx
  src/pages/clusters/containers/Workload/Routes/index.jsx
  src/pages/clusters/containers/Workload/Services/index.jsx
  src/pages/clusters/containers/Workload/StatefulSets/index.jsx
  src/pages/clusters/routes/detail.js
  src/pages/projects/components/Cards/Placement/index.jsx
  src/pages/projects/components/Cards/Placement/index.scss
  src/pages/projects/containers/ConfigMaps/Detail/ConfigDetail/index.jsx
  src/pages/projects/containers/ConfigMaps/Detail/index.jsx
  src/pages/projects/containers/Deployments/Detail/ResourceStatus/index.jsx
  src/pages/projects/containers/Deployments/Detail/index.jsx
  src/pages/projects/containers/Routes/Detail/ResourceStatus/index.jsx
  src/pages/projects/containers/Routes/Detail/index.jsx
  src/pages/projects/containers/Secrets/Detail/SecretDetail/index.jsx
  src/pages/projects/containers/Secrets/Detail/index.jsx
  src/pages/projects/containers/Services/Detail/ResourceStatus/index.jsx
  src/pages/projects/containers/Services/Detail/index.jsx
  src/pages/projects/containers/StatefulSets/Detail/ResourceStatus.jsx
  src/pages/projects/containers/StatefulSets/Detail/index.jsx
  src/pages/projects/containers/Volumes/Detail/ResourceStatus/index.jsx
  src/pages/projects/containers/Volumes/Detail/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#794 fix: Fix federated secrets and configmaps edit
  src/actions/configmap.js
  src/actions/secret.js
  src/pages/fedprojects/containers/ConfigMaps/Detail/index.jsx
  src/pages/fedprojects/containers/ConfigMaps/index.jsx
  src/pages/fedprojects/containers/Secrets/Detail/index.jsx
  src/pages/fedprojects/containers/Secrets/index.jsx
  src/pages/projects/components/Modals/ConfigMapEdit/index.jsx
  src/pages/projects/components/Modals/SecretEdit/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#797 fix: Hide network policy if network disabled
  src/pages/workspaces/containers/BaseInfo/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#799 fix: Fix memory format in nodes list
  src/components/Modals/InviteMember/index.jsx
  src/pages/clusters/containers/Nodes/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#801 fix: Fix workspace project validating
  server/config.yaml
  src/components/Modals/FedProjectCreate/index.jsx
  src/components/Modals/ProjectCreate/index.jsx
  src/core/global.js
  src/locales/tc/workload.js
  src/locales/zh/workload.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#802 fix: Fix node role in cluster overview
  src/pages/clusters/containers/Overview/Dashboard/ClusterNodes/NodesTop5/index.jsx
  src/pages/clusters/containers/Overview/Dashboard/ClusterNodes/NodesTop5/index.scss
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#805 fix: Fix crd api version
  src/utils/constants.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#806 fix: Fix cluster email settings
  server/config.yaml
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#810 fix: Remove network isolation setting in project create
  server/config.yaml
  src/components/Modals/FedProjectCreate/index.jsx
  src/components/Modals/ProjectCreate/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#812 update: Update allocated resource display in cluster nodes
  src/locales/en/nodes.js
  src/locales/zh/nodes.js
  src/pages/access/containers/Workspaces/index.jsx
  src/pages/clusters/containers/Nodes/index.jsx
  src/pages/clusters/containers/Projects/index.jsx
  src/pages/workspaces/containers/Projects/index.jsx
  src/utils/index.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#813 fix: Fix redirect after project delete
  src/actions/federated.js
  src/pages/fedprojects/containers/BaseInfo/index.jsx
  src/pages/projects/containers/BaseInfo/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#815 fix: Fix service session affinity settings
  src/components/Base/Form/Group.jsx
  src/components/Forms/Service/AdvanceSettings/SessionAffinity/index.jsx
  src/components/Forms/Service/AdvanceSettings/index.jsx
  src/components/Forms/Volume/VolumeSettings/FormTemplate.jsx
  src/locales/en/service.js
  src/locales/tc/service.js
  src/locales/zh/service.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#816 fix: Remove storageclass snapshot enable function
  src/components/Modals/StorageClassSnapshot/index.jsx
  src/components/Modals/StorageClassSnapshot/index.scss
  src/locales/en/storage.js
  src/locales/tc/storage.js
  src/locales/zh/storage.js
  src/pages/clusters/containers/Storage/StorageClasses/Detail/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#817 fix: Fix the link of project route In the project overview
  src/pages/projects/containers/Overview/ResourceUsage/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/XS

#819 fix: Fix federated projects batch delete
  src/actions/federated.js
  src/actions/storageclass.js
  src/pages/workspaces/containers/FedProjects/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L
