Repository kubesphere/console, pull requests merged in 2020-12, with the labels that each got.

#1335 Chore(locales): minor wording fix in storage UI
  src/components/Forms/StorageClass/StorageClassSettings/index.jsx
  src/locales/en/storage.js
  src/locales/es/storage.js
  src/locales/tc/storage.js
  src/locales/zh/storage.js
  src/pages/clusters/containers/Storage/StorageClasses/Detail/index.jsx
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/S

#1339 chore: Modify the RegExp in pipeline
  src/stores/devops/pipelines.js
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1340 feat: Support OAuth user register
  server/controllers/session.js
  server/controllers/view.js
  server/routes.js
  server/services/session.js
  server/views/index.html
  server/views/login.html
  src/core/containers/Login/Captcha.jsx
  src/core/containers/Login/index.jsx
  src/core/containers/Login/index.scss
  src/core/containers/OAuthRegister/index.jsx
  src/core/containers/OAuthRegister/index.scss
  src/core/routes.js
  src/locales/en/login.js
  src/locales/es/login.js
  src/locales/tc/login.js
  src/locales/zh/base.js
  src/locales/zh/login.js
  src/stores/root.js
  src/stores/user.js
  src/utils/request.js
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XXL

#1342 fix: Fix ldap account login error
  server/controllers/session.js
  server/controllers/view.js
  server/routes.js
  server/services/session.js
  src/core/containers/LoginConfirm/index.jsx
  src/core/containers/LoginConfirm/index.scss
  src/core/routes.js
  src/stores/user.js
Labels: approved, dco-signoff: yes, lgtm, size/L

#1343 feat: Add user password confirm step
  server/controllers/session.js
  server/services/session.js
  src/actions/user.js
  src/core/containers/PasswordConfirm/index.jsx
  src/core/containers/PasswordConfirm/index.scss
  src/core/routes.js
  src/locales/en/login.js
  src/locales/es/login.js
  src/locales/tc/login.js
  src/locales/zh/login.js
  src/stores/user.js
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/L

#1344 feat: Fetch previous log for terminated container
  src/components/Cards/ContainerLog/index.jsx
  src/components/Modals/ContainerLog/index.jsx
  src/stores/container.js
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/M

#1346 fix: Fix password confirm redirect
  server/controllers/session.js
  server/controllers/view.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1345 Chore(locales): Minor UI update
  src/components/Forms/ImageBuilder/B2IForm/BinaryFileUploader/index.jsx
  src/components/Forms/ImageBuilder/B2IForm/index.jsx
  src/components/Forms/Secret/SecretSettings/ImagerRegistry/index.jsx
  src/locales/en/s2i.js
  src/locales/en/secret.js
  src/locales/es/s2i.js
  src/locales/es/secret.js
  src/locales/tc/s2i.js
  src/locales/tc/secret.js
  src/locales/zh/s2i.js
  src/locales/zh/secret.js
  src/pages/projects/components/Cards/ImageRunRecord/Item/index.jsx
  src/pages/projects/containers/ImageBuilder/Detail/BuildRecords/index.jsx
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/M

#1349 fix: Check password confirm redirect when use login
  server/controllers/session.js
  server/controllers/view.js
  server/services/session.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1347 feature: Add GitLab in pipeline creating
  src/components/Forms/Pipelines/RepoSelect/GitLabForm/index.jsx
  src/components/Forms/Pipelines/RepoSelect/GitLabForm/index.scss
  src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx
  src/components/Forms/Pipelines/RepoSelect/subForm.jsx
  src/components/Modals/Pipelines/AdvanceEdit/index.jsx
  src/locales/en/pipeline.js
  src/locales/es/pipeline.js
  src/locales/tc/pipeline.js
  src/locales/zh/pipeline.js
  src/utils/constants.js
Labels: approved, dco-signoff: yes, lgtm, size/M

#1350 feat: Add trigger for s2i
  src/components/Forms/ImageBuilder/B2IForm/index.jsx
  src/components/Forms/ImageBuilder/S2IForm/index.jsx
  src/locales/en/s2i.js
  src/locales/es/s2i.js
  src/locales/tc/s2i.js
  src/locales/zh/s2i.js
  src/pages/projects/containers/ImageBuilder/Detail/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/M

#1352 fix: Fix login captcha not reload error
  server/public/icon.svg
  server/public/login.css
  src/core/containers/Login/Captcha.jsx
  src/core/containers/Login/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#1353 fix: Display the name and alias in Applications details page
  src/pages/projects/components/Cards/Ingresses/Item.jsx
  src/pages/projects/components/Cards/Services/Item.jsx
  src/pages/projects/components/Cards/Workloads/Item.jsx
Labels: approved, dco-signoff: yes, lgtm, size/S

#1354 improvement: defautl disable time trigger
  src/pages/devops/containers/Pipelines/PipelinesList/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1356 improvement: secret url and regular pattern
  src/components/Forms/ImageBuilder/B2IForm/index.jsx
  src/components/Forms/ImageBuilder/S2IForm/index.jsx
  src/pages/projects/containers/ImageBuilder/Detail/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/S

#1357 fix: Fix project select in cluster monitoring modal
  src/components/Modals/Monitoring/ApplicationResource/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1358 update: Update kiali API
  package.json
  scripts/webpack.base.js
  src/components/Graph/App/index.jsx
  src/components/Graph/Card/index.jsx
  src/components/Graph/Detail/Monitors/index.jsx
  src/locales/en/grayrelease.js
  src/locales/es/grayrelease.js
  src/locales/tc/grayrelease.js
  src/locales/zh/application.js
  src/locales/zh/grayrelease.js
  src/pages/projects/components/Modals/GrayReleaseDetail/Monitor/index.jsx
  src/pages/projects/containers/Applications/CRDAppDetail/TrafficManangement/index.jsx
  src/pages/projects/containers/GrayRelease/Jobs/Item.jsx
  src/stores/application/crd.js
  src/stores/grayrelease.js
  src/utils/object.mapper.js
  yarn.lock
Labels: approved, dco-signoff: yes, lgtm, size/L

#1359 Fix the wrong field names with Gitlab source
  src/components/Forms/Pipelines/RepoSelect/GitLabForm/index.jsx
  src/components/Modals/Pipelines/Base/index.jsx
  src/locales/en/base.js
  src/locales/en/pipeline.js
  src/locales/es/base.js
  src/locales/es/pipeline.js
  src/locales/tc/base.js
  src/locales/tc/pipeline.js
  src/locales/zh/base.js
  src/locales/zh/pipeline.js
  src/pages/devops/containers/Credential/detail/index.jsx
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/S

#1363 fix: Fix pre-register user username
  server/controllers/session.js
  server/services/session.js
  src/locales/en/user.js
  src/locales/es/user.js
  src/locales/tc/user.js
  src/locales/zh/user.js
  src/utils/constants.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1364 fix: Fix import cluster function error
  src/actions/cluster.js
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1365 fix: Fix image registry validate style
  src/components/Forms/Secret/SecretSettings/ImagerRegistry/index.jsx
  src/components/Forms/Secret/SecretSettings/ImagerRegistry/index.scss
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/L

#1366 Fix the wrong query of pipeline list
  src/stores/devops/pipelines.js
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/XS

#1369 feat: Add the credentials in gltlab form
  src/components/Forms/Pipelines/RepoSelect/GitLabForm/index.jsx
  src/components/Forms/Pipelines/RepoSelect/GitLabForm/index.scss
  src/components/Forms/Pipelines/RepoSelect/subForm.jsx
Labels: approved, dco-signoff: yes, lgtm, size/M

#1368 fix: Fix the sonarqube page could not get data
  src/pages/devops/containers/Pipelines/Detail/CodeQuality/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Layout/branch.jsx
  src/pages/devops/containers/Pipelines/Detail/Layout/pipeline.jsx
  src/stores/devops/pipelines.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1375 fix: Fix nav items filter error in global.js
  src/core/global.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1376 fix: Fix pods card item key
  src/components/Cards/Pods/Item.jsx
  src/components/Cards/Pods/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1380 feat: Add discovering tags in multi-branch pipeline
  src/components/Forms/Pipelines/ActionsInput/Item.jsx
  src/components/Forms/Pipelines/ActionsInput/index.jsx
  src/components/Forms/Pipelines/AdvanceSettings/index.jsx
  src/components/Forms/Pipelines/RepoSelect/BitBucketForm/index.jsx
  src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx
  src/components/Forms/Pipelines/RepoSelect/GithubForm/index.scss
  src/components/Forms/Pipelines/RepoSelect/subForm.jsx
  src/stores/devops/scm.js
Labels: approved, dco-signoff: yes, lgtm, size/L

#1381 feat: Add two features in pipeline
  src/locales/en/base.js
  src/locales/en/pipeline.js
  src/locales/es/base.js
  src/locales/es/pipeline.js
  src/locales/tc/pipeline.js
  src/locales/zh/pipeline.js
  src/pages/devops/components/Cards/CodeQualityIssues/index.jsx
  src/pages/devops/components/Cards/CodeQualityResult/index.jsx
  src/pages/devops/components/Modals/JenkinsEdit/index.jsx
  src/pages/devops/components/PipelineStatus/card.jsx
  src/pages/devops/containers/Pipelines/Detail/CodeQuality/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/L

#1382 fix: Fix image pull secret error when edit container form
  src/components/Forms/Service/ContainerSetting/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/Select/index.scss
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
  src/components/Forms/Workload/ContainerSettings/index.jsx
  src/stores/service.js
  src/utils/index.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#1384 fix: Fix node monitoring for edge nodes
  src/pages/clusters/containers/Nodes/Detail/Monitoring/index.jsx
  src/pages/clusters/containers/Nodes/Detail/RunningStatus/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1386 Add a GitHub action for building nightly images
  .github/workflows/nightly-builds.yml
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/M

#1388 Add a Slack notification
  .github/workflows/nightly-builds.yml
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/XS

#1389 Fix the docker hub login issues due to wrong secret var
  .github/workflows/nightly-builds.yml
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/XS

#1390 fix: Fix member cluster etcd monitor data
  src/pages/clusters/containers/Monitor/Cluster/Monitor/Etcd/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1391 Fix the wrong secret usage of docker hub
  .github/workflows/nightly-builds.yml
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/XS

#1385 feat: Add agent in stage
  src/pages/devops/components/Pipeline/Sider/index.jsx
  src/pages/devops/components/Pipeline/Sider/index.scss
  src/pages/devops/components/Pipeline/StepsEditor/index.jsx
  src/pages/devops/components/Pipeline/index.jsx
  src/pages/devops/components/Pipeline/store.js
Labels: approved, dco-signoff: yes, lgtm, size/L

#1392 fix: Fix project error catch when cluster crack
  src/pages/clusters/containers/Workload/Deployments/index.jsx
  src/pages/clusters/containers/layout.jsx
  src/stores/devops.js
  src/stores/project.js
  src/utils/request.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1395 Fix the wrong job filter with job search API
  src/components/Forms/Pipelines/AdvanceSettings/index.jsx
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/XS

#1396 refactor: Refactor traffic graph display algorithm
  src/components/Graph/index.scss
  src/components/Graph/utils.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1402 fix: Fix sonarqube request and remove confirm when nothing changed in Jenkinsfile
  src/pages/devops/components/Modals/JenkinsEdit/index.jsx
  src/pages/devops/components/Pipeline/Sider/index.jsx
  src/pages/devops/components/Pipeline/StepsEditor/index.jsx
  src/pages/devops/components/Pipeline/store.js
  src/pages/devops/containers/Pipelines/Detail/Layout/branch.jsx
  src/pages/devops/containers/Pipelines/Detail/Layout/pipeline.jsx
  src/utils/md5.js
Labels: approved, dco-signoff: yes, lgtm, size/L

#1403 fix bug 1374
  src/pages/projects/containers/Applications/CRDApps.jsx
  src/pages/projects/containers/Applications/OPApps.jsx
  src/pages/workspaces/containers/Apps/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1407 fix: Fix the discover_tag to discover_tags
  src/components/Forms/Pipelines/ActionsInput/Item.jsx
  src/components/Forms/Pipelines/ActionsInput/index.jsx
  src/components/Forms/Pipelines/RepoSelect/BitBucketForm/index.jsx
  src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx
  src/components/Forms/Pipelines/RepoSelect/subForm.jsx
  src/pages/devops/components/Pipeline/store.js
  src/utils/constants.js
Labels: approved, dco-signoff: yes, lgtm, size/S
