Repository kubesphere/console, pull requests merged in 2020-02, with the labels that each got.

#108 update: Update container log fecth method
  src/components/Cards/ContainerLog/index.jsx
  src/components/Modals/ContainerLog/index.jsx
  src/components/Modals/ContainerLog/index.scss
  src/pages/projects/containers/Pods/Containers/Logs.jsx
  src/stores/container.js
  src/utils/constants.js
  src/utils/request.js
Labels: approved, lgtm, size/L

#110 update: Update kubesphere logo
  src/assets/login-logo.svg
  src/assets/logo-white.svg
  src/assets/logo.svg
  src/components/Layout/Header/index.jsx
Labels: approved, lgtm, size/M

#113 picked 2 commits to release-2.1
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageSearch/DropdownContent.jsx
  src/locales/zh/s2i.js
  src/utils/constants.js
Labels: approved, lgtm, size/S

#112 fix: volume detail page report 404 when denpendent storageclass deleted
  src/locales/en/storage.js
  src/locales/zh/storage.js
  src/pages/clusters/containers/Infrastructure/StorageClasses/Detail/index.jsx
  src/pages/clusters/containers/Infrastructure/StorageClasses/index.jsx
  src/pages/projects/containers/Volumes/Detail/index.jsx
  src/utils/object.mapper.js
Labels: approved, lgtm, size/M

#111 Fix/volume status filter no work in 2.1
  src/pages/projects/containers/Volumes/index.jsx
  src/utils/constants.js
Labels: approved, lgtm, size/XS

#83 fix: s2i service private image repo bug
  src/components/Forms/ImageBuilder/S2IForm/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageSearch/DropdownContent.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageSearch/index.jsx
  src/stores/s2i/builder.js
  src/stores/service.js
Labels: approved, lgtm, size/M

#104 fix: Hide common taints if only one node selected
  src/components/Modals/Node/TaintManagement/Batch.jsx
Labels: approved, lgtm, size/S

#103 update: Ehance error tips when backend services cannot access
  server/controllers/session.js
  server/controllers/view.js
  server/locales/zh.properties
  server/views/error.html
Labels: approved, lgtm, size/L

#115 update: Update top5 title style
  src/pages/projects/containers/Overview/UsageRanking/index.jsx
  src/pages/projects/containers/Overview/UsageRanking/index.scss
Labels: approved, lgtm, size/S

#116 fix: Fix job running flicker status
  src/components/Base/Indicator/index.scss
  src/pages/projects/components/JobStatus/index.jsx
  src/pages/projects/containers/Jobs/index.jsx
  src/scss/lego.custom.scss
Labels: approved, lgtm, size/M

#117 fix: remove image name with scheme
  src/components/Forms/Secret/SecretSettings/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageSearch/DropdownContent.jsx
  src/locales/zh/secret.js
Labels: approved, lgtm, size/S

#119 fix: add image search cache
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageSearch/index.jsx
Labels: approved, lgtm, size/M

#118 fix: show pods status after build s2i
  src/pages/projects/components/WorkloadStatus/index.jsx
  src/stores/container.js
  src/utils/status.js
Labels: approved, lgtm, size/S

#120 update: Update pod status and container status
  src/components/Cards/Containers/Item.jsx
  src/components/Forms/Workload/ContainerSettings/index.jsx
  src/components/Inputs/ResourceLimit/index.jsx
  src/components/Inputs/StringInput/index.jsx
  src/components/Modals/Create/index.jsx
  src/locales/zh/workload.js
  src/utils/status.js
Labels: approved, lgtm, size/L

#121 fix single svn bug
  src/components/Forms/CICDs/BaseInfo/index.jsx
  src/components/Forms/CICDs/RepoSelect/subForm.jsx
  src/pages/devops/containers/Pipelines/Detail/Branch/index.jsx
  src/utils/devops.js
Labels: approved, lgtm, size/S

#122 fix: svn type cant be changed after created
  src/components/Forms/CICDs/RepoSelect/SVNForm/index.jsx
  src/components/Forms/CICDs/RepoSelect/subForm.jsx
  src/utils/devops.js
Labels: approved, lgtm, size/XS

#123 fix: Fix pod status error
  src/utils/status.js
Labels: approved, lgtm, size/S

#127 fix: Fix openpitrix app query params
  src/configs/openpitrix/app.js
Labels: approved, lgtm, size/XS

#130 fix: get s2i log error when container not ready
  src/components/Forms/CICDs/ParamsInput/Item.jsx
  src/pages/devops/containers/Pipelines/Modals/editPipelineConfigModal.jsx
  src/pages/projects/components/Cards/ImageRunRecord/Item/index.jsx
  src/pages/projects/components/Cards/S2iBuilder/log.jsx
  src/pages/projects/containers/ImageBuilder/Detail/Components/EditModal.jsx
  src/pages/projects/containers/ImageBuilder/Detail/index.jsx
  src/stores/s2i/run.js
Labels: approved, lgtm

#131 fix: s2i image name need remove url scheme
  src/stores/s2i/builder.js
Labels: approved, lgtm

#133 fix: Fix api version for k8s v1.16
  src/stores/workload/revision.js
Labels: approved, lgtm, size/XS

#134 fix: need to distinguish s2i status and pod status
  src/pages/projects/components/WorkloadStatus/index.jsx
  src/utils/status.js
Labels: approved, lgtm, size/S

#136 Add url input
  src/components/Forms/Secret/SecretSettings/index.jsx
  src/components/Inputs/SchemeInput/index.jsx
  src/components/Inputs/SchemeInput/index.scss
  src/components/Inputs/index.js
  src/utils/constants.js
Labels: approved, lgtm, size/L

#137 refine description of S2i svc
  src/locales/en/service.js
Labels: approved, lgtm, size/XS

#138 fix: Fix workspace search order
  src/pages/clusters/containers/Workspaces/index.jsx
Labels: approved, size/XS

#139 fix: Fix op app query conditions
  src/stores/openpitrix/base.js
Labels: approved, lgtm, size/XS

#141 fix: change image search back structure
  src/stores/container.js
  src/stores/s2i/builder.js
Labels: approved, lgtm, size/S

#142 fix: Fix op app status translation
  src/components/Base/Indicator/index.scss
  src/locales/zh/version.js
  src/pages/projects/containers/Applications/OPApps.jsx
Labels: approved, lgtm, size/XS

#146 fix: Fix workspace redirect 404 rule
  src/components/Modals/ProjectSelect/index.jsx
  src/pages/workspaces/containers/layout.jsx
Labels: approved, lgtm, size/XS

#149 fix: Remove app screen resolution check
  src/components/Forms/GrayRelease/Version/ContainerList/index.jsx
  src/configs/openpitrix/app.js
  src/locales/en/app.js
  src/locales/zh/app.js
  src/pages/apps/components/Cards/ScreenshotsEdit/index.jsx
Labels: approved, lgtm, size/M

#143 Fix/log query tool crash when input equal char
  src/utils/log.js
Labels: approved, lgtm, size/XS

#144 fix: alert list target count different in detail page
  src/pages/clusters/containers/MonitoringCenter/Alerting/Policy/index.jsx
Labels: approved, lgtm, size/XS

#145 refactor: remove password field from mail config form
  src/stores/notification/mailService.js
Labels: approved, lgtm, size/XS

#150 Refactor/show metrics in the same order
  src/pages/clusters/containers/MonitoringCenter/Monitoring/Resource/Ranking/Project/Table/index.jsx
Labels: approved, lgtm, size/S

#151 fix: fix create pipeline error
  src/stores/devops/pipelines.js
Labels: approved, lgtm, size/XS

#152 fix: Fix update service policy resource version
  src/components/Graph/Detail/Monitors/TrafficCard.jsx
  src/components/Graph/Detail/PolicyForm/index.jsx
  src/components/Graph/index.jsx
Labels: approved, lgtm, size/XS

#153 fix: Fix job actions permissions
  src/pages/projects/containers/Jobs/index.jsx
Labels: approved, lgtm, size/XS

#154 fix: monitor component status display wrong
  src/pages/clusters/containers/MonitoringCenter/Monitoring/Cluster/Overview/index.jsx
  src/stores/monitoring/component.js
Labels: approved, lgtm, size/M

#156 update: Update list api default order
  src/stores/alerting/resource.js
  src/stores/application/crd.js
  src/stores/base.js
  src/stores/openpitrix/application.js
  src/stores/pod.js
  src/stores/project.js
  src/stores/role.js
  src/stores/s2i/run.js
  src/stores/user.js
  src/stores/workspace/index.js
  src/stores/workspace/member.js
Labels: approved, lgtm, size/M

#155 fix: Fix authority errors
  src/pages/clusters/containers/MonitoringCenter/Alerting/Message/Detail/Comment/index.jsx
  src/pages/clusters/containers/MonitoringCenter/Alerting/Policy/index.jsx
  src/pages/projects/containers/ImageBuilder/index.jsx
  src/stores/alerting/message.js
Labels: approved, lgtm, size/M

#158 fix: Fix pod list sort order
  src/pages/projects/containers/Pods/index.jsx
  src/stores/pod.js
  src/utils/object.mapper.js
Labels: approved, lgtm, size/XS

#159 fix: Fix resources list orders
  src/pages/projects/containers/Applications/CRDApps.jsx
  src/pages/projects/containers/Jobs/index.jsx
  src/stores/base.js
  src/stores/openpitrix/application.js
  src/utils/constants.js
  src/utils/object.mapper.js
Labels: approved, lgtm, size/M

#161 style: fix no scroll bar of image search in macos
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageSearch/Select/index.scss
Labels: approved, lgtm, size/XS

#162 fix: Remove batch modify members
  src/pages/devops/containers/Members/index.jsx
  src/pages/projects/containers/Members/index.jsx
  src/pages/workspaces/containers/Members/index.jsx
Labels: approved, lgtm, size/S

#160 fix(ks-component-monitoring): component monitoring health loading sta…
  src/stores/monitoring/component.js
Labels: approved, lgtm, size/S

#163 fix: Remove labels empty check
  src/components/Forms/Workload/AdvanceSettings/Metadata/index.jsx
Labels: approved, lgtm, size/XS

#164 fix: Remove refs in yaml
  src/utils/yaml.js
Labels: approved, lgtm, size/S

#166 refactor: remove hightlight word
  src/components/Cards/ContainerLog/index.jsx
Labels: approved, lgtm, size/XS

#165 fix: change ks component model healthy check logic
  src/stores/monitoring/component.js
Labels: approved, lgtm, size/XS

#168 update: Add secret edit yaml modal
  src/pages/projects/containers/Secrets/Detail/index.jsx
  src/pages/projects/containers/Secrets/index.jsx
Labels: approved, lgtm, size/M

#169 fix: Fix secret edit yaml
  src/pages/projects/containers/Secrets/Detail/index.jsx
  src/pages/projects/containers/Secrets/index.jsx
  src/stores/secret.js
Labels: approved, lgtm, size/S

#172 fix: pod monitoring miss zero data display
  src/stores/monitoring/pod.js
Labels: approved, lgtm, size/XS

#174 fix: Fix role desc expand in invite member modal
  src/components/Base/Avatar/index.jsx
  src/components/Modals/InviteMember/User.jsx
  src/components/Modals/InviteMember/index.scss
Labels: approved, lgtm, size/S

#175 fix: Screenshots of application uploaded in sequence
  src/configs/openpitrix/app.js
  src/pages/apps/components/Cards/ScreenshotsEdit/index.jsx
  src/pages/projects/components/Modals/RepoApp/Apps/index.jsx
  src/stores/openpitrix/app.js
  src/stores/openpitrix/base.js
Labels: approved, lgtm, size/M

#177 fix: jump to template list after template app create
  src/pages/projects/containers/Applications/index.jsx
Labels: approved, lgtm, size/XS

#179 fix: Fix openpitrix resources list orders
  src/stores/openpitrix/base.js
Labels: approved, lgtm, size/XS

#180 fix mistaken words
  src/locales/en/workload.js
Labels: approved, kind/documentation, lgtm, size/XS

#181 fix: Fix application crd componentKinds
  server/sample/bookinfo.yaml
  src/pages/projects/components/Modals/CreateApp/Resources/index.jsx
  src/utils/constants.js
Labels: approved, lgtm, size/XS

#182 fix: Fix app manage page logout redirect
  server/libs/utils.js
  src/components/Layout/LoginInfo/index.jsx
  src/utils/index.js
Labels: approved, lgtm, size/S

#178 fix: hide error when s2i not found
  src/pages/projects/components/Cards/S2iBuilder/index.jsx
  src/pages/projects/components/Modals/RebuildS2i/index.jsx
  src/pages/projects/components/Modals/ServiceDelete/index.jsx
  src/stores/s2i/builder.js
Labels: approved, lgtm, size/L

#183 fix: Fix cronjob max length validate
  src/components/Forms/CronJob/BaseInfo/index.jsx
  src/locales/en/workload.js
  src/locales/zh/workload.js
  src/utils/constants.js
Labels: approved, lgtm, size/S

#184 fix: remove custom b2i files limit
  src/components/Forms/ImageBuilder/B2IForm/BinaryFileUploader/index.jsx
  src/locales/en/s2i.js
  src/locales/zh/s2i.js
Labels: approved, lgtm, size/S

#185 fix: fix filter out scaner error
  src/locales/en/cicd.js
  src/locales/zh/cicd.js
  src/pages/devops/containers/Pipelines/Modals/scanRepositoryLogsModal.jsx
Labels: approved, lgtm, size/S

#186 fix mistaken words in pipeline
  src/components/Forms/CICDs/AdvanceSettings/index.jsx
  src/locales/zh/cicd.js
Labels: approved, lgtm, size/S

#187 fix: Fix search by app
  src/pages/projects/containers/Pods/index.jsx
  src/pages/projects/containers/Routes/index.jsx
  src/pages/projects/containers/Services/index.jsx
  src/pages/projects/containers/Workloads/Base.jsx
  src/utils/index.js
  src/utils/index.test.js
Labels: approved, lgtm, size/S

#188 fix: Fix event start time
  src/utils/object.mapper.js
Labels: approved, lgtm, size/XS

#189 fix: show error when custom s2i template
  src/components/Forms/ImageBuilder/B2IForm/BinaryFileUploader/index.jsx
Labels: approved, lgtm, size/XS

#191 fix typo in container settings page
  src/components/Forms/Workload/ContainerSettings/ContainerForm/Commands/index.jsx
  src/locales/zh/s2i.js
Labels: approved, lgtm, size/XS

#195 fix: Fix ingress annotations edit error
  src/components/Base/Button/index.jsx
  src/components/Forms/Route/AdvanceSettings/Metadata/index.jsx
  src/components/Inputs/AnnotationsInput/index.jsx
  src/components/Inputs/AnnotationsInput/index.scss
  src/components/Inputs/PropertiesInput/Item.jsx
  src/components/Inputs/PropertiesInput/index.jsx
  src/components/Inputs/index.js
  src/pages/projects/components/Modals/RouteAnnotationsEdit/index.jsx
Labels: approved, size/M
