Repository kubesphere/console, pull requests merged in 2020-10, with the labels that each got.

#1245 update traffic management wording
  src/components/Forms/GrayRelease/PolicyConfig/Bluegreen/VersionSelect/index.jsx
  src/locales/en/grayrelease.js
  src/locales/es/grayrelease.js
  src/locales/tc/grayrelease.js
  src/locales/zh/grayrelease.js
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/S

#1248 fix word typo
  src/locales/en/alerting.js
  src/locales/en/monitoring.js
  src/locales/es/alerting.js
  src/locales/es/monitoring.js
  src/locales/tc/alerting.js
  src/locales/tc/monitoring.js
  src/locales/zh/alerting.js
  src/locales/zh/monitoring.js
  src/pages/clusters/components/Cards/Monitoring/ETCD/index.jsx
  src/pages/clusters/containers/Monitor/Cluster/Monitor/Etcd/index.jsx
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/M

#1251 Revert "chore: Upgrade dependencies"
  yarn.lock
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#1258 fix: Fix log search styles
  babel.config.js
  cypress/integration/workspaces/members.spec.js
  package.json
  src/components/Graph/Detail/Monitors/TrafficCard.jsx
  src/components/Graph/Detail/PolicyForm/index.scss
  src/components/Inputs/AddonsInput/index.scss
  src/components/Modals/AuditingSearch/Auditing/Detail/index.jsx
  src/components/Modals/AuditingSearch/Auditing/Detail/index.scss
  src/components/Modals/AuditingSearch/Auditing/Home/index.scss
  src/components/Modals/CustomMonitoring/components/TimeRangeSelect/index.scss
  src/components/Modals/EventSearch/Event/Detail/MetadataModal/index.scss
  src/components/Modals/EventSearch/Event/Detail/index.jsx
  src/components/Modals/EventSearch/Event/Detail/index.scss
  src/components/Modals/EventSearch/Event/Home/index.scss
  src/components/Modals/LogSearch/Logging/Detail/index.jsx
  src/components/Modals/LogSearch/Logging/Detail/index.scss
  src/components/Modals/LogSearch/Logging/Home/index.scss
  src/components/Modals/LogSearch/Logging/Search/index.scss
  src/core/App.jsx
  src/core/i18n.js
  src/pages/apps/components/Cards/CreateInfo/index.scss
  src/pages/apps/components/Modals/HelmUpload/index.scss
  src/pages/devops/components/Pipeline/store.js
  src/scss/custom.scss
  src/scss/main.scss
  src/stores/devops/run.js
  yarn.lock
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#1259 fix: Fix the parallel display problem of pipeline in details
  src/stores/devops/run.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1260 chore: Add css extract for kube-design styles
  scripts/webpack.prod.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1264 Fix UI typo
  src/locales/en/pipeline.js
  src/locales/es/pipeline.js
  src/locales/tc/pipeline.js
  src/locales/zh/pipeline.js
  src/utils/constants.js
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/S

#1266 fix: Add a filter file type
  server/components/boot.js
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1267 fix: Fix code editor value update
  src/components/Base/CodeEditor/index.jsx
  src/pages/clusters/containers/Clusters/AddCluster/Configuration/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1273 chore: Change arm64 base image
  Dockerfile.arm64
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1274 chore: Update webpack scripts and script loading strategy
  package.json
  scripts/webpack.base.js
  scripts/webpack.dev.js
  scripts/webpack.e2e.js
  scripts/webpack.prod.js
  scripts/webpack.server.js
  server/components/boot.js
  server/controllers/view.js
  server/libs/utils.js
  server/views/index.html
  src/actions/log.collection.js
  src/components/Forms/AlertingPolicy/AlertingRule/RuleForm/index.jsx
  src/components/Forms/ConfigMap/ConfigMapSettings/DataForm/index.jsx
  src/components/Forms/GrayRelease/Components/index.jsx
  src/components/Forms/ImageBuilder/B2IForm/BinaryFileUploader/index.jsx
  src/components/Forms/KafkaForm/Settings/index.jsx
  src/components/Forms/Pipelines/RepoSelect/subForm.jsx
  src/components/Forms/Route/RouteRules/RuleForm/index.jsx
  src/components/Forms/Secret/SecretSettings/DataForm/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/index.jsx
  src/components/Forms/Workload/VolumeSettings/AddVolume/index.jsx
  src/components/Forms/Workload/VolumeSettings/AddVolumeTemplate/index.jsx
  src/components/Forms/Workload/VolumeSettings/MountConfig/index.jsx
  src/components/Modals/LogCollectionCreate/config.js
  src/components/Modals/LogSearch/Logging/Detail/index.jsx
  src/components/Modals/WithBack/index.jsx
  src/core/App.jsx
  src/core/index.js
  src/pages/appStore/components/Banner/index.jsx
  src/pages/clusters/containers/Clusters/AddCluster/index.jsx
  src/pages/clusters/containers/LogCollections/config.js
  src/pages/devops/components/DetailNav/index.jsx
  src/pages/devops/components/Pipeline/StepsEditor/index.jsx
  src/pages/devops/components/Pipeline/StepsSelector/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Branch/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Layout/branch.jsx
  src/utils/index.js
  src/utils/index.test.js
  src/utils/request.js
  yarn.lock
Labels: approved, dco-signoff: yes, kind/update, lgtm, size/XXL

#1275 fix: Fix audit status code error
  src/components/Modals/AuditingSearch/Auditing/Detail/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1276 fix: Fix form onChange not response
  package.json
  yarn.lock
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1277 fix: Fix gateway loadBalancerIngress error
  src/pages/fedprojects/containers/AdvancedSettings/InternetAccess/Access/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1279 chore: Upgrade node version to v12.18
  .github/workflows/main.yaml
  Dockerfile
  Dockerfile.arm64
  README.md
  babel.config.js
  docker-compose.builder.yaml
  docker-compose.yaml
  package.json
  server/libs/utils.js
  server/server.js
  src/core/index.js
  src/utils/polyfills.js
  yarn.lock
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XXL
