Repository kubesphere/console, pull requests merged in 2020-09, with the labels that each got.

#1227 fix: Fix the incomplete URL substring sanitization
  cypress/integration/projects/deployments/detail.spec.js
  src/components/Cards/Banner/Tip.jsx
  src/components/Cards/Banner/index.jsx
  src/components/Modals/About/index.jsx
  src/components/Modals/History/index.jsx
  src/pages/apps/components/Cards/TestSteps/index.jsx
  src/pages/apps/components/Modals/AppCreate/index.jsx
  src/pages/apps/components/Modals/HelmUpload/index.jsx
  src/pages/clusters/containers/Clusters/AddCluster/Configuration/index.jsx
  src/pages/devops/components/Cards/CodeQualityIssues/issue.jsx
  src/pages/devops/components/Cards/CodeQualityResult/StatusCard.jsx
  src/pages/devops/containers/Pipelines/Detail/Artifacts/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Commit/index.jsx
  src/pages/fedprojects/containers/Overview/Help/index.jsx
  src/pages/fedprojects/containers/Routes/Detail/ResourceStatus/Rule/index.jsx
  src/pages/fedprojects/containers/Services/Detail/Ports/index.jsx
  src/pages/projects/containers/Applications/CRDAppDetail/Ingresses/Item.jsx
  src/pages/projects/containers/Overview/Help/index.jsx
  src/pages/projects/containers/Routes/Detail/ResourceStatus/Rule.jsx
  src/pages/settings/components/Modals/GithubOAuth/index.jsx
  src/pages/settings/containers/BaseInfo/index.jsx
  src/stores/devops/credential.js
  src/utils/constants.js
Labels: approved, dco-signoff: yes, lgtm, size/L

#1230 fix: start script support windows platform
  package.json
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1234 chore: Upgrade dependencies
  yarn.lock
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#1235 update: Restore pod and container select in log search
  src/components/Modals/LogSearch/Logging/Detail/index.jsx
  src/components/Modals/LogSearch/Logging/Detail/index.scss
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#1236 Update log receiver
  src/locales/en/logging.js
  src/locales/es/logging.js
  src/locales/tc/application.js
  src/locales/tc/logging.js
  src/locales/zh/application.js
  src/locales/zh/logging.js
  src/pages/clusters/containers/LogCollections/Detail/index.jsx
  src/pages/clusters/containers/LogCollections/index.jsx
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/M

#1239 fix: Fix volume create from snapshot spec error
  src/components/Base/TypeSelect/index.jsx
  src/components/Forms/Volume/VolumeSettings/SnapshotForm/index.jsx
  src/components/Forms/Volume/VolumeSettings/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1238 update: Restore pod and container select in log search
  src/components/Modals/LogSearch/Logging/Detail/index.jsx
  src/components/Modals/LogSearch/Logging/Detail/index.scss
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#1240 fix: Fix log search link error
  src/components/Modals/LogSearch/Logging/Detail/index.jsx
  src/stores/project.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1244 fix: Fix create volume from snapshot validating
  src/components/Forms/Volume/VolumeSettings/FormTemplate.jsx
  src/components/Forms/Volume/VolumeSettings/SnapshotForm/index.jsx
  src/components/Forms/Volume/VolumeSettings/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/S
