Repository kubesphere/console, pull requests merged in 2020-04, with the labels that each got.

#213 fix: Fix app template list and service create modal error
  src/pages/projects/components/Modals/ServiceCreate/index.jsx
  src/pages/projects/containers/Applications/index.jsx
Labels: approved, kind/bug, lgtm, size/M

#215 chore: Add ehancement issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement.md
Labels: approved, lgtm, size/S

#223 refactor: new montior api
  src/pages/clusters/containers/Nodes/index.jsx
  src/pages/clusters/containers/Overview/Dashboard/ClusterNodes/NodesTop5/index.jsx
Labels: approved, lgtm, size/S

#220 Refactor/new log collection
  src/components/Forms/Elasticsearch/Settings/index.jsx
  src/components/Forms/Fluentd/Settings/index.jsx
  src/components/Forms/KafkaForm/Settings/BrokersInput/index.jsx
  src/components/Forms/KafkaForm/Settings/index.jsx
  src/components/Forms/LoggingCollection/Status/index.jsx
  src/components/Modals/LogCollectionCreate/index.jsx
  src/pages/console/containers/LogCollection/Detail/Configuration/index.jsx
  src/pages/console/containers/LogCollection/Detail/Configuration/index.scss
  src/pages/console/containers/LogCollection/Detail/Log/index.scss
  src/pages/console/containers/LogCollection/Detail/YamlModal/index.jsx
  src/pages/console/containers/LogCollection/Detail/index.jsx
  src/pages/console/containers/LogCollection/Detail/index.scss
  src/pages/console/containers/LogCollection/config.js
  src/pages/console/containers/LogCollection/index.jsx
  src/pages/console/containers/LogCollection/index.scss
  src/pages/console/containers/MailServices/index.jsx
  src/pages/console/containers/MailServices/index.scss
  src/pages/console/routes/index.js
  src/pages/console/routes/logCollection.js
  src/pages/console/routes/platformSettings/index.js
  src/pages/settings/App.jsx
  src/pages/settings/actions/index.js
  src/pages/settings/actions/log.collection.js
  src/pages/settings/containers/LogCollection/Detail/Configuration/index.jsx
  src/pages/settings/containers/LogCollection/Detail/Log/index.jsx
  src/pages/settings/containers/LogCollection/Detail/index.jsx
  src/pages/settings/containers/LogCollection/Detail/routes.js
  src/pages/settings/containers/LogCollection/index.jsx
  src/pages/settings/routes/index.js
  src/pages/settings/routes/logCollection.js
  src/stores/logging/collection/output.js
  src/utils/object.mapper.js
Labels: approved, lgtm, size/XXL
