Repository kubesphere/console, pull requests merged in 2020-05, with the labels that each got.

#231 fix: cluster node count error
  src/pages/clusters/containers/Nodes/index.jsx
  src/stores/node.js
Labels: approved, lgtm, size/XS

#234 fix: Fix nav item rename error
  src/components/Layout/Nav/NavItem.jsx
  src/components/Layout/Nav/index.jsx
  src/components/Layout/Nav/item.jsx
Labels: approved, kind/bug, size/L

#235 fix: Remove unuse routes in pages/console
  src/pages/console/routes/component.js
  src/pages/console/routes/index.js
  src/pages/console/routes/monitoring/alerting/index.js
  src/pages/console/routes/monitoring/alerting/message.js
  src/pages/console/routes/monitoring/alerting/policy.js
  src/pages/console/routes/monitoring/applicationResource.js
  src/pages/console/routes/monitoring/clusterStatus.js
  src/pages/console/routes/monitoring/index.js
  src/pages/console/routes/volume.js
  src/pages/projects/components/Cards/HPA/index.jsx
Labels: approved, size/L

#236 update: Unify memory units
  src/configs/alerting/metrics/rule.config.js
  src/locales/zh/workload.js
  src/utils/monitoring.js
Labels: approved, kind/feature, size/S

#238 chore: support load locales on demand
  src/core/i18n.js
  src/core/index.js
  src/locales/index.js
Labels: approved, kind/feature, size/M

#241 update: Update toolbox and kubectl for multi clusters
  src/actions/toolbox.js
  src/components/Base/List/Item.jsx
  src/components/Cards/Containers/Item.jsx
  src/components/KubeCtl/index.jsx
  src/components/KubeCtl/index.scss
  src/components/KubeTools/index.jsx
  src/components/KubeTools/index.scss
  src/components/Modals/ContianerTerminal/index.jsx
  src/components/Modals/ContianerTerminal/index.scss
  src/components/Modals/KubeConfig/index.jsx
  src/components/Modals/KubeConfig/index.scss
  src/components/Modals/KubeCtl/index.jsx
  src/components/Modals/KubeCtl/index.scss
  src/core/App.jsx
  src/locales/zh/base.js
  src/pages/clusters/containers/KubeConfig/index.jsx
  src/pages/clusters/containers/Overview/Dashboard/Tools/index.jsx
  src/pages/clusters/routes/index.js
  src/pages/console/containers/AppTemplates/index.jsx
  src/pages/console/containers/AppTemplates/index.scss
  src/pages/console/containers/KubeConfig/index.jsx
  src/pages/console/containers/PlatformSettings/index.jsx
  src/pages/console/containers/PlatformSettings/index.scss
  src/pages/console/containers/Projects/index.jsx
  src/pages/console/containers/Projects/index.scss
  src/pages/console/containers/ServiceComponents/Card/index.jsx
  src/pages/console/containers/ServiceComponents/Card/index.scss
  src/pages/console/containers/ServiceComponents/Detail/ServiceDetails/index.jsx
  src/pages/console/containers/ServiceComponents/Detail/index.jsx
  src/pages/console/containers/ServiceComponents/index.jsx
  src/pages/console/containers/ServiceComponents/index.scss
  src/pages/console/routes/index.js
  src/pages/projects/containers/Pods/Containers/Detail.jsx
  src/stores/base.js
  src/stores/terminal.js
Labels: approved, kind/feature, lgtm, size/XXL

#239 Refactor/custom monitor
  src/components/Modals/CustomMonitoring/components/Form/Graph/index.jsx
  src/components/Modals/CustomMonitoring/components/Form/GraphTargetsForm/index.jsx
  src/components/Modals/CustomMonitoring/components/Form/ItemContianer/index.jsx
  src/components/Modals/CustomMonitoring/components/Form/SingleStatData/index.jsx
  src/components/Modals/CustomMonitoring/components/FormInput/TableColumnStyle/index.jsx
  src/components/Modals/CustomMonitoring/components/FormInput/Template/GrafanaTargetInput/index.jsx
  src/components/Modals/CustomMonitoring/components/Graph/Compose/index.jsx
  src/components/Modals/CustomMonitoring/components/TableColumnStyleModal/index.jsx
  src/components/Modals/CustomMonitoring/containers/GraphMonitorForm.jsx
  src/components/Modals/CustomMonitoring/containers/GraphMonitorOverview.jsx
  src/components/Modals/CustomMonitoring/containers/TableMonitorForm.jsx
  src/components/Modals/CustomMonitoring/options.js
  src/stores/monitoring/custom/monitor.js
  src/stores/monitoring/custom/template.js
  src/utils/monitoring.js
Labels: approved, lgtm, size/L

#243 fix: Fix k8s websocket error
  server/components/wsProxy.js
  src/components/HOCs/withList.js
  src/components/KubeTools/index.scss
  src/components/Tables/Base/index.jsx
  src/pages/clusters/containers/Nodes/index.jsx
  src/pages/clusters/containers/Projects/index.jsx
  src/pages/projects/containers/Applications/OPApps.jsx
  src/pages/projects/containers/CustomMonitoring/index.jsx
  src/utils/constants.js
Labels: approved, kind/bug, size/M

#245 update: change devops api from devops to devopsprojects
  src/actions/devops.js
  src/actions/volume.js
  src/components/Forms/CICDs/BaseInfo/index.jsx
  src/components/Modals/DevOpsEdit/index.jsx
  src/components/Modals/ProjectSelect/index.jsx
  src/components/Modals/WorkspaceSelect/index.jsx
  src/pages/console/containers/Dashboard/User/Resources/index.jsx
  src/pages/devops/components/Modals/DevOpsEdit/index.jsx
  src/pages/devops/containers/BaseInfo/index.jsx
  src/pages/devops/containers/Pipelines/index.jsx
  src/pages/devops/containers/layout.jsx
  src/pages/devops/routes/index.js
  src/pages/workspaces/containers/DevOps/index.jsx
  src/pages/workspaces/containers/Members/Detail/DevOps/index.jsx
  src/stores/devops.js
  src/stores/devops/base.js
  src/stores/devops/codeQuality.js
  src/stores/devops/cridential.js
  src/stores/devops/log.js
  src/stores/devops/pipelines.js
  src/stores/devops/run.js
  src/stores/devops/scm.js
  src/stores/monitoring/workspace.js
  src/utils/constants.js
  src/utils/object.mapper.js
Labels: approved, kind/api-change, lgtm, size/L

#249 fix: Fix openpitrix apps loading error
  src/components/Forms/AppTemplate/index.jsx
  src/components/KubeTools/index.jsx
  src/components/KubeTools/index.scss
  src/pages/apps/containers/Reviews/index.jsx
  src/pages/projects/components/Modals/DeployApp/index.jsx
  src/stores/openpitrix/application.js
Labels: approved, kind/bug, size/M

#257 fix: Fix workspace create error
  src/actions/resource.delete.js
  src/pages/access/containers/Workspaces/index.jsx
  src/pages/clusters/components/ResourceTable/ProjectSelect/index.jsx
  src/pages/workspaces/components/Modals/WorkspaceCreate/ClusterSettings/index.jsx
  src/pages/workspaces/components/ResourceTable/ClusterSelect/index.jsx
Labels: approved, kind/bug, size/S

#252 fix(monitoring): workspace monitor miss params
  src/pages/workspaces/containers/Overview/ResourceUsage/Physical/index.jsx
  src/pages/workspaces/containers/Overview/ResourceUsage/Physical/index.scss
  src/pages/workspaces/containers/Overview/ResourceUsage/Virtual/index.jsx
  src/pages/workspaces/containers/Overview/ResourceUsage/Virtual/index.scss
  src/pages/workspaces/containers/Overview/ResourceUsage/index.jsx
Labels: approved, lgtm, size/L

#255 feat: add helm chart form support
  src/components/Forms/AppTemplate/index.jsx
  src/components/Forms/ValuesYamlForm/index.jsx
  src/components/Forms/ValuesYamlForm/index.scss
Labels: approved, lgtm, size/L

#254 update:change pipeline api
  scripts/webpack.dev.js
  src/components/Forms/CICDs/AdvanceSettings/index.jsx
  src/components/Forms/CICDs/BaseInfo/index.jsx
  src/components/Forms/CICDs/RepoSelect/subForm.jsx
  src/components/Forms/CICDs/paramsModal.jsx
  src/pages/devops/containers/Cridential/credentialModal.jsx
  src/pages/devops/containers/Cridential/detail/index.jsx
  src/pages/devops/containers/Cridential/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Sider/pipeline-sider.jsx
  src/pages/devops/containers/Pipelines/Modals/editPipelineConfigModal.jsx
  src/pages/devops/containers/Pipelines/index.jsx
  src/stores/devops.js
  src/stores/devops/base.js
  src/stores/devops/cridential.js
  src/stores/devops/pipelines.js
  src/utils/constants.js
  src/utils/devops.js
  src/utils/object.mapper.js
Labels: approved, lgtm, size/L

#261 fix：delete a constant which is duplicate defined and unused 'Enter Workspace', there is a same constant 'View Workspace'
  src/locales/zh/workspace.js
Labels: approved, lgtm, size/XS

#262 update: Adapt pages for single cluster
  server/config.yaml
  server/locales/zh.properties
  server/services/session.js
  server/views/login.html
  src/actions/project.js
  src/actions/user.js
  src/components/Cards/Containers/Item.jsx
  src/components/Cards/Pods/Item.jsx
  src/components/Cards/Pods/index.jest.js
  src/components/Cards/Pods/index.jsx
  src/components/Inputs/InputPassword/index.jsx
  src/components/Inputs/InputPassword/index.scss
  src/components/Modals/KubeCtl/index.jsx
  src/components/Modals/Monitoring/ApplicationResource/index.jsx
  src/core/global.js
  src/locales/zh/cluster.js
  src/locales/zh/settings.js
  src/pages/clusters/components/Selector/index.jsx
  src/pages/clusters/containers/BaseInfo/index.jsx
  src/pages/clusters/containers/Nodes/Detail/Pods/index.jsx
  src/pages/clusters/containers/Overview/Dashboard/index.jsx
  src/pages/clusters/containers/Overview/index.jsx
  src/pages/clusters/containers/ServiceComponents/Detail/ServiceDetails/index.jsx
  src/pages/clusters/containers/Storage/VolumeSnapshots/index.jsx
  src/pages/clusters/containers/Visibility/index.jsx
  src/pages/clusters/containers/layout.jsx
  src/pages/clusters/routes/detail.js
  src/pages/clusters/routes/index.js
  src/pages/console/containers/Dashboard/Admin/index.jsx
  src/pages/projects/containers/BaseInfo/ProjectInfo/index.jsx
  src/pages/projects/containers/Overview/BaseInfo/index.jsx
  src/pages/projects/containers/Pods/Detail/index.jsx
  src/pages/projects/containers/StatefulSets/Detail/ResourceStatus.jsx
  src/pages/settings/components/Modals/GithubOAuth/index.jsx
  src/pages/settings/components/Modals/GithubOAuth/index.scss
  src/pages/settings/components/Modals/OAuth/index.jsx
  src/pages/settings/components/Modals/OAuth/index.scss
  src/pages/settings/containers/ThirdPartyLogin/index.jsx
  src/pages/workspaces/components/Modals/WorkspaceCreate/ClusterSettings/ClusterSelect/index.jsx
  src/pages/workspaces/components/Modals/WorkspaceCreate/ClusterSettings/ClusterSelect/index.scss
  src/pages/workspaces/components/Modals/WorkspaceCreate/ClusterSettings/index.jsx
  src/pages/workspaces/components/ResourceTable/ClusterSelect/index.jsx
  src/pages/workspaces/components/ResourceTable/index.jsx
  src/pages/workspaces/containers/Projects/index.jsx
  src/pages/workspaces/containers/layout.jsx
  src/stores/cluster/index.js
  src/stores/monitoring/base.js
  src/stores/monitoring/component.js
  src/stores/rank/index.js
  src/stores/workspace.js
  src/utils/constants.js
  src/utils/index.js
  src/utils/object.mapper.js
Labels: approved, kind/feature, size/XL

#265 fix: Fix language switch
  server/services/session.js
  src/components/Layout/LoginInfo/index.jsx
  src/components/Modals/UserSetting/BaseInfo/index.jsx
  src/components/Modals/UserSetting/index.jsx
  src/stores/user.js
Labels: approved, kind/bug, size/M

#266 Feat/network
  server/config.yaml
  src/actions/network.js
  src/components/Modals/Network/Policies/IpBlock.jsx
  src/components/Modals/Network/Policies/index.jsx
  src/components/Modals/Network/Policies/index.scss
  src/locales/en/network.js
  src/locales/zh/base.js
  src/locales/zh/network.js
  src/pages/clusters/containers/Network/Policies/index.jsx
  src/pages/clusters/containers/Network/Policies/index.scss
  src/pages/clusters/routes/detail.js
  src/pages/clusters/routes/index.js
  src/pages/projects/containers/Network/Policies/Detail/Egress/index.jsx
  src/pages/projects/containers/Network/Policies/Detail/Ingress/index.jsx
  src/pages/projects/containers/Network/Policies/Detail/index.jsx
  src/pages/projects/containers/Network/Policies/Detail/routes.js
  src/pages/projects/containers/Network/Policies/IsolateInfo/index.jsx
  src/pages/projects/containers/Network/Policies/IsolateInfo/index.scss
  src/pages/projects/containers/Network/Policies/RuleInfo/index.jsx
  src/pages/projects/containers/Network/Policies/RuleInfo/index.scss
  src/pages/projects/containers/Network/Policies/index.jsx
  src/pages/projects/containers/Network/Policies/index.scss
  src/pages/projects/routes/index.js
  src/stores/network.js
  src/utils/constants.js
  src/utils/form.templates.js
  src/utils/object.mapper.js
Labels: approved, lgtm, size/XXL

#268 update: unify app deploy modals with new design
  src/actions/openpitrix.js
  src/components/Base/Markdown/index.jsx
  src/components/Base/Modal/index.scss
  src/components/Base/Modal/modal.jsx
  src/components/Forms/AppDeploy/AppConfig/SchemaForm/index.jsx
  src/components/Forms/AppDeploy/AppConfig/SchemaForm/index.scss
  src/components/Forms/AppDeploy/AppConfig/index.jsx
  src/components/Forms/AppDeploy/AppConfig/index.scss
  src/components/Forms/AppDeploy/BasicInfo/Placement/index.jsx
  src/components/Forms/AppDeploy/BasicInfo/Placement/index.scss
  src/components/Forms/AppDeploy/BasicInfo/index.jsx
  src/components/Forms/AppDeploy/BasicInfo/index.scss
  src/components/Modals/CustomMonitoring/components/GraphTypeSelectModal/index.jsx
  src/pages/appStore/components/AppInfo/index.jsx
  src/pages/appStore/components/AppList/index.jsx
  src/pages/appStore/components/AppPreview/index.jsx
  src/pages/appStore/components/AppPreview/index.scss
  src/pages/appStore/components/Banner/index.scss
  src/pages/appStore/containers/AppDeploy/index.jsx
  src/pages/appStore/containers/AppDetail/index.jsx
  src/pages/appStore/containers/Home/index.jsx
  src/pages/apps/components/Cards/BaseInfo/index.jsx
  src/pages/apps/components/Lists/VersionList/Item.jsx
  src/pages/apps/components/Modals/AppDeploy/Steps/index.jsx
  src/pages/apps/components/Modals/AppDeploy/Steps/index.scss
  src/pages/apps/components/Modals/AppDeploy/index.jsx
  src/pages/apps/components/Modals/AppDeploy/index.scss
  src/pages/projects/components/Modals/DeployApp/index.jsx
  src/pages/projects/components/Modals/RepoApp/AppDetail/index.jsx
  src/pages/projects/components/Modals/RepoApp/AppDetail/index.scss
  src/pages/projects/components/Modals/RepoApp/index.jsx
  src/pages/projects/containers/Applications/OPApps.jsx
  src/pages/workspaces/containers/Apps/Detail/index.jsx
  src/scss/base.scss
Labels: approved, enhancement, size/XL

#270 fix: Fix app templates list actions
  src/components/Forms/AppTemplate/index.jsx
  src/components/Forms/AppTemplate/index.scss
  src/pages/appStore/containers/AppDetail/index.jsx
  src/pages/apps/containers/Templates/Detail/index.jsx
  src/pages/apps/containers/Templates/Detail/index.scss
  src/pages/apps/containers/Templates/Repos/Card/index.jsx
  src/pages/apps/containers/Templates/Repos/Card/index.scss
  src/pages/apps/containers/Templates/Repos/index.jsx
  src/pages/apps/containers/Templates/Repos/index.scss
  src/pages/apps/containers/Templates/index.jsx
  src/pages/apps/containers/Templates/index.scss
  src/pages/workspaces/containers/Apps/index.jsx
Labels: approved, kind/bug, size/XXL

#271 update: Show custom resource list in crd detail page.
  src/components/HOCs/withTableActions.js
  src/components/Modals/EditYaml/index.jsx
  src/components/Tables/Base/index.jsx
  src/core/containers/Base/Detail/Page/index.jsx
  src/core/containers/Base/Detail/Page/index.scss
  src/core/layouts/Base/index.scss
  src/locales/zh/base.js
  src/pages/clusters/containers/CustomResources/Detail/ConfigFile/index.jsx
  src/pages/clusters/containers/CustomResources/Detail/ResourceStatus/index.jsx
  src/pages/clusters/containers/CustomResources/Detail/ResourceStatus/index.scss
  src/pages/clusters/containers/CustomResources/Detail/index.jsx
  src/pages/clusters/containers/CustomResources/Detail/routes.js
  src/pages/clusters/containers/CustomResources/index.jsx
  src/stores/crd.resource.js
  src/utils/object.mapper.js
Labels: enhancement

#272 update: Update table empty state and add coding mode for composing app
  src/components/EditMode/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageSearch/DropdownContent.jsx
  src/components/HOCs/withList.js
  src/components/Modals/Create/index.jsx
  src/components/Tables/Base/Empty/index.jsx
  src/components/Tables/Base/Empty/index.scss
  src/components/Tables/Base/index.jsx
  src/locales/en/app.js
  src/locales/en/app_template.js
  src/locales/en/base.js
  src/locales/en/secret.js
  src/locales/en/user.js
  src/locales/zh/app.js
  src/locales/zh/app_template.js
  src/locales/zh/application.js
  src/locales/zh/base.js
  src/locales/zh/cluster.js
  src/locales/zh/crd.js
  src/locales/zh/network.js
  src/locales/zh/nodes.js
  src/locales/zh/project.js
  src/locales/zh/role.js
  src/locales/zh/secret.js
  src/locales/zh/storage.js
  src/locales/zh/user.js
  src/locales/zh/workload.js
  src/pages/access/containers/Accounts/index.jsx
  src/pages/access/containers/Roles/index.jsx
  src/pages/clusters/containers/Members/index.jsx
  src/pages/clusters/containers/Projects/Detail/Pods/index.jsx
  src/pages/clusters/containers/Roles/index.jsx
  src/pages/clusters/containers/Storage/Volumes/Detail/ResourceStatus/index.jsx
  src/pages/projects/components/Modals/CreateApp/BaseInfo/index.jsx
  src/pages/projects/components/Modals/CreateApp/Code/index.jsx
  src/pages/projects/components/Modals/CreateApp/Code/index.scss
  src/pages/projects/components/Modals/CreateApp/Services/index.jsx
  src/pages/projects/components/Modals/CreateApp/index.jsx
  src/pages/projects/components/Modals/CreateApp/index.scss
  src/pages/projects/containers/Applications/CRDApps.jsx
  src/pages/projects/containers/Applications/OPApps.jsx
  src/pages/projects/containers/Deployments/Detail/ResourceStatus/index.jsx
  src/pages/projects/containers/ImageBuilder/Detail/ResourceStatus/index.jsx
  src/pages/projects/containers/Jobs/index.jsx
  src/pages/projects/containers/Members/index.jsx
  src/pages/projects/containers/Roles/index.jsx
  src/pages/projects/containers/Routes/index.jsx
  src/pages/projects/containers/Services/Detail/ResourceStatus/index.jsx
  src/pages/projects/containers/Volumes/Detail/ResourceStatus/index.jsx
  src/pages/workspaces/components/Modals/WorkspaceCreate/index.scss
  src/pages/workspaces/containers/Apps/index.jsx
  src/pages/workspaces/containers/Members/index.jsx
  src/pages/workspaces/containers/Roles/index.jsx
  src/utils/index.js
  src/utils/index.test.js
Labels: approved, kind/feature, size/XL

#273 fix: Fix related resource delete
  src/actions/service.js
  src/actions/workload.js
  src/pages/clusters/containers/Overview/Dashboard/KubernetesStatus/index.jsx
  src/pages/clusters/containers/Overview/Dashboard/ResourcesUsage/index.scss
  src/pages/projects/components/Modals/CreateApp/Services/index.jsx
  src/pages/projects/components/Modals/CreateApp/index.jsx
  src/pages/projects/components/Modals/ServiceDelete/index.jsx
  src/pages/projects/components/Modals/WorkloadDelete/index.jsx
  src/pages/projects/containers/DaemonSets/Detail/index.jsx
  src/pages/projects/containers/DaemonSets/index.jsx
  src/pages/projects/containers/Deployments/Detail/index.jsx
  src/pages/projects/containers/Deployments/index.jsx
  src/pages/projects/containers/Services/Detail/index.jsx
  src/pages/projects/containers/Services/index.jsx
  src/pages/projects/containers/StatefulSets/Detail/index.jsx
  src/pages/projects/containers/StatefulSets/index.jsx
  src/stores/application/crd.js
  src/stores/base.js
  src/utils/constants.js
Labels: approved, kind/bug, size/L

#275 fix: Fix workspace kind
  src/utils/constants.js
  src/utils/form.templates.js
Labels: approved, kind/api-change, size/XS

#269 feat: custom monitor template selector
  package.json
  src/assets/elasticsearch.svg
  src/assets/mysql@2x.png
  src/assets/prometheus.svg
  src/assets/redis.svg
  src/components/Inputs/CardSelect/index.jsx
  src/locales/en/logging.js
  src/locales/zh/logging.js
  src/pages/projects/components/Modals/CustomMonitorBasic/index.jsx
  src/pages/projects/components/Modals/CustomMonitorBasic/index.scss
  src/pages/projects/containers/CustomMonitoring/CreateDashborad/index.jsx
  src/pages/projects/containers/CustomMonitoring/index.jsx
  src/stores/monitoring/custom/template.js
  src/stores/monitoring/custom/template.json
  yarn.lock
Labels: approved, kind/feature, lgtm, size/XL

#282 Refactor/custom monitor upgrade
  src/components/Modals/CustomMonitoring/components/Form/SingleStatData/index.jsx
  src/stores/monitoring/custom/template.js
  src/utils/monitoring.js
Labels: approved, lgtm, size/M

#284 fix: Remove unuse code in container form.
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageSearch/DropdownContent.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/index.jsx
  src/components/Forms/Workload/ContainerSettings/index.jsx
Labels: approved, kind/bug, size/M

#279 event search
  src/actions/toolbox.js
  src/components/KubeTools/index.jsx
  src/components/Modals/EventSearch/Event/Detail/MetadataModal/Metadata/index.jsx
  src/components/Modals/EventSearch/Event/Detail/MetadataModal/Metadata/index.scss
  src/components/Modals/EventSearch/Event/Detail/MetadataModal/index.jsx
  src/components/Modals/EventSearch/Event/Detail/MetadataModal/index.scss
  src/components/Modals/EventSearch/Event/Detail/index.jsx
  src/components/Modals/EventSearch/Event/Detail/index.scss
  src/components/Modals/EventSearch/Event/Detail/schema.js
  src/components/Modals/EventSearch/Event/Home/index.jsx
  src/components/Modals/EventSearch/Event/Home/index.scss
  src/components/Modals/EventSearch/Event/index.js
  src/components/Modals/EventSearch/Event/utils.js
  src/components/Modals/EventSearch/index.jsx
  src/locales/en/base.js
  src/locales/en/logging.js
  src/locales/zh/base.js
  src/locales/zh/logging.js
  src/pages/console/containers/EventSearch/index.jsx
  src/pages/console/routes/index.js
  src/stores/eventSearch.js
Labels: approved, lgtm, size/XXL

#287 Refactor/add storage class crd
  src/pages/clusters/containers/Storage/StorageClasses/Detail/Volumes/index.jsx
  src/pages/projects/containers/Volumes/Detail/index.jsx
  src/stores/storageclasscapabilities.js
  src/utils/constants.js
  src/utils/object.mapper.js
Labels: approved, lgtm, size/M

#289 fix: Save hide columns in localStorage by table id
  src/components/HOCs/withList.js
  src/components/Tables/Base/index.jsx
Labels: approved, kind/bug, lgtm, size/M

#286 refactor: remove old api of log query
  src/components/Modals/LogSearch/Logging/Detail/index.jsx
  src/components/Modals/LogSearch/Logging/Detail/index.scss
  src/stores/logging/index.js
  src/stores/logging/query.js
  src/stores/logging/statistics.js
Labels: approved, lgtm, size/L

#290 update: Update node resource request tip
  src/pages/clusters/containers/Nodes/index.jsx
  src/pages/clusters/containers/Nodes/index.scss
Labels: approved, size/M

#291 update: add cluster ahead of api used by devops
  src/actions/devops.js
  src/components/Forms/CICDs/AdvanceSettings/index.jsx
  src/components/Forms/CICDs/BaseInfo/index.jsx
  src/components/Forms/CICDs/RepoSelect/BitBucketForm/index.jsx
  src/components/Forms/CICDs/RepoSelect/GithubForm/index.jsx
  src/components/Forms/CICDs/RepoSelect/subForm.jsx
  src/components/HOCs/withList.js
  src/components/Modals/DevOpsEdit/index.jsx
  src/core/routes.js
  src/pages/devops/components/Modals/DevOpsEdit/index.jsx
  src/pages/devops/components/Pipeline/Sider/index.jsx
  src/pages/devops/components/Pipeline/StepsEditor/index.jsx
  src/pages/devops/components/Pipeline/StepsSelector/index.jsx
  src/pages/devops/components/Pipeline/store.js
  src/pages/devops/containers/BaseInfo/index.jsx
  src/pages/devops/containers/Credential/credentialModal.jsx
  src/pages/devops/containers/Credential/detail/activity.jsx
  src/pages/devops/containers/Credential/detail/index.jsx
  src/pages/devops/containers/Credential/index.jsx
  src/pages/devops/containers/Members/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Branch/index.jsx
  src/pages/devops/containers/Pipelines/Detail/PipeLine/index.jsx
  src/pages/devops/containers/Pipelines/Detail/PullRequest/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Sider/branch-sider.jsx
  src/pages/devops/containers/Pipelines/Detail/Sider/pipeline-sider.jsx
  src/pages/devops/containers/Pipelines/Detail/Sider/runs-sider.jsx
  src/pages/devops/containers/Pipelines/Modals/baseInfoModal.jsx
  src/pages/devops/containers/Pipelines/index.jsx
  src/pages/devops/containers/Roles/index.jsx
  src/pages/devops/containers/layout.jsx
  src/pages/devops/routes/credential/index.js
  src/pages/devops/routes/cridential/index.js
  src/pages/devops/routes/detail.js
  src/pages/devops/routes/index.js
  src/pages/devops/routes/pipeline/branch.js
  src/pages/devops/routes/pipeline/index.js
  src/pages/devops/routes/pipeline/run.js
  src/pages/workspaces/containers/DevOps/index.jsx
  src/pages/workspaces/containers/Projects/index.jsx
  src/stores/devops.js
  src/stores/devops/base.js
  src/stores/devops/codeQuality.js
  src/stores/devops/credential.js
  src/stores/devops/log.js
  src/stores/devops/pipelines.js
  src/stores/devops/run.js
  src/stores/devops/scm.js
  src/stores/user.js
Labels: approved, kind/api-change, lgtm, size/XL

#292 update: Add validation for cluster creating with kubeconfig
  server/config.yaml
  src/locales/zh/cluster.js
  src/pages/clusters/containers/Clusters/AddCluster/Configuration/index.jsx
  src/pages/clusters/containers/Clusters/AddCluster/Configuration/index.scss
  src/pages/clusters/containers/Clusters/AddCluster/index.jsx
  src/stores/cluster/index.js
Labels: approved, size/L

#293 update: Update authorization control
  server/config.yaml
  src/actions/role.js
  src/components/Cards/RuleList/index.jsx
  src/components/Forms/Role/AuthorizationSetting/Authorizations/index.jsx
  src/components/Forms/Role/AuthorizationSetting/Authorizations/index.scss
  src/components/Forms/Role/AuthorizationSetting/Authorizations/item.jsx
  src/components/Forms/Role/AuthorizationSetting/index.jsx
  src/components/Forms/Role/AuthorizationSetting/index.scss
  src/components/Forms/Role/BaseInfo/index.jsx
  src/components/Modals/EditAuthorization/CheckItem.jsx
  src/components/Modals/EditAuthorization/constants.js
  src/components/Modals/EditAuthorization/index.jsx
  src/components/Modals/EditAuthorization/index.scss
  src/components/Modals/RoleCreate/index.jsx
  src/components/Modals/RoleCreate/index.scss
  src/components/Modals/RoleCreate/steps.js
  src/locales/en/user.js
  src/locales/zh/base.js
  src/locales/zh/role.js
  src/locales/zh/user.js
  src/pages/access/containers/Roles/Detail/AuthorizationList/index.jsx
  src/pages/access/containers/Roles/Detail/index.jsx
  src/pages/access/containers/Roles/index.jsx
  src/pages/clusters/actions/cluster.js
  src/pages/clusters/containers/Roles/Detail/index.jsx
  src/pages/clusters/containers/Roles/index.jsx
  src/pages/clusters/containers/Visibility/index.jsx
  src/pages/devops/containers/Roles/Detail/index.jsx
  src/pages/devops/containers/Roles/index.jsx
  src/pages/projects/containers/Roles/Detail/index.jsx
  src/pages/projects/containers/Roles/index.jsx
  src/pages/workspaces/containers/Overview/ResourceUsage/index.jsx
  src/pages/workspaces/containers/Overview/UsageRanking/index.jsx
  src/pages/workspaces/containers/Projects/index.jsx
  src/pages/workspaces/containers/Roles/Detail/index.jsx
  src/pages/workspaces/containers/Roles/index.jsx
  src/stores/workspace.js
  src/utils/object.mapper.js
Labels: approved, kind/feature, size/XXL

#295 fix: Fix terminal link
  src/locales/zh/workload.js
  src/stores/terminal.js
Labels: approved, kind/bug, size/XS

#296 Fix/custom monitor save bug
  src/pages/projects/containers/CustomMonitoring/EditDashborad/index.jsx
  src/stores/monitoring/custom/monitor.js
Labels: lgtm, size/S

#297 feat: cluster networkpolicies management
  src/actions/network.js
  src/components/Modals/Network/Policies/AddByYaml.jsx
  src/locales/en/network.js
  src/locales/zh/network.js
  src/pages/clusters/containers/Network/Policies/index.jsx
  src/pages/projects/containers/Network/Policies/Detail/Egress/index.jsx
  src/pages/projects/containers/Network/Policies/Detail/Ingress/index.jsx
  src/pages/projects/containers/Network/Policies/Detail/Viewer/index.jsx
  src/pages/projects/containers/Network/Policies/Detail/Viewer/index.scss
  src/pages/projects/containers/Network/Policies/Detail/index.jsx
  src/pages/projects/containers/Network/Policies/Detail/routes.js
Labels: approved, kind/feature, lgtm, size/XL

#298 perf(custom-monitor): cache the graph list data
  src/components/Modals/CustomMonitoring/components/GraphOverviewLayout/index.jsx
  src/components/Modals/CustomMonitoring/components/GraphOverviewLayout/index.scss
  src/components/Modals/CustomMonitoring/containers/GraphOverview.jsx
  src/components/Modals/CustomMonitoring/index.jsx
  src/stores/monitoring/custom/monitor.js
Labels: approved, lgtm, size/M

#302 fix: Fix project search in cluster resource list
  src/components/Base/SearchSelect/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/index.jsx
  src/components/HOCs/withList.js
  src/components/Tables/Base/index.jsx
  src/locales/zh/cluster.js
  src/pages/clusters/components/ResourceTable/ProjectSelect/index.jsx
  src/pages/clusters/components/ResourceTable/ProjectSelect/index.scss
  src/pages/clusters/components/ResourceTable/index.jsx
  src/pages/clusters/containers/Projects/index.jsx
  src/pages/clusters/containers/Storage/VolumeSnapshots/index.jsx
  src/pages/clusters/containers/Storage/Volumes/index.jsx
  src/pages/clusters/containers/Workload/CronJobs/index.jsx
  src/pages/clusters/containers/Workload/DaemonSets/index.jsx
  src/pages/clusters/containers/Workload/Deployments/index.jsx
  src/pages/clusters/containers/Workload/Jobs/index.jsx
  src/pages/clusters/containers/Workload/Pods/index.jsx
  src/pages/clusters/containers/Workload/Routes/index.jsx
  src/pages/clusters/containers/Workload/Services/index.jsx
  src/pages/clusters/containers/Workload/StatefulSets/index.jsx
  src/pages/clusters/containers/layout.jsx
  src/scss/lego.custom.scss
  src/stores/base.list.js
  src/stores/cluster/index.js
Labels: approved, kind/bug, size/L

#300 Refine platform setting Chinese description
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  README.md
  src/locales/zh/base.js
Labels: approved, kind/documentation, lgtm, size/M

#304 fix: Fix some errs in devops inclue role and user
  src/components/Modals/InviteMember/index.jsx
  src/pages/devops/components/Pipeline/StepModals/git.jsx
  src/pages/devops/components/Pipeline/StepsSelector/index.jsx
  src/pages/devops/containers/Roles/index.jsx
  src/pages/projects/containers/Roles/index.jsx
  src/pages/workspaces/containers/Members/Detail/DevOps/index.jsx
  src/pages/workspaces/containers/Members/Detail/Projects/index.jsx
  src/pages/workspaces/containers/Members/Detail/index.jsx
  src/stores/devops.js
  src/stores/user.js
Labels: approved, kind/bug, lgtm, size/L
