Repository kubesphere/console, pull requests merged in 2020-06, with the labels that each got.

#308 feat: Add access history modal
  server/config.yaml
  server/services/session.js
  src/components/Base/Modal/modal.jsx
  src/components/Base/Tag/index.scss
  src/components/Base/Text/index.scss
  src/components/Forms/AppDeploy/BasicInfo/Placement/index.jsx
  src/components/Forms/AppDeploy/BasicInfo/index.jsx
  src/components/Forms/AppDeploy/BasicInfo/index.scss
  src/components/History/Card.jsx
  src/components/History/index.jsx
  src/components/History/index.scss
  src/components/Layout/GlobalNav/index.jsx
  src/components/Layout/GlobalNav/index.scss
  src/components/Modals/EditAuthorization/constants.js
  src/core/global.js
  src/core/layouts/Base/index.jsx
  src/locales/en/app.js
  src/locales/zh/app.js
  src/locales/zh/base.js
  src/locales/zh/role.js
  src/pages/apps/components/Modals/AppDeploy/index.jsx
  src/pages/apps/components/VersionSelect/index.jsx
  src/pages/apps/containers/layout.jsx
  src/pages/apps/containers/layout.scss
  src/pages/clusters/components/Cards/Cluster/index.jsx
  src/pages/clusters/components/Selector/index.jsx
  src/pages/clusters/containers/Monitor/Resource/Ranking/Project/Table/index.jsx
  src/pages/clusters/containers/Monitor/Resource/Ranking/Project/index.jsx
  src/pages/clusters/containers/Overview/Dashboard/index.jsx
  src/pages/clusters/containers/Storage/StorageClasses/Detail/Volumes/index.jsx
  src/pages/clusters/containers/layout.jsx
  src/pages/devops/containers/layout.jsx
  src/pages/projects/components/Modals/ServiceCreate/InApp.jsx
  src/pages/projects/components/Selector/index.jsx
  src/pages/projects/components/Selector/index.scss
  src/pages/projects/containers/Applications/Banner.jsx
  src/pages/projects/containers/Applications/CRDApps.jsx
  src/pages/projects/containers/Applications/OPApps.jsx
  src/pages/projects/containers/StatefulSets/Detail/ResourceStatus.jsx
  src/pages/projects/containers/StatefulSets/Detail/ServiceCard/index.jsx
  src/pages/projects/containers/layout.jsx
  src/pages/workspaces/components/Selector/index.jsx
  src/pages/workspaces/components/Selector/index.scss
  src/pages/workspaces/containers/DevOps/index.jsx
  src/pages/workspaces/containers/Projects/index.jsx
  src/pages/workspaces/containers/layout.jsx
  src/scss/base.scss
  src/stores/openpitrix/application.js
  src/stores/user.js
Labels: approved, kind/feature, size/XL

#309 fix: Hide history modal if item clicked.
  src/components/History/Card.jsx
  src/components/History/index.jsx
  src/components/History/index.scss
Labels: approved, kind/bug, size/XS

#310 refactor: add cluster selector for log query tools
  src/components/Modals/LogSearch/Logging/Detail/index.jsx
  src/components/Modals/LogSearch/Logging/Home/index.jsx
  src/components/Modals/LogSearch/Logging/Home/index.scss
  src/components/Modals/LogSearch/Logging/Search/index.jsx
  src/components/Modals/LogSearch/Logging/Search/index.scss
  src/components/Modals/LogSearch/index.jsx
  src/stores/logging/index.js
Labels: approved, lgtm, size/L

#312 fix: Fix version fetching status conditions in app deploy form
  src/components/Forms/AppDeploy/BasicInfo/index.jsx
  src/pages/appStore/containers/AppDeploy/index.jsx
  src/pages/apps/components/Modals/AppDeploy/index.jsx
Labels: approved, kind/bug, lgtm, size/XS

#311 fix: Fix toolbox trigger and position
  src/components/KubeTools/index.jsx
  src/components/KubeTools/index.scss
Labels: approved, kind/bug, lgtm, size/M

#313 chore: Update github workflow, remove preview deploy
  .github/workflows/main.yaml
Labels: approved, kind/bug, size/S

#307 Update locales
  server/locales/zh.properties
  server/views/login.html
  src/actions/toolbox.js
  src/components/KubeTools/index.jsx
  src/locales/en/base.js
  src/locales/en/nodes.js
  src/locales/zh/base.js
  src/locales/zh/cluster.js
  src/locales/zh/mail.js
  src/pages/clusters/containers/Overview/Dashboard/KubernetesStatus/index.jsx
  src/pages/clusters/containers/Overview/Dashboard/Tools/index.jsx
Labels: approved, kind/documentation, lgtm, size/M

#320 fix: Fix resource update when workload scale
  src/components/Cards/Pods/index.jsx
  src/pages/projects/components/Cards/ClusterWorkloadStatus/Cluster.jsx
  src/pages/projects/components/Cards/ClusterWorkloadStatus/index.jsx
  src/pages/projects/containers/Deployments/Detail/ResourceStatus/index.jsx
  src/pages/projects/containers/Services/Detail/ResourceStatus/index.jsx
  src/stores/federated.js
Labels: approved, kind/bug, lgtm, size/M

#318 fix: Fix cluster group label and application crd app creating error
  src/components/Modals/DevOpsCreate/index.jsx
  src/components/Modals/DevOpsCreate/index.scss
  src/components/Modals/ProjectCreate/index.jsx
  src/components/Modals/ProjectCreate/index.scss
  src/components/TextPreview/index.jsx
  src/locales/zh/app.js
  src/locales/zh/app_template.js
  src/locales/zh/service.js
  src/pages/appStore/components/AppPreview/index.jsx
  src/pages/apps/components/AppPreview/index.jsx
  src/pages/apps/components/Lists/VersionList/Item.jsx
  src/pages/apps/components/Modals/AppReview/index.jsx
  src/pages/apps/components/TextPreview/index.jsx
  src/pages/clusters/components/Cards/Cluster/index.jsx
  src/pages/clusters/components/Cards/Cluster/index.scss
  src/pages/clusters/containers/Overview/Dashboard/index.jsx
  src/pages/projects/components/Cards/ClusterWorkloadStatus/Cluster.jsx
  src/pages/projects/components/Modals/CreateApp/Code/index.scss
  src/pages/projects/components/Modals/CreateApp/index.jsx
  src/pages/projects/components/Modals/CreateApp/index.scss
  src/pages/projects/components/Modals/ServiceCreate/InApp.jsx
  src/pages/projects/containers/Services/Detail/ServiceAccess/ClusterService/index.jsx
  src/pages/projects/containers/Services/Detail/ServiceAccess/ClusterService/index.scss
Labels: approved, kind/bug, lgtm, size/L

#323 fix: update network-isolate status under project
  src/components/Modals/Network/Policies/index.scss
  src/pages/projects/containers/Network/Policies/IsolateInfo/index.scss
  src/pages/projects/containers/Network/Policies/index.jsx
Labels: approved, kind/flake, lgtm, size/M

#325 fix: Fix pod link error
  src/components/Base/Tag/index.scss
  src/components/Base/Text/index.jsx
  src/components/Base/Text/index.scss
  src/components/History/Card.jsx
  src/components/Inputs/SelectInput/index.jsx
  src/components/Inputs/SelectInput/index.scss
  src/pages/clusters/containers/Clusters/AddCluster/BaseInfo/index.jsx
  src/pages/clusters/containers/Projects/Detail/Pods/index.jsx
  src/pages/projects/components/Cards/ClusterWorkloadStatus/Cluster.jsx
  src/pages/projects/components/Cards/ClusterWorkloadStatus/index.scss
  src/pages/projects/containers/Deployments/Detail/ResourceStatus/index.jsx
  src/pages/projects/containers/ImageBuilder/Detail/ResourceStatus/index.jsx
  src/pages/projects/containers/Services/Detail/ResourceStatus/index.jsx
  src/pages/projects/containers/Services/Detail/ServiceAccess/ClusterService/index.jsx
  src/pages/projects/containers/Services/Detail/ServiceAccess/ClusterService/index.scss
  src/pages/projects/containers/Services/Detail/ServiceAccess/index.jsx
  src/pages/projects/containers/Volumes/Detail/ResourceStatus/index.jsx
  src/pages/projects/routes/detail.js
  src/pages/workspaces/components/Modals/WorkspaceCreate/ClusterSettings/ClusterSelect/index.jsx
  src/utils/constants.js
Labels: approved, kind/bug, size/L

#326 feat: edit yaml for custom monitoring dashboard
  src/components/Forms/Dashboard/BaseInfo/index.jsx
  src/components/Forms/Dashboard/BaseInfo/index.scss
  src/configs/steps/dashborads.js
  src/locales/zh/logging.js
  src/pages/projects/components/Modals/CustomMonitorBasic/index.jsx
  src/pages/projects/containers/CustomMonitoring/CreateDashborad/index.jsx
  src/pages/projects/containers/CustomMonitoring/index.jsx
  src/stores/monitoring/custom/template.json
  src/utils/constants.js
  src/utils/form.templates.js
Labels: approved, lgtm, size/L

#328 update: Unify cluster info with a common component
  src/components/Base/Tag/index.scss
  src/components/ClusterTitle/index.jsx
  src/components/ClusterTitle/index.scss
  src/components/History/Card.jsx
  src/components/History/index.jsx
  src/components/History/index.scss
  src/components/Inputs/SelectInput/index.jsx
  src/components/Inputs/SelectInput/index.scss
  src/components/Modals/DevOpsCreate/index.jsx
  src/components/Modals/ProjectCreate/index.jsx
  src/components/Modals/ProjectCreate/index.scss
  src/locales/en/base.js
  src/locales/zh/base.js
  src/pages/clusters/components/Cards/Cluster/index.jsx
  src/pages/clusters/components/Cards/Cluster/index.scss
  src/pages/clusters/components/Modals/ClusterSelect/Card/index.jsx
  src/pages/clusters/components/Modals/EditBasicInfo/index.jsx
  src/pages/clusters/containers/Clusters/AddCluster/BaseInfo/index.jsx
  src/pages/clusters/containers/Overview/Dashboard/index.jsx
  src/pages/clusters/containers/Overview/Dashboard/index.scss
  src/pages/clusters/containers/layout.jsx
  src/pages/projects/components/Cards/ClusterWorkloadStatus/Cluster.jsx
  src/pages/projects/containers/Services/Detail/ServiceAccess/ClusterService/index.jsx
  src/pages/projects/containers/Services/Detail/ServiceAccess/ClusterService/index.scss
  src/pages/workspaces/components/Modals/WorkspaceCreate/ClusterSettings/ClusterSelect/index.jsx
  src/pages/workspaces/components/Modals/WorkspaceCreate/ClusterSettings/ClusterSelect/index.scss
  src/scss/lego.custom.scss
  src/utils/constants.js
Labels: approved, kind/update, size/XL

#329 update: Update api for cluster members
  src/stores/user.js
Labels: approved, kind/api-change, size/S

#331 fix: Fix api for single cluster
  src/components/Terminal/index.jsx
  src/pages/workspaces/components/Modals/WorkspaceCreate/index.jsx
  src/stores/logging/index.js
  src/stores/terminal.js
Labels: approved, kind/bug, size/M

#334 chore(locales): Update english locales
  server/config.yaml
  src/components/Layout/LoginInfo/index.jsx
  src/locales/en/alerting.js
  src/locales/en/base.js
  src/locales/en/cluster.js
  src/locales/en/crd.js
  src/locales/en/network.js
  src/locales/en/nodes.js
  src/locales/en/role.js
  src/locales/en/storage.js
  src/locales/en/user.js
  src/locales/zh/app.js
  src/locales/zh/base.js
  src/locales/zh/network.js
  src/locales/zh/role.js
  src/pages/apps/containers/layout.jsx
  src/pages/console/containers/Dashboard/Admin/index.jsx
Labels: approved, lgtm, size/L

#335 Refactor/move mail service config to cluster console
  server/config.yaml
  src/components/Forms/MailServerForm/index.jsx
  src/pages/clusters/containers/MailServices/index.jsx
  src/pages/clusters/containers/MailServices/index.scss
  src/pages/clusters/routes/index.js
  src/stores/notification/mailService.js
Labels: approved, lgtm, size/L

#336 fix: Hide some pages in single cluster mode
  src/actions/devops.js
  src/pages/clusters/containers/BaseInfo/index.jsx
  src/pages/clusters/routes/index.js
  src/pages/projects/routes/detail.js
  src/pages/projects/routes/index.js
  src/pages/workspaces/components/Modals/WorkspaceCreate/index.jsx
  src/pages/workspaces/containers/DevOps/index.jsx
  src/stores/cluster/index.js
  src/stores/project.js
Labels: approved, kind/bug, size/S

#339 chore(locales): Update english locales
  server/config.yaml
  src/components/Base/Steps/index.jsx
  src/components/Modals/EditAuthorization/index.jsx
  src/locales/en/base.js
  src/locales/en/cluster.js
  src/locales/en/nodes.js
  src/locales/en/project.js
  src/locales/en/user.js
  src/locales/zh/app.js
  src/locales/zh/base.js
  src/locales/zh/cluster.js
  src/locales/zh/nodes.js
  src/locales/zh/project.js
  src/locales/zh/role.js
  src/pages/access/containers/layout.jsx
  src/pages/clusters/components/Modals/EditBasicInfo/index.jsx
  src/pages/clusters/containers/Clusters/AddCluster/BaseInfo/index.jsx
  src/pages/console/containers/Dashboard/Admin/PlatformStatus/index.jsx
Labels: approved, kind/documentation, size/L

#337 refactor: add ip metric in node rank list
  src/pages/clusters/containers/Overview/Dashboard/ClusterNodes/NodesTop5/index.jsx
Labels: approved, lgtm, size/XS

#340 fix: remove workspace param on fetch projects and services
  src/components/Modals/Network/Policies/index.jsx
  src/pages/projects/containers/Network/Policies/index.jsx
  src/pages/projects/containers/Network/Policies/index.scss
Labels: approved, kind/bug, lgtm, size/S

#341 En/update-Monitoring
  src/locales/en/monitoring.js
Labels: kind/documentation, size/M

#343 update: Update openpitrix application api
  src/actions/openpitrix.js
  src/actions/resource.delete.js
  src/pages/apps/components/Modals/AppDeploy/index.jsx
  src/pages/projects/containers/Applications/OPAppDetail/routes.js
  src/pages/projects/containers/Applications/OPApps.jsx
  src/pages/projects/routes/detail.js
  src/stores/openpitrix/app.js
  src/stores/openpitrix/application.js
  src/stores/openpitrix/base.js
  src/utils/object.mapper.js
Labels: approved, kind/api-change, size/L

#348 update: Use rules from upper level when no rules in current level
  server/config.yaml
  src/components/Layout/GlobalNav/item.jsx
  src/core/containers/Base/Detail/Page/index.jsx
  src/core/global.js
  src/locales/en/base.js
  src/locales/zh/base.js
  src/locales/zh/role.js
  src/pages/access/containers/Roles/index.jsx
  src/pages/clusters/components/Modals/ClusterSelect/index.jsx
  src/pages/clusters/containers/Clusters/index.jsx
  src/pages/devops/containers/layout.jsx
  src/pages/projects/containers/Base/Detail/index.jsx
  src/pages/projects/containers/layout.jsx
  src/stores/user.js
Labels: approved, kind/update, size/L

#350 chore: Update eslint
  .eslintrc.js
  package.json
  src/actions/role.js
  src/components/Graph/utils.js
  src/locales/en/monitoring.js
  src/locales/en/role.js
  src/locales/en/storage.js
  src/pages/clusters/actions/cluster.js
  src/pages/devops/components/Pipeline/store.js
  src/pages/settings/actions/log.collection.js
  src/stores/alerting/base.js
  src/stores/application/crd.js
  src/stores/devops.js
  src/stores/devops/codeQuality.js
  src/stores/devops/credential.js
  src/stores/devops/pipelines.js
  src/stores/devops/run.js
  src/stores/devops/scm.js
  src/stores/monitoring/custom/singlestat.js
  src/stores/monitoring/custom/template.js
  src/stores/openpitrix/runtime.js
  src/stores/role.js
  src/stores/s2i/run.js
  src/utils/devops.js
  src/utils/index.js
  src/utils/request.js
  src/utils/router.config.js
  src/utils/service.js
  src/utils/socket.client.js
  src/utils/status.js
  src/utils/tracing.js
  src/utils/volume.js
  yarn.lock
Labels: approved, kind/bug, size/XXL

#351 update: Update page control with ks mdoule
  src/components/KubeTools/index.jsx
  src/core/global.js
Labels: approved, kind/bug, size/S

#352 fix: Fix some link errors
  src/components/Cards/Containers/Item.jsx
  src/components/Cards/Pods/index.jsx
  src/core/global.js
  src/locales/en/base.js
  src/locales/zh/base.js
  src/pages/clusters/containers/Projects/Detail/Overview/index.jsx
  src/pages/console/routes/index.js
  src/pages/projects/containers/Overview/ResourceUsage/AppResourceItem/index.jsx
  src/pages/projects/containers/Overview/ResourceUsage/index.jsx
  src/pages/projects/containers/Overview/UsageRanking/index.jsx
  src/pages/projects/containers/Pods/Containers/Detail.jsx
  src/pages/projects/containers/Pods/Detail/index.jsx
  src/pages/projects/containers/Volumes/Detail/index.jsx
Labels: approved, kind/bug, size/L

#353 fix: Fix links in cluster project overview page
  src/pages/projects/containers/Overview/ResourceUsage/AppResourceItem/index.jsx
Labels: approved, kind/bug, size/XS

#354 update: Update apis to kapis in devops
  src/components/Forms/CICDs/RepoSelect/GithubForm/index.jsx
  src/components/Modals/ProjectSelect/index.jsx
  src/pages/devops/components/Pipeline/StepModals/withCredentials.jsx
  src/pages/devops/components/Pipeline/store.js
  src/pages/devops/containers/BaseInfo/index.jsx
  src/pages/devops/containers/Credential/index.jsx
  src/pages/devops/containers/Members/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Branch/index.jsx
  src/pages/devops/containers/Pipelines/Detail/PipeLine/index.jsx
  src/pages/devops/containers/Pipelines/Detail/PipeLine/jenkinsEdit.jsx
  src/pages/devops/containers/Pipelines/Detail/Sider/branch-sider.jsx
  src/pages/devops/containers/Pipelines/Detail/Sider/nav.jsx
  src/pages/devops/containers/Pipelines/Detail/Sider/pipeline-sider.jsx
  src/pages/devops/containers/Pipelines/Detail/Sider/runs-sider.jsx
  src/pages/devops/containers/Pipelines/Detail/TaskStatus/index.jsx
  src/pages/devops/containers/Pipelines/Modals/editPipelineConfigModal.jsx
  src/pages/devops/containers/Pipelines/Modals/scanRepositoryLogsModal.jsx
  src/pages/devops/containers/Pipelines/index.jsx
  src/pages/devops/containers/Roles/index.jsx
  src/pages/devops/containers/layout.jsx
  src/pages/workspaces/containers/DevOps/index.jsx
  src/stores/devops.js
  src/stores/devops/credential.js
  src/stores/devops/pipelines.js
  src/stores/devops/scm.js
  src/stores/monitoring/workspace.js
  src/utils/constants.js
  src/utils/devops.js
Labels: approved, kind/api-change, lgtm, size/XL

#355 fix: Fix some ks module dependencies
  src/components/Modals/EditAuthorization/constants.js
  src/components/Modals/EditAuthorization/index.jsx
  src/pages/access/containers/Accounts/index.jsx
  src/pages/console/containers/Dashboard/Admin/PlatformStatus/index.jsx
Labels: approved, kind/bug, size/M

#345 chore(locales): Update Chinese locales for workbench, crd, network
  src/locales/zh/base.js
  src/locales/zh/crd.js
  src/locales/zh/network.js
  src/pages/console/containers/Dashboard/Admin/PlatformStatus/index.jsx
  src/pages/settings/containers/BaseInfo/index.jsx
  src/pages/settings/containers/layout.jsx
Labels: approved, kind/documentation, lgtm, size/S

#346 update: update custom monitoring templates
  src/stores/monitoring/custom/template.json
Labels: approved, kind/bug, lgtm, size/XXL

#370 refactor: Refact store providers for page modules
  src/components/Base/List/Item.jsx
  src/core/App.jsx
  src/core/containers/Base/Detail/Page/index.jsx
  src/core/index.js
  src/core/layouts/List/index.scss
  src/pages/clusters/components/Modals/ClusterSelect/Card/index.jsx
  src/pages/clusters/components/Modals/ClusterSelect/Card/index.scss
  src/pages/clusters/containers/Base/Detail/index.jsx
  src/pages/clusters/containers/Base/List/index.jsx
  src/pages/clusters/containers/Workload/Pods/index.jsx
  src/pages/clusters/containers/layout.jsx
  src/pages/clusters/containers/layout.scss
  src/pages/clusters/routes/index.js
  src/pages/projects/App.jsx
  src/pages/projects/containers/Base/Detail/index.jsx
  src/pages/projects/containers/Base/List/index.jsx
  src/pages/projects/containers/ConfigMaps/Detail/index.jsx
  src/pages/projects/containers/CronJobs/Detail/index.jsx
  src/pages/projects/containers/DaemonSets/Detail/index.jsx
  src/pages/projects/containers/Deployments/Detail/ResourceStatus/index.jsx
  src/pages/projects/containers/Deployments/Detail/index.jsx
  src/pages/projects/containers/Jobs/Detail/index.jsx
  src/pages/projects/containers/Pods/Detail/index.jsx
  src/pages/projects/containers/Pods/index.jsx
  src/pages/projects/containers/Routes/Detail/index.jsx
  src/pages/projects/containers/Services/Detail/index.jsx
  src/pages/projects/containers/StatefulSets/Detail/index.jsx
  src/pages/projects/containers/Volumes/Detail/index.jsx
  src/pages/projects/containers/layout.jsx
  src/pages/projects/routes/index.js
  src/pages/workspaces/App.jsx
  src/pages/workspaces/containers/Base/List/index.jsx
  src/pages/workspaces/containers/Members/Detail/index.jsx
  src/pages/workspaces/containers/layout.jsx
  src/pages/workspaces/containers/layout.scss
  src/pages/workspaces/routes/index.js
Labels: approved, kind/update, size/XXL

#371 fix: Fix error content in storage class create modal
  src/components/Forms/StorageClass/ProvisionerSettings/index.jsx
Labels: approved, kind/bug, lgtm, size/XS

#374 fix: Fix issues
  src/components/Modals/RoleCreate/index.jsx
  src/components/Tables/Base/Empty/index.jsx
  src/locales/zh/cluster.js
  src/pages/clusters/containers/BaseInfo/index.jsx
  src/pages/clusters/containers/CustomResources/Detail/ResourceStatus/index.jsx
  src/pages/clusters/containers/CustomResources/index.jsx
  src/pages/clusters/containers/Nodes/index.jsx
  src/pages/clusters/containers/Overview/Dashboard/ClusterInfo/index.jsx
  src/pages/clusters/containers/Overview/Dashboard/ServiceComponents/index.jsx
  src/pages/clusters/containers/Overview/Dashboard/ServiceComponents/index.scss
  src/pages/clusters/containers/Overview/Dashboard/index.jsx
  src/pages/clusters/containers/Projects/Detail/index.jsx
  src/pages/clusters/containers/ServiceComponents/index.jsx
  src/stores/cluster/index.js
Labels: approved, kind/bug, size/L

#368 chore(locales): Update En loc
  src/locales/en/application.js
  src/locales/en/monitoring.js
  src/locales/en/network.js
  src/locales/en/role.js
  src/locales/en/workload.js
Labels: approved, kind/documentation, lgtm, size/M

#372 fix: Generated an appropriate file name when download yaml
  src/components/EditMode/index.jsx
Labels: approved, kind/bug, size/S

#375 docs(custom-monitoring): add english translation
  src/locales/en/monitoring.js
  src/locales/zh/monitoring.js
Labels: approved, lgtm, size/XS

#380 fix: Fix data merge error in container settings form
  src/components/Forms/Workload/ContainerSettings/ContainerForm/Commands/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/index.jsx
  src/components/Forms/Workload/ContainerSettings/index.jsx
Labels: approved, kind/bug, size/S

#378 fix: Fix log search api
  src/components/Modals/LogSearch/index.jsx
  src/utils/index.js
  src/utils/object.mapper.js
Labels: approved, kind/bug, size/S

#382 chore(locales): En UI update
  src/locales/en/app_repo.js
  src/locales/en/app_store.js
  src/locales/en/base.js
  src/locales/en/cluster.js
  src/locales/en/crd.js
  src/locales/en/monitoring.js
  src/locales/en/secret.js
  src/locales/en/workload.js
  src/locales/en/workspace.js
Labels: approved, lgtm, size/M

#386 fix: Replace double slash in url
  src/utils/index.js
Labels: approved, kind/bug, size/XS

#388 fix: Fix custom monitoring nav authKey
  server/config.yaml
  src/locales/zh/monitoring.js
Labels: approved, kind/bug, size/XS

#389 fix: Fix redis default maxAge
  server/store/index.js
Labels: approved, kind/bug, size/XS

#387 fix: Fix devops create time in the table
  src/components/Modals/ProjectSelect/index.jsx
  src/pages/devops/components/Pipeline/Sider/index.jsx
  src/pages/devops/containers/BaseInfo/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Sider/pipeline-sider.jsx
  src/pages/devops/containers/Pipelines/Detail/Sider/runs-sider.jsx
  src/pages/devops/containers/Pipelines/index.jsx
  src/pages/workspaces/containers/DevOps/index.jsx
  src/stores/devops.js
  src/utils/devops.js
Labels: approved, kind/bug, lgtm, size/M

#390 chores(locales): Update En UI
  src/components/Cards/LogQuery/index.jsx
  src/components/Cards/Monitoring/Controller/TimeSelector/Range/Custom.jsx
  src/components/Cards/Monitoring/Controller/TimeSelector/Range/Default.jsx
  src/components/Forms/AlertingPolicy/AlertingRule/RuleForm/index.jsx
  src/components/Layout/Header/index.jsx
  src/components/Modals/CustomMonitoring/components/TimeRangeSelect/index.jsx
  src/components/Modals/EventSearch/Event/Home/index.jsx
  src/components/Modals/InviteMember/index.jsx
  src/components/Modals/Network/Policies/index.jsx
  src/components/Tables/Visible/index.jsx
  src/locales/en/alerting.js
  src/locales/en/base.js
  src/locales/en/monitoring.js
  src/locales/en/network.js
  src/locales/en/project.js
  src/locales/zh/base.js
  src/locales/zh/logging.js
  src/locales/zh/monitoring.js
  src/locales/zh/network.js
  src/locales/zh/project.js
  src/pages/devops/containers/Members/index.jsx
  src/pages/projects/containers/Members/index.jsx
  src/pages/projects/containers/Network/Policies/RuleInfo/index.jsx
Labels: approved, kind/documentation, lgtm, size/L

#398 fix: Fix project roles fetch path
  src/stores/role.js
Labels: approved, kind/bug, size/S

#399 fix: Add empty tip if workspace has no cluster
  server/config.yaml
  src/actions/project.js
  src/components/Modals/ProjectCreate/index.jsx
  src/locales/en/workspace.js
  src/locales/zh/workspace.js
  src/pages/clusters/containers/layout.jsx
  src/pages/workspaces/components/Modals/WorkspaceCreate/BaseInfo/index.jsx
  src/pages/workspaces/components/Modals/WorkspaceCreate/ClusterSettings/ClusterSelect/index.jsx
  src/pages/workspaces/components/ResourceTable/index.jsx
  src/pages/workspaces/containers/BaseInfo/index.jsx
  src/pages/workspaces/containers/BaseInfo/index.scss
  src/pages/workspaces/containers/Clusters/index.jsx
  src/pages/workspaces/containers/Overview/ResourceUsage/index.jsx
  src/pages/workspaces/containers/Overview/UsageRanking/index.jsx
Labels: approved, kind/bug, size/L

#400 fix: Fix service components in cluster overview page
  src/pages/clusters/containers/Overview/Dashboard/ServiceComponents/index.jsx
Labels: approved, kind/bug, size/M

#391 fix: hide 404 when storageclasscapabilities is not exist
  src/pages/projects/containers/Volumes/Detail/index.jsx
  src/stores/storageclasscapabilities.js
Labels: approved, lgtm, size/M

#392 fix(custom-monitoring): batch delete custom monitoring dashboards error
  src/pages/projects/containers/CustomMonitoring/index.jsx
Labels: approved, lgtm, size/S

#393 fix: Fix the PullRequest table bug
  src/pages/devops/containers/Pipelines/Detail/PullRequest/index.jsx
Labels: approved, lgtm, size/XS

#395 fix(custom-monitoring): long-text-layout-error
  src/components/Modals/CustomMonitoring/components/RowsSortItem/index.scss
Labels: approved, lgtm, size/XS

#396 fix(custom-monitor): can not generete metirc id when __name__ is null
  src/stores/monitoring/custom/monitor.js
Labels: approved, lgtm, size/XS

#401 fix: Fix project creation in workspace
  src/actions/project.js
  src/components/Modals/Monitoring/ApplicationResource/index.jsx
  src/pages/workspaces/containers/Overview/ResourceUsage/Physical/index.jsx
  src/pages/workspaces/containers/Overview/ResourceUsage/Virtual/index.jsx
  src/pages/workspaces/containers/Overview/ResourceUsage/index.jsx
  src/stores/devops.js
  src/stores/monitoring/cluster.js
  src/stores/monitoring/workspace.js
  src/stores/project.js
Labels: approved, kind/bug, size/M

#402 fix: Fix image search error
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/index.jsx
Labels: approved, kind/bug, size/XS

#397 Chores(locales): Update En UI
  src/components/Cards/RankTable/WorkspaceTable/index.jsx
  src/components/Cards/Tips/index.jsx
  src/components/Modals/CustomMonitoring/containers/RefreshIntervalSelector.jsx
  src/components/Modals/LogSearch/Logging/Home/index.jsx
  src/components/Modals/ProjectCreate/index.jsx
  src/components/Modals/QuotaEdit/Quotas/Item.jsx
  src/locales/en/base.js
  src/locales/en/component.js
  src/locales/en/monitoring.js
  src/locales/en/nodes.js
  src/locales/en/role.js
  src/locales/en/sort_rank.js
  src/locales/en/terminal.js
  src/locales/en/workload.js
  src/locales/zh/cluster.js
  src/locales/zh/dashboard.js
  src/locales/zh/logging.js
  src/locales/zh/monitoring.js
  src/locales/zh/project.js
  src/locales/zh/workload.js
  src/pages/clusters/containers/Monitor/Resource/Ranking/Project/Table/index.jsx
  src/pages/clusters/containers/Overview/Dashboard/KubernetesStatus/index.jsx
  src/pages/projects/containers/AdvancedSettings/InternetAccess/index.jsx
  src/pages/projects/containers/Deployments/Detail/Monitoring/index.jsx
  src/pages/projects/containers/Pods/Detail/Monitoring.jsx
  src/pages/projects/containers/Pods/Detail/ScheduleInfo/index.jsx
  src/pages/projects/containers/Pods/Detail/routes.js
  src/pages/projects/containers/Routes/index.jsx
Labels: approved, kind/documentation, lgtm, size/L

#404 fix: adjust the network policy creation logic and optimize the ui di…
  server/config.yaml
  src/components/Modals/Network/Policies/IpBlock.jsx
  src/components/Modals/Network/Policies/index.jsx
  src/components/Modals/Network/Policies/index.scss
  src/locales/en/network.js
  src/locales/zh/network.js
  src/pages/projects/containers/Network/Policies/RuleInfo/index.jsx
  src/pages/projects/containers/Network/Policies/RuleInfo/index.scss
  src/pages/projects/containers/Network/Policies/index.jsx
Labels: approved, kind/flake, lgtm, size/L

#406 chores(locales): EN UI update
  server/config.yaml
  src/components/Inputs/InputPassword/index.jsx
  src/locales/en/app.js
  src/locales/en/app_repo.js
  src/locales/en/application.js
  src/locales/en/base.js
  src/locales/en/cluster.js
  src/locales/en/devops.js
  src/locales/en/project.js
  src/locales/en/role.js
  src/locales/en/service.js
  src/locales/en/storage.js
  src/locales/en/user.js
  src/locales/en/workload.js
  src/locales/en/workspace.js
  src/locales/zh/base.js
  src/locales/zh/user.js
  src/locales/zh/workspace.js
  src/pages/access/containers/Workspaces/index.jsx
  src/pages/access/containers/layout.jsx
  src/pages/console/components/Cards/Workspace/index.jsx
  src/pages/workspaces/components/Modals/WorkspaceCreate/BaseInfo/index.jsx
  src/pages/workspaces/components/Modals/WorkspaceSelect/Card/index.jsx
  src/pages/workspaces/containers/Clusters/index.jsx
Labels: approved, kind/documentation, lgtm, size/L

#407 update: Update openpitrix api
  src/actions/openpitrix.js
  src/components/Forms/AppDeploy/BasicInfo/Placement/index.jsx
  src/pages/apps/components/Forms/AppDeploy/index.jsx
  src/pages/apps/components/Forms/AppDeploy/index.scss
  src/pages/apps/components/Lists/VersionList/Item.jsx
  src/pages/projects/containers/Applications/OPAppDetail/routes.js
  src/pages/projects/containers/Applications/OPApps.jsx
  src/pages/projects/containers/Overview/Applications/index.jsx
  src/pages/projects/routes/detail.js
  src/stores/openpitrix/app.js
  src/stores/openpitrix/application.js
Labels: approved, kind/api-change, size/XL

#409 chores(locales): EN loc update
  src/components/Base/Avatar/index.jsx
  src/components/Modals/AssignWorkspace/index.jsx
  src/components/Modals/ModifyPassword/index.jsx
  src/locales/en/app.js
  src/locales/en/application.js
  src/locales/en/base.js
  src/locales/en/project.js
  src/locales/en/role.js
  src/locales/zh/app.js
  src/locales/zh/base.js
  src/locales/zh/cluster.js
  src/locales/zh/project.js
  src/locales/zh/user.js
  src/pages/access/containers/Accounts/Detail/index.jsx
  src/pages/apps/components/Cards/BaseInfo/index.jsx
  src/pages/apps/components/Forms/AppBaseEdit/index.jsx
  src/pages/clusters/containers/Clusters/AddCluster/Configuration/index.jsx
  src/pages/projects/containers/Overview/Help/index.jsx
Labels: approved, kind/documentation, lgtm, size/M

#410 fix: Fix the params of s2irun and the DevOps data isn't refreshed bug
  src/pages/devops/containers/Roles/Detail/index.jsx
  src/pages/projects/containers/ImageBuilder/Detail/index.jsx
  src/pages/workspaces/containers/DevOps/index.jsx
  src/stores/devops.js
  src/stores/s2i/builder.js
Labels: approved, lgtm, size/M

#411 update: Update pages for normal user
  server/config.yaml
  server/services/session.js
  src/components/Layout/Header/index.jsx
  src/components/Modals/ProjectCreate/index.jsx
  src/core/containers/Base/Detail/Page/index.jsx
  src/pages/access/containers/layout.jsx
  src/pages/access/routes/index.js
  src/pages/clusters/containers/Projects/Detail/index.jsx
  src/pages/clusters/containers/Projects/index.jsx
  src/pages/console/containers/Dashboard/User/Resources/Card/index.jsx
  src/pages/console/containers/Dashboard/User/Resources/Card/index.scss
  src/pages/console/containers/Dashboard/User/Resources/index.jsx
  src/pages/console/containers/Dashboard/User/Resources/index.scss
  src/pages/console/containers/Dashboard/User/Workspaces/index.jsx
  src/pages/console/containers/Dashboard/User/Workspaces/index.scss
  src/pages/console/containers/Dashboard/User/index.jsx
  src/pages/console/containers/Dashboard/User/index.scss
  src/pages/console/containers/Dashboard/index.jsx
  src/pages/settings/containers/LogCollection/index.jsx
  src/pages/workspaces/components/Modals/WorkspaceCreate/index.jsx
  src/pages/workspaces/containers/BaseInfo/index.jsx
  src/pages/workspaces/containers/Projects/index.jsx
  src/stores/project.js
  src/stores/secret.js
  src/stores/user.js
Labels: approved, kind/api-change, size/XXL

#412 EN UI update
  src/components/Forms/AlertingPolicy/NotificationRule/index.jsx
  src/components/Forms/GrayRelease/Components/Card/index.jsx
  src/components/Tables/Base/index.jsx
  src/locales/en/alerting.js
  src/locales/en/application.js
  src/locales/en/base.js
  src/locales/en/grayrelease.js
  src/locales/en/logging.js
  src/locales/en/monitoring.js
  src/locales/en/network.js
  src/locales/en/s2i.js
  src/locales/zh/alerting.js
  src/locales/zh/base.js
  src/locales/zh/grayrelease.js
  src/utils/constants.js
Labels: approved, lgtm, size/M

#414 fix: create custom monitor dashboard error in yaml mode
  src/pages/projects/containers/CustomMonitoring/CreateDashborad/index.jsx
  src/utils/monitoring.js
Labels: approved, lgtm, size/S

#415 fix: Fix issues
  src/actions/service.js
  src/components/Cards/Monitoring/Controller/index.jsx
  src/components/Cards/Pods/index.jsx
  src/components/Forms/Route/RouteRules/RuleList/index.jsx
  src/components/Forms/Route/RouteRules/index.jsx
  src/components/Forms/Workload/ContainerSettings/index.jsx
  src/components/HOCs/withList.js
  src/core/global.js
  src/locales/en/cluster.js
  src/locales/zh/cluster.js
  src/pages/clusters/containers/Clusters/AddCluster/Configuration/index.jsx
  src/pages/clusters/containers/Projects/Detail/index.jsx
  src/pages/fedprojects/containers/Deployments/Detail/ResourceStatus/index.jsx
  src/pages/fedprojects/containers/Services/Detail/ResourceStatus/index.jsx
  src/pages/projects/components/Modals/CreateApp/Routes/RuleList/index.jsx
  src/pages/projects/containers/CronJobs/Detail/index.jsx
  src/pages/projects/containers/Jobs/Detail/index.jsx
  src/pages/projects/containers/Routes/Detail/ResourceStatus/Rule.jsx
  src/pages/projects/containers/Routes/Detail/ResourceStatus/index.scss
  src/pages/projects/containers/Routes/Detail/index.jsx
  src/pages/projects/containers/Services/Detail/index.jsx
Labels: approved, kind/bug, size/L

#416 fix: Fix project create url error
  src/actions/project.js
  src/pages/workspaces/containers/FedProjects/index.jsx
  src/stores/project.js
Labels: approved, kind/bug, size/M

#418 fix: Fix federated svc resource status
  src/pages/fedprojects/containers/Services/Detail/ResourceStatus/index.jsx
Labels: approved, kind/bug, size/M

#419 update: Update the role authority in devops
  src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Branch/index.jsx
  src/pages/devops/containers/Pipelines/Detail/PipeLine/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Sider/branch-sider.jsx
  src/pages/devops/containers/Pipelines/Detail/Sider/pipeline-sider.jsx
  src/pages/devops/containers/Pipelines/Detail/Sider/runs-sider.jsx
  src/pages/devops/containers/Pipelines/index.jsx
Labels: kind/bug, size/S

#421 fix: Fix ks module page control, Add cluster module controle
  server/config.yaml
  src/components/Cards/RankTable/NodeTable/index.jsx
  src/components/Forms/AppDeploy/BasicInfo/Placement/index.jsx
  src/components/Forms/Workload/VolumeSettings/index.jsx
  src/components/Inputs/EnvironmentInput/Item.jsx
  src/components/KubeTools/index.jsx
  src/components/Modals/EditAuthorization/constants.js
  src/components/Modals/ProjectSelect/index.jsx
  src/core/global.js
  src/core/routes.js
  src/pages/clusters/containers/Monitor/Cluster/Overview/index.jsx
  src/pages/clusters/containers/Monitor/Resource/Usage/Statistics/index.jsx
  src/pages/clusters/containers/Overview/Dashboard/ServiceComponents/index.jsx
  src/pages/clusters/containers/ServiceComponents/index.jsx
  src/pages/clusters/containers/layout.jsx
  src/pages/console/components/Cards/Workspace/index.jsx
  src/pages/devops/containers/BaseInfo/index.jsx
  src/pages/devops/containers/layout.jsx
  src/pages/fedprojects/App.jsx
  src/pages/fedprojects/containers/AdvancedSettings/InternetAccess/Access/index.jsx
  src/pages/fedprojects/containers/AdvancedSettings/index.jsx
  src/pages/fedprojects/containers/Applications/Detail/routes.js
  src/pages/fedprojects/containers/BaseInfo/ProjectInfo/index.jsx
  src/pages/fedprojects/containers/BaseInfo/index.jsx
  src/pages/fedprojects/containers/Overview/BaseInfo/index.jsx
  src/pages/projects/App.jsx
  src/pages/projects/components/Modals/CreateApp/index.jsx
  src/pages/projects/components/Modals/GatewaySetting/index.jsx
  src/pages/projects/components/Modals/ServiceCreate/index.jsx
  src/pages/projects/containers/AdvancedSettings/InternetAccess/index.jsx
  src/pages/projects/containers/AdvancedSettings/index.jsx
  src/pages/projects/containers/Applications/CRDAppDetail/routes.js
  src/pages/projects/containers/Applications/CRDApps.jsx
  src/pages/projects/containers/Applications/OPAppDetail/routes.js
  src/pages/projects/containers/BaseInfo/ProjectInfo/index.jsx
  src/pages/projects/containers/BaseInfo/index.jsx
  src/pages/projects/containers/GrayRelease/Categories/index.jsx
  src/pages/projects/containers/GrayRelease/Jobs/index.jsx
  src/pages/projects/containers/Overview/BaseInfo/index.jsx
  src/pages/projects/containers/Overview/ResourceUsage/index.jsx
  src/pages/projects/routes/grayrelease.js
  src/pages/projects/routes/imagebuilder.js
  src/pages/projects/routes/index.js
  src/pages/workspaces/components/Modals/WorkspaceSelect/Card/index.jsx
  src/pages/workspaces/components/ResourceTable/ClusterSelect/index.jsx
  src/pages/workspaces/components/ResourceTable/index.jsx
  src/pages/workspaces/containers/DevOps/index.jsx
  src/pages/workspaces/containers/Overview/ResourceUsage/Statistics/index.jsx
  src/pages/workspaces/containers/Projects/index.jsx
  src/pages/workspaces/routes/index.js
  src/stores/openpitrix/application.js
  src/stores/workspace.js
  src/utils/router.config.js
Labels: approved, kind/bug, size/XL

#420 En UI update
  src/components/Base/Steps/index.jsx
  src/components/Cards/ProjectQuota/QuotaItem/index.jsx
  src/components/Forms/AlertingPolicy/AlertingRule/RuleForm/index.jsx
  src/components/Forms/ImageBuilder/S2IForm/index.jsx
  src/components/Forms/MailServerForm/index.jsx
  src/components/Forms/StorageClass/BaseInfo/index.jsx
  src/components/Forms/StorageClass/StorageClassSettings/index.jsx
  src/components/Forms/Workload/VolumeSettings/AddExistVolumes/index.jsx
  src/components/Forms/Workload/VolumeSettings/index.jsx
  src/locales/en/alerting.js
  src/locales/en/application.js
  src/locales/en/cluster.js
  src/locales/en/ingress.js
  src/locales/en/mail.js
  src/locales/en/monitoring.js
  src/locales/en/network.js
  src/locales/en/project.js
  src/locales/en/role.js
  src/locales/en/storage.js
  src/locales/zh/alerting.js
  src/locales/zh/base.js
  src/locales/zh/network.js
  src/locales/zh/project.js
  src/locales/zh/storage.js
  src/locales/zh/workload.js
  src/pages/clusters/containers/Alerting/Policies/Card/index.jsx
  src/pages/clusters/containers/Alerting/Policies/index.jsx
  src/pages/clusters/containers/Storage/StorageClasses/Detail/index.jsx
  src/pages/fedprojects/containers/AdvancedSettings/LogCollection/index.jsx
  src/pages/fedprojects/containers/AdvancedSettings/index.jsx
  src/pages/fedprojects/containers/Alerting/Policies/index.jsx
  src/pages/fedprojects/containers/QuotaManage/ResourceQuota/QuotaItem/index.jsx
  src/pages/projects/containers/AdvancedSettings/LogCollection/index.jsx
  src/pages/projects/containers/AdvancedSettings/index.jsx
  src/pages/projects/containers/Alerting/Policies/index.jsx
  src/pages/projects/containers/BaseInfo/ResourceQuota/QuotaItem/index.jsx
Labels: approved, kind/documentation, lgtm, size/L

#424 fix: Add cluster select in project selector
  src/components/Forms/Workload/ClusterDiffSettings/ContainerImage/index.jsx
  src/components/Modals/ProjectSelect/index.jsx
  src/components/Modals/ProjectSelect/index.scss
  src/locales/zh/base.js
  src/pages/clusters/components/Modals/EditBasicInfo/index.jsx
  src/pages/clusters/containers/Clusters/AddCluster/BaseInfo/index.jsx
  src/pages/fedprojects/containers/Base/List/index.jsx
  src/pages/projects/components/Selector/index.jsx
  src/pages/workspaces/components/Modals/WorkspaceCreate/ClusterSettings/ClusterSelect/index.jsx
  src/pages/workspaces/containers/DevOps/index.jsx
  src/pages/workspaces/containers/Projects/index.jsx
  src/stores/workspace.js
  src/utils/constants.js
Labels: approved, kind/bug, size/L

#423 fix: Not allowed to select a cluster without Devops
  src/components/Modals/DevOpsCreate/index.jsx
  src/components/Modals/DevOpsCreate/index.scss
  src/locales/en/devops.js
  src/locales/zh/devops.js
  src/pages/workspaces/containers/DevOps/index.jsx
Labels: approved, kind/bug, lgtm, size/M

#428 fix: Fix devops page when devops not installed
  server/config.yaml
  src/components/Tables/Base/index.jsx
  src/core/global.js
  src/pages/workspaces/components/ResourceTable/index.jsx
  src/pages/workspaces/containers/DevOps/index.jsx
  src/stores/devops.js
Labels: approved, kind/bug, lgtm, size/M

#425 fix: add label selector filter for log output list
  src/pages/settings/containers/LogCollection/index.jsx
  src/stores/logging/collection/output.js
Labels: approved, lgtm, size/S

#426 fix: wrong pvc snapshot link address
  src/pages/projects/containers/Volumes/Detail/Snapshots/index.jsx
Labels: approved, lgtm, size/XS

#427 Docs/custom monitor i18n
  src/locales/en/monitoring.js
  src/locales/zh/monitoring.js
  src/utils/constants.js
Labels: approved, lgtm, size/S

#429 En UI update
  src/components/Base/Empty/index.jsx
  src/components/Base/List/index.test.js
  src/components/Forms/AppDeploy/BasicInfo/index.jsx
  src/components/Forms/ConfigMap/ConfigMapSettings/DataForm/index.jsx
  src/components/Forms/ConfigMap/ConfigMapSettings/DataList/index.jsx
  src/components/Forms/Route/RouteRules/RuleForm/index.jsx
  src/components/Forms/Route/RouteRules/RuleList/Item.jsx
  src/components/Forms/Secret/SecretSettings/DataForm/index.jsx
  src/components/Forms/Secret/SecretSettings/DataList/index.jsx
  src/components/Forms/Workload/ContainerSettings/index.jsx
  src/configs/steps/imagebuilder.js
  src/locales/en/nodes.js
  src/locales/en/project.js
  src/locales/en/storage.js
  src/locales/zh/base.js
  src/locales/zh/s2i.js
  src/locales/zh/secret.js
  src/locales/zh/workload.js
  src/pages/clusters/containers/Alerting/Messages/Detail/AlertDetail/index.jsx
  src/pages/clusters/containers/Alerting/Messages/Detail/Comment/index.jsx
  src/pages/clusters/containers/Alerting/Messages/Detail/NotificationHistory/index.jsx
  src/pages/fedprojects/containers/Overview/UsageRanking/index.jsx
  src/pages/projects/components/Modals/CreateApp/Routes/RuleForm/index.jsx
  src/pages/projects/components/Modals/CreateApp/Routes/RuleList/Item.jsx
  src/pages/projects/components/Modals/CreateApp/Services/ServiceList/Item.jsx
  src/pages/projects/containers/Network/Policies/Detail/Viewer/index.jsx
  src/pages/projects/containers/Overview/UsageRanking/index.jsx
  src/pages/workspaces/containers/FedProjects/index.jsx
  src/stores/secret.js
Labels: approved, kind/documentation, lgtm, size/M

#432 update: Update add cluster form
  src/pages/clusters/containers/Clusters/AddCluster/Configuration/index.jsx
  src/pages/clusters/containers/Clusters/AddCluster/index.jsx
Labels: approved, kind/update, size/XS

#433 fix: x-asix render error when custom monitoring edit form only change…
  src/components/Modals/CustomMonitoring/components/Form/Field/index.scss
  src/components/Modals/CustomMonitoring/containers/GraphMonitorForm.jsx
  src/stores/monitoring/custom/monitor.js
Labels: approved, lgtm, size/S

#434 fix: Fix roles fetch
  src/stores/role.js
Labels: approved, kind/bug, size/XS

#435 chore(locales): EN UI update
  src/components/Forms/Service/ContainerSetting/ContainerSetting/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
  src/components/Forms/Workload/ContainerSettings/PodAffinity/index.jsx
  src/components/Forms/Workload/ContainerSettings/index.jsx
  src/components/TextPreview/index.jsx
  src/locales/en/application.js
  src/locales/en/configmap.js
  src/locales/en/network.js
  src/locales/en/service.js
  src/locales/en/workload.js
  src/locales/zh/app_template.js
  src/locales/zh/application.js
  src/locales/zh/s2i.js
  src/locales/zh/workload.js
  src/pages/appStore/components/AppPreview/index.jsx
  src/pages/apps/components/AppPreview/index.jsx
  src/pages/apps/components/Cards/AppReadme/index.jsx
  src/pages/apps/components/Cards/Introduction/index.jsx
  src/pages/apps/components/TextPreview/index.jsx
  src/pages/projects/containers/Applications/OPAppDetail/AppTemplate/index.jsx
Labels: approved, kind/documentation, lgtm, size/M

#448 fix: Fix workspace api
  src/actions/workspace.js
  src/components/Base/CodeEditor/index.jsx
  src/components/Base/Form/Item.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ProbeForm/index.jsx
  src/components/Inputs/index.js
  src/pages/clusters/containers/Clusters/AddCluster/Configuration/index.jsx
  src/pages/projects/components/Selector/index.scss
  src/pages/workspaces/components/Modals/WorkspaceCreate/BaseInfo/index.jsx
  src/pages/workspaces/components/Modals/WorkspaceCreate/ClusterSettings/ClusterSelect/index.jsx
  src/pages/workspaces/components/Modals/WorkspaceCreate/ClusterSettings/index.jsx
  src/pages/workspaces/components/Selector/index.scss
  src/pages/workspaces/containers/BaseInfo/index.jsx
  src/pages/workspaces/containers/BaseInfo/index.scss
  src/stores/node.js
  src/stores/role.js
  src/utils/object.mapper.js
Labels: approved, kind/bug, size/L

#430 chore(locales): Update english locales for storage, user, role, clust…
  server/config.yaml
  src/locales/en/base.js
  src/locales/en/storage.js
  src/locales/en/user.js
  src/locales/zh/base.js
  src/locales/zh/cluster.js
  src/locales/zh/network.js
  src/locales/zh/storage.js
Labels: approved, kind/documentation, lgtm, size/S

#447 Chore(locales): EN UI update
  src/components/Cards/Containers/Item.jsx
  src/components/Forms/Route/AdvanceSettings/index.jsx
  src/components/Forms/Service/AdvanceSettings/SessionAffinity/index.jsx
  src/components/Forms/Service/AdvanceSettings/index.jsx
  src/components/Forms/Volume/AdvanceSettings/index.jsx
  src/components/Forms/Workload/AdvanceSettings/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/Commands/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/HealthChecker/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/Ports/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ProbeForm/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ProbeInput/index.jsx
  src/components/Forms/Workload/VolumeSettings/AddVolume/index.jsx
  src/components/Forms/Workload/VolumeSettings/VolumeList/index.jsx
  src/components/Inputs/MountInput/Item.jsx
  src/locales/en/s2i.js
  src/locales/en/service.js
  src/locales/en/workload.js
  src/locales/zh/s2i.js
  src/locales/zh/service.js
  src/locales/zh/workload.js
  src/pages/projects/components/Cards/ContainerTemplate/Item.jsx
  src/pages/projects/components/Cards/Probe/index.jsx
Labels: approved, kind/documentation, lgtm, size/L

#452 fix: Fix users update by websocket
  src/pages/access/containers/Accounts/index.jsx
  src/utils/constants.js
Labels: approved, kind/bug, size/XS

#453 Chore(locales): En UI update
  src/components/Forms/CronJob/BaseInfo/index.jsx
  src/components/Forms/Service/BaseInfo/index.jsx
  src/locales/en/ingress.js
  src/locales/en/network.js
  src/locales/en/service.js
  src/locales/en/workload.js
  src/locales/zh/service.js
  src/locales/zh/workload.js
  src/pages/clusters/containers/Network/Policies/index.jsx
  src/pages/projects/components/Modals/ServiceCreate/index.jsx
  src/pages/projects/containers/Network/Policies/index.jsx
  src/pages/projects/containers/Services/Detail/index.jsx
Labels: approved, kind/documentation, lgtm, size/M

#454 fix: Fix history modal hotkey
  src/components/Base/CodeEditor/index.jsx
  src/components/KubeTools/index.jsx
  src/components/Modals/History/Card.jsx
  src/components/Modals/History/index.jsx
  src/components/Modals/History/index.scss
  src/core/layouts/Base/index.jsx
  src/locales/zh/base.js
  src/pages/clusters/containers/Overview/Initializing/index.jsx
  src/stores/base.list.js
  src/stores/openpitrix/application.js
  src/stores/project.js
  src/stores/root.js
  src/utils/object.mapper.js
Labels: approved, kind/bug, size/L

#455 fix: Fix cluster overview agent yaml
  src/pages/clusters/containers/Overview/Initializing/index.jsx
  src/pages/workspaces/components/Modals/WorkspaceCreate/ClusterSettings/ClusterSelect/index.jsx
Labels: approved, kind/bug, size/S

#460 fix: Fix project and workload resource realtime update
  src/actions/project.js
  src/components/HOCs/withList.js
  src/components/Modals/Create/index.jsx
  src/components/Tables/Base/index.jsx
  src/core/global.js
  src/pages/fedprojects/components/ClusterWorkloadStatus/Cluster.jsx
  src/pages/fedprojects/containers/AdvancedSettings/InternetAccess/Access/index.jsx
  src/pages/fedprojects/containers/Deployments/Detail/Monitoring/index.jsx
  src/pages/fedprojects/containers/Deployments/Detail/ResourceStatus/index.jsx
  src/pages/fedprojects/containers/QuotaManage/ResourceQuota/index.jsx
  src/pages/fedprojects/containers/Services/Detail/ResourceStatus/index.jsx
  src/pages/projects/App.jsx
  src/pages/projects/containers/AdvancedSettings/InternetAccess/index.jsx
  src/pages/projects/containers/AdvancedSettings/index.jsx
  src/pages/workspaces/containers/Projects/index.jsx
  src/stores/federated.js
  src/stores/project.js
  src/utils/socket.client.js
Labels: approved, kind/bug, size/L

#456 fix: fix some issues there are 436,438,444,445,449
  src/components/Modals/DevOpsCreate/index.jsx
  src/components/Modals/DevOpsEdit/index.jsx
  src/components/Modals/ProjectSelect/index.jsx
  src/locales/en/base.js
  src/locales/zh/base.js
  src/pages/devops/components/Pipeline/StepModals/withCredentials.jsx
  src/pages/devops/components/Pipeline/store.js
  src/pages/devops/containers/Pipelines/index.jsx
  src/pages/devops/containers/Roles/index.jsx
  src/utils/constants.js
Labels: approved, lgtm, size/M

#459 Event search enhancements
  src/components/Modals/AuditingSearch/Auditing/Detail/index.jsx
  src/components/Modals/AuditingSearch/Auditing/Detail/index.scss
  src/components/Modals/AuditingSearch/Auditing/Home/index.jsx
  src/components/Modals/AuditingSearch/Auditing/Home/index.scss
  src/components/Modals/AuditingSearch/Auditing/utils.js
  src/components/Modals/AuditingSearch/index.jsx
  src/components/Modals/EventSearch/Event/Detail/index.jsx
  src/components/Modals/EventSearch/Event/Detail/index.scss
  src/components/Modals/EventSearch/Event/Home/index.jsx
  src/components/Modals/EventSearch/Event/Home/index.scss
  src/components/Modals/EventSearch/Event/utils.js
  src/components/Modals/EventSearch/index.jsx
  src/locales/en/logging.js
  src/locales/zh/logging.js
  src/stores/auditing.js
  src/stores/eventSearch.js
Labels: approved, lgtm, size/XXL

#457 Chore(locales): EN UI update
  src/components/Charts/Bar/TimeBar/index.jsx
  src/components/Forms/Route/RouteRules/RuleList/index.jsx
  src/components/Forms/Route/RouteRules/index.jsx
  src/components/Forms/Service/ServiceSettings/SelectorsInput/index.jsx
  src/components/Inputs/PropertiesInput/index.jsx
  src/components/Modals/History/index.jsx
  src/components/Modals/LogSearch/Logging/Home/index.jsx
  src/components/Modals/LogSearch/Logging/Search/index.jsx
  src/components/Modals/LogSearch/Logging/SearchInput/index.jsx
  src/components/Modals/Monitoring/Multiple/Base/Resources.jsx
  src/components/Modals/Node/TaintManagement/TaintInput/index.jsx
  src/components/Modals/UserSetting/PasswordSetting/index.jsx
  src/locales/en/base.js
  src/locales/en/ingress.js
  src/locales/en/logging.js
  src/locales/en/storage.js
  src/locales/en/workload.js
  src/locales/zh/base.js
  src/locales/zh/ingress.js
  src/locales/zh/logging.js
  src/locales/zh/monitoring.js
  src/locales/zh/service.js
  src/locales/zh/user.js
  src/locales/zh/workload.js
  src/pages/clusters/containers/Workload/Jobs/index.jsx
  src/pages/fedprojects/containers/Deployments/Detail/Monitoring/index.jsx
  src/pages/fedprojects/containers/Overview/Help/index.jsx
  src/pages/projects/containers/Deployments/Detail/Monitoring/index.jsx
  src/pages/projects/containers/ImageBuilder/Detail/routes.js
  src/pages/projects/containers/Jobs/Detail/ExcuteRecords/index.jsx
  src/pages/projects/containers/Jobs/Detail/routes.js
  src/pages/projects/containers/Jobs/index.jsx
  src/pages/projects/routes/imagebuilder.js
Labels: approved, kind/documentation, lgtm, size/L

#461 fix: Fix project create and secret create error
  src/locales/zh/logging.js
  src/pages/projects/containers/Secrets/index.jsx
  src/stores/cluster/index.js
  src/stores/project.js
  src/stores/secret.js
Labels: approved, kind/bug, size/S

#463 fix: Fix the wrong value of the target template when s2i is rebuild
  src/components/Forms/ImageBuilder/S2IForm/TemplateSelect/index.jsx
Labels: approved, lgtm, size/XS

#465 fix: Fix application create error
  src/pages/projects/components/Modals/CreateApp/Services/ServiceList/Item.jsx
Labels: approved, kind/bug, size/S

#466 fix: Add cluster detail websocket when adding cluster
  src/pages/clusters/containers/Overview/Initializing/index.jsx
Labels: approved, kind/bug, size/M

#471 fix: Fix configmap detail return title
  src/pages/fedprojects/containers/ConfigMaps/Detail/index.jsx
  src/pages/projects/containers/ConfigMaps/Detail/index.jsx
Labels: approved, kind/bug, size/XS

#468 fix: modify network policy the rule for CIDR to add ports
  src/components/Modals/Network/Policies/IpBlock.jsx
  src/locales/en/network.js
  src/locales/zh/network.js
Labels: approved, kind/flake, lgtm, size/S

#474 fix: Fix logging, events, auditing clusters filter
  src/components/Modals/AuditingSearch/index.jsx
  src/components/Modals/EventSearch/index.jsx
  src/components/Modals/LogSearch/index.jsx
  src/locales/zh/logging.js
  src/scss/utilities.scss
Labels: approved, kind/bug, size/L

#469 chore(locales): EN UI update
  src/components/Modals/History/index.jsx
  src/locales/en/app.js
  src/locales/en/monitoring.js
  src/locales/en/version.js
  src/locales/en/workload.js
  src/locales/en/workspace.js
  src/locales/zh/base.js
  src/locales/zh/s2i.js
  src/locales/zh/workload.js
  src/locales/zh/workspace.js
Labels: approved, kind/documentation, lgtm, size/L

#475 fix: Add config for network isolate default value
  server/config.yaml
  src/components/Modals/AuditingSearch/Auditing/Home/index.scss
  src/components/Modals/AuditingSearch/index.jsx
  src/components/Modals/EventSearch/Event/Home/index.scss
  src/components/Modals/EventSearch/index.jsx
  src/components/Modals/LogSearch/Logging/Home/index.scss
  src/components/Modals/LogSearch/Logging/Search/index.scss
  src/components/Modals/LogSearch/index.jsx
  src/components/Modals/ProjectCreate/index.jsx
  src/core/global.js
  src/pages/projects/containers/Network/Policies/index.jsx
  src/pages/workspaces/components/Modals/WorkspaceCreate/BaseInfo/index.jsx
Labels: approved, kind/bug, size/M

#477 fix: Fix policy form api
  src/components/Graph/Detail/PolicyForm/index.jsx
Labels: approved, kind/bug, size/XS

#476 chore(locales): EN UI update
  src/components/Forms/ImageBuilder/S2IForm/index.jsx
  src/components/Modals/EventSearch/Event/utils.js
  src/locales/en/app_template.js
  src/locales/en/s2i.js
  src/locales/en/service.js
  src/locales/zh/role.js
  src/locales/zh/s2i.js
Labels: approved, kind/documentation, lgtm, size/M

#478 chore(locales): EN UI update
  src/components/Cards/ContainerLog/index.jsx
  src/components/Cards/Monitoring/Controller/index.jsx
  src/components/Cards/Pods/Item.jsx
  src/locales/en/application.js
  src/locales/en/cluster.js
  src/locales/en/dashboard.js
  src/locales/en/grayrelease.js
  src/locales/en/nodes.js
  src/locales/en/project.js
  src/locales/en/service.js
  src/locales/zh/application.js
  src/locales/zh/cluster.js
  src/locales/zh/dashboard.js
  src/locales/zh/nodes.js
  src/pages/clusters/containers/Monitor/Resource/Usage/Trend/index.jsx
Labels: approved, kind/documentation, lgtm, size/L

#462 Event search enhancements
  src/components/Modals/AuditingSearch/Auditing/Detail/MetadataModal/index.scss
  src/components/Modals/AuditingSearch/Auditing/Detail/index.jsx
  src/components/Modals/AuditingSearch/Auditing/Detail/index.scss
  src/components/Modals/AuditingSearch/Auditing/Home/index.scss
  src/components/Modals/EventSearch/Event/Detail/MetadataModal/Metadata/index.scss
  src/components/Modals/EventSearch/Event/Detail/MetadataModal/index.scss
  src/components/Modals/EventSearch/Event/Detail/index.jsx
  src/components/Modals/EventSearch/Event/Detail/index.scss
  src/components/Modals/EventSearch/Event/Home/index.scss
  src/locales/en/logging.js
  src/locales/zh/logging.js
Labels: approved, lgtm, size/L

#479 fix: Fix cluster api
  src/actions/resource.edit.js
  src/actions/service.js
  src/components/Forms/Service/ServiceSettings/WorkloadSelect/index.jsx
  src/stores/cluster/index.js
Labels: approved, kind/bug, size/S

#482 fix: Fix some multi clusters issues.
  src/actions/project.js
  src/components/Forms/Workload/VolumeSettings/index.jsx
  src/pages/clusters/containers/Overview/Dashboard/ClusterInfo/index.jsx
  src/pages/projects/containers/Routes/Detail/ResourceStatus/index.jsx
  src/pages/workspaces/components/Modals/WorkspaceCreate/ClusterSettings/ClusterSelect/index.jsx
  src/pages/workspaces/components/ResourceTable/index.jsx
  src/pages/workspaces/containers/DevOps/index.jsx
  src/pages/workspaces/containers/FedProjects/index.jsx
  src/pages/workspaces/containers/Projects/index.jsx
  src/stores/project.js
Labels: approved, kind/bug, size/M

#484 fix: Fix no project name and mirror name when creating a mirror.
  src/actions/imagebuilder.js
  src/components/Base/Upload/utils/request.js
  src/components/Forms/ImageBuilder/B2IForm/BinaryFileUploader/index.jsx
  src/components/Forms/ImageBuilder/B2IForm/index.jsx
  src/components/Forms/ImageBuilder/S2IForm/index.jsx
  src/pages/projects/components/Cards/ImageRunRecord/Item/index.jsx
  src/pages/projects/components/Cards/S2iBuilder/log.jsx
  src/pages/projects/containers/ImageBuilder/Detail/index.jsx
  src/stores/s2i/builder.js
  src/stores/s2i/run.js
Labels: approved, lgtm, size/L

#488 fix: Fix preset roles description.
  server/config.yaml
  src/actions/member.js
  src/components/Modals/UserCreate/index.jsx
  src/locales/en/role.js
  src/locales/zh/role.js
  src/pages/access/containers/Roles/Detail/index.jsx
  src/pages/access/containers/Roles/index.jsx
  src/pages/clusters/containers/Roles/Detail/index.jsx
  src/pages/clusters/containers/Roles/index.jsx
  src/pages/devops/containers/Roles/Detail/index.jsx
  src/pages/devops/containers/Roles/index.jsx
  src/pages/projects/containers/Roles/Detail/index.jsx
  src/pages/projects/containers/Roles/index.jsx
  src/pages/workspaces/containers/Roles/Detail/index.jsx
  src/pages/workspaces/containers/Roles/index.jsx
  src/stores/cluster/index.js
  src/stores/role.js
  src/utils/object.mapper.js
Labels: approved, kind/bug, size/L

#489 fix: Add props upadte logic for code editor
  src/components/Base/CodeEditor/index.jsx
  src/components/Forms/AppDeploy/AppConfig/index.jsx
Labels: approved, kind/bug, size/S

#490 fix: Fix no devopsRoles after refreshing the pipeline page
  src/components/Forms/CICDs/BaseInfo/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Artifacts/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Sider/branch-sider.jsx
  src/pages/devops/containers/Pipelines/Detail/Sider/pipeline-sider.jsx
  src/pages/devops/containers/Pipelines/Detail/Sider/runs-sider.jsx
  src/pages/devops/containers/Pipelines/index.jsx
  src/stores/devops/pipelines.js
Labels: approved, lgtm, size/L

#491 fix: Add upgrade for openpitrix app instance
  src/actions/openpitrix.js
  src/components/Forms/AppDeploy/AppConfig/index.jsx
  src/components/Modals/ProjectSelect/index.jsx
  src/locales/zh/application.js
  src/pages/apps/components/Lists/InstanceList/Item.jsx
  src/pages/projects/containers/Applications/OPAppDetail/AppTemplate/index.jsx
  src/pages/projects/containers/Applications/OPAppDetail/VersionInfo/index.jsx
  src/stores/openpitrix/app.js
  src/stores/openpitrix/application.js
  src/stores/openpitrix/version.js
Labels: approved, kind/update, size/L

#492 fix: Fix create modal data update
  src/components/Modals/Create/index.jsx
Labels: approved, kind/bug, size/XS

#499 update: Move log collection to cluster pages
  server/config.yaml
  src/actions/log.collection.js
  src/components/Base/Modal/modal.jsx
  src/components/Modals/AuditingSearch/Auditing/Detail/index.jsx
  src/components/Modals/AuditingSearch/Auditing/utils.js
  src/components/Modals/EventSearch/Event/Detail/index.jsx
  src/components/Modals/UserSetting/index.jsx
  src/core/containers/Base/Detail/EnvVariables/index.jsx
  src/core/layouts/Base/index.jsx
  src/locales/en/logging.js
  src/locales/zh/base.js
  src/locales/zh/logging.js
  src/pages/clusters/actions/cluster.js
  src/pages/clusters/containers/ConfigMaps/index.jsx
  src/pages/clusters/containers/ConfigMaps/index.scss
  src/pages/clusters/containers/LogCollections/Detail/Configuration/index.jsx
  src/pages/clusters/containers/LogCollections/Detail/Configuration/index.scss
  src/pages/clusters/containers/LogCollections/Detail/Log/index.jsx
  src/pages/clusters/containers/LogCollections/Detail/Log/index.scss
  src/pages/clusters/containers/LogCollections/Detail/YamlModal/index.jsx
  src/pages/clusters/containers/LogCollections/Detail/index.jsx
  src/pages/clusters/containers/LogCollections/Detail/index.scss
  src/pages/clusters/containers/LogCollections/Detail/routes.js
  src/pages/clusters/containers/LogCollections/config.js
  src/pages/clusters/containers/LogCollections/index.jsx
  src/pages/clusters/containers/LogCollections/index.scss
  src/pages/clusters/containers/Secrets/index.jsx
  src/pages/clusters/containers/Secrets/index.scss
  src/pages/clusters/routes/detail.js
  src/pages/clusters/routes/index.js
  src/pages/projects/containers/Pods/Containers/Detail.jsx
  src/pages/projects/containers/Pods/Containers/Monitoring.jsx
  src/pages/projects/containers/Pods/Detail/ResourceStatus.jsx
  src/pages/projects/containers/Secrets/Detail/index.jsx
  src/pages/settings/App.jsx
  src/pages/settings/actions/index.js
  src/pages/settings/containers/LogCollection/Detail/index.jsx
  src/pages/settings/containers/LogCollection/index.scss
  src/pages/settings/containers/MailServices/index.jsx
  src/pages/settings/containers/MailServices/index.scss
  src/pages/settings/routes/index.js
  src/pages/settings/routes/logCollection.js
  src/stores/cluster/index.js
  src/stores/container.js
  src/stores/logging/collection/output.js
  src/utils/object.mapper.js
  src/utils/request.js
Labels: approved, kind/update, size/XXL

#502 fix: Fix workspace nav with ks module
  server/config.yaml
  src/core/global.js
  src/pages/workspaces/App.jsx
  src/pages/workspaces/containers/Projects/index.jsx
Labels: approved, size/S

#501 chore(locales): minor wording and punctuation updates
  src/components/Forms/ImageBuilder/B2IForm/index.jsx
  src/locales/en/cluster.js
  src/locales/en/logging.js
  src/locales/en/version.js
  src/locales/en/workspace.js
  src/locales/zh/s2i.js
  src/locales/zh/version.js
Labels: approved, kind/documentation, lgtm, size/M

#504 update: Add project monitoring data in project list
  src/components/Modals/ProjectSelect/ClusterSelect/index.jsx
  src/components/Modals/ProjectSelect/ClusterSelect/index.scss
  src/components/Modals/ProjectSelect/index.jsx
  src/components/Modals/ProjectSelect/index.scss
  src/pages/clusters/containers/Projects/index.jsx
  src/pages/workspaces/containers/Projects/index.jsx
Labels: approved, kind/update, size/L

#494 chore(locales): Update role console. In Chinese, should use Chinese m…
  src/locales/zh/role.js
Labels: approved, area/locale, lgtm, size/M

#505 fix: Abort data fetch if there is no cluster
  src/pages/workspaces/containers/DevOps/index.jsx
  src/pages/workspaces/containers/Projects/index.jsx
Labels: approved, kind/bug, size/M

#509 fix: Fix lang switch error
  server/controllers/api.js
  src/stores/user.js
  src/utils/cookie.js
Labels: approved, kind/bug, size/XS

#510 fix: Fix some issues
  src/components/Modals/EditAuthorization/CheckItem.jsx
  src/components/Modals/EditAuthorization/constants.js
  src/components/Modals/ProjectSelect/index.jsx
  src/components/Modals/ProjectSelect/index.scss
  src/locales/en/network.js
  src/locales/en/role.js
  src/locales/zh/project.js
  src/pages/access/containers/Workspaces/index.jsx
  src/pages/access/containers/Workspaces/index.scss
  src/pages/clusters/containers/Projects/Detail/Overview/index.jsx
  src/pages/clusters/containers/Projects/Detail/Overview/index.scss
  src/pages/console/components/Cards/Workspace/index.jsx
  src/pages/workspaces/components/Modals/WorkspaceCreate/ClusterSettings/ClusterSelect/index.jsx
  src/pages/workspaces/components/Modals/WorkspaceSelect/Card/index.jsx
  src/pages/workspaces/components/Modals/WorkspaceSelect/Card/index.scss
  src/pages/workspaces/components/Modals/WorkspaceSelect/index.jsx
  src/pages/workspaces/containers/Overview/ResourceUsage/Statistics/index.jsx
  src/pages/workspaces/containers/Overview/ResourceUsage/index.jsx
  src/pages/workspaces/containers/Projects/index.jsx
  src/stores/devops.js
  src/stores/monitoring/project.js
  src/stores/openpitrix/application.js
  src/utils/object.mapper.js
Labels: approved, kind/bug, size/L

#513 fix: Fix cluster filter in eventSearch and auditingSearch
  src/components/Modals/AuditingSearch/Auditing/Detail/index.jsx
  src/components/Modals/AuditingSearch/Auditing/Home/index.jsx
  src/components/Modals/AuditingSearch/index.jsx
  src/components/Modals/EventSearch/Event/Detail/index.jsx
  src/components/Modals/EventSearch/Event/Home/index.jsx
  src/components/Modals/EventSearch/Event/Home/index.scss
  src/components/Modals/EventSearch/index.jsx
  src/components/Modals/LogSearch/Logging/Home/index.jsx
  src/components/Modals/LogSearch/Logging/Search/index.jsx
  src/components/Modals/LogSearch/index.jsx
Labels: approved, kind/bug, size/M

#512 Typo fix and role description wording improvement
  src/components/Modals/AuditingSearch/Auditing/Home/index.jsx
  src/locales/en/base.js
  src/locales/en/logging.js
  src/locales/en/monitoring.js
  src/locales/en/role.js
  src/locales/zh/app.js
  src/locales/zh/logging.js
  src/locales/zh/role.js
  src/pages/apps/components/Forms/AppBaseEdit/index.jsx
  src/stores/monitoring/custom/template.json
Labels: approved, kind/documentation, lgtm, size/M

#514 fix: Fix locales error
  src/locales/en/role.js
  src/locales/zh/role.js
Labels: approved, kind/bug, size/XS

#518 fix: Fix cluster log collection
  server/config.yaml
  src/components/Base/RadioGroup/index.jsx
  src/pages/clusters/containers/LogCollections/index.jsx
Labels: approved, kind/bug, size/S

#519 style: Change font size of component status in cluster monitoing
  src/pages/clusters/containers/Monitor/Cluster/Overview/index.jsx
Labels: approved, kind/bug, size/XS

#521 Add cluster authorization desc and fix log collecting wording
  src/locales/en/cluster.js
  src/locales/en/logging.js
  src/locales/zh/cluster.js
Labels: approved, kind/documentation, lgtm, size/XS

#520 Update: add auto resize textarea
  src/components/Base/TextArea/index.jsx
  src/components/Base/TextArea/index.scss
  src/components/Base/TextArea/index.test.js
  src/components/Base/index.js
  src/components/Forms/ConfigMap/ConfigMapSettings/DataForm/index.jsx
  src/components/Forms/ConfigMap/ConfigMapSettings/DataForm/index.scss
Labels: approved, lgtm, size/L

#522 fix: Fix log collector title and styles
  src/components/Modals/LogCollectionCreate/index.jsx
  src/locales/en/logging.js
  src/locales/zh/logging.js
  src/pages/clusters/containers/LogCollections/index.jsx
Labels: approved, kind/bug, size/S

#524 fix: Fix log collector form data
  src/stores/logging/collection/output.js
Labels: approved, kind/bug, size/XS

#526 fix: Add manager for cluster visibility table
  src/pages/clusters/components/Modals/ClusterVisibility/WorkspaceItem/index.jsx
  src/pages/clusters/components/Modals/ClusterVisibility/WorkspaceItem/index.scss
  src/pages/clusters/containers/Visibility/index.jsx
  src/utils/object.mapper.js
Labels: approved, kind/bug, size/S

#532 fix: Show hostname in loadBalancerIngress
  src/locales/zh/service.js
  src/pages/clusters/containers/Workload/Routes/index.jsx
  src/pages/fedprojects/containers/AdvancedSettings/InternetAccess/Access/index.jsx
  src/pages/fedprojects/containers/Applications/Detail/AppIngresses/Ingresses/index.jsx
  src/pages/fedprojects/containers/Routes/Detail/ResourceStatus/Item/index.jsx
  src/pages/projects/containers/AdvancedSettings/InternetAccess/index.jsx
  src/pages/projects/containers/Routes/Detail/index.jsx
  src/pages/projects/containers/Routes/index.jsx
  src/pages/projects/containers/Services/Detail/index.jsx
  src/utils/object.mapper.js
Labels: approved, kind/bug, size/M
