Repository kubesphere/console, pull requests merged in 2020-11, with the labels that each got.

#1282 chore: Add react fast refresh
  package.json
  scripts/webpack.base.js
  scripts/webpack.dev.js
  yarn.lock
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/M

#1280 fix: Remove application fetching limit in grayrelease modal
  src/components/Forms/GrayRelease/Components/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1284 fix: Show replicas control with HPA
  src/pages/projects/containers/Deployments/Detail/ResourceStatus/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1286 fix: Add service DNS info
  src/pages/projects/containers/Services/Detail/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1285 fix: Save kube tools position to local storage
  src/components/KubeTools/index.jsx
  src/components/KubeTools/index.scss
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1287 fix: Fix redis session expire time too long
  server/config.yaml
  server/store/index.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1290 fix: Fix some bugs about cron and pipeline stage
  src/components/Forms/Pipelines/AdvanceSettings/index.jsx
  src/pages/appStore/containers/AppDeploy/index.jsx
  src/pages/devops/components/Cards/CodeQualityResult/index.jsx
  src/pages/devops/components/Pipeline/StepModals/kubernetesDeploy.jsx
  src/pages/devops/containers/Pipelines/Detail/Layout/pipeline.jsx
  src/stores/openpitrix/app.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#1295 fix: Fix unexpect token ... error
  package.json
  yarn.lock
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1294 fix: Fix the webhook address in the pipeline edit page
  src/components/Forms/Pipelines/AdvanceSettings/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Artifacts/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/M

#1296 fix: Fix cluster creating form errors
  src/components/Forms/Cluster/AdvanceSettings/index.jsx
  src/components/Forms/Cluster/ClusterSettings/index.jsx
  src/components/Forms/Cluster/NodeList/AddNode.jsx
  src/locales/en/cluster.js
  src/locales/es/cluster.js
  src/locales/tc/cluster.js
  src/locales/zh/cluster.js
  src/pages/clusters/containers/Overview/Initializing/KubeKeyCluster/Progress/index.jsx
  src/pages/clusters/containers/Overview/Initializing/KubeKeyCluster/Progress/index.scss
  src/stores/cluster/kubekey.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1299 change K8S/k8s to K8s which is the official spelling from Kubernetes
  src/locales/en/monitoring.js
  src/locales/en/storage.js
  src/locales/es/monitoring.js
  src/locales/es/storage.js
  src/locales/tc/monitoring.js
  src/locales/zh/monitoring.js
  src/pages/clusters/containers/Monitor/Cluster/Overview/index.jsx
  src/utils/constants.js
  src/utils/index.js
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S

#1297 Chore(locales): refine some UI
  src/configs/openpitrix/version.js
  src/locales/en/dashboard.js
  src/locales/en/version.js
  src/locales/es/version.js
  src/locales/tc/version.js
  src/locales/zh/version.js
  src/pages/apps/components/Cards/TestSteps/index.jsx
  src/pages/apps/components/Modals/VersionSubmit/index.jsx
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/S

#1302 fix: Add app.kubernetes.io/vendor label for service monitor
  src/components/Base/Panel/index.jsx
  src/components/Base/Panel/index.scss
  src/pages/projects/components/Modals/ServiceMonitor/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1303 feat: Add network topology page
  package.json
  src/locales/zh/workload.js
  src/pages/projects/containers/Services/Topology/Detail/BaseInfo/index.jsx
  src/pages/projects/containers/Services/Topology/Detail/BaseInfo/index.scss
  src/pages/projects/containers/Services/Topology/Detail/Childrens/index.jsx
  src/pages/projects/containers/Services/Topology/Detail/Connections/index.jsx
  src/pages/projects/containers/Services/Topology/Detail/Table/index.jsx
  src/pages/projects/containers/Services/Topology/Detail/Table/index.scss
  src/pages/projects/containers/Services/Topology/Detail/Tables/index.jsx
  src/pages/projects/containers/Services/Topology/Detail/Tables/index.scss
  src/pages/projects/containers/Services/Topology/Detail/index.jsx
  src/pages/projects/containers/Services/Topology/Detail/index.scss
  src/pages/projects/containers/Services/Topology/Edge/index.jsx
  src/pages/projects/containers/Services/Topology/Edge/index.scss
  src/pages/projects/containers/Services/Topology/RadioButtons/index.jsx
  src/pages/projects/containers/Services/Topology/RadioButtons/index.scss
  src/pages/projects/containers/Services/Topology/Service/index.jsx
  src/pages/projects/containers/Services/Topology/Service/index.scss
  src/pages/projects/containers/Services/Topology/index.jsx
  src/pages/projects/containers/Services/Topology/index.scss
  src/pages/projects/containers/Services/index.jsx
  src/stores/network/topology.js
  src/stores/network/utils.js
  yarn.lock
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XXL

#1305 fix: Fix health data filter in app traffic monitor
  src/stores/application/crd.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1307 feat: Support promql highlight and suggestions
  package.json
  src/components/Base/Cascader/Item.jsx
  src/components/Base/Cascader/index.jsx
  src/components/Base/Cascader/index.scss
  src/components/Modals/CustomMonitoring/components/MetircQueryInput/index.jsx
  src/components/Modals/CustomMonitoring/components/MetircQueryInput/index.scss
  src/components/Modals/CustomMonitoring/components/PromQLInput/Suggestions/Item.jsx
  src/components/Modals/CustomMonitoring/components/PromQLInput/Suggestions/index.jsx
  src/components/Modals/CustomMonitoring/components/PromQLInput/Suggestions/index.scss
  src/components/Modals/CustomMonitoring/components/PromQLInput/grammar.js
  src/components/Modals/CustomMonitoring/components/PromQLInput/index.jsx
  src/components/Modals/CustomMonitoring/components/PromQLInput/index.scss
  src/components/Modals/CustomMonitoring/components/PromQLInput/promql.js
  yarn.lock
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#1308 fix: Fix TypeSelect import missing
  src/pages/projects/components/Modals/RepoApp/AppDetail/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1311 fix: Add table query limit in pipeline run
  src/stores/devops/run.js
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1312 chore: Optimize volume mount for developing with docker
  README.md
  docker-compose.builder.yaml
  docker-compose.yaml
  docs/access-backend.md
  docs/development-with-docker.md
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/S

#1317 update: Support labelsets suggestion for promql
  src/components/Modals/CustomMonitoring/components/MetircQueryInput/index.jsx
  src/components/Modals/CustomMonitoring/components/MetircQueryInput/index.scss
  src/components/Modals/CustomMonitoring/components/PromQLInput/Suggestions/index.jsx
  src/components/Modals/CustomMonitoring/components/PromQLInput/history.js
  src/components/Modals/CustomMonitoring/components/PromQLInput/index.jsx
  src/components/Modals/CustomMonitoring/components/PromQLInput/index.scss
  src/components/Modals/CustomMonitoring/components/PromQLInput/promql.js
  src/stores/monitoring/custom/labelsets.js
Labels: approved, dco-signoff: yes, lgtm, size/L

#1320 fix: Fix image search error in multi cluster project
  src/components/Forms/Workload/ContainerSettings/ClusterReplicasControl/Placement/index.scss
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
  src/pages/projects/components/Modals/CreateApp/Services/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1315 feature: Add some features in Pipeline
  src/actions/pipeline.js
  src/assets/pipeline/ci-temple-en.svg
  src/assets/pipeline/ci-temple-zh.svg
  src/assets/pipeline/cicd-temple-en.svg
  src/assets/pipeline/cicd-temple-zh.svg
  src/assets/pipeline/layer-black.svg
  src/assets/pipeline/pipeline-icon-dark.svg
  src/assets/pipeline/pipeline-icon.svg
  src/components/Forms/Pipelines/ActionsInput/Item.jsx
  src/components/Forms/Pipelines/ActionsInput/index.jsx
  src/components/Modals/Pipelines/Copy/index.jsx
  src/components/Modals/Pipelines/PipelineEdit/index.jsx
  src/components/Modals/Pipelines/PipelineEdit/index.scss
  src/locales/en/pipeline.js
  src/locales/es/pipeline.js
  src/locales/tc/pipeline.js
  src/locales/zh/pipeline.js
  src/pages/devops/components/Modals/JenkinsEdit/index.jsx
  src/pages/devops/components/Pipeline/PipelineTemplate/index.jsx
  src/pages/devops/components/Pipeline/PipelineTemplate/index.scss
  src/pages/devops/components/Pipeline/PipelineTemplate/templePipeline.js
  src/pages/devops/components/Pipeline/store.js
  src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
  src/pages/devops/containers/Pipelines/Detail/PipelineLogDialog/index.scss
  src/pages/devops/containers/Pipelines/PipelinesList/index.jsx
  src/scss/base.scss
  src/stores/devops/pipelines.js
  src/utils/constants.js
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XXL

#1323 fix: Fix grayrelease strategy workloads info
  src/components/Forms/GrayRelease/Components/index.jsx
  src/components/Forms/GrayRelease/Version/index.jsx
  src/components/Forms/GrayRelease/Version/index.scss
  src/pages/projects/components/Modals/GrayReleaseDetail/index.jsx
  src/pages/projects/components/Modals/GrayReleaseDetail/index.scss
  src/stores/grayrelease.js
  src/utils/object.mapper.js
Labels: approved, dco-signoff: yes, lgtm, size/M

#1324 update: Optimize SelectInput
  src/components/Inputs/SelectInput/index.jsx
  src/components/Inputs/SelectInput/index.scss
Labels: approved, dco-signoff: yes, lgtm, size/M

#1325 chore: disable react refresh overlay
  scripts/webpack.dev.js
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1327 Update account zhcn version
  src/locales/zh/base.js
  src/locales/zh/component.js
  src/locales/zh/logging.js
  src/locales/zh/mail.js
  src/locales/zh/pipeline.js
  src/locales/zh/role.js
  src/locales/zh/secret.js
  src/locales/zh/user.js
  src/locales/zh/workspace.js
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/M

#1328 fix: Fix spec.clusterIP for stateful service
  src/components/Forms/Workload/ContainerSettings/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1329 update: Update terminal API
  src/stores/terminal.js
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, size/XS

#1330 refactor: Refact oauth login process to support sso
  server/controllers/session.js
  server/views/login.html
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/S

#1331 update: Remove login error tip from server log
  server/controllers/view.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1332 fix: Fill service port name input with defaultValue if undefined
  src/components/Inputs/ContainerPort/index.jsx
  src/components/Inputs/ContainerServicePort/index.jsx
  src/components/Inputs/ServicePort/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1333 fix: Fix unsafe external link and incomplete sanitization
  src/components/Modals/CustomMonitoring/components/PromQLInput/promql.js
  src/pages/projects/components/Modals/ServiceMonitor/Authorization/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1334 fix: Fix promise polyfills
  package.json
  src/core/index.js
  yarn.lock
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S
