Repository kubesphere/console, pull requests merged in 2020-08, with the labels that each got.

#1049 fix: Fix the paging of credential and the role name in the Devops
  src/pages/devops/containers/Credential/index.jsx
  src/pages/devops/containers/Roles/index.jsx
  src/stores/devops/credential.js
  src/stores/devops/scm.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1051 update: Refactor federated resources list with resource API
  src/actions/project.js
  src/components/Cards/Events/index.jsx
  src/components/Forms/Route/RouteRules/index.jsx
  src/components/Forms/Workload/ContainerSettings/index.jsx
  src/components/Forms/Workload/VolumeSettings/MountConfig/index.jsx
  src/components/Forms/Workload/VolumeSettings/index.jsx
  src/components/HOCs/withList.js
  src/pages/fedprojects/containers/Applications/Detail/AppComponents/index.jsx
  src/pages/fedprojects/containers/Applications/Detail/AppIngresses/index.jsx
  src/pages/fedprojects/containers/Applications/Detail/Tracing/index.jsx
  src/pages/fedprojects/containers/Applications/Detail/TrafficManangement/index.jsx
  src/pages/fedprojects/containers/Applications/Detail/index.jsx
  src/pages/fedprojects/containers/Applications/index.jsx
  src/pages/fedprojects/containers/BaseInfo/index.jsx
  src/pages/fedprojects/containers/ConfigMaps/Detail/ConfigDetail/index.jsx
  src/pages/fedprojects/containers/ConfigMaps/index.jsx
  src/pages/fedprojects/containers/Overview/LimitRange/index.jsx
  src/pages/fedprojects/containers/Overview/LimitRange/index.scss
  src/pages/fedprojects/containers/Overview/index.jsx
  src/pages/fedprojects/containers/Secrets/Detail/SecretDetail/index.jsx
  src/pages/fedprojects/containers/Secrets/Detail/index.jsx
  src/pages/fedprojects/containers/Secrets/index.jsx
  src/pages/fedprojects/containers/Services/Detail/index.jsx
  src/pages/fedprojects/containers/Services/index.jsx
  src/pages/fedprojects/containers/StatefulSets/Detail/ServiceCard/index.jsx
  src/pages/fedprojects/containers/Volumes/Detail/index.jsx
  src/pages/projects/components/Modals/CreateApp/Routes/index.jsx
  src/pages/projects/containers/Overview/ResourceUsage/index.jsx
  src/stores/federated.js
  src/utils/object.mapper.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#1054 refactor: Refactor project role templates
  src/components/Modals/EditAuthorization/CheckItem.jsx
  src/components/Modals/EditAuthorization/constants.js
  src/locales/en/grayrelease.js
  src/locales/en/role.js
  src/locales/es/grayrelease.js
  src/locales/es/role.js
  src/locales/tc/grayrelease.js
  src/locales/tc/role.js
  src/locales/zh/grayrelease.js
  src/locales/zh/role.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#1056 fix: Fix cluster settings permission
  server/config.yaml
  src/components/Forms/MailServerForm/index.jsx
  src/components/Inputs/UrlInput/index.jsx
  src/pages/clusters/containers/LogCollections/Detail/Log/index.jsx
  src/pages/clusters/containers/LogCollections/Detail/Log/index.scss
  src/pages/clusters/containers/LogCollections/Detail/index.jsx
  src/pages/clusters/containers/LogCollections/Detail/routes.js
  src/pages/clusters/containers/LogCollections/index.jsx
  src/pages/clusters/containers/MailServices/index.jsx
  src/pages/clusters/containers/Visibility/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#1057 fix: Fix the bug when editing the pipeline and add sortBy in the credential
  src/components/Forms/CICDs/AdvanceSettings/index.jsx
  src/components/Forms/CICDs/BaseInfo/index.jsx
  src/components/Forms/CICDs/RepoSelect/BitBucketForm/index.jsx
  src/pages/devops/containers/Credential/index.jsx
  src/pages/devops/containers/Pipelines/Modals/editPipelineConfigModal.jsx
  src/pages/devops/containers/Pipelines/index.jsx
  src/stores/devops/credential.js
  src/stores/devops/pipelines.js
Labels: approved, dco-signoff: yes, lgtm, size/M

#1058 fix: Fix cluster crd permission
  server/config.yaml
  src/core/global.js
  src/pages/clusters/containers/CustomResources/Detail/ResourceStatus/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1059 update: Update tc locale, modify the new descriptions
  src/locales/tc/base.js
  src/locales/tc/project.js
  src/locales/tc/role.js
  src/locales/tc/storage.js
  src/locales/tc/workload.js
Labels: approved, dco-signoff: yes, lgtm, size/S

#1064 fix new UI wording and add missing es key
  src/components/Forms/Volume/VolumeSettings/FormTemplate.jsx
  src/components/Forms/Workload/VolumeSettings/AddHostPath/index.jsx
  src/components/Forms/Workload/VolumeSettings/AddTemporary/index.jsx
  src/components/Forms/Workload/VolumeSettings/AddVolumeTemplate/index.jsx
  src/components/Modals/SetDefaultStorageClass/index.jsx
  src/locales/en/storage.js
  src/locales/es/cicd.js
  src/locales/es/storage.js
  src/locales/es/workload.js
  src/locales/tc/storage.js
  src/locales/zh/storage.js
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/M

#1062 fix: Fix app store not login page
  server/config.yaml
  server/proxy.js
  src/components/Layout/Header/index.jsx
  src/pages/appStore/containers/AppDetail/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1066 fix: Show project overview when user can view workloads
  server/config.yaml
  src/core/global.js
  src/pages/console/containers/Dashboard/index.jsx
  src/pages/projects/containers/Base/List/index.jsx
  src/pages/projects/containers/BaseInfo/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1069 fix: Fix the issues about the devops create and edit, verify the access,the reviewer
  src/actions/devops.js
  src/components/Forms/CICDs/RepoSelect/BitBucketForm/index.jsx
  src/components/Modals/DevOpsCreate/index.jsx
  src/pages/devops/components/Pipeline/StepModals/input.jsx
  src/pages/devops/components/Pipeline/store.js
  src/pages/workspaces/containers/DevOps/index.jsx
  src/stores/devops.js
  src/stores/devops/scm.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#1071 fix: Fix the bug about Network Policy description Details
  src/components/Modals/Network/Policies/index.jsx
  src/locales/en/network.js
  src/locales/zh/network.js
  src/pages/projects/containers/Network/Policies/Detail/Viewer/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1073 fix: Remove resource_name in monitoring codes
  src/components/Cards/RankTable/WorkspaceTable/index.jsx
  src/components/Modals/Monitoring/Multiple/Pods.jsx
  src/components/Modals/Monitoring/Multiple/index.js
  src/components/Modals/Monitoring/Multiple/index.scss
  src/pages/clusters/components/Cards/Monitoring/UsageRank/index.jsx
  src/pages/clusters/components/Cards/Monitoring/UsageRank/index.scss
  src/pages/clusters/components/Cards/Monitoring/UsageRank/select.jsx
  src/pages/clusters/components/Cards/Monitoring/index.js
  src/pages/clusters/containers/Base/Detail/index.jsx
  src/pages/clusters/containers/Monitor/Cluster/Ranking/index.jsx
  src/pages/clusters/containers/Monitor/Resource/Ranking/Project/index.jsx
  src/pages/fedprojects/containers/Base/Detail/index.jsx
  src/pages/fedprojects/containers/Deployments/Detail/Monitoring/index.jsx
  src/pages/fedprojects/containers/Overview/UsageRanking/index.jsx
  src/pages/projects/components/Modals/GrayReleaseDetail/Component/index.jsx
  src/pages/projects/components/Modals/PodsMonitoring/Charts.jsx
  src/pages/projects/components/Modals/PodsMonitoring/Resources.jsx
  src/pages/projects/components/Modals/PodsMonitoring/index.jsx
  src/pages/projects/components/Modals/PodsMonitoring/index.scss
  src/pages/projects/containers/Base/Detail/index.jsx
  src/pages/projects/containers/Deployments/Detail/Monitoring/index.jsx
  src/pages/projects/containers/Overview/UsageRanking/index.jsx
  src/pages/workspaces/containers/Overview/UsageRanking/index.jsx
  src/stores/monitoring/base.js
  src/stores/monitoring/component.js
  src/stores/monitoring/container.js
  src/stores/monitoring/node.js
  src/stores/monitoring/pod.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XL

#1075 fix: Fix volume snapshots paging
  src/pages/projects/containers/Volumes/Detail/Snapshots/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1076 fix: Fix dashboard redirect
  src/pages/console/containers/Dashboard/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1077 fix: Fix chart schema parse
  src/components/Base/Slider/index.jsx
  src/components/Base/Slider/index.scss
  src/pages/clusters/containers/Alerting/Messages/Detail/AlertDetail/index.jsx
  src/stores/openpitrix/version.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1078 fix: Fix heml chart without schema deploy
  src/components/Forms/AppDeploy/AppConfig/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1074 fix: add the version description in app info and title in build mirror
  src/locales/en/app_store.js
  src/locales/es/app_store.js
  src/locales/tc/app_store.js
  src/locales/zh/app_store.js
  src/pages/appStore/components/AppInfo/index.jsx
  src/pages/appStore/components/AppInfo/index.scss
  src/pages/appStore/containers/AppDetail/index.jsx
  src/pages/projects/components/Cards/ImageBuilderLastRun/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1080 fix: Fix the role delete when it has authorized users
  src/pages/devops/containers/Roles/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1079 fix: Fix op app list data getting
  src/pages/projects/containers/Applications/OPApps.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1084 fix: Fix cluster diff form styles
  package.json
  src/components/Forms/Workload/ClusterDiffSettings/ContainerImage/index.jsx
  src/components/Forms/Workload/ClusterDiffSettings/ContainerPorts/index.jsx
  src/components/Forms/Workload/ClusterDiffSettings/ContainerPorts/index.scss
  src/components/Forms/Workload/ClusterDiffSettings/EditForm/index.jsx
  src/components/Forms/Workload/ClusterDiffSettings/EditForm/index.scss
  src/components/Forms/Workload/ClusterDiffSettings/Environments/index.jsx
  src/components/Forms/Workload/ClusterDiffSettings/Environments/index.scss
  yarn.lock
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#1087 fix: Fix some issues
  server/config.yaml
  server/libs/request.base.js
  src/actions/storageclass.js
  src/components/Forms/Workload/ContainerSettings/ContainerList/Card.jsx
  src/core/global.js
  src/locales/en/workload.js
  src/locales/es/workload.js
  src/locales/tc/workload.js
  src/locales/zh/workload.js
  src/pages/projects/containers/Base/List/index.jsx
  src/utils/object.mapper.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1086 fix: Fix operations for platform-admin
  server/services/session.js
  src/components/KubeTools/index.jsx
  src/pages/clusters/containers/Overview/Dashboard/index.jsx
  src/pages/clusters/containers/Projects/Detail/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1089 fix: Delete the back icon in pipeline breadcrumb
  src/components/Base/Breadcrumb/index.jsx
  src/components/Base/Breadcrumb/index.test.js
  src/core/layouts/Detail/index.jsx
  src/pages/devops/containers/Credential/detail/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Sider/runs-sider.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1090 fix: Fix project base info
  src/pages/devops/containers/BaseInfo/index.jsx
  src/pages/devops/containers/BaseInfo/index.scss
  src/pages/projects/containers/BaseInfo/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#1082 Add network policy UI key for es, tc
  src/locales/en/network.js
  src/locales/es/network.js
  src/locales/tc/network.js
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/XS

#1081 add component UI text
  src/locales/en/component.js
  src/locales/es/component.js
  src/locales/tc/component.js
  src/locales/zh/component.js
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/M

#1091 chore: Remove unuse components
  src/locales/es/app_template.js
  src/locales/es/crd.js
  src/locales/es/settings.js
  src/locales/es/sort_rank.js
  src/locales/es/workspace.js
  src/pages/apps/components/AppPreview/index.jsx
  src/pages/apps/components/AppPreview/index.scss
  src/pages/apps/components/Cards/Versions/Item.jsx
  src/pages/apps/components/Cards/Versions/index.jsx
  src/pages/apps/components/Cards/Versions/index.scss
  src/pages/projects/containers/ImageBuilder/Detail/Components/CodeResource/index.jsx
  src/pages/projects/containers/ImageBuilder/Detail/Components/CodeResource/index.scss
  src/pages/projects/containers/ImageBuilder/Detail/Components/EditModal.jsx
  src/pages/projects/containers/ImageBuilder/Detail/Components/S2iRecordTable.jsx
  src/pages/projects/containers/ImageBuilder/Detail/Components/index.scss
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XXL

#1096 chore: Update locales for projec role description
  src/locales/en/role.js
  src/locales/es/role.js
  src/locales/tc/role.js
  src/locales/zh/role.js
  src/pages/projects/containers/Applications/CRDAppDetail/routes.js
  src/pages/projects/containers/Applications/OPAppDetail/routes.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1093 fix: Fix some issues about alias, get the pipeline data and the build mirror restart
  src/actions/imagebuilder.js
  src/components/Forms/AlertingPolicy/BaseInfo/index.jsx
  src/components/Forms/ImageBuilder/RerunForm/index.jsx
  src/components/Modals/DevOpsEdit/index.jsx
  src/pages/devops/components/Modals/DevOpsEdit/index.jsx
  src/pages/devops/containers/Pipelines/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1094 update: Update tc locale, modify three new descriptions
  src/locales/tc/component.js
  src/locales/tc/network.js
  src/locales/tc/role.js
Labels: approved, dco-signoff: yes, lgtm, size/S

#1095 modify doc
  src/locales/zh/base.js
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1099 fix: Fix resource permission
  server/config.yaml
  src/components/Modals/EditAuthorization/CheckItem.jsx
  src/pages/clusters/containers/Overview/Dashboard/index.jsx
  src/pages/projects/containers/Applications/CRDAppDetail/GrayRelease/index.jsx
  src/pages/projects/containers/GrayRelease/Categories/index.jsx
  src/pages/projects/containers/GrayRelease/index.jsx
  src/pages/projects/containers/VolumeSnapshots/Detail/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1104 fix: Fix workspace network policy
  src/pages/workspaces/containers/BaseInfo/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1103 Fix crd and nav UI
  src/locales/en/base.js
  src/locales/en/cluster.js
  src/locales/en/crd.js
  src/locales/en/role.js
  src/locales/es/base.js
  src/locales/es/cluster.js
  src/locales/es/crd.js
  src/locales/es/role.js
  src/locales/tc/cluster.js
  src/locales/tc/crd.js
  src/locales/zh/crd.js
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/M

#1110 fix: Fix cluster visibility for public cluster
  src/pages/clusters/actions/cluster.js
  src/pages/clusters/components/Modals/ClusterVisibility/index.jsx
  src/pages/clusters/containers/Visibility/index.jsx
  src/stores/cluster/index.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1113 Fix image size UI
  src/locales/en/app.js
  src/locales/es/app.js
  src/locales/tc/app.js
  src/locales/zh/app.js
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/S

#1115 fix: Fix redirect after project deleted
  src/pages/clusters/containers/Projects/Detail/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1111 fix: Fix type switch in volume create modal
  src/components/Forms/Volume/VolumeSettings/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1118 fix: Fix cluster API
  src/stores/cluster/index.js
  src/utils/object.mapper.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1120 Add new account status UI
  src/locales/en/user.js
  src/locales/es/user.js
  src/locales/tc/user.js
  src/locales/zh/user.js
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/XS

#1121 update: Update storageclass description
  src/components/Forms/StorageClass/BaseInfo/index.jsx
  src/pages/clusters/containers/Storage/StorageClasses/Detail/index.jsx
  src/pages/clusters/containers/Storage/StorageClasses/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1122 fix: Fix credential management in devops role create
  src/components/Modals/EditAuthorization/constants.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1123 fix: Fix use settings modal restore
  src/components/Modals/UserSetting/BaseInfo/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1124 fix: Fix code erros tip by eslint
  package.json
  src/components/Base/Dragger/index.jsx
  src/components/Base/ScrollLoad/index.jsx
  src/components/Base/Steps/index.jsx
  src/components/Forms/GrayRelease/Components/Card/index.jsx
  src/components/Forms/ImageBuilder/B2IForm/index.jsx
  src/components/Graph/Detail/Monitors/TrafficCard.jsx
  src/components/Inputs/InputPassword/index.jsx
  src/components/Modals/AuditingSearch/Auditing/Detail/MetadataModal/Metadata/index.jsx
  src/components/Modals/CustomMonitoring/components/Form/GraphTargetsForm/index.jsx
  src/components/Modals/CustomMonitoring/components/FormInput/TableColumnStyle/index.jsx
  src/components/Modals/CustomMonitoring/components/RowTitleEditor/index.jsx
  src/components/Modals/CustomMonitoring/components/TableColumnStyleModal/index.jsx
  src/components/Modals/EventSearch/Event/Detail/MetadataModal/Metadata/index.jsx
  src/components/Tables/Ranking/index.jsx
  src/components/TextPreview/index.jsx
  src/pages/appStore/components/AppPreview/index.jsx
  src/pages/appStore/components/Banner/index.jsx
  src/pages/devops/components/Cards/CodeQualityResult/StatusCard.jsx
  src/pages/devops/components/Pipeline/StepModals/kubernetesDeploy.jsx
  src/pages/devops/components/Pipeline/StepsEditor/index.jsx
  src/pages/devops/containers/Pipelines/Detail/PipelineLogDialog/index.jsx
  src/pages/projects/components/Cards/ImageArtifacts/Item/index.jsx
  src/pages/projects/components/Modals/RepoApp/AppDetail/Banner/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1125 fix: Trim space of search word
  src/components/Base/Search/index.jsx
  src/components/Tables/Base/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1126 fix: Fix volume snapshots
  src/pages/appStore/containers/AppDetail/index.scss
  src/pages/clusters/containers/Storage/VolumeSnapshots/index.jsx
  src/pages/projects/containers/VolumeSnapshots/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1128 fix: Fix cluster projects operations
  src/pages/clusters/containers/Projects/Detail/index.jsx
  src/pages/clusters/containers/Projects/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1127 Chore(locales): minor grammar fix
  src/locales/en/network.js
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/XS

#1131 fix secret UI
  src/components/Forms/Secret/SecretSettings/index.jsx
  src/locales/en/secret.js
  src/locales/es/secret.js
  src/locales/tc/secret.js
  src/locales/zh/secret.js
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/S

#1136 fix: Fix the name's length limitation and the description don't displayed in pipeline.
  src/components/Forms/CICDs/BaseInfo/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Sider/pipeline-sider.jsx
  src/pages/devops/containers/Pipelines/index.jsx
  src/stores/devops.js
  src/stores/devops/pipelines.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1130 fix: Fix cluster project detail
  src/pages/clusters/containers/Projects/Detail/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1138 fix: Fix advance settings of federated resource
  src/components/Charts/Pie/PieChart/index.jsx
  src/components/Forms/Workload/AdvanceSettings/Metadata/index.jsx
  src/components/Forms/Workload/AdvanceSettings/Metadata/index.scss
  src/components/Forms/Workload/AdvanceSettings/NodeSchedule/index.scss
  src/components/Forms/Workload/AdvanceSettings/index.jsx
  src/components/Forms/Workload/AdvanceSettings/index.scss
  src/stores/cluster/index.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1140 fix: Fix errors in app edit
  src/pages/apps/components/Modals/AppEdit/index.jsx
  src/utils/constants.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1141 fix: Fix project detail reload in cluster pages
  src/pages/clusters/containers/Projects/Detail/Quota/index.jsx
  src/pages/clusters/containers/Projects/Detail/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1142 fix: Add remove tip for app template
  src/actions/openpitrix.js
  src/locales/en/app.js
  src/locales/es/app.js
  src/locales/tc/app.js
  src/locales/zh/app.js
  src/pages/workspaces/containers/Apps/Detail/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1144 update: Add default resource edit in cluster project detail
  src/components/Cards/ProjectQuota/QuotaItem/index.jsx
  src/components/Cards/ProjectQuota/QuotaItem/index.scss
  src/components/Cards/ProjectQuota/index.jsx
  src/components/Cards/ProjectQuota/index.scss
  src/pages/clusters/containers/Projects/Detail/Quota/index.jsx
  src/pages/clusters/containers/Projects/Detail/index.jsx
Labels: approved, dco-signoff: yes, kind/update, lgtm, size/L

#1145 fix: Fix project edit in cluster management
  src/pages/clusters/containers/Projects/Detail/index.jsx
  src/pages/clusters/containers/Projects/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1143 fix: Fix the size of the upload icon should not exceed 96px and add the jpg, tgz MIME type
  src/configs/openpitrix/app.js
  src/locales/en/app.js
  src/locales/es/app.js
  src/locales/tc/app.js
  src/locales/zh/app.js
  src/pages/apps/components/Cards/CreateInfo/index.jsx
  src/pages/apps/components/Forms/AppBaseEdit/index.jsx
  src/stores/openpitrix/file.js
Labels: approved, dco-signoff: yes, lgtm, size/M

#1149 update: Update tc locale, modify new descriptions and adjust the terms
  server/locales/tc.properties
  src/locales/tc/app.js
  src/locales/tc/base.js
  src/locales/tc/cicd.js
  src/locales/tc/cluster.js
  src/locales/tc/dashboard.js
  src/locales/tc/role.js
  src/locales/tc/settings.js
  src/locales/tc/user.js
Labels: approved, dco-signoff: yes, lgtm, size/M

#1153 fix: Fix volumes detail
  src/pages/fedprojects/containers/Volumes/Detail/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1147 fix: Fix log search results order
  src/components/Modals/AuditingSearch/Auditing/Detail/index.jsx
  src/components/Modals/AuditingSearch/Auditing/Detail/index.scss
  src/components/Modals/EventSearch/Event/Detail/index.jsx
  src/components/Modals/EventSearch/Event/Detail/index.scss
  src/components/Modals/LogSearch/Logging/Detail/index.jsx
  src/components/Modals/LogSearch/Logging/Search/index.jsx
  src/components/Modals/LogSearch/Logging/Search/index.scss
  src/components/Tables/Visible/index.jsx
  src/components/Tables/Visible/index.scss
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1146 fix: Fix the filter in pipeline table and get more then 10 items in the credential list
  src/components/Forms/CICDs/RepoSelect/GitForm/index.jsx
  src/components/Forms/CICDs/RepoSelect/SVNForm/index.jsx
  src/components/Forms/CICDs/RepoSelect/subForm.jsx
  src/pages/devops/components/Pipeline/StepModals/checkout.jsx
  src/pages/devops/components/Pipeline/StepModals/git.jsx
  src/pages/devops/components/Pipeline/StepModals/kubernetesDeploy.jsx
  src/pages/devops/components/Pipeline/StepModals/withCredentials.jsx
  src/pages/devops/components/Pipeline/store.js
  src/pages/devops/containers/Credential/index.jsx
  src/pages/devops/containers/Pipelines/index.jsx
  src/stores/devops/credential.js
  src/stores/devops/scm.js
Labels: approved, dco-signoff: yes, lgtm, size/L

#1155 fix: Filter terminating project
  src/components/Forms/AppDeploy/BasicInfo/Placement/index.jsx
  src/components/Inputs/ProjectSelect/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1159 Unify code repo UI
  src/components/Forms/ImageBuilder/S2IForm/index.jsx
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/XS

#1157 fix: Fix some issues
  server/middlewares/checkIfExist.js
  src/components/Modals/LogSearch/Logging/Detail/index.jsx
  src/locales/en/app.js
  src/locales/es/app.js
  src/locales/tc/app.js
  src/locales/zh/app.js
  src/pages/apps/components/Cards/ConfigFile/index.jsx
  src/pages/apps/components/Cards/UploadInfo/index.jsx
  src/pages/apps/components/Forms/VersionEdit/index.jsx
  src/pages/apps/components/Lists/VersionList/Item.jsx
  src/pages/workspaces/containers/Apps/Detail/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#1160 fix: Fix volumes missing in workload container setting
  src/components/Forms/Workload/ContainerSettings/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1161 fix: Fix ceph rbd provisioner
  src/utils/constants.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1162 fix: Restore check if exist api
  server/middlewares/checkIfExist.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1163 chore: Add locales for deployment location
  src/components/Forms/Workload/ContainerSettings/index.jsx
  src/locales/en/workload.js
  src/locales/es/workload.js
  src/locales/tc/workload.js
  src/locales/zh/workload.js
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/S

#1164 fix: Fix some issues in pipeline and s2i
  src/locales/en/s2i.js
  src/locales/es/s2i.js
  src/locales/tc/s2i.js
  src/locales/zh/s2i.js
  src/pages/devops/containers/Pipelines/index.jsx
  src/pages/projects/components/Cards/ImageRunRecord/Item/index.jsx
  src/pages/projects/components/Cards/S2iBuilder/index.jsx
  src/pages/projects/components/Cards/S2iBuilder/log.jsx
  src/pages/projects/components/Health/index.jsx
  src/pages/projects/containers/Deployments/Detail/ResourceStatus/index.jsx
  src/utils/request.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#1167 fix: Omit version in service selector
  src/components/Forms/Service/AdvanceSettings/index.jsx
  src/components/Forms/Service/BaseInfo/index.jsx
  src/components/Forms/Workload/ContainerSettings/index.jsx
  src/pages/projects/containers/Services/Detail/ResourceStatus/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1168 fix: Fix project applications permission and operations
  src/core/global.js
  src/pages/projects/containers/Applications/OPAppDetail/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1170 fix: Fix some issues about the BitBucket and jenkinsfile
  src/components/Forms/CICDs/RepoSelect/BitBucketForm/index.jsx
  src/components/Forms/CICDs/RepoSelect/GithubForm/index.jsx
  src/components/Forms/CICDs/RepoSelect/index.jsx
  src/pages/devops/components/Pipeline/StepModals/script.jsx
  src/pages/devops/components/Pipeline/store.js
  src/pages/devops/containers/Pipelines/Detail/Commit/index.jsx
  src/stores/devops/run.js
  src/stores/devops/scm.js
  src/stores/notification/mailService.js
  src/utils/index.js
  src/utils/request.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#1171 fix: Fix monitoring date in xAxis
  src/components/Charts/Area/MultiArea/index.jsx
  src/components/Charts/Area/PercentArea/index.jsx
  src/components/Charts/Bar/SimpleBar/index.jsx
  src/components/Charts/Bar/StackedBar/index.jsx
  src/components/Forms/Service/BaseInfo/index.jsx
  src/pages/projects/containers/Services/Detail/index.jsx
  src/stores/service.js
  src/utils/monitoring.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#1173 docs: chang 'folk' to 'fork'
  docs/development-workflow.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1176 fix: Fix log collection form
  src/actions/log.collection.js
  src/components/Forms/Elasticsearch/Settings/index.jsx
  src/components/Modals/LogCollectionCreate/config.js
  src/locales/en/logging.js
  src/locales/es/logging.js
  src/locales/tc/logging.js
  src/locales/zh/logging.js
  src/pages/clusters/containers/LogCollections/Detail/Configuration/index.jsx
  src/pages/clusters/containers/LogCollections/config.js
  src/pages/clusters/containers/LogCollections/index.scss
  src/stores/logging/collection/output.js
  src/utils/constants.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#1177 chore(locales): minor wording update
  src/locales/en/s2i.js
  src/locales/en/storage.js
  src/locales/es/s2i.js
  src/locales/es/storage.js
  src/locales/tc/s2i.js
  src/locales/zh/s2i.js
  src/pages/projects/components/Cards/ImageRunRecord/Item/index.jsx
  src/pages/projects/components/Cards/S2iBuilder/log.jsx
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/S

#1180 fix: Fix job update time
  src/locales/en/workload.js
  src/locales/es/workload.js
  src/locales/tc/workload.js
  src/locales/zh/workload.js
  src/pages/clusters/containers/Workload/Jobs/index.jsx
  src/pages/projects/containers/Jobs/index.jsx
  src/utils/object.mapper.js
  src/utils/workload.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1181 fix: Remove unit test for getLocalTime
  src/utils/index.test.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1182 fix: Fix federated workload edit permission
  src/pages/fedprojects/components/ClusterWorkloadStatus/Cluster.jsx
  src/pages/fedprojects/components/ClusterWorkloadStatus/index.jsx
  src/pages/fedprojects/containers/Deployments/Detail/ResourceStatus/index.jsx
  src/pages/fedprojects/containers/Services/Detail/ResourceStatus/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1184 chore(locales): Update tc locale
  src/locales/tc/app.js
  src/locales/tc/base.js
  src/locales/tc/logging.js
  src/locales/tc/s2i.js
  src/locales/tc/storage.js
  src/locales/tc/workload.js
Labels: approved, dco-signoff: yes, lgtm, size/S

#1185 fix: Fix the empty list display the wrong desc in the credential of devops
  src/pages/devops/containers/Credential/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1186 fix: Fix created success tip when workload requests empty
  src/stores/workload/index.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1187 fix: Fix create time format in volume detail
  src/pages/fedprojects/containers/Volumes/Detail/index.jsx
  src/pages/projects/containers/VolumeSnapshots/Detail/index.jsx
  src/pages/projects/containers/Volumes/Detail/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1188 fix: Fix the run pipeline in the branch and pipeline list
  src/pages/devops/containers/Pipelines/Detail/Sider/branch-sider.jsx
  src/pages/devops/containers/Pipelines/index.jsx
  src/stores/devops/base.js
  src/stores/devops/scm.js
  src/utils/request.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1190 fix: Fix loadbalancer info of service, ingress and gateway
  src/components/Forms/Route/RouteRules/RuleForm/index.jsx
  src/core/containers/Base/Detail/BaseInfo/Attributes/index.scss
  src/pages/clusters/containers/Workload/Routes/index.jsx
  src/pages/clusters/containers/Workload/Services/index.jsx
  src/pages/fedprojects/containers/AdvancedSettings/InternetAccess/Access/index.jsx
  src/pages/fedprojects/containers/Applications/Detail/AppIngresses/Ingresses/index.jsx
  src/pages/fedprojects/containers/Routes/Detail/ResourceStatus/Item/index.jsx
  src/pages/fedprojects/containers/Services/Detail/Ports/index.jsx
  src/pages/projects/components/Cards/Services/Item.jsx
  src/pages/projects/components/Modals/CreateApp/Routes/RuleForm/index.jsx
  src/pages/projects/components/Modals/CreateApp/index.jsx
  src/pages/projects/components/ServiceAccess/index.jsx
  src/pages/projects/containers/AdvancedSettings/InternetAccess/index.jsx
  src/pages/projects/containers/Routes/Detail/index.jsx
  src/pages/projects/containers/Routes/index.jsx
  src/pages/projects/containers/Services/Detail/Ports/index.jsx
  src/pages/projects/containers/Services/Detail/index.jsx
  src/pages/projects/containers/Services/index.jsx
  src/utils/object.mapper.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#1191 fix: Remove click access of service
  src/pages/projects/containers/Services/Detail/Ports/index.jsx
  src/pages/projects/containers/Services/Detail/ResourceStatus/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1193 Add service component desc
  src/locales/en/component.js
  src/locales/es/component.js
  src/locales/tc/component.js
  src/locales/zh/component.js
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/M

#1192 fix: Fix log collection text
  src/components/Forms/LoggingCollection/Status/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1194 fix: Fix the default value of shallow clone is false
  src/components/Forms/CICDs/AdvanceSettings/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1195 fix: Show volume usage card for all types
  src/pages/projects/containers/Volumes/Detail/ResourceStatus/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1196 fix: Fix the pipeline list had no access control
  src/pages/devops/containers/Pipelines/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1197 fix: Change pending op application to failed
  src/stores/openpitrix/application.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1198 fix: Fix Dragger onClick event
  src/components/Base/Dragger/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1200 fix: Fix PropertiesInput controled mode
  src/components/Forms/Service/ServiceSettings/SelectorsInput/index.jsx
  src/components/Inputs/PropertiesInput/index.jsx
  src/scss/lego.custom.scss
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1199 chore(locales): Update tc locale, modify component.js
  src/locales/tc/component.js
Labels: approved, dco-signoff: yes, lgtm, size/S

#1201 fix: Fix pod link error in graph detail
  src/components/Graph/Detail/Pods/Item.jsx
  src/components/Graph/Detail/Pods/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1202 fix: Fix loadBalancerIngress undefined error
  src/pages/fedprojects/containers/Applications/Detail/AppIngresses/Ingresses/index.jsx
  src/pages/fedprojects/containers/Routes/Detail/ResourceStatus/Item/index.jsx
  src/pages/projects/containers/AdvancedSettings/InternetAccess/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1204 fix: Add validator for servicemesh policy form
  src/components/Graph/Detail/PolicyForm/Session.jsx
  src/components/Graph/Detail/PolicyForm/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1205 fix: Fix clusters fetch API when creating workspace
  src/pages/workspaces/components/Modals/WorkspaceCreate/ClusterSettings/ClusterSelect/index.jsx
  src/stores/cluster/index.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1206 fix: Fix service edit cluster info missing
  src/actions/service.js
  src/components/Forms/Service/ServiceSettings/SelectorsInput/index.jsx
  src/pages/projects/components/Modals/ServiceSetting/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1203 add documentation links
  server/config.yaml
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/M

#1207 fix: Fix node conditions card
  src/pages/clusters/components/ResourceTable/index.jsx
  src/pages/clusters/containers/Nodes/Detail/RunningStatus/ConditionCard/index.jsx
  src/pages/clusters/containers/Nodes/Detail/RunningStatus/TaintCard/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1208 fix: Fix docs link
  src/utils/index.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1209 fix: Fix volume detail incorrect info
  src/pages/projects/components/Cards/Placement/index.jsx
  src/pages/projects/containers/Volumes/Detail/index.jsx
  src/stores/storageclasscapabilities.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1212 fix: Fix batch deletion items by rowkey in the Devops list
  src/actions/devops.js
  src/pages/workspaces/containers/DevOps/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1213 chore: Update docs links
  server/config.yaml
  src/pages/clusters/containers/Clusters/AddCluster/Configuration/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1214 fix: Fix the run job in the pipeline list have no parameters
  src/pages/devops/containers/Pipelines/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1215 update: Show entire yaml file of workload revision
  src/components/DiffYaml/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1216 fix: Fix log collection detail info
  src/pages/clusters/containers/LogCollections/Detail/Configuration/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1217 chore(locales): Update tc locale, modify typo
  src/locales/tc/workspace.js
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1218 fix: Fix app deploy placement and app status
  src/components/Forms/AppDeploy/BasicInfo/Placement/index.jsx
  src/stores/openpitrix/application.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1219 update: Add volume monitor tip
  src/locales/en/storage.js
  src/locales/es/storage.js
  src/locales/tc/storage.js
  src/locales/zh/storage.js
  src/pages/fedprojects/containers/Volumes/Detail/ResourceStatus/index.jsx
  src/pages/projects/containers/Volumes/Detail/ResourceStatus/UsageCard/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1220 Improve search field wording
  src/components/Cards/LogQuery/index.jsx
  src/components/Modals/ProjectSelect/index.jsx
  src/components/Tables/Base/index.jsx
  src/locales/en/alerting.js
  src/locales/en/base.js
  src/locales/es/alerting.js
  src/locales/es/base.js
  src/locales/tc/alerting.js
  src/locales/tc/base.js
  src/locales/zh/alerting.js
  src/locales/zh/base.js
  src/pages/clusters/components/Modals/ClusterSelect/index.jsx
  src/pages/clusters/containers/Alerting/Messages/index.jsx
  src/pages/clusters/containers/Clusters/index.jsx
  src/pages/clusters/containers/Storage/StorageClasses/Detail/Volumes/index.jsx
  src/pages/projects/containers/Alerting/Messages/index.jsx
  src/pages/workspaces/components/Modals/WorkspaceSelect/index.jsx
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/M

#1221 fix: Fix the error which the type of choice in the parameters have no choices
  src/components/Forms/CICDs/paramsModal.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1222 fix: Support rendering html in markdown component.
  src/components/Base/Markdown/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1223 chore(locales): Update tc locale, modify storage.js
  src/locales/tc/storage.js
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1225 fix: Support empty node taint value.
  src/components/Modals/Node/TaintManagement/TaintInput/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1226 fix: Fix log query export url
  src/components/Cards/LogQuery/index.jsx
  src/components/Modals/LogSearch/Logging/Detail/index.jsx
  src/stores/logging/index.js
  src/stores/logging/query.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S
