Repository kubesphere/console, pull requests merged in 2021-05, with the labels that each got.

#1870 Update github actions
  .github/workflows/main.yaml
Labels: approved, dco-signoff: yes, kind/cleanup, size/XS

#1866 send notfication only when failed
  .github/workflows/nightly-builds.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1881 fix: Fix the last login time of user in dashboard
  server/services/session.js
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1879 Fix bug in ROLE_USER_TIP.
  locales/es/role.js
  locales/tc/role.js
  locales/zh/role.js
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/XS

#1883 fix: Fix the app template version
  src/pages/apps/components/Forms/VersionEdit/index.jsx
  src/utils/constants.js
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1885 fix: smtp server port
  src/components/Forms/Notification/MailForm/index.jsx
  src/utils/constants.js
Labels: approved, dco-signoff: yes, lgtm, size/S

#1886 fix: Fix the time of alarm message displayed
  src/pages/projects/containers/Alerting/Policies/Detail/AlertMessages/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1880 chore: Modify the role name
  locales/en/meter.js
  locales/en/role.js
  locales/es/meter.js
  locales/es/role.js
  locales/tc/meter.js
  locales/tc/role.js
  locales/zh/meter.js
  locales/zh/role.js
  src/components/Modals/Bill/constats.js
  src/components/Modals/RoleCreate/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/S

#1890 fix: Remove the logging of tracing in clusterModule
  src/pages/projects/containers/Applications/CRDAppDetail/routes.js
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1887 fix: deselect the svg after performing an action on the svg like editing
  src/actions/configmap.js
  src/actions/resource.edit.js
  src/actions/router.js
  src/actions/service.js
  src/actions/serviceaccount.js
  src/components/Modals/EditBasicInfo/index.jsx
  src/components/Modals/EditServiceAccount/index.jsx
  src/components/Modals/EditYaml/index.jsx
  src/components/Modals/ModifyServiceAccountRole/index.jsx
  src/pages/clusters/containers/ServiceAccounts/index.jsx
  src/pages/projects/components/Modals/ConfigMapEdit/index.jsx
  src/pages/projects/components/Modals/RouteAnnotationsEdit/index.jsx
  src/pages/projects/components/Modals/RouteRulesEdit/index.jsx
  src/pages/projects/components/Modals/ServiceGatewaySetting/index.jsx
  src/pages/projects/components/Modals/ServiceSetting/index.jsx
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/L

#1888 fix: Fix the agent label is reset when the drawer is blur
  src/pages/devops/components/Pipeline/StepsEditor/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/M

#1895 fix: Modify default description infomation on Workspaces page
  src/pages/access/containers/Workspaces/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1894 fix: rename the button 'Rerun' to 'Run' on the b2i page #1543
  src/pages/projects/containers/ImageBuilder/Detail/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1896 fix: UI adjustment for Metering and Billing
  locales/en/meter.js
  locales/es/meter.js
  locales/tc/meter.js
  locales/zh/meter.js
  src/components/Modals/Bill/Details/Cluster/index.jsx
  src/components/Modals/Bill/components/Crumb/index.scss
  src/components/Modals/Bill/components/SideCard/item.jsx
  src/components/Modals/Bill/components/SideCard/item.scss
  src/components/Modals/Bill/components/Title/index.jsx
  src/stores/meter/base.js
Labels: approved, dco-signoff: yes, lgtm, size/L

#1904 fix: Screenshots wolud be deleted only if the edit is saved
  src/pages/apps/components/Modals/AppEdit/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1899 fix: Deleted workspace roles can not be used in Department Management
  locales/en/role.js
  locales/es/role.js
  locales/tc/role.js
  locales/zh/role.js
  src/components/Modals/RoleDelete/index.jsx
  src/stores/group.js
Labels: approved, dco-signoff: yes, lgtm, size/M

#1897 fix: Modify the naming rules of account names
  locales/en/user.js
  locales/es/user.js
  locales/tc/user.js
  locales/zh/user.js
  src/components/Modals/UserCreate/index.jsx
  src/core/containers/LoginConfirm/index.jsx
  src/utils/constants.js
Labels: approved, dco-signoff: yes, lgtm, size/S

#1902 fix: Update the sync status of credential
  src/pages/devops/containers/Credential/detail/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Branch/index.jsx
  src/pages/devops/containers/Pipelines/Detail/PullRequest/index.jsx
  src/pages/devops/containers/Pipelines/PipelinesList/index.jsx
Labels: approved, area/devops, dco-signoff: yes, lgtm, size/M

#1905 fix: Trusted User in multi-branch pipeline
  src/components/Forms/Pipelines/ActionsInput/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1912 fix: Modify the EditYaml module and EditBasicInfo module
  src/components/Modals/EditBasicInfo/index.jsx
  src/components/Modals/EditYaml/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1911 fix: Content is reset while editing credential with kubeconfig
  src/components/Modals/CredentialCreate/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1873 fix: Fix the webhook url in the single cluster
  src/components/Forms/Pipelines/AdvanceSettings/index.jsx
Labels: approved, area/devops, dco-signoff: yes, lgtm, size/XS

#1900 fix: Fix the multi-branch Pipeline run API is incorrect
  src/components/Forms/Pipelines/ParamsFormModal/index.jsx
Labels: approved, area/devops, dco-signoff: yes, lgtm, size/XS

#1906 Add gitpod as a tool to browser code lines
  .gitignore
  .gitpod.Dockerfile
  .gitpod.yml
  README.md
  scripts/webpack.dev.js
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/M

#1913 fix: Remove the console error
  src/actions/configmap.js
  src/pages/projects/components/Modals/ConfigMapEdit/index.jsx
  src/pages/projects/components/Modals/ServiceSetting/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1914 fix builderImage default value
  src/components/Forms/ImageBuilder/S2IForm/TemplateSelect/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1909 fix: Modify the display height and position of the cascader module
  src/components/Base/Cascader/Item.jsx
  src/components/Base/Cascader/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1863 Add Jenkins overview monitoring template
  src/assets/jenkins.svg
  src/stores/monitoring/custom/template.json
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XXL

#1901 chore: Fix the UI of code repository
  src/components/Forms/Pipelines/BaseInfo/index.jsx
  src/components/Forms/Pipelines/RepoSelect/index.scss
Labels: approved, area/devops, dco-signoff: yes, lgtm, size/M

#1922 fix: Rename the 'Rerun' to 'Run'
  src/components/Forms/ImageBuilder/RerunForm/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS
