Repository kubesphere/console, pull requests merged in 2021-07, with the labels that each got.

#2081 Revert "[release-3.1] feat: Add scan repo trigger in GitLab"
  locales/en/pipeline.js
  locales/es/pipeline.js
  locales/tc/pipeline.js
  locales/zh/pipeline.js
  src/components/Forms/Pipelines/AdvanceSettings/index.jsx
  src/components/Modals/Pipelines/ScanRepositoryLogs/index.jsx
  src/pages/devops/components/Pipeline/StepModals/environment.jsx
  src/pages/devops/containers/Pipelines/Detail/Layout/pipeline.jsx
  src/utils/constants.js
Labels: approved, dco-signoff: no, lgtm, size/M

#2084 fix: Fix auto logout when the clusterRole is not member
  src/utils/index.js
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2083 fix: Fix get cluster list in bill have no cluster view permission
  src/utils/meter.js
Labels: approved, dco-signoff: yes, lgtm, size/M

#2093 [release-3.1]fix: Fix the component click bubble problem
  src/components/Forms/Workload/ClusterDiffSettings/EditForm/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/S

#2095 fix: Fix the error caused by judgment conditions of cluster version in gitlab
  src/components/Forms/Pipelines/RepoSelect/subForm.jsx
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2097 fix: Fix add validator of limit resource in container image
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/S

#2100 fix: Fix the project quota can not submit
  src/actions/project.js
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2103 fix: Container logs do not display full Spaces.
  src/components/Cards/ContainerLog/index.scss
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#2109 fix: Fix error of deleting multiple resources in cluster
  src/actions/resource.delete.js
Labels: approved, do-not-merge/release-note-label-needed, lgtm, size/S

#2098 fix: Fix missing unit when creating/expanding volume
  src/components/Forms/Volume/VolumeSettings/FormTemplate.jsx
  src/components/Inputs/UnitSlider/index.jsx
  src/components/Inputs/index.js
  src/pages/projects/components/Modals/ExpandVolume/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/M

#2090 fix: Fix the typo in DevOps credential creating dialog
  locales/en/pipeline.js
  locales/es/pipeline.js
  locales/tc/pipeline.js
  locales/zh/pipeline.js
  src/components/Modals/CredentialCreate/index.jsx
  src/pages/devops/containers/Credential/detail/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#2089 fix: Modify the width of marks and let words not be squeezed
  src/components/Inputs/ResourceLimit/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2119 update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: release-note, size/M

#2117 support setting tag env in Makefile
  Makefile
Labels: approved, kind/feature, lgtm, release-note, size/XS

#2114 fix: Fix 'About' window can't be closed automatically
  src/components/Modals/About/index.jsx
Labels: approved, kind/bug, lgtm, release-note, size/XS

#2124 docs: compatible with the Mac of M1 chip
  README.md
Labels: approved, do-not-merge/release-note-label-needed, lgtm, size/XS

#2125 fix: Fix multi-cluster projects should not be able to select on BaseInfo step
  locales/en/workload.js
  locales/es/workload.js
  locales/tc/workload.js
  locales/zh/workload.js
  src/components/Forms/Workload/BaseInfo/index.jsx
Labels: approved, kind/bug, lgtm, release-note, size/M

#2108 fix: fix CronJobs rerun request url
  src/pages/projects/containers/CronJobs/Detail/JobRecords/index.jsx
Labels: approved, do-not-merge/release-note-label-needed, kind/bug, lgtm, size/XS

#2126 fix: Fix the project can not be selected in cluster
  src/components/Forms/Workload/BaseInfo/index.jsx
  yarn.lock
Labels: approved, do-not-merge/release-note-label-needed, kind/bug, lgtm, size/S
