Repository kubesphere/console, pull requests merged in 2021-11, with the labels that each got.

#2577 fix: Can't mount configMap in federatedDeployment
  src/components/Forms/Workload/VolumeSettings/MountConfig/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#2580 feat: Add GPU monitor template in custom monitor dashboard
  src/components/Modals/CustomMonitoring/containers/GraphMonitorForm.jsx
  src/components/Modals/CustomMonitoring/containers/TextMonitorForm.jsx
  src/stores/monitoring/custom/template.json
Labels: size/L, lgtm, approved, kind/feature, release-note

#2583 fix: Fix the tracing not display in create gateway modal
  src/actions/gateways.js
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#2582 Fix: Update es pipeline options
  locales/es/pipeline.js
Labels: size/XS, lgtm, approved, needs-ok-to-test, release-note-none, kind/require-ui-text-review

#2575 Fix the branch column of pipeline list
  src/pages/devops/containers/Pipelines/PipelinesList/index.jsx
Labels: size/XS, lgtm, approved, area/devops, kind/bug, needs-ok-to-test, release-note-none, hacktoberfest-accepted

#2579 fix: Mount hostpath volume error
  src/components/Cards/Volumes/Item.jsx
  src/utils/volume.js
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#2585 fix: Sonarqube testing bug
  server/views/blank_markdown.html
  src/components/Cards/LogQuery/index.scss
  src/components/Cards/Pods/Item.jsx
  src/components/Forms/ImageBuilder/B2IForm/index.scss
  src/components/Forms/ImageBuilder/S2IForm/index.scss
  src/components/Forms/Pipelines/RepoSelect/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/Input/index.scss
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/Select/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/index.scss
  src/components/Forms/Workload/ContainerSettings/index.scss
  src/components/Inputs/TagInput/index.scss
  src/components/Modals/Bill/Details/Cluster/index.jsx
  src/components/Modals/Bill/components/SideCard/item.jsx
  src/components/Modals/CustomMonitoring/components/GraphTypeSelectModal/index.scss
  src/components/Modals/LogSearch/Logging/Detail/index.scss
  src/components/Modals/Network/Policies/IpBlock.jsx
  src/components/Modals/ProjectSelect/index.jsx
  src/components/Modals/VolumeFunctionManage/index.scss
  src/pages/clusters/containers/Gateway/Components/Pods/Item.jsx
  src/pages/clusters/containers/Gateway/Detail/GatewayLog/index.scss
  src/pages/clusters/containers/Overview/Initializing/KubeKeyCluster/Logs/index.scss
  src/pages/devops/containers/Pipelines/Detail/Layout/pipeline.jsx
  src/pages/fedprojects/components/ClusterWorkloadStatus/index.scss
  src/pages/projects/components/Cards/ImageRunRecord/Item/index.scss
  src/pages/projects/containers/Services/Topology/Service/index.scss
  src/scss/markdown.scss
  src/scss/mixins.scss
  src/stores/devops/credential.js
  src/utils/constants.js
  src/utils/devops.js
  src/utils/request.js
  src/utils/status.js
Labels: size/L, lgtm, approved, kind/bug, release-note-none

#2588 fix:change '</br>' in tip text of grayrelease
  locales/zh/grayrelease.js
Labels: size/XS, lgtm, approved, kind/bug, needs-ok-to-test, release-note-none

#2587 fix:Remove the Activity option in the operation drop-down list of the pipeline list page
  src/pages/devops/containers/Pipelines/PipelinesList/index.jsx
Labels: lgtm, approved, size/S, area/devops, kind/bug, needs-ok-to-test, release-note-none

#2589 feat: Add available quotas tip during editing cluster different setting
  src/components/Forms/Workload/ClusterDiffSettings/ContainerImage/index.jsx
  src/components/Forms/Workload/ClusterDiffSettings/index.jsx
  src/pages/fedprojects/components/ClusterDiffSettings/index.jsx
  src/pages/fedprojects/components/ContainerImage/index.jsx
  src/pages/fedprojects/components/ContainerSetting/index.jsx
Labels: size/L, lgtm, approved, kind/feature, release-note-none

#2590 fix: Sonarqube bug
  src/components/Cards/Pods/Item.jsx
  src/pages/clusters/containers/Gateway/Components/Pods/Item.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#2596 fix: modify the address jump url of 'User Manual'.
  server/config.yaml
Labels: size/XS, lgtm, approved, kind/bug, needs-ok-to-test, release-note-none

#2594 fix: Fix the running status and log not be auto-updated in the pipeline
  src/stores/devops/run.js
Labels: size/XS, lgtm, approved, area/devops, kind/bug, release-note

#2601 fix: Optimize Synchronization Interval Descriptions.
  locales/en/app_repo.js
  locales/es/app_repo.js
  locales/tc/app_repo.js
  locales/zh/app_repo.js
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#2600 fix: Configmap's secret text too long
  src/components/Base/List/index.scss
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#2615 fix: Fix the UI of gpu quota
  package.json
  src/pages/projects/containers/BaseInfo/ResourceQuota/QuotaItem/index.jsx
  src/pages/workspaces/containers/QuotaManage/ResourceQuota/QuotaItem/index.jsx
  src/utils/constants.js
  yarn.lock
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#2610 fix: incorrect status display of DevOps Projects
  src/components/Base/Indicator/index.scss
  src/utils/object.mapper.js
Labels: size/XS, lgtm, approved, area/devops, kind/bug, needs-ok-to-test, tide/merge-method-squash, release-note-none

#2611 fix: Change UI element layout in the pipeline creation dialog box
  src/components/Forms/Pipelines/AdvanceSettings/index.jsx
Labels: lgtm, approved, size/M, area/devops, kind/design, ok-to-test, tide/merge-method-squash, release-note-none

#2608 fix: Delete update button in gateway page
  src/pages/clusters/containers/Gateway/Components/GatewayCard/index.jsx
  src/pages/clusters/containers/Gateway/Detail/index.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note

#2613 fix: Update project available quota when editing project quota
  src/components/Modals/QuotaEdit/index.jsx
  src/pages/fedprojects/containers/Overview/LimitRange/index.jsx
  src/pages/fedprojects/containers/QuotaManage/ResourceQuota/index.jsx
  src/utils/workload.js
Labels: lgtm, approved, size/M, kind/bug, release-note

#2621 fix: Remove Labels shown on the credential detail page
  src/pages/devops/containers/Credential/detail/index.jsx
Labels: size/XS, lgtm, approved, kind/cleanup, needs-ok-to-test, release-note

#2598 fix: Log detail highlight keyword is [Object Object]
  src/components/Modals/LogSearch/Logging/Search/index.jsx
  src/pages/clusters/containers/Gateway/Detail/GatewayLog/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note

#2622 fix: Status label inccrect
  src/components/Forms/Workload/VolumeSettings/AddExistVolumes/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note

#2627 Change Run Count to Run ID.
  locales/en/pipeline.js
  locales/es/pipeline.js
  locales/tc/pipeline.js
  locales/zh/pipeline.js
  src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Layout/runs.jsx
Labels: lgtm, approved, size/S, area/devops, kind/documentation, release-note-none

#2628 fix: Update documentation links to kubesphere.io and kubesphere.com.cn
  locales/en/app.js
  locales/en/logging.js
  locales/en/meter.js
  locales/es/app.js
  locales/tc/app.js
  locales/zh/app.js
  locales/zh/logging.js
  locales/zh/meter.js
  server/config.yaml
  src/components/Layout/Header/index.jsx
  src/components/Modals/AuditingSearch/index.jsx
  src/components/Modals/Bill/Details/Cluster/index.jsx
  src/components/Modals/EventSearch/index.jsx
  src/components/Modals/LogSearch/index.jsx
  src/pages/apps/components/Cards/TestSteps/index.jsx
  src/pages/apps/components/Modals/AppCreate/index.jsx
  src/pages/apps/components/Modals/HelmUpload/index.jsx
  src/utils/index.js
Labels: lgtm, approved, size/M, kind/bug, release-note

#2619 feat: Add avalibale quota tip when edting project resource default quota
  src/actions/project.js
  src/pages/fedprojects/containers/BaseInfo/index.jsx
  src/pages/fedprojects/containers/Overview/LimitRange/index.jsx
  src/pages/projects/components/Modals/DefaultResourceEdit/index.jsx
Labels: size/L, lgtm, approved, kind/feature, release-note

#2620 feat: Add status filter in pods manage page
  src/pages/clusters/containers/Workload/Pods/index.jsx
  src/pages/projects/containers/Pods/index.jsx
  src/utils/constants.js
Labels: lgtm, approved, size/M, kind/feature, release-note

#2630 fix: Update ui style in pv management page
  src/pages/fedprojects/containers/Volumes/index.jsx
  src/pages/projects/containers/Volumes/index.jsx
  src/pages/projects/containers/Volumes/index.scss
Labels: size/L, lgtm, approved, kind/bug, release-note-none

#2629 fix: No kind information on view volume instance yaml page
  src/stores/pv.js
Labels: lgtm, approved, size/S, kind/bug, release-note

#2649 feat: Optimize log query style
  src/components/Modals/LogSearch/Logging/Detail/index.jsx
  src/components/Modals/LogSearch/Logging/Detail/index.scss
Labels: lgtm, approved, size/M, kind/design, kind/feature, release-note-none

#2651 fix: Notification condition to add new tag validation rules
  locales/en/notification.js
  locales/es/notification.js
  locales/tc/notification.js
  locales/zh/notification.js
  src/components/Forms/Notification/BaseForm/ConditionSelect/index.jsx
  src/utils/constants.js
Labels: lgtm, approved, size/S, kind/bug, release-note-none, kind/require-ui-text-review

#2652 fix: Statefulsets deployment deatil page error
  src/pages/projects/containers/Deployments/Detail/ResourceStatus/index.jsx
  src/stores/workload/env.js
Labels: lgtm, approved, size/S, kind/bug, do-not-merge/release-note-label-needed

#2659 fix: Ui text error in pods management page
  locales/en/base.js
  locales/zh/base.js
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#2660 fix: Add the Deprecated tip of Kubernetes Deploy in Pipeline
  locales/en/devops.js
  locales/es/devops.js
  locales/tc/devops.js
  locales/zh/devops.js
  src/pages/devops/components/Pipeline/StepsSelector/index.jsx
  src/pages/devops/components/Pipeline/StepsSelector/index.scss
Labels: lgtm, approved, size/M, area/devops, kind/bug, release-note

#2656 fix: Can't update volume for deloyment
  src/components/Cards/Volumes/Item.jsx
  src/components/Forms/Workload/VolumeSettings/AddVolume/index.jsx
  src/components/Forms/Workload/VolumeSettings/index.jsx
Labels: size/L, lgtm, approved, kind/bug, release-note

#2667 fix: modify the jump of 'Component Status' of 'Cluster Status' page.
  src/pages/clusters/containers/Monitor/Cluster/Overview/index.jsx
  src/pages/clusters/containers/Monitor/Cluster/Overview/index.scss
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#2668 opt: Update avaliable quotas tips when creating deployment
  locales/en/project.js
  locales/en/workload.js
  locales/es/workload.js
  locales/tc/workload.js
  locales/zh/project.js
  locales/zh/workload.js
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
  src/components/Forms/Workload/ContainerSettings/index.jsx
  src/components/Inputs/ResourceLimit/index.jsx
  src/components/Modals/QuotaEdit/index.jsx
  src/pages/fedprojects/components/ContainerSetting/index.jsx
  src/pages/projects/components/Modals/DefaultResourceEdit/index.jsx
  src/stores/quota.js
  src/stores/workspace.quota.js
  src/utils/workload.js
Labels: size/L, lgtm, approved, kind/bug, release-note

#2678 fix: StatefulSet setting modal can't open
  src/components/Forms/Workload/VolumeSettings/VolumeTemplateList/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#2679 fix: Cannot use application fields for filtering
  src/components/HOCs/withList.js
  src/pages/projects/containers/Services/index.jsx
  src/stores/base.js
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#2681 fix: Update seconds verification rule
  src/components/Modals/AppRepoCreate/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#2682 fix: Update gpu limit number verification rule
  src/components/Inputs/ResourceLimit/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#2692 fix: Search params problem
  src/components/HOCs/withList.js
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#2686 fix: AccessMode abbreviation error in volume manage page
  src/utils/index.js
Labels: size/XS, lgtm, approved, kind/bug, release-note
