Repository kubesphere/console, pull requests merged in 2021-02, with the labels that each got.

#1460 update: Update application service mesh monitor
  package.json
  src/components/Graph/Card/index.jsx
  src/components/Graph/Card/index.scss
  src/components/Graph/Detail/Monitors/ServiceMonitor.jsx
  src/components/Graph/Detail/Monitors/WorkloadMonitor.jsx
  src/components/Graph/Detail/Monitors/WorkloadSelect/index.jsx
  src/components/Graph/Detail/Monitors/WorkloadSelect/index.scss
  src/components/Graph/Detail/Monitors/index.jsx
  src/components/Graph/Detail/Monitors/index.scss
  src/components/Graph/Detail/Pods/index.jsx
  src/components/Graph/Detail/index.jsx
  src/components/Graph/Detail/index.scss
  src/components/Graph/index.jsx
  src/pages/projects/components/Modals/CreateApp/index.jsx
  src/pages/projects/containers/Applications/CRDAppDetail/Tracing/index.jsx
  src/pages/projects/containers/GrayRelease/Categories/index.jsx
  yarn.lock
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/XXL

#1462 fix workspace groups module
  locales/en/group.js
  locales/es/group.js
  locales/tc/group.js
  locales/zh/group.js
  src/components/Modals/GroupDelete/index.jsx
  src/components/Modals/GroupDelete/index.scss
  src/components/Tree/style.scss
  src/pages/workspaces/components/Modals/EditGroup/Detail/Form/DevopsSelect.jsx
  src/pages/workspaces/components/Modals/EditGroup/Detail/index.jsx
  src/pages/workspaces/components/Modals/EditGroup/Detail/index.scss
  src/pages/workspaces/components/Modals/EditGroup/index.jsx
  src/pages/workspaces/containers/Groups/GroupUser/User.jsx
  src/pages/workspaces/containers/Groups/GroupUser/index.scss
  src/utils/group.js
Labels: approved, dco-signoff: yes, lgtm, size/L

#1463 chore: Change the URL of the GitLab projectList API with params
  src/pages/devops/containers/Pipelines/PipelinesList/index.jsx
  src/stores/devops/scm.js
Labels: approved, area/devops, dco-signoff: yes, lgtm, size/S

#1465 fix: fix namespace spell err and can't get SC data in AddVolumeTemplate
  src/components/Forms/Workload/VolumeSettings/AddVolumeTemplate/index.jsx
  src/components/Forms/Workload/VolumeSettings/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1468 fix: Fix too long text and the style is not friendly
  src/pages/workspaces/components/Modals/EditGroup/Detail/Card/index.scss
  src/pages/workspaces/components/Modals/EditGroup/Detail/index.scss
  src/pages/workspaces/containers/Groups/GroupTree/index.jsx
  src/pages/workspaces/containers/Groups/GroupUser/index.scss
  src/pages/workspaces/containers/Groups/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/M

#1470 fix: Fix the data is empty in GitLab
  locales/en/pipeline.js
  locales/es/pipeline.js
  locales/tc/pipeline.js
  locales/zh/pipeline.js
  src/components/Forms/Pipelines/RepoSelect/GitLabForm/index.jsx
  src/stores/devops/scm.js
Labels: approved, dco-signoff: yes, lgtm, size/M

#1472 fix: Fix tree overflow
  src/components/Tree/style.scss
  src/pages/workspaces/containers/Groups/GroupTree/index.jsx
  src/pages/workspaces/containers/Groups/GroupTree/index.scss
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/M

#1469 Deployment mode adout affinity
  locales/en/workload.js
  locales/es/workload.js
  locales/tc/workload.js
  locales/zh/workload.js
  src/actions/workload.js
  src/components/EditForms/Workload/Affinity/index.jsx
  src/components/Forms/Workload/ContainerSettings/Affinity/index.jsx
  src/components/Forms/Workload/ContainerSettings/index.jsx
  src/components/Modals/Edit/Form/index.jsx
  src/components/Modals/Edit/index.jsx
  src/pages/projects/components/Modals/ConfigTemplate/config.js
Labels: approved, dco-signoff: yes, lgtm, size/L

#1473 fix: Fix the create credential modal in repo form have not to submit
  locales/en/pipeline.js
  locales/es/pipeline.js
  locales/tc/pipeline.js
  locales/zh/pipeline.js
  package.json
  src/components/Forms/Pipelines/RepoSelect/subForm.jsx
  src/pages/devops/components/Pipeline/StepModals/branch.jsx
  src/pages/devops/containers/Pipelines/Detail/routes.js
  src/stores/devops/scm.js
  yarn.lock
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/M

#1474 fix: Fix application ingress edit error
  src/pages/projects/components/Modals/CreateApp/Routes/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1475 chore: Support search and vscode keymap in CodeEditor
  src/components/Base/CodeEditor/AceEditor.jsx
  src/components/Base/CodeEditor/custom.css
  src/components/Base/CodeEditor/index.jsx
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/M

#1478 Fix: fix group multiple refresh and modal tree overflow
  src/pages/workspaces/components/Modals/EditGroup/Department/index.jsx
  src/pages/workspaces/components/Modals/EditGroup/Department/index.scss
  src/pages/workspaces/containers/Groups/GroupTree/index.jsx
  src/pages/workspaces/containers/Groups/GroupTree/index.scss
  src/pages/workspaces/containers/Groups/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/M

#1476 feat: Add Ignore Cert in the Image
  locales/en/workload.js
  locales/es/workload.js
  locales/tc/workload.js
  locales/zh/workload.js
  src/components/Forms/Pipelines/RepoSelect/subForm.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/index.scss
  src/stores/container.js
Labels: approved, area/devops, dco-signoff: yes, lgtm, size/M

#1459 Fix typo in Traditional Chinese translations
  locales/tc/alerting.js
  locales/tc/app.js
  locales/tc/application.js
  locales/tc/base.js
Labels: approved, dco-signoff: yes, lgtm, size/M

#1482 fix: Fix history card style in single cluster mode
  src/pages/console/containers/Dashboard/Admin/History/Card.jsx
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/XS

#1484 chore: Update object edit modal locales
  src/components/Modals/ObjectEdit/index.jsx
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/XS

#1486 Fix the field of basic-auth secret
  src/stores/devops/scm.js
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/XS

#1488 fix:code editor error
  src/pages/projects/containers/ServiceAccounts/Detail/ServiceAccountDetail/Secret.jsx
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1489 fix: Support http2, grpc protocols in canary release request content …
  locales/en/grayrelease.js
  locales/es/grayrelease.js
  locales/tc/grayrelease.js
  locales/zh/grayrelease.js
  src/components/Forms/GrayRelease/Components/index.jsx
  src/components/Forms/GrayRelease/PolicyConfig/Canary/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1477 update: Update oauth callback to support cas
  server/controllers/session.js
  server/routes.js
  server/services/session.js
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XS

#1492 fix: Fix the message of commit in pipeline Pull-Request detail
  locales/tc/base.js
  locales/zh/base.js
  src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Commit/index.jsx
  src/stores/devops/run.js
Labels: approved, area/devops, dco-signoff: yes, lgtm, size/M

#1493 Feat: Namespace started with kube- is not allowed
  locales/en/base.js
  locales/es/base.js
  locales/tc/base.js
  locales/zh/base.js
  src/components/Modals/ProjectCreate/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/S
