Repository kubesphere/console, pull requests merged in 2021-08, with the labels that each got.

#2128 fix: Fix the cursor of project's Selector
  src/pages/projects/components/Selector/index.scss
Labels: approved, kind/bug, lgtm, release-note, size/XS

#2118 fix: Fix the value of quota when it's equal to infinity
  src/actions/project.js
Labels: approved, kind/bug, lgtm, release-note, size/XS

#2111 fix: Fix the translation for workspace members
  locales/tc/workspace.js
  locales/zh/workspace.js
Labels: approved, kind/bug, lgtm, release-note-none, size/XS

#2142 fix: Remove the pod count in fedproject overview
  src/pages/fedprojects/containers/Overview/ResourceUsage/index.jsx
Labels: approved, do-not-merge/release-note-label-needed, kind/bug, lgtm, size/XS

#2144 fix: Didn't show the full changeset of a pipeline run.
  src/stores/devops/run.js
Labels: lgtm, approved, size/S, kind/bug, ok-to-test, release-note

#2139 feat: The number of replicas button is change to "+" and "-"
  src/pages/projects/components/Cards/Replica/Status/NumberControl.jsx
  src/pages/projects/components/Cards/Replica/Status/index.scss
Labels: lgtm, approved, size/S, kind/feature, do-not-merge/release-note-label-needed

#2133 fix: The name of devops project is wrong in branch detail page
  src/pages/devops/containers/Pipelines/Detail/Layout/branch.jsx
Labels: lgtm, approved, kind/bug

#2137 fix: Fix pop up window cannot be closed
  src/pages/projects/components/Modals/CreateAppService/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, do-not-merge/release-note-label-needed

#2150 fix: Modify the description and default value about old branches discard
  locales/en/pipeline.js
  locales/es/pipeline.js
  locales/tc/pipeline.js
  locales/zh/pipeline.js
  src/components/Forms/Pipelines/AdvanceSettings/index.jsx
Labels: lgtm, approved, size/M, kind/bug, do-not-merge/release-note-label-needed

#2147 feat: Support to display multiple ip's of pod
  src/components/Cards/Pods/Item.jsx
  src/components/Cards/Pods/index.scss
  src/utils/object.mapper.js
Labels: lgtm, approved, size/M, kind/feature, do-not-merge/release-note-label-needed

#2151 fix: Fix networksStatus error in pod
  src/utils/object.mapper.js
Labels: size/XS, lgtm, approved, kind/bug, do-not-merge/release-note-label-needed

#2134 fix: Pipeline editor cant save init value
  src/pages/devops/components/Pipeline/StepModals/script.jsx
  src/pages/devops/components/Pipeline/StepModals/shell.jsx
Labels: lgtm, approved, size/S, area/devops, kind/bug, do-not-merge/release-note-label-needed

#2087 fix: Add the validation rule in editing container configuration template page
  locales/en/workload.js
  locales/es/workload.js
  locales/tc/workload.js
  locales/zh/workload.js
  src/components/Forms/Workload/ContainerSettings/UpdateStrategy/index.jsx
Labels: lgtm, approved, size/M, dco-signoff: yes

#2153 fix: Detect UI text entries in different locale files.
  package.json
  scripts/checkRepeat.js
  scripts/locale-plugin.js
Labels: lgtm, approved, size/M, kind/feature, release-note

#2163 Update Pods Page
  locales/en/base.js
  locales/en/workload.js
  locales/es/base.js
  locales/es/workload.js
  locales/tc/base.js
  locales/tc/workload.js
  locales/zh/base.js
  locales/zh/workload.js
  src/components/Cards/Pods/Item.jsx
  src/pages/clusters/containers/Workload/Pods/index.jsx
  src/pages/projects/containers/Pods/Detail/index.jsx
  src/pages/projects/containers/Pods/index.jsx
Labels: lgtm, approved

#2155 feat: The fedProject add the clusters feature
  locales/en/project.js
  locales/es/project.js
  locales/tc/project.js
  locales/zh/project.js
  src/actions/federated.js
  src/components/Forms/AppDeploy/BasicInfo/Placement/index.jsx
  src/pages/fedprojects/App.jsx
  src/pages/fedprojects/containers/BaseInfo/ProjectInfo/index.jsx
  src/pages/fedprojects/containers/BaseInfo/index.jsx
  src/pages/workspaces/components/Modals/FedProjectAddCluster/index.jsx
  src/pages/workspaces/components/Modals/FedProjectAddCluster/index.scss
  src/pages/workspaces/containers/FedProjects/index.jsx
Labels: size/L, lgtm, approved, kind/feature, do-not-merge/release-note-label-needed

#2156 Improve the image tag name in the makefile
  Makefile
Labels: size/XS, lgtm, approved, kind/cleanup, release-note-none

#2173 feat: Disclaimer at app store
  locales/en/app_store.js
  locales/es/app_store.js
  locales/tc/app_store.js
  locales/zh/app_store.js
  src/pages/apps/components/AppInfo/index.jsx
  src/pages/apps/components/AppInfo/index.scss
  src/pages/apps/containers/AppDetail/index.jsx
Labels: size/L, lgtm, approved, kind/feature, release-note

#2171 fix: Fix access type error on the edit service page
  src/pages/fedprojects/components/ServiceSetting/index.jsx
  src/pages/projects/components/Modals/ServiceSetting/Form.jsx
  src/pages/projects/components/Modals/ServiceSetting/index.jsx
  src/utils/constants.js
Labels: lgtm, approved, size/S, kind/bug, release-note

#2177 Replace the tag name to latest if branch name is master
  Makefile
Labels: size/XS, lgtm, approved, release-note-none

#2178 update: Update service types value
  src/utils/constants.js
Labels: size/XS, lgtm, approved, kind/bug, release-note

#2056 fix: Fix the repeat key in quota editor modal
  src/components/Modals/QuotaEdit/Quotas/Item.jsx
  src/components/Modals/QuotaEdit/Quotas/index.jsx
  src/pages/projects/containers/BaseInfo/ResourceQuota/QuotaItem/index.jsx
  src/pages/projects/containers/BaseInfo/ResourceQuota/QuotaItem/index.scss
  src/pages/projects/containers/BaseInfo/ResourceQuota/index.jsx
Labels: size/L, lgtm, approved, kind/bug, dco-signoff: yes

#2170 fix: Custom pod replicas deployment
  locales/en/workload.js
  locales/es/workload.js
  locales/zh/workload.js
  src/actions/workload.js
  src/components/Forms/Workload/ContainerSettings/Affinity/index.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note

#2161 fix: Project Quota or Container Quota greater than Workspace Quota
  locales/en/workload.js
  locales/es/workload.js
  locales/tc/workload.js
  locales/zh/workload.js
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/index.jsx
  src/components/Forms/Workload/ContainerSettings/index.jsx
  src/components/Inputs/ResourceLimit/index.jsx
  src/components/Inputs/ResourceLimit/index.scss
  src/components/Modals/QuotaEdit/index.jsx
Labels: size/L, lgtm, approved, kind/bug, release-note-none

#2127 fix: enter a number with two places of decimal directly and limit input maximum
  src/actions/project.js
  src/components/Inputs/ResourceLimit/index.jsx
Labels: size/L, lgtm, approved, kind/bug, release-note

#2187 Update UI text on Jobs and CronJobs pages
  locales/en/base.js
  locales/en/cluster.js
  locales/en/project.js
  locales/en/workload.js
  locales/es/base.js
  locales/es/cluster.js
  locales/es/project.js
  locales/es/workload.js
  locales/tc/base.js
  locales/tc/cluster.js
  locales/tc/project.js
  locales/tc/workload.js
  locales/zh/base.js
  locales/zh/cluster.js
  locales/zh/project.js
  locales/zh/workload.js
  src/components/Forms/CronJob/BaseInfo/index.jsx
  src/components/Forms/Job/ContainerSettings/index.jsx
  src/components/Forms/Job/JobSettings/index.jsx
  src/components/Forms/Workload/AdvanceSettings/Metadata/index.jsx
  src/components/Forms/Workload/VolumeSettings/VolumeList/index.jsx
  src/components/Forms/Workload/VolumeSettings/index.jsx
  src/pages/clusters/containers/Nodes/Detail/routes.js
  src/pages/clusters/containers/Overview/Initializing/index.jsx
  src/pages/clusters/containers/Workload/CronJobs/index.jsx
  src/pages/clusters/containers/Workload/Jobs/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Layout/runs.jsx
  src/pages/fedprojects/containers/AdvancedSettings/LogCollection/index.jsx
  src/pages/fedprojects/containers/AdvancedSettings/index.jsx
  src/pages/projects/components/Cards/S2iBuilder/RerunModal/index.jsx
  src/pages/projects/components/Modals/RebuildS2i/index.jsx
  src/pages/projects/containers/AdvancedSettings/LogCollection/index.jsx
  src/pages/projects/containers/AdvancedSettings/index.jsx
  src/pages/projects/containers/CronJobs/Detail/index.jsx
  src/pages/projects/containers/CronJobs/index.jsx
  src/pages/projects/containers/Jobs/Detail/index.jsx
  src/pages/projects/containers/Jobs/index.jsx
  src/pages/projects/containers/Services/Topology/index.jsx
Labels: size/L, lgtm, approved, kind/documentation, do-not-merge/release-note-label-needed

#2199 feat: Change the judgment field in storage management
  locales/en/scheduleDeployment.js
  locales/es/scheduleDeployment.js
  locales/tc/scheduleDeployment.js
  locales/zh/scheduleDeployment.js
  src/actions/storageclass.js
  src/components/Modals/VolumeFunctionManage/index.jsx
  src/components/Modals/VolumeFunctionManage/index.scss
  src/pages/clusters/containers/Storage/StorageClasses/Detail/index.jsx
  src/pages/projects/containers/Volumes/Detail/index.jsx
Labels: size/L, lgtm, approved, kind/feature, release-note

#2196 feat: change the select component to the autoComplete component in ru…
  src/components/Inputs/RulePath/index.jsx
  src/components/Inputs/RulePath/index.scss
Labels: lgtm, approved, size/S, kind/feature, ok-to-test, release-note

#2203 fix: set fixed replicas mode as default mode in workload create form
  src/actions/workload.js
  src/components/Forms/Workload/ContainerSettings/ClusterReplicasControl/index.jsx
  src/components/Forms/Workload/ContainerSettings/index.jsx
Labels: lgtm, approved, size/S, kind/feature, release-note-none

#2194 fix: Fix the referer url
  server/controllers/view.js
Labels: size/XS, lgtm, approved, kind/bug, release-note

#2167 feat: The fedProject service support the sort and edit service
  src/pages/fedprojects/containers/Services/index.jsx
Labels: lgtm, approved, size/S, release-note
