Repository kubesphere/console, pull requests merged in 2021-09, with the labels that each got.

#2204 fix: Code optimization about pr #2199
  src/actions/storageclass.js
  src/components/Modals/VolumeFunctionManage/index.jsx
  src/pages/projects/containers/Volumes/Detail/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#2129 feat: Add pod annotation in pod container of creat workload
  locales/en/workload.js
  locales/es/workload.js
  locales/tc/workload.js
  locales/zh/workload.js
  src/components/Forms/Workload/ContainerSettings/Metadata/index.jsx
  src/components/Forms/Workload/ContainerSettings/index.jsx
Labels: lgtm, approved, size/M, kind/feature, release-note

#2218 feat: support multiple snapshotclass when taking snapshot
  locales/en/storage.js
  locales/es/storage.js
  locales/tc/storage.js
  locales/zh/storage.js
  src/actions/volume.js
  src/pages/projects/components/Modals/ResourceSnapshot/index.jsx
  src/pages/projects/containers/Volumes/Detail/index.jsx
  src/stores/volume.js
Labels: size/L, lgtm, approved, kind/feature, release-note

#2225 change image tag to match branch name
  .github/workflows/main.yaml
Labels: size/XS, kind/cleanup, release-note-none

#2222 Update UI Text on Banners
  locales/en/ingress.js
  locales/en/ippool.js
  locales/es/ingress.js
  locales/es/ippool.js
  locales/tc/crd.js
  locales/tc/ingress.js
  locales/tc/ippool.js
  locales/tc/secret.js
  locales/zh/crd.js
  locales/zh/ingress.js
  locales/zh/ippool.js
  locales/zh/secret.js
Labels: lgtm, approved, size/M, kind/documentation, do-not-merge/release-note-label-needed

#2200 fix: Fix the status of the branches in the pipeline
  src/pages/devops/containers/Pipelines/Detail/Branch/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Branch/index.scss
  src/pages/devops/containers/Pipelines/Detail/PullRequest/index.jsx
  src/pages/devops/containers/Pipelines/Detail/PullRequest/index.scss
Labels: lgtm, approved, size/M, area/devops, release-note

#2221 fix: Code optimization about pr #2218
  src/actions/volume.js
  src/pages/projects/containers/Volumes/Detail/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#2220 feat: support choose volume binding mode when create storageclass
  locales/en/storage.js
  locales/es/storage.js
  locales/tc/storage.js
  locales/zh/storage.js
  src/components/Forms/StorageClass/StorageClassSettings/index.jsx
  src/utils/form.templates.js
Labels: lgtm, approved, size/M, kind/feature, release-note

#2215 fix: Fix the pod render in workload of alerting
  src/pages/projects/containers/Alerting/Messages/index.jsx
  src/pages/projects/containers/Alerting/Policies/Detail/AlertMessages/index.jsx
  src/utils/alerting.js
  src/utils/constants.js
Labels: lgtm, approved, size/M, release-note

#2206 fix: Fix the position of hammer icon when title is empty on Create ConfigMap modal
  src/components/Base/List/Item.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note

#2211 fix: Hide unbind cluster panel in the host cluster
  src/pages/clusters/containers/BaseInfo/index.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note

#2088 fix: Modify the validation rules of imageName on S2I page
  src/components/Forms/ImageBuilder/B2IForm/index.jsx
  src/components/Forms/ImageBuilder/S2IForm/index.jsx
  src/utils/constants.js
Labels: lgtm, approved, size/S, area/devops, dco-signoff: yes

#2195 Support to login docker in GitPod automatically
  .gitpod.yml
Labels: size/XS, lgtm, approved, kind/cleanup, release-note-none

#2165 feat: The fedProject router support the sort, edit rules and edit annotation
  src/components/Base/Switch/index.scss
  src/pages/fedprojects/containers/Routes/index.jsx
Labels: lgtm, approved, size/M, kind/feature, release-note

#2239 Update banner descriptions, fix minor errors, and update UI text.
  locales/en/alerting.js
  locales/en/cluster.js
  locales/en/monitoring.js
  locales/en/storage.js
  locales/es/alerting.js
  locales/es/cluster.js
  locales/es/monitoring.js
  locales/es/storage.js
  locales/tc/alerting.js
  locales/tc/cluster.js
  locales/tc/monitoring.js
  locales/tc/storage.js
  locales/zh/alerting.js
  locales/zh/cluster.js
  locales/zh/monitoring.js
  locales/zh/storage.js
  src/components/Forms/StorageClass/StorageClassSettings/index.jsx
  src/pages/clusters/containers/Monitor/Resource/Usage/Virtual/index.jsx
  src/pages/clusters/containers/Storage/StorageClasses/Detail/index.jsx
  src/pages/clusters/containers/Storage/StorageClasses/index.jsx
Labels: size/L, lgtm, approved, kind/documentation, release-note-none

#2237 Fix: Can not get snapshot events in snapshot detail page
  src/utils/constants.js
Labels: size/XS, lgtm, approved, kind/bug, release-note-none, kind/require-ui-text-review

#2230 fix: Close jump function of clicking pod in PVC detail page of multi-cluster
  src/pages/fedprojects/containers/Volumes/Detail/VolumeMounts/PodsCard/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#2241 fix: Remove node status icon
  src/pages/clusters/containers/Monitor/Cluster/Overview/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#2238 fix: Disable the drapdown of type during editing secret
  src/actions/secret.js
  src/components/Forms/Secret/SecretSettings/index.jsx
  src/pages/projects/components/Modals/SecretEdit/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#2242 feat: Add the kubeconfig in toolbox
  locales/en/terminal.js
  locales/es/terminal.js
  locales/tc/terminal.js
  locales/zh/terminal.js
  src/components/KubeTools/index.jsx
  src/components/Modals/KubeConfig/index.jsx
Labels: lgtm, approved, size/S, kind/feature, release-note-none, kind/require-ui-text-review

#2214 feat: Add Grafana dashboard in custom monitoring
  locales/en/logging.js
  locales/es/logging.js
  locales/tc/logging.js
  locales/zh/logging.js
  src/actions/custom.monitoring.js
  src/assets/elasticsearch-das.svg
  src/assets/grafana.svg
  src/assets/json.svg
  src/assets/mysql.svg
  src/assets/redis-das.svg
  src/components/Forms/Dashboard/BaseInfo/index.jsx
  src/components/Forms/Dashboard/BaseInfo/index.scss
  src/components/Inputs/CardSelect/index.jsx
  src/components/Modals/GrafanaModal/Uploader/index.jsx
  src/components/Modals/GrafanaModal/Uploader/index.scss
  src/components/Modals/GrafanaModal/index.jsx
  src/components/Modals/GrafanaModal/index.scss
  src/pages/projects/containers/CustomMonitoring/CreateDashborad/index.jsx
  src/stores/monitoring/custom/template.json
Labels: lgtm, approved, size/XL, kind/feature, release-note

#2253 feat: support set gpu limit of container default resource
  locales/en/workload.js
  locales/zh/workload.js
  src/actions/project.js
  src/assets/GPU.svg
  src/components/Inputs/ResourceLimit/index.jsx
  src/components/Inputs/ResourceLimit/index.scss
  src/pages/projects/components/Modals/DefaultResourceEdit/index.jsx
  src/stores/limitrange.js
Labels: size/L, lgtm, approved, kind/feature, release-note

#2227 feat: Add create config or secret in env params
  locales/en/configmap.js
  locales/en/secret.js
  locales/en/workload.js
  locales/es/configmap.js
  locales/es/secret.js
  locales/es/workload.js
  locales/tc/configmap.js
  locales/tc/secret.js
  locales/tc/workload.js
  locales/zh/configmap.js
  locales/zh/secret.js
  locales/zh/workload.js
  src/actions/configmap.js
  src/actions/secret.js
  src/components/Forms/Workload/ContainerSettings/ContainerForm/Environments/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/index.jsx
  src/components/Forms/Workload/ContainerSettings/index.jsx
  src/components/Inputs/EnvironmentInput/Item.jsx
  src/components/Inputs/EnvironmentInput/index.jsx
  src/components/Inputs/EnvironmentInput/index.scss
  src/components/Inputs/EnvironmentInput/index.test.js
  src/pages/projects/containers/Services/index.jsx
Labels: size/L, lgtm, approved, kind/feature, release-note, kind/require-ui-text-review

#2254 feat: Support set gpu limit of project quota
  src/actions/project.js
  src/components/Inputs/ResourceLimit/index.jsx
  src/components/Modals/QuotaEdit/index.jsx
Labels: lgtm, approved, size/M, kind/feature, release-note-none

#2252 Refactor with PipelineRun listing and creation API
  src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
  src/stores/devops.js
  src/stores/devops/pipelines.js
Labels: lgtm, approved, size/M, area/devops, kind/api-change, release-note

#2258 feat: Support edit gpu limit for Jobs and CronJob
  src/actions/workload.js
  src/utils/index.js
Labels: lgtm, approved, size/S, kind/feature, release-note-none

#2259 feat: Support edit gpu limit of deployment template
  src/actions/federated.js
  src/actions/workload.js
  src/components/EditForms/Workload/PodTemplate/index.jsx
Labels: lgtm, approved, size/M, kind/feature, release-note-none

#2257 feat: Support set gpu limit for deployment
  src/components/Forms/Workload/ContainerSettings/index.jsx
  src/components/Inputs/ResourceLimit/index.jsx
Labels: lgtm, approved, size/M, kind/feature, release-note-none

#2260 support client authentication
  server/config.yaml
  server/controllers/session.js
  server/services/session.js
Labels: lgtm, approved, size/M, kind/api-change, release-note-none

#2245 fix: No cancel button in Gateway setting page
  src/pages/projects/components/Modals/GatewaySetting/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note

#2205 update: Update the ingress api
  locales/zh/service.js
  server/sample/bookinfo.yaml
  src/components/Forms/Route/RouteRules/RuleForm/index.jsx
  src/components/Forms/Route/RouteRules/RuleList/Item.jsx
  src/components/Inputs/RulePath/index.jsx
  src/pages/projects/components/Modals/CreateApp/Routes/RuleForm/index.jsx
  src/pages/projects/components/Modals/CreateApp/Services/index.jsx
  src/pages/projects/components/Modals/GatewaySetting/index.jsx
  src/pages/projects/containers/Routes/Detail/ResourceStatus/Rule.jsx
  src/stores/application/crd.js
  src/utils/constants.js
  src/utils/form.templates.js
Labels: approved, size/M, kind/api-change, release-note

#2130 fix: disallow user zoom out below 75% in safari browser
  src/core/index.js
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#2263 fix: Update input label width and ui text
  src/components/Inputs/ResourceLimit/index.jsx
  src/components/Inputs/ResourceLimit/index.scss
Labels: lgtm, approved, size/S, kind/bug, release-note-none, kind/require-ui-text-review

#2267 fix: Container default resource modal can't close
  src/actions/project.js
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#2268 fix: Resource limit input bug
  src/components/Inputs/ResourceLimit/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#2272 fix: Can not save container image when creating deployment
  src/components/Forms/Workload/ContainerSettings/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#2269 feat: Support notification filter key custom
  src/components/Forms/Notification/BaseForm/ConditionSelect/index.jsx
  src/components/Forms/Notification/BaseForm/ConditionSelect/index.scss
  src/components/Forms/Notification/BaseForm/index.jsx
Labels: size/L, lgtm, approved, kind/feature, do-not-merge/release-note-label-needed

#2174 fix: Unified translation
  locales/zh/pipeline.js
Labels: lgtm, approved, size/M, ok-to-test, do-not-merge/release-note-label-needed, kind/require-ui-text-review

#2283 feat: Init the single cluster name with config
  src/utils/constants.js
Labels: size/XS, lgtm, approved, kind/feature, release-note

#2251 feat: Website static link control
  server/config.yaml
  src/components/Cards/Banner/Tip.jsx
  src/components/Cards/Banner/index.jsx
  src/components/Cards/Banner/index.scss
  src/components/Forms/AlertingPolicy/AlertingRule/index.jsx
  src/components/Forms/Cluster/Configuration/index.jsx
  src/components/Forms/Cluster/Configuration/index.scss
  src/components/Forms/Cluster/EdgeNode/AddNode/index.jsx
  src/components/Forms/CronJob/BaseInfo/index.jsx
  src/components/Forms/ImageBuilder/B2IForm/index.jsx
  src/components/Forms/ImageBuilder/S2IForm/index.jsx
  src/components/Forms/Pipelines/AdvanceSettings/index.jsx
  src/components/Forms/StorageClass/ProvisionerSettings/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/index.jsx
  src/components/Layout/Header/index.jsx
  src/components/Modals/About/index.jsx
  src/components/Modals/About/index.scss
  src/components/Modals/KubeConfig/index.jsx
  src/components/Modals/KubeCtl/index.jsx
  src/pages/apps/components/AppInfo/index.jsx
  src/pages/apps/components/Cards/BaseInfo/index.jsx
  src/pages/apps/components/Cards/BaseInfo/index.scss
  src/pages/apps/components/Cards/TestSteps/index.jsx
  src/pages/apps/components/Cards/TestSteps/index.scss
  src/pages/apps/components/Modals/AppCreate/index.jsx
  src/pages/apps/components/Modals/HelmUpload/index.jsx
  src/pages/clusters/containers/Network/Policies/index.jsx
  src/pages/fedprojects/containers/Overview/Help/index.jsx
  src/pages/fedprojects/containers/Overview/Help/index.scss
  src/pages/fedprojects/containers/Volumes/Detail/ResourceStatus/index.jsx
  src/pages/projects/components/Modals/CreateApp/BaseInfo/index.jsx
  src/pages/projects/containers/Network/Policies/index.jsx
  src/pages/projects/containers/Overview/Help/index.jsx
  src/pages/projects/containers/Overview/Help/index.scss
  src/pages/projects/containers/ServiceAccounts/Detail/ServiceAccountDetail/Secret.jsx
  src/pages/projects/containers/Volumes/Detail/ResourceStatus/UsageCard/index.jsx
  src/pages/settings/components/Modals/GithubOAuth/index.jsx
  src/pages/settings/components/Modals/GithubOAuth/index.scss
  src/pages/settings/containers/BaseInfo/index.jsx
  src/pages/settings/containers/BaseInfo/index.scss
  src/scss/mixins.scss
  src/utils/index.js
Labels: size/L, lgtm, approved, kind/bug, release-note-none

#2305 fix: Change the dashboards api
  src/utils/constants.js
Labels: size/XS, lgtm, approved, kind/api-change, kind/bug, release-note-none

#2314 fix: Storageclass status Incorrect
  src/pages/clusters/containers/Storage/PV/detail/index.jsx
  src/pages/clusters/containers/Storage/StorageClasses/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none, kind/require-ui-text-review

#2311 feat: Add app repo sync period
  locales/en/app_repo.js
  locales/es/app_repo.js
  locales/tc/app_repo.js
  locales/zh/app_repo.js
  src/components/Modals/AppRepoCreate/index.jsx
  src/components/Modals/AppRepoCreate/index.scss
  src/components/Modals/AppRepoCreate/time.input.jsx
Labels: size/L, lgtm, approved, kind/feature, release-note, kind/require-ui-text-review

#2319 fix: Disallow set gpu limit for workSpace
  src/actions/federated.js
  src/actions/project.js
  src/actions/workload.js
  src/components/EditForms/Workload/PodTemplate/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/index.jsx
  src/components/Forms/Workload/ContainerSettings/index.jsx
  src/components/Inputs/ResourceLimit/index.jsx
  src/components/Modals/QuotaEdit/index.jsx
  src/pages/fedprojects/containers/Deployments/Detail/index.jsx
  src/pages/fedprojects/containers/Deployments/index.jsx
  src/pages/projects/components/Modals/DefaultResourceEdit/index.jsx
  src/pages/projects/containers/BaseInfo/index.jsx
  src/pages/projects/containers/CronJobs/index.jsx
  src/pages/projects/containers/Deployments/Detail/index.jsx
  src/pages/projects/containers/Deployments/index.jsx
  src/pages/projects/containers/Jobs/index.jsx
  src/stores/federated.js
  src/stores/limitrange.js
  src/utils/index.js
Labels: size/L, lgtm, approved, kind/bug, release-note-none

#2318 fix: Fix some notification issues
  locales/en/notification.js
  locales/es/notification.js
  locales/tc/notification.js
  locales/zh/notification.js
  package.json
  src/components/Forms/Notification/BaseForm/ConditionSelect/index.jsx
  src/components/Forms/Notification/BaseForm/index.jsx
  src/components/Forms/Notification/MailForm/index.jsx
  src/components/Forms/Notification/WebhookForm/index.jsx
  src/pages/settings/containers/Notification/DingTalk/index.jsx
  src/pages/settings/containers/Notification/Mail/index.jsx
  src/pages/settings/containers/Notification/Slack/index.jsx
  src/pages/settings/containers/Notification/WeCom/index.jsx
  src/pages/settings/containers/Notification/Webhook/index.jsx
  yarn.lock
Labels: size/L, lgtm, approved, kind/bug, do-not-merge/release-note-label-needed

#2290 fix: ResourceLimit component input style problem and can't create deployment
  locales/zh/workload.js
  src/components/Inputs/ResourceLimit/index.jsx
  src/components/Inputs/ResourceLimit/index.scss
Labels: lgtm, approved, size/M, kind/bug, release-note-none, kind/require-ui-text-review

#2329 fix: Check the backend if support pv manag
  src/pages/clusters/containers/Storage/PV/index.jsx
  src/pages/clusters/containers/Storage/Volumes/Volume/index.jsx
  src/pages/clusters/containers/Storage/Volumes/index.jsx
  src/stores/base.js
  src/utils/object.mapper.js
Labels: lgtm, approved, size/M, kind/bug, release-note-none, kind/require-ui-text-review

#2330 fix: Bound pv can't delete
  src/components/HOCs/withTableActions.js
  src/pages/clusters/containers/Storage/PV/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#2331 fix: Storage type didn't display
  src/components/Forms/Workload/VolumeSettings/AddExistVolumes/index.jsx
  src/pages/clusters/containers/Workload/Deployments/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#2289 feat: add app agreement confirm popup
  locales/en/app_store.js
  locales/en/base.js
  locales/es/app_store.js
  locales/es/base.js
  locales/tc/app_store.js
  locales/tc/base.js
  locales/zh/app_store.js
  locales/zh/base.js
  src/actions/openpitrix.js
  src/assets/app-safety.svg
  src/components/Cards/App/index.jsx
  src/components/Cards/App/index.scss
  src/pages/apps/components/AppBase/index.jsx
  src/pages/apps/components/AppInfo/index.jsx
  src/pages/apps/components/AppInfo/index.scss
  src/pages/apps/components/Modals/AppAgreement/index.jsx
  src/pages/apps/components/Modals/AppAgreement/index.scss
  src/pages/apps/containers/AppDetail/index.jsx
Labels: lgtm, approved, size/XL, kind/feature, release-note

#2342 Avoid gh repo fork prompt
  .gitpod.yml
Labels: size/XS, lgtm, approved, kind/cleanup, release-note-none

#2340 fix: Fix the default time range is displayed incorrectly on the overview page
  src/pages/fedprojects/containers/Overview/ResourceUsage/index.jsx
  src/pages/projects/containers/Overview/ResourceUsage/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note

#2341 fix: Requets is equal to limits and allow user to cancel gpu limits
  src/actions/project.js
  src/components/Inputs/ResourceLimit/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#2336 fix: Update storageClass Capability logic
  src/actions/storageclass.js
  src/components/HOCs/withTableActions.js
  src/components/Modals/VolumeFunctionManage/index.jsx
  src/pages/clusters/containers/Storage/PV/index.jsx
  src/pages/clusters/containers/Storage/Volumes/index.jsx
  src/stores/base.js
Labels: size/L, lgtm, approved, kind/bug, release-note-none

#2347 remove service port name
  docs/access-backend.md
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#2354 fix: Pvc info not display
  locales/en/storage.js
  src/pages/clusters/containers/Storage/Volumes/Volume/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none, kind/require-ui-text-review

#2359 fix: Pv delete button status incrrect
  src/pages/clusters/containers/Storage/PV/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#2352 docs: Change the resource status to RESOURCE_STATUS
  src/components/Base/Breadcrumb/index.test.js
  src/pages/clusters/containers/CustomResources/Detail/routes.js
  src/pages/clusters/containers/Gateway/Detail/routes.js
  src/pages/clusters/containers/LogCollections/Detail/routes.js
  src/pages/clusters/containers/Storage/PV/detail/routes.js
  src/pages/fedprojects/containers/Deployments/Detail/routes.js
  src/pages/fedprojects/containers/Routes/Detail/routes.js
  src/pages/fedprojects/containers/Services/Detail/routes.js
  src/pages/fedprojects/containers/StatefulSets/Detail/routes.js
  src/pages/fedprojects/containers/Volumes/Detail/routes.js
  src/pages/projects/containers/Applications/OPAppDetail/routes.js
  src/pages/projects/containers/DaemonSets/Detail/routes.js
  src/pages/projects/containers/ImageBuilder/Detail/routes.js
  src/pages/projects/containers/Jobs/Detail/routes.js
  src/pages/projects/containers/Pods/Containers/routes.js
  src/pages/projects/containers/Pods/Detail/routes.js
  src/pages/projects/containers/Routes/Detail/routes.js
  src/pages/projects/containers/Services/Detail/routes.js
  src/pages/projects/containers/StatefulSets/Detail/routes.js
  src/pages/projects/containers/Volumes/Detail/routes.js
Labels: lgtm, approved, size/M, release-note-none

#2323 fix: Change the pipeline api from v2 to v3
  src/components/Forms/Pipelines/AdvanceSettings/index.jsx
  src/pages/devops/components/DetailNav/index.jsx
  src/pages/devops/components/Pipeline/store.js
  src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Branch/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Layout/runs.jsx
  src/pages/devops/containers/Pipelines/Detail/PipelineLogDialog/index.jsx
  src/pages/devops/containers/Pipelines/Detail/PipelineLogDialog/logItem.jsx
  src/pages/devops/containers/Pipelines/Detail/PullRequest/index.jsx
  src/pages/devops/containers/Pipelines/Detail/TaskStatus/index.jsx
  src/pages/devops/containers/Pipelines/Detail/routes.js
  src/stores/devops.js
  src/stores/devops/base.js
  src/stores/devops/codeQuality.js
  src/stores/devops/credential.js
  src/stores/devops/log.js
  src/stores/devops/pipelines.js
  src/stores/devops/run.js
  src/stores/devops/scm.js
  src/stores/monitoring/workspace.js
Labels: lgtm, approved, size/XL, area/devops, kind/api-change, kind/bug, release-note

#2363 fix: The data is empty when create a app with template
  src/pages/apps/components/AppBase/index.jsx
  src/pages/apps/components/Modals/AppCreate/index.jsx
  src/pages/apps/components/Modals/HelmUpload/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#2348 fix: Change pvc access modes to list
  src/components/Forms/Volume/VolumeSettings/FormTemplate.jsx
  src/pages/clusters/containers/Storage/Volumes/Volume/index.jsx
  src/pages/projects/containers/Volumes/index.jsx
Labels: lgtm, approved, size/M, kind/bug, ok-to-test, release-note

#2366 fix: The old gateway can not view
  src/actions/gateways.js
  src/pages/clusters/containers/Gateway/Components/GatewayCard/index.jsx
  src/pages/clusters/containers/Projects/Detail/Gateway/index.jsx
  src/pages/fedprojects/containers/Gateway/Access/index.jsx
  src/pages/projects/components/Modals/GatewaySetting/index.jsx
  src/pages/projects/containers/Gateway/index.jsx
  src/stores/gateway.js
Labels: lgtm, approved, size/M, release-note-none

#2368 fix: Change the secret verify api
  src/components/Forms/Secret/SecretSettings/ImagerRegistry/index.jsx
  src/components/Forms/Secret/SecretSettings/index.jsx
  src/stores/secret.js
Labels: lgtm, approved, size/S, kind/api-change, kind/bug, release-note

#2369 fix: Change the image config api
  locales/en/workload.js
  locales/es/workload.js
  locales/tc/workload.js
  locales/zh/workload.js
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/index.jsx
  src/stores/container.js
  src/utils/object.mapper.js
Labels: lgtm, approved, size/M, kind/api-change, release-note
