Repository kubesphere/console, pull requests merged in 2021-06, with the labels that each got.

#1848 feat: delete related resources when deleting workspace
  locales/en/workspace.js
  locales/es/workspace.js
  locales/tc/workspace.js
  locales/zh/workspace.js
  src/actions/workspace.js
  src/pages/access/containers/Workspaces/index.jsx
  src/pages/workspaces/components/Modals/WorkspaceDelete/index.jsx
  src/pages/workspaces/components/Modals/WorkspaceDelete/index.scss
  src/pages/workspaces/containers/BaseInfo/index.jsx
  src/stores/workspace.js
Labels: approved, dco-signoff: yes, lgtm, size/L

#1921 fix: Modify system workspace rules control to show a web terminal on container of system-workspace
  server/config.yaml
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1927 fix: Fix the node label list of member cluster
  src/pages/devops/components/Pipeline/store.js
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/XS

#1931 chore: Remove the description of drag in the pipeline
  src/pages/devops/components/Pipeline/StepsEditor/index.jsx
Labels: approved, area/devops, dco-signoff: yes, lgtm, size/XS

#1932 fix: Fix the pipeline detail page could not use the browser go back button
  src/pages/devops/containers/Pipelines/PipelinesList/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1936 fix: Fix the page of member in workspace is not displayed correctly after refreshing
  src/pages/workspaces/containers/Members/Detail/DevOps/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1941 fix: Fix command input box validation failed
  src/components/Inputs/StringInput/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1944 fix: Modify the style of Select
  src/components/Inputs/AddonsInput/index.scss
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1945 fix: Fix workspace settings name duplicate when creating custom workspace roles
  locales/en/role.js
  locales/es/role.js
  locales/tc/role.js
  locales/zh/role.js
Labels: approved, dco-signoff: yes, lgtm, size/S

#1947 fix: Modify the validation rules for the input box on the alerting policy page
  locales/en/alerting.js
  locales/es/alerting.js
  locales/tc/alerting.js
  locales/zh/alerting.js
  src/components/Forms/AlertingPolicy/BaseInfo/index.jsx
  src/configs/alerting/metrics/rule.config.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1948 fix: Fix the sh and lable is not correct in pipeline editor
  src/pages/devops/components/Pipeline/Card/detail.jsx
  src/pages/devops/components/Pipeline/StepModals/script.jsx
  src/pages/devops/components/Pipeline/StepModals/shell.jsx
  src/pages/devops/components/Pipeline/StepsEditor/StepContainer.jsx
  src/pages/devops/components/Pipeline/StepsEditor/index.jsx
  src/pages/devops/components/Pipeline/store.js
Labels: approved, area/devops, dco-signoff: yes, lgtm, size/M

#1965 feat: Determine whether to log out according to the 401 and error messages on the member cluster page
  src/core/index.js
  src/utils/index.js
  src/utils/request.js
Labels: approved, dco-signoff: yes, lgtm, size/S

#1961 fix: Fix failed to assign an administrator to a project
  src/actions/project.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1918 feat: Add edit service in the detail of service in the federated project
  src/actions/federated.js
  src/actions/router.js
  src/actions/service.js
  src/actions/volume.js
  src/components/EditForms/Workload/PodTemplate/index.jsx
  src/components/EditForms/Workload/UpdateStrategy/index.jsx
  src/components/Forms/Route/RouteRules/RuleForm/ClusterSelect/index.jsx
  src/components/Forms/Volume/ClusterDiffSettings/EditForm/index.jsx
  src/components/Forms/Volume/ClusterDiffSettings/VolumeSettings/index.jsx
  src/components/Forms/Volume/ClusterDiffSettings/index.jsx
  src/components/Forms/Volume/VolumeSettings/FormTemplate.jsx
  src/components/Forms/Volume/VolumeSettings/index.jsx
  src/components/Forms/Workload/ClusterDiffSettings/ClustersMapper/index.jsx
  src/components/Forms/Workload/ClusterDiffSettings/ContainerPortsWithService/index.jsx
  src/components/Forms/Workload/ClusterDiffSettings/ContainerPortsWithService/index.scss
  src/components/Forms/Workload/ClusterDiffSettings/ContainersMapper/index.jsx
  src/components/Forms/Workload/ClusterDiffSettings/ContainersMapperWithService/index.jsx
  src/components/Forms/Workload/ClusterDiffSettings/ContainersMapperWithService/index.scss
  src/components/Forms/Workload/ClusterDiffSettings/EditForm/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
  src/components/Forms/Workload/ContainerSettings/UpdateStrategy/index.jsx
  src/components/Forms/Workload/ContainerSettings/index.jsx
  src/components/Inputs/ResourceLimit/index.jsx
  src/components/Modals/Edit/Form/index.jsx
  src/components/Modals/Edit/Form/wrapper.jsx
  src/components/Modals/Edit/index.jsx
  src/pages/fedprojects/components/CheckboxGroup/index.jsx
  src/pages/fedprojects/components/ClusterDiffSettings/index.jsx
  src/pages/fedprojects/components/ConfigTemplate/config.js
  src/pages/fedprojects/components/ConfigTemplate/index.jsx
  src/pages/fedprojects/components/ConfigTemplate/index.scss
  src/pages/fedprojects/components/ContainerImage/index.jsx
  src/pages/fedprojects/components/ContainerSetting/index.jsx
  src/pages/fedprojects/components/ContainerSetting/index.scss
  src/pages/fedprojects/components/RouteRulesEdit/index.jsx
  src/pages/fedprojects/components/RouteRulesEdit/index.scss
  src/pages/fedprojects/components/ServiceSetting/Form.jsx
  src/pages/fedprojects/components/ServiceSetting/ServiceSettingsForm/index.jsx
  src/pages/fedprojects/components/ServiceSetting/ServiceSettingsForm/index.scss
  src/pages/fedprojects/components/ServiceSetting/index.jsx
  src/pages/fedprojects/components/ServiceSetting/index.scss
  src/pages/fedprojects/components/VolumeSetting/VolumeSettingForm.jsx
  src/pages/fedprojects/components/VolumeSetting/config.js
  src/pages/fedprojects/components/VolumeSetting/index.jsx
  src/pages/fedprojects/components/VolumeSetting/index.scss
  src/pages/fedprojects/containers/Deployments/Detail/index.jsx
  src/pages/fedprojects/containers/Routes/Detail/index.jsx
  src/pages/fedprojects/containers/Services/Detail/ServiceAccess/ClusterService/index.jsx
  src/pages/fedprojects/containers/Services/Detail/index.jsx
  src/pages/fedprojects/containers/StatefulSets/Detail/index.jsx
  src/pages/fedprojects/containers/Volumes/Detail/index.jsx
  src/pages/projects/components/Modals/RouteRulesEdit/index.jsx
  src/utils/constants.js
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XXL

#2002 fix: Fix unable connect to container terminal due to forbidden error
  src/components/Modals/ContianerTerminal/index.jsx
  src/components/Modals/KubeCtl/index.jsx
  src/stores/terminal.js
Labels: approved, dco-signoff: yes, lgtm, size/L

#2005 [release-3.1] fix: Deleted workspace roles can not be used in Department Management
  locales/en/role.js
  locales/es/role.js
  locales/tc/role.js
  locales/zh/role.js
  src/actions/configmap.js
  src/components/Modals/EditBasicInfo/index.jsx
  src/components/Modals/EditYaml/index.jsx
  src/components/Modals/RoleDelete/index.jsx
  src/pages/projects/components/Modals/ConfigMapEdit/index.jsx
  src/pages/projects/components/Modals/ServiceSetting/index.jsx
  src/stores/group.js
Labels: approved, dco-signoff: yes, lgtm, size/L

#2013 fix: Fix workspace quota api path error
  src/pages/workspaces/components/Modals/QuotaEdit/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#2017 Force pull base image
  .github/workflows/main.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2016 fix: Cancel closing modal due to clicking mask
  src/components/Base/Modal/modal.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#2018 fix: Hide the password value in env
  src/components/Cards/Containers/EnvVariables/index.jsx
  src/pages/projects/containers/Secrets/Detail/SecretDetail/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/M

#2012 fix: Modify the desc of app on locales file.
  locales/en/app.js
  locales/es/app.js
  locales/tc/app.js
  locales/zh/app.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#2011 fix: Modify the link of AppCreate modal
  src/pages/apps/components/Modals/AppCreate/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2009 fix: Fix the problem of redirection when logging out caused by apps in the route
  server/libs/utils.js
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2004 feat: Add scan repo trigger in GitLab
  locales/en/pipeline.js
  locales/es/pipeline.js
  locales/tc/pipeline.js
  locales/zh/pipeline.js
  src/components/Forms/Pipelines/AdvanceSettings/index.jsx
  src/components/Modals/Pipelines/ScanRepositoryLogs/index.jsx
  src/pages/devops/components/Pipeline/StepModals/environment.jsx
  src/pages/devops/containers/Pipelines/Detail/Layout/pipeline.jsx
  src/utils/constants.js
Labels: approved, area/devops, dco-signoff: yes, lgtm, size/M

#2003 fix: Remove the previous parameter of log
  src/components/Cards/ContainerLog/index.jsx
  src/components/Modals/ContainerLog/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/S

#2008 fix: Add placeholder for 'Select resource'
  src/components/Inputs/EnvironmentInput/Item.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1968 fix: Fix misleading volumes quota
  locales/en/project.js
  locales/es/project.js
  locales/tc/project.js
  locales/zh/project.js
  src/actions/project.js
  src/components/Modals/QuotaEdit/Quotas/Item.jsx
Labels: approved, dco-signoff: yes, lgtm, size/S

#2020 fix: Add fuchunlan to the list of reviewers
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2023 fix: Add cancel button in create service modal
  src/pages/projects/components/Modals/ServiceCreate/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1934 fix: Change the color of the button on the Metering and Billing page.
  src/components/Modals/Bill/Home/index.scss
  src/components/Modals/Bill/components/Crumb/index.scss
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XS

#2024 yarn.lock file isn't required by runtime
  .dockerignore
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/XS

#1933 fix: Add 'select all' option when deleting related resource of a specified workload
  src/pages/projects/components/Modals/WorkloadDelete/index.jsx
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/S

#1940 fix: Set the first app template to default.
  src/components/Forms/Dashboard/BaseInfo/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1939 fix: Fix routing page prompts error in multi-cluster project
  src/components/Forms/Route/RouteRules/RuleForm/index.jsx
  src/pages/projects/components/Modals/CreateApp/Routes/RuleForm/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/M

#2001 feat: Able to create resource quota for extended resources
  src/components/Modals/QuotaEdit/Quotas/Item.jsx
  src/components/Modals/QuotaEdit/Quotas/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/L

#2030 --export is deprecated on kubectl:v1.19.8, use kubectl neat instead
  .github/workflows/deploy-pr.yml
Labels: dco-signoff: yes, kind/cleanup, size/XS

#2028 fix: Service monitor is not associated when service is viewed and deleted
  src/actions/service.js
  src/pages/projects/components/Cards/ServiceMonitors/index.jsx
  src/pages/projects/containers/Services/Detail/ResourceStatus/index.jsx
  src/pages/projects/containers/Services/Detail/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/S

#1969 fix: Fix receiver mail sync error
  src/pages/settings/containers/Notification/Mail/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1971 fix: Show action button on alertPolicyDetail.
  src/pages/clusters/containers/Base/Detail/index.jsx
  src/scss/custom.scss
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#2032 chore: Add fuchunlan reviewers
  OWNERS
Labels: approved, dco-signoff: no, lgtm, size/XS

#2033 update: Update the kube-design version
  package.json
  yarn.lock
Labels: approved, dco-signoff: yes, lgtm, size/M

#2036 Fix the incorrect tag of CI auto-push image
  .github/workflows/main.yaml
Labels: approved, dco-signoff: yes, kind/optimization, size/XS

#2041 fix: Add the cancel button in app create modal
  src/pages/apps/components/Modals/AppCreate/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2042 fix: Change the guide link in AppCreate and HelmUpload
  src/pages/apps/components/Modals/AppCreate/index.jsx
  src/pages/apps/components/Modals/HelmUpload/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#2022 fix: Change the method of time select in trace
  src/components/Cards/Monitoring/Controller/TimeSelector/index.jsx
  src/pages/fedprojects/containers/Applications/Detail/AppComponents/Components/ServiceCard/index.jsx
  src/pages/fedprojects/containers/Applications/Detail/Tracing/index.jsx
  src/pages/fedprojects/containers/Applications/Detail/Tracing/index.scss
  src/pages/projects/containers/Applications/CRDAppDetail/Tracing/index.jsx
  src/pages/projects/containers/Applications/CRDAppDetail/Tracing/index.scss
  src/pages/projects/containers/Services/Detail/index.jsx
  src/stores/application/crd.js
Labels: approved, dco-signoff: yes, lgtm, size/L

#1967 fix: Modify the red prompt box on Maintain Organization Modal.
  src/components/Inputs/ArrayInput/index.jsx
  src/pages/workspaces/components/Modals/EditGroup/Detail/Form/DevopsSelect.jsx
  src/pages/workspaces/components/Modals/EditGroup/Detail/Form/ProjectSelect.jsx
  src/pages/workspaces/components/Modals/EditGroup/Detail/Form/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#2049 fix: Add fuchunlan reviewer
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2054 fix: Fix Bill page view error caused by the dependence of workspace on unloaded clusters
  src/components/Modals/Bill/Details/Cluster/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2059 fix: Multi-cluster projects appear in the project list of a cluster
  src/components/Modals/ProjectSelect/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2066 fix: Add fedproject in bill
  src/utils/meter.js
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2064 fix:remove edit extranet access button in stateful service detail page
  src/pages/projects/containers/Services/Detail/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2062 fix: Fix the permission of workspace quota
  server/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#2063 fix: Add close button in create app template modal
  src/pages/projects/components/Modals/DeployApp/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/XS
