Repository kubesphere/console, pull requests merged in 2021-12, with the labels that each got.

#2695 fix: Fix the error of failure to get gateway without cluster permission in the project
  src/components/Forms/Route/RouteRules/index.jsx
  src/pages/clusters/containers/Gateway/Components/GatewayCard/index.jsx
  src/pages/clusters/containers/Projects/Detail/Gateway/index.jsx
  src/pages/fedprojects/containers/Applications/Detail/AppIngresses/Ingresses/index.jsx
  src/pages/fedprojects/containers/Gateway/Access/index.jsx
  src/pages/fedprojects/containers/Routes/Detail/ResourceStatus/Item/index.jsx
  src/pages/fedprojects/containers/Services/Detail/ServiceAccess/ClusterService/index.jsx
  src/pages/projects/components/Modals/CreateApp/index.jsx
  src/pages/projects/containers/Gateway/index.jsx
  src/pages/projects/containers/Routes/Detail/ResourceStatus/index.jsx
  src/pages/projects/containers/Routes/index.jsx
  src/stores/gateway.js
Labels: size/L, lgtm, approved, kind/bug, release-note

#2676 fix: Remove the invalid parameter template in the service edit mode
  src/utils/index.js
Labels: size/XS, lgtm, approved, kind/bug, ok-to-test, release-note-none

#2710 fix: Update gateway delete tip text
  locales/en/l10n-clusterManagement-projects-list.js
  locales/zh/base.js
  src/actions/gateways.js
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#2705 fix: Certificate verification problem
  src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#2702 fix: User can't open container terminal
  src/utils/index.js
Labels: size/XS, lgtm, approved, kind/bug, release-note

#2703 fix: Jenkins edit modal scroll
  src/pages/devops/components/Modals/JenkinsEdit/index.scss
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#2715 fix: Cluster resource usage time controller is covered up
  src/components/Base/Card/index.scss
Labels: size/XS, lgtm, approved, kind/bug, release-note

#2727 docs: Merge from release-3.2 to resolve differences.
  locales/en/base.js
  locales/en/logging.js
  locales/en/login.js
  locales/en/monitoring.js
  locales/en/pipeline.js
  locales/en/project.js
  locales/en/role.js
  locales/en/secret.js
  locales/en/user.js
  locales/en/version.js
  locales/en/workload.js
Labels: lgtm, approved, size/M, kind/documentation, release-note-none

#2728 docs: Update locale package.
  locales/en/cluster.js
  locales/en/dashboard.js
  locales/en/devops.js
  locales/en/gateway.js
  locales/en/ingress.js
  locales/en/ippool.js
  locales/en/l10n-accessControl-users-list.js
  locales/en/l10n-clusterManagement-applicationWorkloads-daemonsets-list.js
  locales/en/l10n-clusterManagement-applicationWorkloads-deployments-list.js
  locales/en/l10n-clusterManagement-applicationWorkloads-routes-list.js
  locales/en/l10n-clusterManagement-applicationWorkloads-statefulsets-list.js
  locales/en/l10n-clusterManagement-clusterSettings-basicInformation.js
  locales/en/l10n-clusterManagement-clusterSettings-gatewaySettings-details.js
  locales/en/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
  locales/en/l10n-clusterManagement-clusters.js
  locales/en/l10n-clusterManagement-crds-details.js
  locales/en/l10n-clusterManagement-monitoring&Alerting-customMonitoring.js
  locales/en/l10n-clusterManagement-network-networkPolicies-list.js
  locales/en/l10n-clusterManagement-network-podIpPools-details.js
  locales/en/l10n-clusterManagement-network-podIpPools-list.js
  locales/en/l10n-clusterManagement-projects-list.js
  locales/en/l10n-devopsProjects-devopsProjectSettings-basinInformation.js
  locales/en/l10n-devopsProjects-devopsProjectSettings-credentials-details.js
  locales/en/l10n-devopsProjects-devopsProjectSettings-credentials-list.js
  locales/en/l10n-devopsProjects-devopsProjectSettings-devopsProjectMembers.js
  locales/en/l10n-devopsProjects-devopsProjectSettings-devopsProjectRoles-list.js
  locales/en/l10n-devopsProjects-pipeline-details.js
  locales/en/l10n-devopsProjects-pipeline-list.js
  locales/en/l10n-multiclusterProjects-list.js
  locales/en/l10n-projects-overview.js
  locales/en/l10n-projects-projectSettings-gatewaySettings-list.js
  locales/en/l10n-projects-projectSettings-networkIsolation.js
  locales/en/l10n-workbench.js
  locales/en/l10n-workspaces-appManagement-appRepositories-list.js
  locales/en/l10n-workspaces-devopsProjects-list.js
  locales/en/monitoring.js
  locales/en/network.js
  locales/en/pipeline.js
  locales/en/project.js
  src/pages/clusters/containers/BaseInfo/index.jsx
Labels: size/L, lgtm, approved, kind/documentation, release-note-none

#2722 fix: Resource Monitor Modal selected time range does not work
  src/components/Modals/Monitoring/ApplicationResource/index.jsx
  src/components/Modals/Monitoring/Controller/index.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note

#2730 fix: Failed to create a statefulSet with a volume template added
  src/components/Forms/Workload/VolumeSettings/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note

#2735 fix: Application deployment fails if we click too fast
  src/pages/apps/containers/AppDeploy/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#2734 feat: Add an s2i tip for not supporting containerd runtime
  locales/en/s2i.js
  locales/zh/s2i.js
  server/controllers/view.js
  server/services/session.js
  src/components/Forms/ImageBuilder/LanguageSelect/index.jsx
  src/components/Forms/ImageBuilder/LanguageSelect/index.scss
Labels: lgtm, approved, size/M, area/devops, kind/feature, release-note, kind/require-ui-text-review

#2669 Add i18n items for the PipelineRun role
  locales/en/role.js
  locales/zh/role.js
Labels: lgtm, approved, size/S, area/devops, release-note-none

#2750 fix devops pipelienrun role
  locales/en/role.js
  locales/zh/role.js
Labels: lgtm, approved, size/S, area/devops, release-note-none

#2751 fix : modify volume access mode 'ROM' to 'ROX'.
  src/utils/index.js
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#2753 fix: Fix the branch name not encode.
  src/components/Forms/Route/RouteRules/RuleForm/index.jsx
  src/stores/devops/pipelines.js
Labels: size/XS, lgtm, approved, area/devops, kind/bug, do-not-merge/release-note-label-needed

#2758 fix: Update gateway setting conflect
  locales/en/l10n-projects-projectSettings-gatewaySettings-list.js
  src/actions/gateways.js
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#2759 fix: Gateway time range switch problem
  src/pages/clusters/containers/Gateway/Components/TimeSelector/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#2766 docs: Add localization guide.
  README.md
  docs/images/crowdin-comment.png
  docs/images/crowdin-file-name.png
  docs/images/crowdin-select-langauge.png
  docs/images/crowdin-ui-string.png
  docs/join-the-kubesphere-localization-project.md
Labels: lgtm, approved, size/M, kind/documentation, release-note-none

#2764 add build support for multiple platforms
  .dockerignore
  .github/workflows/main.yaml
  .github/workflows/nightly-builds.yml
  .gitignore
  Dockerfile
  Dockerfile.arm64
  Dockerfile.multistage
  Makefile
  README.md
  build/Dockerfile
  docker-compose.builder.yaml
  docker-compose.yaml
  docker-run
  docs/images/dashboard-ui.png
  hack/docker_build.sh
  hack/docker_build_multiarch.sh
Labels: size/L, lgtm, approved, kind/cleanup, kind/feature, tide/merge-method-squash, release-note-none

#2765 fix: Gpu limit validation error
  src/components/Inputs/ResourceLimit/index.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#2773 fix: Update gateway Replicas error
  src/pages/clusters/containers/Gateway/Detail/ResourceStatus/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#2775 fix: Terminal log 403 error if user not login
  server/services/session.js
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#2783 fix: App categories name is 'all'
  src/pages/apps/containers/Home/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#2784 fix: Fix the wrong url of the harbor image
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/DropdownContent.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/Select/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/Select/index.scss
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/index.scss
Labels: lgtm, approved, size/M, kind/bug, release-note

#2778 fix: highlight the matched keywords in the query result of gateway logs
  src/pages/clusters/containers/Gateway/Detail/GatewayLog/index.jsx
  src/pages/clusters/containers/Gateway/Detail/GatewayLog/index.scss
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#2781 docs: Update localization guide.
  docs/images/crowdin-html-and-variables.png
  docs/join-the-kubesphere-localization-project.md
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#2769 fix: Delete update button on gateway page if the gateway doesn't need to update
  src/pages/clusters/containers/Gateway/Components/GatewayCard/index.jsx
  src/pages/clusters/containers/Gateway/Detail/index.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#2788 docs: Update EN Locales
  locales/en/l10n-clusterManagement-clusterSettings-logReceivers-details.js
  locales/en/l10n-devopsProjects-devopsProjectSettings-devopsProjectRoles-list.js
  locales/en/l10n-devopsProjects-pipeline-details.js
  locales/en/l10n-projects-applicationWorkloads-services-list.js
  locales/en/l10n-projects-overview.js
  locales/en/role.js
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#2794 fix: Document link error
  src/components/Layout/Header/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#2795 fix: Fix the url is http need annotations in docker repo secret
  src/components/Forms/Secret/SecretSettings/ImagerRegistry/index.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note

#2782 feat: Add more support for language configuration
  server/config.yaml
  src/components/Modals/UserSetting/BaseInfo/index.jsx
Labels: lgtm, approved, size/S, kind/feature, release-note

#2804 fix: Hide the operation button that is no run id in pipeline
  src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
Labels: size/XS, lgtm, approved, area/devops, kind/bug, release-note-none

#2802 fix: Fix the null of gateway data in access page of composing app
  src/pages/clusters/containers/Gateway/Components/GatewayCard/index.jsx
  src/pages/clusters/containers/Gateway/Detail/AnnotationsCard/index.jsx
  src/pages/clusters/containers/Gateway/Detail/GatewayConfig/index.jsx
  src/pages/clusters/containers/Gateway/Detail/ResourceStatus/index.jsx
  src/pages/fedprojects/containers/Applications/Detail/AppIngresses/Ingresses/index.jsx
  src/pages/fedprojects/containers/Routes/Detail/ResourceStatus/Item/index.jsx
Labels: lgtm, approved, size/S, kind/bug, do-not-merge/release-note-label-needed

#2807 fix: Fix the link of gateway pod container
  src/pages/clusters/containers/Gateway/Components/Pods/Item.jsx
  src/pages/clusters/containers/Gateway/Components/Pods/index.jsx
  src/pages/clusters/containers/Gateway/Detail/ResourceStatus/index.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#2813 Fix CVE-2021-28831
  build/Dockerfile
Labels: size/XS, lgtm, kind/flake, release-note-none

#2814 fix: After editing the pipeline configuration, the pipeline disappears
  src/pages/devops/containers/Pipelines/Detail/Layout/pipeline.jsx
Labels: lgtm, approved, size/S, area/devops, kind/bug, release-note-none

#2815 docs: Add preview environment address to l10n guide.
  docs/join-the-kubesphere-localization-project.md
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#2809 fix: Incorrect information for exceeding the resource limit
  locales/en/l10n-projects-applicationWorkloads-deployments-list.js
  src/components/Forms/Workload/ContainerSettings/ContainerList/QuotaCheck.jsx
  src/utils/workload.js
Labels: lgtm, approved, size/M, kind/bug, release-note-none, kind/require-ui-text-review

#2823 docs: Update locale package.
  locales/ar/role.js
  locales/ar/workload.js
  locales/en/l10n-projects-applicationWorkloads-apps-composedApps-list.js
  locales/en/role.js
  locales/en/workload.js
  locales/es/role.js
  locales/es/workload.js
  locales/fr/role.js
  locales/fr/workload.js
  locales/hi/role.js
  locales/hi/workload.js
  locales/lt/role.js
  locales/lt/workload.js
  locales/pl/role.js
  locales/pl/workload.js
  locales/tc/role.js
  locales/tc/workload.js
  locales/tr/role.js
  locales/tr/workload.js
  locales/zh/role.js
  locales/zh/workload.js
Labels: lgtm, approved, size/XXL, kind/documentation, release-note-none

#2824 docs: Update l10n guide.
  docs/join-the-kubesphere-localization-project.md
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#2825 fix failing docker build
  build/Dockerfile
Labels: size/XS, lgtm, approved, kind/bug, kind/failing-test, release-note-none

#2828 docs: Update language options.
  server/config.yaml
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#2831 docs: Fix minor issue in localization guide.
  docs/join-the-kubesphere-localization-project.md
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#2832 fix: Notification condition filter custom tag value validation rules.
  locales/en/l10n-platformSettings-notificationManagement-notificationConfiguration.js
  locales/zh/l10n-platformSettings-notificationManagement-notificationConfiguration.js
  src/components/Inputs/TagInput/autosuggest.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note-none, kind/require-ui-text-review

#2841 docs: Update l10n guide.
  docs/join-the-kubesphere-localization-project.md
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#2844 docs: Sync zh locale files from master.
  locales/zh/l10n-clusterManagement-clusterSettings-logReceivers-details.js
  locales/zh/l10n-clusterManagement-monitoring&Alerting-clusterStatus.js
  locales/zh/l10n-devopsProjects-devopsProjectSettings-credentials-details.js
  locales/zh/l10n-devopsProjects-devopsProjectSettings-devopsProjectRoles-list.js
  locales/zh/l10n-devopsProjects-pipeline-details.js
  locales/zh/l10n-devopsProjects-pipeline-list.js
  locales/zh/l10n-projects-applicationWorkloads-services-list.js
  locales/zh/l10n-projects-overview.js
  locales/zh/l10n-projects-projectSettings-basicInformation.js
  locales/zh/l10n-projects-projectSettings-gatewaySettings-list.js
  locales/zh/l10n-projects-projectSettings-projectRoles-list.js
  locales/zh/l10n-toobox-auditLogSearch-details.js
  locales/zh/l10n-toobox-resourceConsumptionStatistics-clusterResourceConsumption.js
Labels: size/L, lgtm, approved, kind/documentation, release-note-none

#2845 fix: The data is empty when modifying the stateful service during creating apps
  src/pages/projects/components/Modals/CreateAppService/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note

#2846 fix: Update container resource occupation validation strategy
  src/components/Forms/Workload/ContainerSettings/ContainerList/QuotaCheck.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note

#2847 fix: Gateway configuration options input error
  src/components/Inputs/PropertiesInput/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note

#2843 fix: Add environment variables validation and tips
  locales/en/l10n-projects-applicationWorkloads-deployments-list.js
  src/components/Inputs/ArrayInput/Item.jsx
  src/components/Inputs/ArrayInput/index.scss
  src/components/Inputs/EnvironmentInput/Item.jsx
  src/components/Inputs/EnvironmentInput/index.scss
  src/utils/constants.js
Labels: size/L, lgtm, approved, kind/bug, release-note

#2857 fix: Deleted pv still in the table list
  src/pages/clusters/containers/Storage/PV/detail/ResourceStatus/index.jsx
  src/pages/clusters/containers/Storage/PV/index.jsx
  src/pages/clusters/containers/Storage/Volumes/Volume/index.jsx
  src/pages/fedprojects/containers/Volumes/index.jsx
  src/pages/projects/containers/Volumes/index.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note

#2864 fix: Update Secrets failed for multi cluster project
  src/actions/secret.js
  src/stores/federated.js
Labels: lgtm, approved, size/S, kind/bug, release-note

#2869 fix: Update configMap failed for multi-cluster project
  src/actions/configmap.js
Labels: size/XS, lgtm, approved, kind/bug, release-note

#2868 fix: Update application routes failed for multi-cluster project
  src/actions/router.js
Labels: lgtm, approved, size/S, kind/bug, release-note

#2865 fix: Can't search table data by name
  src/stores/base.js
  src/stores/service.js
Labels: lgtm, approved, size/M, kind/bug, release-note

#2867 fix: Can't validate Image registry information after updating host cluster name in multi-cluster project
  src/components/Forms/Secret/SecretSettings/ImagerRegistry/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note

#2863 fix: Gpu tip info error and gpu limit number error
  server/config.yaml
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
  src/components/Forms/Workload/ContainerSettings/index.jsx
  src/components/Inputs/ResourceLimit/index.jsx
  src/components/Modals/QuotaEdit/Quotas/index.jsx
  src/components/Modals/QuotaEdit/index.jsx
  src/pages/fedprojects/components/ContainerSetting/index.jsx
  src/pages/projects/components/Modals/DefaultResourceEdit/index.jsx
  src/utils/index.js
Labels: size/L, lgtm, approved, kind/bug, release-note-none

#2859 fix: Disable PVC expand, clone and create snapshot when it's in pending
  src/pages/projects/containers/Volumes/Detail/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note

#2874 fix: Add prompt information for button in log search detail page
  src/components/Modals/LogSearch/Logging/Detail/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note

#2873 fix: User-defined resource quota and GPU limit are not displayed in the quotas card for the multi-cluster project
  src/pages/fedprojects/containers/QuotaManage/ResourceQuota/QuotaItem/index.jsx
  src/pages/fedprojects/containers/QuotaManage/ResourceQuota/index.jsx
  src/pages/projects/containers/BaseInfo/ResourceQuota/QuotaItem/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note

#2878 fix: The number of worker nodes is incorrect
  src/stores/node.js
Labels: size/XS, lgtm, approved, kind/bug, release-note

#2879 fix: Cancel gpu field when edit project quota
  src/actions/project.js
  src/components/Inputs/ResourceLimit/index.jsx
  src/components/Modals/QuotaEdit/index.jsx
  src/stores/federated.js
  src/stores/limitrange.js
  src/utils/index.js
Labels: size/L, lgtm, approved, kind/bug, release-note-none

#2880 fix: Delete gpu field when editing project default resource
  src/actions/project.js
  src/components/Inputs/ResourceLimit/index.jsx
  src/pages/fedprojects/containers/BaseInfo/DefaultResource/index.jsx
  src/pages/fedprojects/containers/BaseInfo/DefaultResource/index.scss
  src/pages/projects/components/Modals/DefaultResourceEdit/index.jsx
  src/pages/projects/containers/BaseInfo/DefaultResource/index.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note

#2881 fix: The quantity unit of the container group quota is incorrect
  src/components/Modals/QuotaEdit/Quotas/Item.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note

#2882 fix: Yaml content is not matched with the monitoring template type
  src/components/Forms/Dashboard/BaseInfo/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note

#2883 fix: The replicas count is covered by the operation button when creating a composing Application in the multi-cluster project
  src/pages/projects/components/Modals/CreateApp/Services/ServiceList/index.scss
Labels: size/XS, lgtm, approved, kind/bug, release-note

#2884 fix: prompt is missing a period
  locales/zh/role.js
Labels: size/XS, lgtm, approved, kind/bug, release-note-none, kind/require-ui-text-review

#2887 fix: Platform version incorrect
  src/pages/console/containers/Dashboard/Admin/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#2885 fix: Pipeline start time invalid
  src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note
