Repository kubesphere/console, pull requests merged in 2021-04, with the labels that each got.

#1732 Update outdated alerting UI
  locales/en/alerting.js
  locales/es/alerting.js
  locales/tc/alerting.js
  locales/zh/alerting.js
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/S

#1729 Recipient UI Text Update
  locales/en/notification.js
  locales/es/notification.js
  locales/tc/notification.js
  locales/zh/notification.js
  src/components/Forms/Notification/MailForm/index.jsx
  src/components/Forms/Notification/WeComForm/index.jsx
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/S

#1736 chore: add the params of add default taint in url
  src/components/Forms/Cluster/EdgeNode/AddNode/index.jsx
  src/stores/edgenode.js
Labels: approved, dco-signoff: yes, lgtm, size/M

#1737 fix: Fix custom alerting table properties
  src/components/Forms/AlertingPolicy/AlertingRule/MonitoringTarget/WorkloadSelect.jsx
  src/pages/projects/containers/Alerting/Messages/index.jsx
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/M

#1740 fix: Fix alerting message alerting resource
  src/components/Layout/LoginInfo/index.scss
  src/pages/projects/containers/Services/Detail/ResourceStatus/index.jsx
  src/utils/alerting.js
  src/utils/object.mapper.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#1529 Update docs\development-workflow.md
  docs/development-workflow.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/M

#1739 fix: Fix the operation with differenrt role operator in pipeline
  src/pages/devops/containers/Base/Detail/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Layout/branch.jsx
  src/pages/devops/containers/Pipelines/Detail/Layout/pipeline.jsx
  src/pages/devops/containers/Pipelines/Detail/Layout/runs.jsx
Labels: approved, dco-signoff: yes, lgtm, size/S

#1733 fix: fix the buildImage selected
  src/components/Forms/ImageBuilder/LanguageSelect/index.jsx
  src/components/Forms/ImageBuilder/S2IForm/TemplateSelect/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/S

#1741 fix: Fix data mismatch when switch alerting type
  locales/en/base.js
  locales/es/base.js
  locales/tc/base.js
  locales/zh/base.js
  server/config.yaml
  src/pages/projects/containers/Alerting/Messages/index.jsx
  src/pages/projects/containers/Alerting/Policies/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1743 fix: user setting modal error
  src/components/Modals/UserSetting/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1744 upgrade: upgrade add wecom receiver text
  locales/en/notification.js
  locales/es/notification.js
  locales/tc/notification.js
  locales/zh/notification.js
  src/components/Forms/Notification/WeComForm/index.jsx
  src/components/Inputs/BoxInput/index.scss
Labels: approved, dco-signoff: yes, lgtm, size/M

#1745 upgrade: upgrade group delete modal tip
  locales/en/group.js
  locales/es/group.js
  locales/tc/group.js
  src/pages/workspaces/containers/Groups/GroupTree/index.scss
  src/pages/workspaces/containers/Groups/GroupUser/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/S

#1746 chore: Unify English fonts and convert plural names into singular
  src/components/Modals/Bill/components/MeterDetailCard/index.scss
  src/components/Modals/Bill/constats.js
Labels: approved, dco-signoff: yes, lgtm, size/S

#1747 Chore(locales): Update some UI
  locales/en/alerting.js
  locales/en/application.js
  locales/en/cluster.js
  locales/en/role.js
  locales/zh/alerting.js
  locales/zh/project.js
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/M

#1748 upgrade: add notification receiver quantity limit
  locales/en/notification.js
  locales/es/notification.js
  locales/tc/notification.js
  locales/zh/notification.js
  server/config.yaml
  src/components/Forms/Notification/DingTalkForm/index.jsx
  src/components/Forms/Notification/MailForm/Item.jsx
  src/components/Forms/Notification/SlackForm/Item.jsx
  src/components/Forms/Notification/WeComForm/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/M

#1751 fix: Do not create credential after choose github or bitbucket
  src/stores/devops/scm.js
Labels: approved, area/devops, dco-signoff: yes, lgtm, size/M

#1752 Update metering and billing UI
  locales/en/meter.js
  src/components/Modals/Bill/components/ConstomPieChart/index.jsx
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/M

#1753 fix: Add the cluster params in opresource
  src/stores/meter/base.js
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/XS

#1755 chore: move the sync status from vredential list to credential detail
  src/pages/devops/containers/Credential/detail/index.jsx
  src/pages/devops/containers/Credential/index.jsx
Labels: approved, area/devops, dco-signoff: yes, lgtm, size/M

#1756 fix: Fix op app update if not change the yaml template
  src/pages/projects/components/Modals/AppTemplateEdit/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1758 minor: rename deploy resource
  .github/workflows/deploy-backend/kubesphere.tf
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/XS

#1754 Fix pre-registration username
  server/controllers/session.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1757 fix: Fix workspace list in ippool workspace assign modal
  src/components/Modals/Network/IPPoolWorkspace/index.jsx
  src/pages/clusters/containers/Network/IPPools/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1760 feat: add service accounts role i18n
  locales/en/role.js
  locales/es/role.js
  locales/tc/role.js
  locales/zh/role.js
Labels: approved, dco-signoff: yes, lgtm, size/S

#1763 chore: Remove the monitor tab in edge node detail
  src/pages/clusters/containers/EdgeNodes/Detail/routes.js
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1761 feat: Add credential in github and bitbucket
  src/components/Forms/Pipelines/RepoSelect/BitBucketForm/index.jsx
  src/components/Forms/Pipelines/RepoSelect/BitBucketForm/index.scss
  src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx
  src/components/Forms/Pipelines/RepoSelect/GithubForm/index.scss
  src/components/Forms/Pipelines/RepoSelect/subForm.jsx
  src/components/Modals/CredentialCreate/index.jsx
  src/pages/devops/containers/Credential/detail/index.jsx
  src/stores/devops/credential.js
  src/stores/devops/scm.js
Labels: approved, area/devops, dco-signoff: yes, kind/feature, lgtm, size/L

#1765 fix: Fix some op applications issues
  package.json
  src/configs/openpitrix/app.js
  src/pages/projects/containers/Applications/CRDApps.jsx
  src/pages/projects/containers/Applications/OPApps.jsx
  src/pages/workspaces/containers/Repos/Detail/Events/index.jsx
  src/stores/openpitrix/application.js
  src/utils/index.js
  yarn.lock
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1764 Update Traditional Chinese translations
  locales/tc/app.js
  locales/tc/base.js
  locales/tc/meter.js
  locales/tc/user.js
  locales/tc/version.js
  locales/tc/workload.js
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/M

#1767 Chore(locales): Update some UI text
  locales/en/app.js
  locales/en/app_store.js
  locales/en/application.js
  locales/en/base.js
  locales/en/devops.js
  locales/en/grayrelease.js
  locales/en/nodes.js
  locales/en/service.js
  locales/en/terminal.js
  locales/en/version.js
  locales/en/workload.js
  locales/es/app_store.js
  locales/es/nodes.js
  locales/es/version.js
  locales/tc/app_store.js
  locales/tc/version.js
  locales/zh/app_store.js
  locales/zh/role.js
  locales/zh/version.js
  src/actions/openpitrix.js
  src/configs/openpitrix/app.js
  src/pages/apps/components/AppBase/index.jsx
  src/pages/apps/components/Cards/ConfigFile/index.jsx
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/L

#1762 Few UI Updated
  locales/en/pipeline.js
  locales/es/pipeline.js
  locales/tc/pipeline.js
  locales/zh/base.js
  locales/zh/pipeline.js
  src/components/Forms/Pipelines/AdvanceSettings/index.jsx
  src/components/Forms/Pipelines/BaseInfo/index.jsx
  src/pages/devops/components/Pipeline/StepModals/input.jsx
Labels: approved, dco-signoff: yes, lgtm, size/L

#1774 fix: Compatible with old ks versions
  locales/en/cluster.js
  locales/es/cluster.js
  locales/tc/cluster.js
  locales/zh/cluster.js
  server/config.yaml
  src/components/Layout/Nav/NavItem.jsx
  src/components/Layout/Nav/index.scss
  src/configs/openpitrix/app.js
  src/core/global.js
  src/pages/clusters/components/Modals/EditBasicInfo/index.jsx
  src/pages/workspaces/components/Modals/EditGroup/Detail/Form/ProjectSelect.jsx
  src/pages/workspaces/components/Modals/EditGroup/Detail/Form/index.jsx
  src/pages/workspaces/components/Modals/EditGroup/Detail/Form/index.scss
  src/pages/workspaces/containers/QuotaManage/ResourceQuota/index.jsx
  src/pages/workspaces/containers/QuotaManage/ResourceQuota/index.scss
  src/stores/openpitrix/application.js
  src/stores/terminal.js
  src/utils/index.js
  src/utils/object.mapper.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#1776 fix: Fix kubectl url by cluster version
  locales/en/cluster.js
  locales/es/cluster.js
  locales/tc/cluster.js
  locales/zh/cluster.js
  src/components/Base/Modal/index.scss
  src/components/Modals/KubeCtl/index.jsx
  src/pages/clusters/containers/KubeCtl/index.jsx
  src/pages/clusters/containers/Overview/Dashboard/ClusterInfo/index.jsx
  src/pages/clusters/containers/Overview/Dashboard/Tools/index.jsx
  src/pages/clusters/routes/index.js
  src/pages/console/routes/index.js
  src/pages/terminal/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#1777 update: Add application status in detail page and repo watch
  locales/en/app_repo.js
  locales/es/app_repo.js
  locales/tc/app_repo.js
  locales/zh/app_repo.js
  src/components/Base/Indicator/index.scss
  src/components/Modals/AppRepoCreate/index.scss
  src/components/Modals/AppRepoCreate/url.input.jsx
  src/pages/projects/containers/Applications/CRDAppDetail/index.jsx
  src/pages/projects/containers/Applications/OPAppDetail/index.jsx
  src/pages/workspaces/containers/Repos/index.jsx
  src/stores/openpitrix/repo.js
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/M

#1778 Modify OWNERS
  OWNERS
Labels: dco-signoff: yes

#1770 fix: Fix the repo selected is incorrect after search
  src/components/Forms/Pipelines/RepoSelect/BitBucketForm/index.jsx
  src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx
  src/components/Forms/Pipelines/RepoSelect/index.scss
  src/pages/devops/containers/Pipelines/Detail/Layout/pipeline.jsx
  src/pages/devops/containers/Pipelines/PipelinesList/index.jsx
  src/stores/devops/scm.js
Labels: approved, area/devops, dco-signoff: yes, lgtm, size/M

#1771 fix: Fix some issue about member cluster in metering
  locales/en/meter.js
  locales/es/meter.js
  locales/tc/meter.js
  locales/zh/meter.js
  src/components/Modals/Bill/Details/Cluster/index.jsx
  src/components/Modals/Bill/components/LineChart/MonitorTab/index.jsx
  src/components/Modals/Bill/components/LineChart/index.jsx
  src/components/Modals/Bill/components/LineChart/index.scss
  src/components/Modals/Bill/components/SideCard/item.jsx
  src/components/Modals/Bill/components/SideCard/item.scss
  src/components/Modals/Bill/components/Title/index.scss
  src/stores/meter/base.js
Labels: approved, dco-signoff: yes, lgtm, size/L

#1772 Add a multi-stage dockerfile to build console
  Dockerfile.multistage
  Makefile
  README.md
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/M

#1783 fix: Fix cluster version check in single cluster mode
  server/services/session.js
  src/components/Modals/KubeCtl/index.jsx
  src/core/global.js
  src/pages/workspaces/components/Modals/EditGroup/Detail/Form/index.jsx
  src/pages/workspaces/containers/QuotaManage/ResourceQuota/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1784 fix: Fix fedrated project creation
  src/actions/federated.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1780 chore: Add Composing Apps local
  locales/en/application.js
  locales/es/application.js
  locales/tc/application.js
  locales/zh/application.js
  src/pages/fedprojects/containers/Applications/index.jsx
  src/pages/projects/containers/Applications/Banner.jsx
  src/pages/projects/containers/Applications/CRDApps.jsx
Labels: approved, dco-signoff: yes, lgtm, size/S

#1779 feat: Gitlab is not displayed when the current cluster version is 3.0.0
  src/components/Forms/Pipelines/RepoSelect/subForm.jsx
  src/pages/devops/containers/layout.jsx
Labels: approved, dco-signoff: yes, lgtm, size/M

#1785 fix: Fix custom alerting auth key
  server/config.yaml
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1787 fix: Fix termianl url in single cluster mode
  src/components/Modals/KubeCtl/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1786 fix: Add empty message in repo form
  src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx
  src/components/Forms/Pipelines/RepoSelect/GithubForm/index.scss
  src/stores/devops/scm.js
Labels: approved, dco-signoff: yes, lgtm, size/L

#1789 fix: Fix cluster ks version and metadata.finalizer
  src/pages/clusters/containers/Overview/Dashboard/ClusterInfo/index.jsx
  src/utils/object.mapper.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1796 fix: Fix the price line-chart height and ws have disabled status
  src/components/Modals/Bill/Details/Cluster/index.jsx
  src/components/Modals/Bill/components/LineChart/index.jsx
  src/components/Modals/Bill/components/LineChart/index.scss
  src/utils/meter.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1790 chore: Modify the decimal point in chart data
  src/components/Modals/Bill/Details/Cluster/index.jsx
  src/components/Modals/Bill/Details/Cluster/index.scss
  src/components/Modals/Bill/components/LineChart/MonitorTab/index.jsx
  src/components/Modals/Bill/components/LineChart/MonitorTab/index.scss
  src/components/Modals/Bill/components/LineChart/index.jsx
  src/utils/monitoring.js
Labels: approved, dco-signoff: yes, lgtm, size/M

#1799 fix: Fix the url of service Provider Website on APP Review Content page
  src/pages/apps/components/Cards/BaseInfo/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1798 fix: Fix selected category doesn't match with the list
  src/pages/apps/containers/Categories/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/S

#1792 fix: fix storageclass doc link
  server/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1742 Review UI text on the Department Management page.
  locales/en/base.js
  locales/en/group.js
  locales/en/role.js
  locales/en/workspace.js
  src/pages/workspaces/components/Modals/EditGroup/Detail/Form/index.jsx
  src/pages/workspaces/containers/BaseInfo/index.jsx
  src/pages/workspaces/containers/Groups/index.jsx
Labels: approved, dco-signoff: no, kind/documentation, lgtm, size/M

#1791 Update some UI text
  locales/en/alerting.js
  locales/en/base.js
  locales/en/logging.js
  locales/en/service.monitor.js
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/M

#1788 Chore(locales): Update some UI
  locales/en/meter.js
  locales/es/meter.js
  locales/tc/meter.js
  locales/zh/meter.js
  src/components/Modals/Bill/Details/Cluster/index.jsx
  src/components/Modals/Bill/constats.js
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/S

#1805 chore: Remove Update Notice when the pipeline run
  src/actions/pipeline.js
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1804 fix: Fix the pod terminal with different cluster version
  src/components/Modals/ContianerTerminal/index.jsx
  src/components/Terminal/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/L

#1803 fix: Fix the create button in empty of alert policies page
  src/pages/projects/containers/Alerting/Policies/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1802 fix: Fix the checkbox in kubernetesDeploy
  src/pages/devops/components/Pipeline/StepModals/kubernetesDeploy.jsx
  src/pages/devops/components/Pipeline/StepsSelector/index.jsx
  src/pages/devops/components/Pipeline/store.js
Labels: approved, dco-signoff: yes, lgtm, size/L

#1801 feat: add cluster upgrade tip to the group
  locales/en/cluster.js
  locales/es/cluster.js
  locales/tc/cluster.js
  locales/zh/cluster.js
  src/pages/workspaces/components/Modals/EditGroup/Detail/Form/DevopsSelect.jsx
  src/pages/workspaces/components/Modals/EditGroup/Detail/Form/ProjectSelect.jsx
  src/pages/workspaces/components/Modals/EditGroup/Detail/Form/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/M

#1809 fix a s2i link
  locales/en/s2i.js
  locales/zh/s2i.js
  server/config.yaml
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/XS

#1808 fix: project custom alert page error in old version
  server/config.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1807 Update UI text on the Department Management page.
  locales/es/group.js
  locales/tc/group.js
  locales/zh/group.js
  src/pages/workspaces/components/Modals/EditGroup/Detail/Form/index.jsx
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/XS

#1811 fix: Disable multiple cluster projects when creating network policy
  src/components/Inputs/ProjectSelect/index.jsx
  src/components/Modals/Network/Policies/index.jsx
  src/components/Modals/Network/Policies/index.scss
Labels: approved, dco-signoff: yes, lgtm, size/S

#1812 fix: Add input in expand volume modal
  src/pages/projects/components/Modals/ExpandVolume/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1806 fix: Fix the price data with less 0
  src/components/Modals/Bill/Details/Cluster/index.jsx
  src/components/Modals/Bill/components/LineChart/index.jsx
  src/components/Modals/Bill/components/MeterDetailCard/index.jsx
  src/components/Modals/Bill/components/Tables/index.jsx
  src/stores/meter/base.js
Labels: approved, dco-signoff: yes, lgtm, size/M

#1817 fix: Add bouncing in some type of status
  src/components/Base/Indicator/index.jsx
  src/components/Base/Indicator/index.scss
  src/components/Base/Status/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/M

#1822 chore: Add reviewers
  OWNERS
Labels: dco-signoff: yes, lgtm, size/XS

#1821 chore: Fix the bug that the status code is 503 in resource list API
  src/stores/meter/base.js
  src/stores/meter/cluster.js
Labels: approved, dco-signoff: yes, lgtm, size/S

#1819 fix: Replace namespaced_resources_filter to resources_filter
  src/components/Cards/Pods/index.jsx
  src/stores/monitoring/base.js
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, size/XS

#1820 fix: Fix the pod name is Incorrect in terminal modal
  src/components/Modals/ContianerTerminal/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/M

#1828 fix: Fix application template and repo status
  src/components/Base/Indicator/index.jsx
  src/components/Base/Indicator/index.scss
  src/components/Base/Status/index.jsx
  src/pages/projects/containers/Applications/CRDApps.jsx
  src/pages/projects/containers/Applications/OPApps.jsx
  src/pages/workspaces/containers/Repos/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1826 fix: Fix metering of single cluster in disabled status
  src/components/Modals/Bill/Details/Cluster/index.jsx
  src/components/Modals/Bill/components/Crumb/index.scss
  src/components/Modals/Bill/components/SideCard/index.jsx
  src/components/Modals/Bill/components/SideCard/index.scss
  src/components/Modals/Bill/components/SideCard/item.jsx
  src/components/Modals/Bill/components/SideCard/item.scss
  src/utils/meter.js
Labels: approved, dco-signoff: yes, lgtm, size/M

#1823 Chore(locales): Update some UI text
  locales/en/app.js
  locales/en/base.js
  locales/en/cluster.js
  locales/en/login.js
  locales/en/project.js
  locales/en/role.js
  locales/en/workload.js
  locales/es/app.js
  locales/es/workload.js
  locales/tc/app.js
  locales/tc/workload.js
  locales/zh/app.js
  locales/zh/cluster.js
  locales/zh/workload.js
  src/components/Forms/AlertingPolicy/BaseInfo/index.jsx
  src/components/Forms/AppDeploy/BasicInfo/index.jsx
  src/components/Forms/Cluster/BaseInfo/index.jsx
  src/components/Forms/Cluster/EdgeNode/AddNode/index.jsx
  src/components/Forms/CronJob/BaseInfo/index.jsx
  src/components/Forms/Dashboard/BaseInfo/index.jsx
  src/components/Forms/GrayRelease/BaseInfo/index.jsx
  src/components/Forms/Pipelines/BaseInfo/index.jsx
  src/components/Forms/Service/BaseInfo/index.jsx
  src/components/Forms/Service/ContainerSetting/ContainerSetting/index.jsx
  src/components/Forms/ServiceAccount/BaseInfo/index.jsx
  src/components/Forms/StorageClass/BaseInfo/index.jsx
  src/components/Forms/Workload/BaseInfo/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
  src/components/Forms/Workload/VolumeSettings/AddHostPath/index.jsx
  src/components/Forms/Workload/VolumeSettings/AddTemporary/index.jsx
  src/components/Forms/Workload/VolumeSettings/AddVolumeTemplate/index.jsx
  src/components/Modals/DevOpsCreate/index.jsx
  src/components/Modals/FedProjectCreate/index.jsx
  src/components/Modals/Pipelines/Copy/index.jsx
  src/components/Modals/ProjectCreate/index.jsx
  src/components/Modals/RoleCreate/index.jsx
  src/pages/projects/components/Modals/CreateApp/BaseInfo/index.jsx
  src/pages/projects/components/Modals/ResourceNamed/index.jsx
  src/pages/workspaces/components/Modals/EditGroup/Detail/Form/index.jsx
  src/pages/workspaces/components/Modals/WorkspaceCreate/BaseInfo/index.jsx
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/L

#1834 Update image builder UI
  locales/en/role.js
  locales/en/s2i.js
  locales/es/role.js
  locales/zh/role.js
  locales/zh/s2i.js
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/S

#1836 fix typo
  locales/en/app.js
  locales/es/app.js
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/XS

#1833 upgrade: Update user group workspace role description
  locales/en/cluster.js
  locales/es/cluster.js
  locales/tc/cluster.js
  locales/zh/cluster.js
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1838 fix alerting desc
  locales/en/alerting.js
  locales/en/cluster.js
  locales/tc/alerting.js
  locales/zh/alerting.js
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/S

#1839 Chore(locales): Update few S2I-related UI
  locales/en/s2i.js
  locales/es/s2i.js
  locales/tc/s2i.js
  locales/zh/s2i.js
  src/components/Inputs/S2iEnviroment/index.jsx
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/S

#1841 fix: alerting rule and policies query api error
  src/components/Forms/AlertingPolicy/AlertingRule/QueryMonitor/index.jsx
  src/components/Forms/AlertingPolicy/AlertingRule/index.jsx
  src/pages/projects/containers/Alerting/Policies/Detail/AlertRules/Monitoring.jsx
Labels: approved, dco-signoff: yes, lgtm, size/S

#1840 chore(locales): Update tc locale
  locales/tc/alerting.js
  locales/tc/app_repo.js
  locales/tc/cluster.js
  locales/tc/meter.js
  locales/tc/notification.js
  locales/tc/role.js
Labels: approved, dco-signoff: yes, lgtm, size/M

#1842 feat: support OpenID Connect RP-Initiated Logout
  server/controllers/session.js
  server/services/session.js
  src/core/containers/Login/index.jsx
  src/stores/root.js
Labels: approved, dco-signoff: yes, lgtm, size/M

#1846 update image builder cn UI
  locales/zh/role.js
  locales/zh/s2i.js
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/S

#1849 fix: Fix the enable_discarder checkbox
  src/components/Forms/Pipelines/AdvanceSettings/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1850 fix: Fix the yaml editor in pipeline step
  src/pages/devops/components/Pipeline/Sider/index.jsx
  src/pages/devops/components/Pipeline/StepsEditor/index.jsx
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/XS

#1851 fix: Fix the role match the users-manager
  src/pages/console/containers/Dashboard/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1852 fix: Fix the export resource UI in bill
  src/components/Modals/Bill/components/Crumb/index.scss
  src/components/Modals/Bill/components/SideCard/index.jsx
  src/components/Modals/Bill/components/SideCard/index.scss
  src/components/Modals/Bill/components/SideCard/item.jsx
  src/components/Modals/Bill/components/SideCard/item.scss
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1853 Fix third party login console UI
  locales/en/login.js
  locales/en/user.js
  locales/es/login.js
  locales/es/user.js
  locales/tc/login.js
  locales/tc/user.js
  locales/zh/login.js
  locales/zh/user.js
  src/components/Modals/UserCreate/index.jsx
  src/core/containers/LoginConfirm/index.jsx
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/S

#1854 fix: Remove post_logout_redirect_uri
  server/controllers/session.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1859 fix: deploy app failed
  src/pages/apps/components/Modals/AppDeploy/index.jsx
  src/pages/apps/containers/AppDeploy/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1868 Development-workflow.md content link error fix.
  docs/development-workflow.md
Labels: approved, dco-signoff: yes, lgtm, size/XS
