Repository kubesphere/console, pull requests merged in 2021-03, with the labels that each got.

#1497 fix: Remove system-workspace from cluster visibility list
  src/pages/clusters/components/Modals/ClusterVisibility/WorkspaceItem/index.jsx
  src/pages/clusters/components/Modals/ClusterVisibility/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1498 fix: tree node style
  src/components/Tree/style.scss
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1499 Add Gitlab as the scm support type
  locales/en/devops.js
  locales/es/devops.js
  locales/tc/devops.js
  locales/zh/devops.js
Labels: approved, area/devops, dco-signoff: yes, kind/documentation, lgtm, size/XS

#1501 fix: Fix the error tip when the empty active page in the brach page
  src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Branch/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Layout/pipeline.jsx
  src/pages/devops/containers/Pipelines/Detail/PullRequest/index.jsx
  src/stores/devops/pipelines.js
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/L

#1503 fix: Fix service topology detail error
  locales/en/service.js
  locales/es/service.js
  locales/tc/service.js
  locales/zh/service.js
  scripts/locale-plugin.js
  src/pages/projects/containers/Services/Topology/Detail/Table/index.jsx
  src/pages/projects/containers/Services/Topology/Service/index.jsx
  src/pages/projects/containers/Services/Topology/Service/index.scss
  src/pages/projects/containers/Services/Topology/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1500 fix: Support op applications watch
  src/components/HOCs/withList.js
  src/pages/projects/containers/Applications/OPApps.jsx
  src/stores/openpitrix/application.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1513 Update Traditional Chinese translations in alerting.js
  locales/tc/alerting.js
Labels: approved, dco-signoff: yes, lgtm, size/M

#1514 Update Traditional Chinese translations in app.js
  locales/tc/app.js
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/S

#1516 fix: Fix custom alerting issues
  locales/en/alerting.js
  locales/es/alerting.js
  locales/zh/alerting.js
  src/actions/alerting.js
  src/components/Cards/Monitoring/Controller/TimeSelector/index.jsx
  src/components/Cards/Monitoring/Controller/TimeSelector/utils.js
  src/components/Charts/Area/MultiArea/index.jsx
  src/components/Forms/AlertingPolicy/AlertingRule/MonitoringTarget/NodeSelect.jsx
  src/components/Forms/AlertingPolicy/AlertingRule/MonitoringTarget/WorkloadSelect.jsx
  src/components/Forms/AlertingPolicy/AlertingRule/QueryMonitor/index.jsx
  src/components/Forms/AlertingPolicy/AlertingRule/RuleInput/index.jsx
  src/components/Forms/AlertingPolicy/AlertingRule/index.jsx
  src/components/Modals/CustomMonitoring/components/PromQLInput/index.jsx
  src/configs/alerting/metrics/rule.config.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#1518 feat: Support workspace quota
  locales/en/workspace.js
  locales/es/workspace.js
  locales/tc/workspace.js
  locales/zh/workload.js
  locales/zh/workspace.js
  server/config.yaml
  src/actions/workspace.js
  src/components/Forms/Workload/ContainerSettings/ContainerList/QuotaCheck.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerList/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerList/index.scss
  src/components/Forms/Workload/ContainerSettings/index.jsx
  src/components/Inputs/StringInput/index.jsx
  src/pages/clusters/components/Modals/EditBasicInfo/index.jsx
  src/pages/clusters/containers/BaseInfo/index.jsx
  src/pages/projects/containers/CronJobs/index.jsx
  src/pages/projects/containers/DaemonSets/index.jsx
  src/pages/projects/containers/Deployments/index.jsx
  src/pages/projects/containers/Jobs/index.jsx
  src/pages/workspaces/components/Modals/QuotaEdit/index.jsx
  src/pages/workspaces/components/Modals/QuotaEdit/index.scss
  src/pages/workspaces/containers/QuotaManage/ResourceQuota/QuotaItem/index.jsx
  src/pages/workspaces/containers/QuotaManage/ResourceQuota/QuotaItem/index.scss
  src/pages/workspaces/containers/QuotaManage/ResourceQuota/index.jsx
  src/pages/workspaces/containers/QuotaManage/ResourceQuota/index.scss
  src/pages/workspaces/containers/QuotaManage/index.jsx
  src/pages/workspaces/containers/QuotaManage/index.scss
  src/pages/workspaces/routes/index.js
  src/stores/workspace.quota.js
  src/utils/constants.js
  src/utils/index.js
  src/utils/index.test.js
  src/utils/workload.js
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XXL

#1520 fix: Fix workspace quota locales
  locales/en/workload.js
  locales/es/workload.js
  locales/tc/workload.js
  locales/zh/workload.js
  src/components/Forms/Workload/ContainerSettings/ContainerList/QuotaCheck.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1521 fix: Fix edit workspace quota
  src/actions/workspace.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1517 Update Traditional Chinese translations in ippool.js
  locales/tc/ippool.js
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/M

#1523 fix: Fix alert active time locale
  locales/en/alerting.js
  locales/es/alerting.js
  locales/tc/alerting.js
  locales/zh/alerting.js
  src/pages/projects/containers/Alerting/Policies/Detail/index.jsx
  src/pages/projects/containers/Alerting/Policies/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1526 fix:sshpass for actions
  .github/workflows/deploy-pr.yml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1527 improvement: add images name to the comment
  .github/workflows/deploy-pr.yml
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/XS

#1522 Update Traditional Chinese translations in serviceaccounts.js
  locales/tc/serviceaccounts.js
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1524 Update Traditional Chinese translations in workspace.js
  locales/tc/workspace.js
Labels: approved, dco-signoff: yes, lgtm, size/S

#1528 Chore(locales): Update some UI
  locales/en/app.js
  locales/en/devops.js
  locales/en/ippool.js
  locales/en/pipeline.js
  locales/en/serviceaccounts.js
  locales/en/workspace.js
  locales/es/serviceaccounts.js
  locales/es/workspace.js
  locales/tc/workspace.js
  locales/zh/ippool.js
  locales/zh/serviceaccounts.js
  locales/zh/workload.js
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/M

#1530 update: Update tc locales, the workload.js part has been translated.
  locales/tc/workload.js
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1532 fix: Fix alerting rule unit and monitor data process
  src/configs/alerting/metrics/rule.config.js
  src/utils/monitoring.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1535 refactor: Move service monitor to service detail page
  locales/en/service.monitor.js
  locales/es/service.monitor.js
  locales/tc/service.monitor.js
  locales/zh/service.monitor.js
  src/actions/service.js
  src/components/Inputs/SecretSelect/index.jsx
  src/pages/projects/components/Cards/ServiceMonitors/Item.jsx
  src/pages/projects/components/Cards/ServiceMonitors/index.jsx
  src/pages/projects/components/Cards/ServiceMonitors/index.scss
  src/pages/projects/components/Cards/Workloads/Item.jsx
  src/pages/projects/components/Modals/ServiceMonitor/Authorization/index.jsx
  src/pages/projects/components/Modals/ServiceMonitor/Endpoint/index.jsx
  src/pages/projects/components/Modals/ServiceMonitor/index.jsx
  src/pages/projects/containers/Applications/CRDAppDetail/Components/index.jsx
  src/pages/projects/containers/Applications/CRDAppDetail/index.jsx
  src/pages/projects/containers/Applications/OPAppDetail/ResourceStatus/index.jsx
  src/pages/projects/containers/Applications/OPAppDetail/index.jsx
  src/pages/projects/containers/Services/Detail/ResourceStatus/index.jsx
  src/pages/projects/containers/Services/Detail/index.jsx
  src/utils/object.mapper.js
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/L

#1533 feat: Add sync status in pipeline and credential
  locales/en/pipeline.js
  locales/es/pipeline.js
  locales/tc/pipeline.js
  locales/zh/pipeline.js
  src/pages/devops/containers/Credential/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Artifacts/index.jsx
  src/pages/devops/containers/Pipelines/PipelinesList/index.jsx
  src/pages/workspaces/containers/DevOps/index.jsx
  src/stores/devops/pipelines.js
Labels: approved, area/devops, dco-signoff: yes, kind/feature, lgtm, size/L

#1531 Update Traditional Chinese translations in workspace.js
  locales/tc/workspace.js
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/XS

#1539 fix: Fix openpitrix apps review not working
  locales/en/app.js
  locales/en/version.js
  locales/es/app.js
  locales/es/version.js
  locales/tc/app.js
  locales/tc/version.js
  locales/zh/app.js
  locales/zh/app_store.js
  locales/zh/cluster.js
  locales/zh/version.js
  src/actions/openpitrix.js
  src/pages/apps/components/Forms/VersionEdit/index.jsx
  src/pages/apps/containers/Categories/index.jsx
  src/pages/apps/containers/Reviews/index.jsx
  src/pages/apps/containers/StoreManage/Detail/index.jsx
  src/pages/apps/containers/StoreManage/index.jsx
  src/pages/workspaces/containers/Apps/Detail/index.jsx
  src/utils/app.js
  src/utils/constants.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1537 Update Traditional Chinese translations
  locales/tc/alerting.js
  locales/tc/app_repo.js
  locales/tc/base.js
  locales/tc/dashboard.js
  locales/tc/pipeline.js
  locales/tc/workload.js
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/M

#1541 fix: Fix app tracing error
  src/components/Modals/ProjectSelect/index.jsx
  src/pages/projects/containers/Applications/CRDAppDetail/Tracing/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1553 chore: remove branch select and re-order the SCM source
  src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Branch/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Layout/branch.jsx
  src/utils/constants.js
Labels: approved, area/devops, dco-signoff: yes, lgtm, size/M

#1555 Chore(locales): Update some UI text
  locales/en/base.js
  locales/en/cluster.js
  locales/en/ippool.js
  locales/en/serviceaccounts.js
  locales/es/base.js
  locales/es/cluster.js
  locales/es/ippool.js
  locales/tc/base.js
  locales/tc/cluster.js
  locales/tc/ippool.js
  locales/zh/base.js
  locales/zh/cluster.js
  locales/zh/ippool.js
  locales/zh/login.js
  locales/zh/serviceaccounts.js
  src/components/Cards/Pods/index.jsx
  src/components/Forms/Cluster/NodeList/AddNode.jsx
  src/components/Forms/ImageBuilder/B2IForm/index.jsx
  src/components/Forms/ImageBuilder/S2IForm/index.jsx
  src/components/Modals/Network/IPPoolsCreate/index.jsx
  src/components/Tables/Base/FilterInput/index.jsx
  src/pages/apps/components/Lists/InstanceList/index.jsx
  src/pages/apps/components/Lists/VersionList/index.jsx
  src/pages/projects/containers/Jobs/Detail/ExcuteRecords/index.jsx
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/L

#1558 UI modification trial
  locales/en/application.js
  locales/en/devops.js
  locales/en/service.js
  locales/en/workload.js
Labels: approved, dco-signoff: yes, lgtm, size/S

#1559 chore: Fix locale plugin write to disk
  scripts/locale-plugin.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1560 fix: Add uncheck tip for role authorize edit
  locales/en/alerting.js
  locales/en/role.js
  locales/es/alerting.js
  locales/es/role.js
  locales/tc/role.js
  locales/zh/alerting.js
  locales/zh/role.js
  scripts/locale-plugin.js
  src/components/Modals/EditAuthorization/CheckItem.jsx
  src/core/containers/PasswordConfirm/index.jsx
  src/pages/clusters/containers/ServiceAccounts/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1561 fix: Fix custom monitoring issues
  src/components/Forms/Dashboard/BaseInfo/index.jsx
  src/components/Modals/EditYaml/index.scss
  src/core/layouts/Base/index.jsx
  src/pages/clusters/containers/CustomMonitoring/index.jsx
  src/pages/clusters/containers/CustomResources/Detail/ResourceStatus/index.jsx
  src/pages/projects/containers/CustomMonitoring/index.jsx
  src/utils/constants.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1563 fix: fix serviceaccount issues
  locales/en/serviceaccounts.js
  locales/es/serviceaccounts.js
  locales/tc/serviceaccounts.js
  locales/zh/serviceaccounts.js
  src/actions/serviceaccount.js
  src/pages/clusters/containers/ServiceAccounts/index.jsx
  src/pages/projects/containers/ServiceAccounts/Detail/index.jsx
  src/pages/projects/containers/ServiceAccounts/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/S

#1562 chore: Fix lint-staged rules
  package.json
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1564 update: Update op module key
  server/config.yaml
  src/components/Modals/EditAuthorization/constants.js
  src/core/global.js
  src/pages/console/containers/Dashboard/Admin/PlatformStatus/index.jsx
  src/pages/projects/containers/Applications/Banner.jsx
  src/pages/projects/containers/Applications/OPApps.jsx
  src/pages/projects/containers/Overview/index.jsx
  src/pages/projects/routes/index.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1566 fix: Fix multicluster application tracing page error
  src/pages/fedprojects/components/ClusterSelect/index.scss
  src/pages/fedprojects/containers/Applications/Detail/Tracing/index.jsx
  src/pages/fedprojects/containers/Applications/Detail/Tracing/index.scss
  src/pages/projects/components/Modals/CreateApp/Routes/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1568 update: add termianl entrance page
  scripts/webpack.base.js
  server/controllers/view.js
  server/routes.js
  server/views/terminal.html
  src/components/KubeTools/index.jsx
  src/core/terminal.js
  src/pages/console/routes/index.js
  src/pages/terminal/index.jsx
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/L

#1570 UI updated
  locales/en/pipeline.js
  locales/en/project.js
  locales/en/workload.js
Labels: approved, dco-signoff: yes, lgtm, size/M

#1571 fix: Fix terminal url
  src/components/KubeTools/index.jsx
  src/pages/terminal/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1572 Chore(locales): Update some UI text
  locales/en/alerting.js
  locales/en/base.js
  locales/en/devops.js
  locales/en/group.js
  locales/en/pipeline.js
  locales/en/project.js
  locales/en/s2i.js
  locales/en/user.js
  locales/en/workspace.js
  locales/es/alerting.js
  locales/es/group.js
  locales/es/pipeline.js
  locales/es/workspace.js
  locales/tc/alerting.js
  locales/tc/group.js
  locales/tc/pipeline.js
  locales/tc/workspace.js
  locales/zh/alerting.js
  locales/zh/application.js
  locales/zh/group.js
  locales/zh/logging.js
  locales/zh/pipeline.js
  locales/zh/workspace.js
  src/components/Forms/AlertingPolicy/NotificationRule/index.jsx
  src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx
  src/pages/workspaces/components/Modals/EditGroup/Detail/Card/index.jsx
  src/pages/workspaces/components/Modals/EditGroup/Detail/Form/index.jsx
  src/pages/workspaces/components/Modals/EditGroup/Detail/index.jsx
  src/pages/workspaces/containers/Groups/GroupUser/User.jsx
  src/pages/workspaces/containers/Groups/index.jsx
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/L

#1567 update: Show current App version in app template edit
  locales/en/app.js
  locales/es/app.js
  locales/tc/app.js
  locales/zh/app.js
  src/pages/projects/components/Modals/AppTemplateEdit/index.jsx
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/M

#1573 fix: Fix Edge Node apiVersion and listUrl
  src/stores/edgenode.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1579 fix: Fix op app review status
  locales/en/version.js
  locales/es/version.js
  locales/tc/version.js
  locales/zh/version.js
  src/components/Base/Indicator/index.scss
  src/configs/openpitrix/app.js
  src/pages/projects/components/Modals/DeployApp/index.jsx
  src/stores/openpitrix/base.js
  src/utils/app.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1577 fix: Fix storage class api in sts create form
  src/components/Forms/Volume/VolumeSettings/FormTemplate.jsx
  src/components/Forms/Workload/VolumeSettings/AddVolumeTemplate/index.jsx
  src/components/Forms/Workload/VolumeSettings/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1586 chore: Refactor webpack build script for multiple entries
  scripts/webpack.e2e.js
  scripts/webpack.prod.js
  server/controllers/view.js
  server/libs/utils.js
  server/views/terminal.html
  src/core/terminal.js
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/L

#1578 page loading animations opimization
  server/public/loading.css
  server/views/components/loading.html
  server/views/index.html
  server/views/terminal.html
Labels: approved, dco-signoff: yes, lgtm, size/M

#1582 chore: group delete modal
  locales/zh/group.js
  src/components/Modals/GroupDelete/index.jsx
  src/components/Modals/GroupDelete/index.scss
  src/pages/workspaces/components/Modals/EditGroup/Detail/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/L

#1588 fix: Fix network ippool create validate error and input search
  package.json
  src/components/Modals/AppRepoCreate/url.input.jsx
  src/components/Modals/Network/IPPoolsCreate/index.jsx
  yarn.lock
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1584 fix: Fix the local language and the join URL
  locales/en/nodes.js
  locales/es/nodes.js
  locales/tc/nodes.js
  locales/zh/nodes.js
  src/components/Forms/Cluster/EdgeNode/AddNode/index.jsx
  src/stores/edgenode.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1592 fix: terminal page loading delay
  server/public/loading.css
Labels: approved, dco-signoff: yes, lgtm, size/S

#1591 Chore(locales): Update some UI
  locales/en/app.js
  locales/en/app_repo.js
  locales/en/application.js
  locales/en/base.js
  locales/en/cluster.js
  locales/en/monitoring.js
  locales/en/nodes.js
  locales/en/role.js
  locales/en/storage.js
  locales/en/workload.js
  locales/en/workspace.js
  locales/es/app_repo.js
  locales/es/application.js
  locales/es/cluster.js
  locales/es/role.js
  locales/es/storage.js
  locales/tc/app_repo.js
  locales/tc/application.js
  locales/tc/cluster.js
  locales/tc/storage.js
  locales/zh/app_repo.js
  locales/zh/application.js
  locales/zh/cluster.js
  locales/zh/storage.js
  src/actions/volume.js
  src/pages/fedprojects/containers/Volumes/Detail/ResourceStatus/UsageCard/index.jsx
  src/pages/projects/components/Modals/CreateApp/Routes/RuleList/index.jsx
  src/pages/projects/containers/Volumes/Detail/ResourceStatus/UsageCard/index.jsx
  src/pages/projects/containers/Volumes/Detail/index.jsx
  src/pages/workspaces/containers/Repos/index.jsx
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/L

#1589 update: update resource edit notify
  src/actions/resource.edit.js
Labels: approved, dco-signoff: yes, lgtm, size/XS

#1594 fix: Fix some issues
  locales/zh/version.js
  scripts/webpack.e2e.js
  scripts/webpack.prod.js
  src/components/Forms/AlertingPolicy/AlertingRule/MonitoringTarget/WorkloadSelect.jsx
  src/components/Modals/AppRepoCreate/index.jsx
  src/components/Modals/EditYaml/index.scss
  src/pages/clusters/containers/ServiceComponents/index.jsx
  src/pages/projects/components/Cards/HPA/index.jsx
  src/stores/component.js
Labels: approved, dco-signoff: yes, lgtm, size/M

#1595 fix: Remove updatedTime in secret detail page
  src/pages/projects/containers/Secrets/Detail/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1597 refactor: Refactor navs hover and click behaviors
  src/components/Layout/Nav/NavItem.jsx
  src/components/Layout/Nav/index.jsx
  src/components/Layout/Nav/index.scss
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/L

#1606 fix: Fix checkbox in edit authorization
  package.json
  src/components/Modals/EditAuthorization/CheckItem.jsx
  src/components/Modals/EditAuthorization/index.scss
  yarn.lock
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1609 fix: Fix resource limit error tip
  src/components/Inputs/ResourceLimit/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1611 fix: Fix ippool issues
  locales/zh/cluster.js
  locales/zh/ippool.js
  src/components/Modals/Network/IPPoolsCreate/index.jsx
  src/pages/clusters/containers/Network/IPPools/Detail/index.jsx
  src/pages/clusters/containers/Network/IPPools/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1612 fix: Fix resource limit error check
  src/components/Inputs/ResourceLimit/index.jsx
  src/components/Modals/QuotaEdit/index.jsx
  src/pages/projects/components/Modals/DefaultResourceEdit/index.jsx
  src/pages/workspaces/components/Modals/QuotaEdit/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1615 fix: Fix oauth cas provider
  server/services/session.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1616 chore(locales): Update tc locale
  locales/tc/cluster.js
  locales/tc/ippool.js
  locales/tc/workload.js
Labels: approved, dco-signoff: yes, lgtm, size/M

#1614 Chore(locales): Update some UI text
  locales/en/app.js
  locales/en/base.js
  locales/en/cluster.js
  locales/en/monitoring.js
  locales/en/nodes.js
  locales/en/version.js
  locales/en/workload.js
  locales/es/app.js
  locales/es/base.js
  locales/es/cluster.js
  locales/es/monitoring.js
  locales/es/version.js
  locales/es/workload.js
  locales/tc/app.js
  locales/tc/base.js
  locales/tc/monitoring.js
  locales/tc/version.js
  locales/tc/workload.js
  locales/zh/app.js
  locales/zh/base.js
  locales/zh/monitoring.js
  locales/zh/version.js
  locales/zh/workload.js
  src/components/Forms/Service/ContainerSetting/ContainerSetting/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerList/QuotaCheck.jsx
  src/pages/apps/components/Cards/ConfigFile/index.jsx
  src/pages/apps/components/Lists/VersionList/Item.jsx
  src/pages/clusters/containers/Monitor/Cluster/Overview/index.jsx
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/L

#1613 fix: Fix the issue about copy pipeline descripton
  src/components/Forms/Pipelines/AdvanceSettings/index.jsx
  src/components/Forms/Pipelines/BaseInfo/index.jsx
  src/components/Modals/Pipelines/Copy/index.jsx
  src/utils/devops.js
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/S

#1622 fix: Fix grayrelease component select and container edit
  server/config.yaml
  src/components/Forms/GrayRelease/Components/index.jsx
  src/components/Forms/GrayRelease/Version/ContainerList/Card.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1623 Reviewed EN UI text of the Application Repositories page.
  locales/en/app.js
  locales/en/app_repo.js
  locales/en/base.js
  locales/en/dashboard.js
  src/components/Modals/AppRepoCreate/url.input.jsx
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/M

#1534 feat : notification manager
  locales/en/mail.js
  locales/en/notification.js
  locales/es/mail.js
  locales/es/notification.js
  locales/es/settings.js
  locales/tc/mail.js
  locales/tc/notification.js
  locales/tc/pipeline.js
  locales/tc/settings.js
  locales/zh/mail.js
  locales/zh/notification.js
  locales/zh/pipeline.js
  locales/zh/settings.js
  server/config.yaml
  src/components/Base/ToggleField/index.jsx
  src/components/Base/index.js
  src/components/Forms/MailServerForm/index.jsx
  src/components/Forms/MailServerForm/index.scss
  src/components/Forms/Notification/DingTalkForm/index.jsx
  src/components/Forms/Notification/DingTalkForm/index.scss
  src/components/Forms/Notification/MailForm/Item.jsx
  src/components/Forms/Notification/MailForm/index.jsx
  src/components/Forms/Notification/MailForm/index.scss
  src/components/Forms/Notification/SlackForm/Item.jsx
  src/components/Forms/Notification/SlackForm/index.jsx
  src/components/Forms/Notification/SlackForm/index.scss
  src/components/Forms/Notification/WeComForm/Item.jsx
  src/components/Forms/Notification/WeComForm/index.jsx
  src/components/Forms/Notification/WeComForm/index.scss
  src/components/Forms/Notification/WebhookForm/index.jsx
  src/components/Forms/Notification/WebhookForm/index.scss
  src/components/Forms/Pipelines/AdvanceSettings/index.jsx
  src/components/Inputs/BoxInput/index.jsx
  src/components/Inputs/BoxInput/index.scss
  src/components/Inputs/StringInput/index.jsx
  src/components/Inputs/index.js
  src/pages/clusters/containers/MailServices/index.jsx
  src/pages/clusters/containers/MailServices/index.scss
  src/pages/clusters/routes/index.js
  src/pages/settings/containers/Notification/DingTalk/index.jsx
  src/pages/settings/containers/Notification/Mail/index.jsx
  src/pages/settings/containers/Notification/Slack/index.jsx
  src/pages/settings/containers/Notification/WeCom/index.jsx
  src/pages/settings/containers/Notification/Webhook/index.jsx
  src/pages/settings/routes/index.js
  src/stores/notification/address.js
  src/stores/notification/base.js
  src/stores/notification/config.js
  src/stores/notification/index.js
  src/stores/notification/mailService.js
  src/stores/notification/receiver.js
  src/stores/notification/secret.js
  src/utils/form.templates.js
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XXL

#1624 fix: Fix resource delete type missing
  locales/en/user.js
  locales/es/user.js
  locales/tc/user.js
  locales/zh/user.js
  src/components/HOCs/withList.js
  src/components/Modals/UserCreate/index.jsx
  src/core/containers/LoginConfirm/index.jsx
  src/pages/access/containers/Accounts/Detail/index.jsx
  src/pages/access/containers/Accounts/index.jsx
  src/pages/clusters/containers/ConfigMaps/index.jsx
  src/pages/clusters/containers/EdgeNodes/index.jsx
  src/pages/clusters/containers/Network/IPPools/index.jsx
  src/pages/clusters/containers/Network/Policies/index.jsx
  src/pages/clusters/containers/Nodes/index.jsx
  src/pages/clusters/containers/Projects/index.jsx
  src/pages/clusters/containers/Secrets/index.jsx
  src/pages/clusters/containers/ServiceAccounts/index.jsx
  src/pages/clusters/containers/Storage/VolumeSnapshots/index.jsx
  src/pages/clusters/containers/Storage/Volumes/index.jsx
  src/pages/clusters/containers/Workload/CronJobs/index.jsx
  src/pages/clusters/containers/Workload/DaemonSets/index.jsx
  src/pages/clusters/containers/Workload/Deployments/index.jsx
  src/pages/clusters/containers/Workload/Jobs/index.jsx
  src/pages/clusters/containers/Workload/Pods/index.jsx
  src/pages/clusters/containers/Workload/Routes/index.jsx
  src/pages/clusters/containers/Workload/Services/index.jsx
  src/pages/clusters/containers/Workload/StatefulSets/index.jsx
  src/pages/devops/containers/Pipelines/PipelinesList/index.jsx
  src/pages/devops/containers/Roles/index.jsx
  src/pages/fedprojects/containers/ConfigMaps/index.jsx
  src/pages/fedprojects/containers/Deployments/index.jsx
  src/pages/fedprojects/containers/Routes/index.jsx
  src/pages/fedprojects/containers/Secrets/index.jsx
  src/pages/fedprojects/containers/Services/index.jsx
  src/pages/fedprojects/containers/StatefulSets/index.jsx
  src/pages/fedprojects/containers/Volumes/index.jsx
  src/pages/projects/containers/Alerting/Policies/index.jsx
  src/pages/projects/containers/Applications/OPApps.jsx
  src/pages/projects/containers/ConfigMaps/index.jsx
  src/pages/projects/containers/CronJobs/index.jsx
  src/pages/projects/containers/DaemonSets/index.jsx
  src/pages/projects/containers/Deployments/index.jsx
  src/pages/projects/containers/Jobs/index.jsx
  src/pages/projects/containers/Pods/index.jsx
  src/pages/projects/containers/Roles/index.jsx
  src/pages/projects/containers/Routes/index.jsx
  src/pages/projects/containers/Secrets/index.jsx
  src/pages/projects/containers/ServiceAccounts/index.jsx
  src/pages/projects/containers/Services/index.jsx
  src/pages/projects/containers/StatefulSets/index.jsx
  src/pages/projects/containers/VolumeSnapshots/index.jsx
  src/pages/projects/containers/Volumes/index.jsx
  src/pages/workspaces/containers/DevOps/index.jsx
  src/pages/workspaces/containers/Projects/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/L

#1627 Chore(locales): Update some UI text
  locales/en/app.js
  locales/en/app_repo.js
  locales/en/application.js
  locales/en/base.js
  locales/en/cluster.js
  locales/en/component.js
  locales/en/dashboard.js
  locales/en/devops.js
  locales/en/grayrelease.js
  locales/en/monitoring.js
  locales/en/network.js
  locales/en/notification.js
  locales/en/project.js
  locales/en/service.js
  locales/en/sort_rank.js
  locales/en/workload.js
  locales/en/workspace.js
  locales/es/app.js
  locales/es/cluster.js
  locales/es/grayrelease.js
  locales/es/notification.js
  locales/tc/app.js
  locales/tc/grayrelease.js
  locales/tc/notification.js
  locales/zh/app.js
  locales/zh/application.js
  locales/zh/grayrelease.js
  locales/zh/notification.js
  src/components/Forms/Notification/MailForm/Item.jsx
  src/pages/apps/components/Cards/ReadmeEdit/index.jsx
  src/pages/projects/containers/Applications/Banner.jsx
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/L

#1640 fix: Fix op app description and download package
  .gitignore
  package.json
  scripts/webpack.base.js
  scripts/webpack.e2e.js
  scripts/webpack.prod.js
  src/components/Forms/AppDeploy/BasicInfo/index.jsx
  src/utils/app.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1636 fix: Fix ip pool create
  src/components/Modals/Network/IPPoolsCreate/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1635 fix: Fix total page error
  package.json
  yarn.lock
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1632 Chore(locales): Update some UI text
  locales/en/logging.js
  locales/en/login.js
  locales/en/notification.js
  locales/en/user.js
  locales/es/logging.js
  locales/es/notification.js
  locales/tc/logging.js
  locales/tc/notification.js
  locales/zh/logging.js
  locales/zh/notification.js
  src/components/Forms/Notification/DingTalkForm/index.jsx
  src/components/Forms/Notification/MailForm/Item.jsx
  src/components/Forms/Notification/MailForm/index.jsx
  src/components/Forms/Notification/SlackForm/Item.jsx
  src/components/Forms/Notification/SlackForm/index.jsx
  src/components/Forms/Notification/WeComForm/index.jsx
  src/components/Forms/Notification/WebhookForm/index.jsx
  src/components/Inputs/UrlInput/index.jsx
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/L

#1644 Optimized text in the delete dialog box.
  locales/en/base.js
  src/components/Modals/Delete/index.jsx
  src/components/Modals/Delete/index.scss
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/S

#1648 feat: add kubeconfig desc in the service account
  locales/en/serviceaccounts.js
  locales/es/serviceaccounts.js
  locales/tc/serviceaccounts.js
  locales/zh/serviceaccounts.js
  src/pages/projects/containers/ServiceAccounts/Detail/ServiceAccountDetail/Secret.jsx
  src/pages/projects/containers/ServiceAccounts/Detail/ServiceAccountDetail/index.scss
Labels: approved, dco-signoff: yes, lgtm, size/M

#1646 update: Update alerting level value
  locales/en/alerting.js
  locales/es/alerting.js
  locales/tc/alerting.js
  locales/zh/alerting.js
  scripts/webpack.prod.js
  src/components/Cards/RankTable/NodeTable/index.jsx
  src/configs/alerting/metrics/rule.config.js
  src/pages/apps/components/Modals/AppReview/index.scss
  src/pages/clusters/containers/Monitor/Cluster/Overview/index.scss
  src/pages/projects/containers/Services/Detail/ResourceStatus/index.jsx
  src/utils/form.templates.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#1649 fix: Fix css styles build error
  scripts/webpack.e2e.js
  scripts/webpack.prod.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1626 Update Traditional Chinese translations
  locales/tc/alerting.js
  locales/tc/app.js
  locales/tc/app_template.js
  locales/tc/base.js
  locales/tc/cluster.js
  locales/tc/dashboard.js
  locales/tc/devops.js
  locales/tc/grayrelease.js
  locales/tc/ingress.js
  locales/tc/logging.js
  locales/tc/pipeline.js
  locales/tc/project.js
  locales/tc/role.js
  locales/tc/s2i.js
  locales/tc/service.js
  locales/tc/storage.js
  locales/tc/version.js
  locales/tc/workload.js
  locales/tc/workspace.js
Labels: approved, dco-signoff: yes, lgtm, size/L

#1651 fix: FIx node list can not filter role and add edge node install tip
  locales/en/nodes.js
  locales/es/nodes.js
  locales/tc/nodes.js
  locales/zh/nodes.js
  src/components/Forms/Cluster/EdgeNode/AddNode/index.jsx
  src/components/Forms/Cluster/EdgeNode/AddNode/index.scss
  src/stores/node.js
Labels: approved, dco-signoff: yes, lgtm, size/M

#1659 Removed all exclamation points in UI text.
  src/actions/alerting.js
  src/actions/application.js
  src/actions/cluster.js
  src/actions/configmap.js
  src/actions/custom.monitoring.js
  src/actions/devops.credential.js
  src/actions/devops.js
  src/actions/federated.js
  src/actions/group.js
  src/actions/imagebuilder.js
  src/actions/log.collection.js
  src/actions/member.js
  src/actions/network.js
  src/actions/node.js
  src/actions/openpitrix.js
  src/actions/pipeline.js
  src/actions/project.js
  src/actions/resource.delete.js
  src/actions/resource.edit.js
  src/actions/role.js
  src/actions/router.js
  src/actions/secret.js
  src/actions/service.js
  src/actions/serviceaccount.js
  src/actions/storageclass.js
  src/actions/user.js
  src/actions/volume.js
  src/actions/workload.js
  src/actions/workspace.js
  src/components/Cards/ContainerLog/index.jsx
  src/components/Graph/Detail/PolicyForm/index.jsx
  src/pages/apps/components/Cards/ConfigFile/index.jsx
  src/pages/apps/components/Cards/UploadInfo/index.jsx
  src/pages/apps/components/Lists/VersionList/Item.jsx
  src/pages/apps/components/Lists/VersionList/index.jsx
  src/pages/apps/components/Modals/HelmUpload/index.jsx
  src/pages/clusters/actions/cluster.js
  src/pages/clusters/containers/Storage/StorageClasses/index.jsx
  src/pages/devops/containers/BaseInfo/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Layout/branch.jsx
  src/pages/projects/components/Cards/HPA/index.jsx
  src/pages/projects/containers/GrayRelease/Categories/index.jsx
  src/pages/projects/containers/GrayRelease/Jobs/index.jsx
  src/pages/workspaces/components/Modals/EditGroup/Detail/index.jsx
  src/pages/workspaces/containers/Groups/index.jsx
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/L

#1660 chore: Fix kube design style compile script
  babel.config.js
  locales/en/base.js
  package.json
  src/components/Modals/Delete/index.jsx
  src/core/App.jsx
  src/core/terminal.js
  yarn.lock
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1655 fix: visit the workspace default page when user without permissions
  src/pages/workspaces/containers/Base/List/index.jsx
  src/pages/workspaces/routes/index.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1672 fix: Fix workload quota tip
  package.json
  src/components/Forms/Workload/ContainerSettings/ContainerList/QuotaCheck.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerList/index.jsx
  src/components/Forms/Workload/ContainerSettings/index.jsx
  src/components/Inputs/ResourceLimit/index.jsx
  src/components/Inputs/StringInput/index.jsx
  src/utils/workload.js
  yarn.lock
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1675 fix: Fix ippool max mask length and first cidr error
  src/components/Modals/Network/IPPoolsCreate/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1677 fix: Fix app reupload trigger twice error
  src/pages/apps/components/Cards/UploadInfo/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1678 fix: Fix related template check in authorization edit form
  src/components/Modals/EditAuthorization/CheckItem.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1682 fix: Fix crd resources filters
  src/pages/clusters/containers/CustomResources/Detail/ResourceStatus/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1669 Update Traditional Chinese translations in nodes.js
  locales/tc/nodes.js
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/S

#1661 Reviewed EN UI text on the Accounts page.
  locales/en/login.js
  locales/en/role.js
  locales/en/user.js
  src/components/Inputs/InputPassword/index.jsx
  src/core/containers/PasswordConfirm/index.jsx
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/M

#1681 fix: fix some issue about Bitbucket
  locales/en/devops.js
  locales/es/devops.js
  locales/tc/devops.js
  locales/zh/devops.js
  src/components/Forms/Pipelines/RepoSelect/BitBucketForm/index.jsx
  src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx
  src/components/Forms/Pipelines/RepoSelect/GithubForm/index.scss
  src/pages/devops/containers/Pipelines/PipelinesList/index.jsx
  src/stores/devops/scm.js
  src/utils/constants.js
Labels: approved, area/devops, dco-signoff: yes, lgtm, size/L

#1691 fix: Remove resource limit component debounce
  src/components/Inputs/ResourceLimit/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1690 Reviewed UI text related to workspaces.
  locales/en/base.js
  locales/en/lego.js
  locales/en/storage.js
  locales/en/workload.js
  locales/en/workspace.js
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/L

#1692 Fix some links on the console
  server/config.yaml
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/S

#1695 fix: fix add same key for taints in node
  src/components/Modals/Node/TaintManagement/Batch.jsx
  src/components/Modals/Node/TaintManagement/TaintInput/Item.jsx
  src/components/Modals/Node/TaintManagement/TaintInput/index.jsx
  src/components/Modals/Node/TaintManagement/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/M

#1696 Chore(locales):Update some UI text
  locales/en/app_store.js
  locales/en/application.js
  locales/en/base.js
  locales/en/grayrelease.js
  locales/en/logging.js
  locales/en/monitoring.js
  locales/es/app_store.js
  locales/es/base.js
  locales/es/grayrelease.js
  locales/es/logging.js
  locales/tc/app_store.js
  locales/tc/base.js
  locales/tc/grayrelease.js
  locales/tc/logging.js
  locales/zh/app_store.js
  locales/zh/base.js
  locales/zh/grayrelease.js
  locales/zh/logging.js
  src/components/Modals/AuditingSearch/Auditing/Home/index.jsx
  src/components/Modals/AuditingSearch/Auditing/utils.js
  src/components/Modals/EventSearch/Event/Home/index.jsx
  src/components/Modals/LogSearch/Logging/Home/index.jsx
  src/pages/apps/containers/Home/index.jsx
  src/pages/console/containers/Dashboard/Admin/index.jsx
  src/pages/projects/containers/GrayRelease/Jobs/Item.jsx
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/L

#1699 fix: allow failure while deploying new env
  .github/workflows/deploy-backend.yml
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/XS

#1552 feat: Add meter modal page without the number of deploy
  locales/en/base.js
  locales/en/meter.js
  locales/es/base.js
  locales/es/meter.js
  locales/tc/base.js
  locales/tc/meter.js
  locales/zh/base.js
  locales/zh/meter.js
  src/actions/toolbox.js
  src/components/KubeTools/index.jsx
  src/components/Modals/Bill/Details/Cluster/index.jsx
  src/components/Modals/Bill/Details/Cluster/index.scss
  src/components/Modals/Bill/Details/index.jsx
  src/components/Modals/Bill/Home/index.jsx
  src/components/Modals/Bill/Home/index.scss
  src/components/Modals/Bill/components/BillIcon/index.jsx
  src/components/Modals/Bill/components/BillIcon/index.scss
  src/components/Modals/Bill/components/ConstomPieChart/index.jsx
  src/components/Modals/Bill/components/ConstomPieChart/index.scss
  src/components/Modals/Bill/components/Crumb/index.jsx
  src/components/Modals/Bill/components/Crumb/index.scss
  src/components/Modals/Bill/components/CustomToolTip/index.jsx
  src/components/Modals/Bill/components/CustomToolTip/index.scss
  src/components/Modals/Bill/components/LineChart/MonitorTab/index.jsx
  src/components/Modals/Bill/components/LineChart/MonitorTab/index.scss
  src/components/Modals/Bill/components/LineChart/index.jsx
  src/components/Modals/Bill/components/LineChart/index.scss
  src/components/Modals/Bill/components/MeterDetailCard/index.jsx
  src/components/Modals/Bill/components/MeterDetailCard/index.scss
  src/components/Modals/Bill/components/ResourceSelect/index.jsx
  src/components/Modals/Bill/components/ResourceSelect/index.scss
  src/components/Modals/Bill/components/SideCard/index.jsx
  src/components/Modals/Bill/components/SideCard/index.scss
  src/components/Modals/Bill/components/SideCard/item.jsx
  src/components/Modals/Bill/components/SideCard/item.scss
  src/components/Modals/Bill/components/Tables/index.jsx
  src/components/Modals/Bill/components/Tables/index.scss
  src/components/Modals/Bill/components/TimeSelect/index.jsx
  src/components/Modals/Bill/components/TimeSelect/index.scss
  src/components/Modals/Bill/components/Title/index.jsx
  src/components/Modals/Bill/components/Title/index.scss
  src/components/Modals/Bill/constats.js
  src/components/Modals/Bill/index.jsx
  src/components/Modals/Bill/index.scss
  src/components/Modals/FullscreenModal/index.scss
  src/pages/console/containers/Bill/index.jsx
  src/pages/console/routes/index.js
  src/pages/projects/containers/Deployments/Detail/Monitoring/index.jsx
  src/stores/meter/base.js
  src/stores/meter/cluster.js
  src/stores/openpitrix/application.js
  src/utils/constants.js
  src/utils/meter.js
  src/utils/monitoring.js
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#1705 fix: Fix some issues about meter page
  src/components/Modals/Bill/Details/Cluster/index.jsx
  src/components/Modals/Bill/Details/Cluster/index.scss
  src/components/Modals/Bill/components/Crumb/index.jsx
  src/components/Modals/Bill/components/Crumb/index.scss
  src/components/Modals/Bill/components/MeterDetailCard/index.jsx
  src/components/Modals/Bill/components/MeterDetailCard/index.scss
  src/components/Modals/Bill/components/SideCard/index.jsx
  src/components/Modals/Bill/components/Tables/index.jsx
  src/stores/meter/base.js
  src/stores/meter/cluster.js
  src/utils/meter.js
Labels: approved, dco-signoff: yes, lgtm, size/L

#1709 fix: Set the default status is queued in pipeline status detail
  src/pages/devops/containers/Pipelines/Detail/TaskStatus/index.jsx
Labels: approved, area/devops, dco-signoff: yes, lgtm, size/S

#1706 fix: Fix the card height in monitor-cluster overview
  src/pages/clusters/containers/Monitor/Cluster/Overview/index.jsx
  src/pages/clusters/containers/Monitor/Cluster/Overview/index.scss
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1707 fix: add receiver validate & fix appsecret in dingtalk
  locales/en/notification.js
  locales/es/notification.js
  locales/tc/notification.js
  locales/zh/notification.js
  src/components/Base/List/index.scss
  src/components/Forms/Notification/DingTalkForm/index.jsx
  src/components/Forms/Notification/MailForm/Item.jsx
  src/components/Forms/Notification/MailForm/index.jsx
  src/components/Forms/Notification/SlackForm/Item.jsx
  src/components/Forms/Notification/WeComForm/index.jsx
  src/components/Inputs/BoxInput/index.jsx
  src/components/Inputs/UrlInput/index.jsx
  src/pages/settings/containers/Notification/DingTalk/index.jsx
  src/pages/settings/containers/Notification/WeCom/index.jsx
  src/utils/form.templates.js
Labels: approved, dco-signoff: yes, lgtm, size/L

#1710 Chore(locales): Update some UI text
  locales/en/app.js
  locales/en/application.js
  locales/es/application.js
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/M

#1713 fix: Fix app categories overflow
  src/pages/apps/components/AppList/index.jsx
  src/pages/apps/containers/Home/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/S

#1715 fix: Fix snapshot status
  locales/en/base.js
  locales/en/storage.js
  locales/es/base.js
  locales/es/storage.js
  locales/tc/base.js
  locales/tc/storage.js
  locales/zh/base.js
  locales/zh/storage.js
  src/components/Base/Indicator/index.scss
  src/utils/constants.js
  src/utils/object.mapper.js
Labels: approved, dco-signoff: yes, lgtm, size/S

#1712 fix: Fix batch export bill both application and openpitrix
  src/components/Modals/Bill/components/SideCard/index.jsx
  src/components/Modals/Bill/components/SideCard/item.jsx
  src/stores/meter/base.js
  src/utils/meter.js
Labels: approved, dco-signoff: yes, lgtm, size/L

#1717 fix: Fix pod metrics with namespaced_resources_filter
  src/components/Cards/Pods/index.jsx
  src/stores/monitoring/base.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1711 fix: Disable creating cluster
  src/actions/cluster.js
  src/components/Forms/Cluster/Configuration/index.jsx
  src/components/Forms/Cluster/Title/index.scss
  src/configs/steps/clusters.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1720 feat: Add checkbox to add default stain
  locales/en/nodes.js
  locales/es/nodes.js
  locales/tc/nodes.js
  locales/zh/nodes.js
  src/components/Forms/Cluster/EdgeNode/AddNode/index.jsx
  src/components/Forms/Cluster/EdgeNode/AddNode/index.scss
Labels: approved, dco-signoff: yes, lgtm, size/S

#1722 fix: Fix authorized user list loading state
  src/components/Tables/Base/index.jsx
  src/pages/access/containers/Roles/Detail/AuthorizedUsers/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1716 Chore(locales): Update some UI text
  locales/en/alerting.js
  locales/en/base.js
  locales/en/dashboard.js
  locales/en/ingress.js
  locales/en/logging.js
  locales/en/meter.js
  locales/en/monitoring.js
  locales/en/nodes.js
  locales/en/secret.js
  locales/en/storage.js
  locales/en/workload.js
  locales/es/alerting.js
  locales/es/base.js
  locales/tc/base.js
  locales/zh/base.js
  locales/zh/meter.js
  src/components/Tables/Base/index.jsx
  src/pages/console/containers/Dashboard/Admin/PlatformStatus/index.jsx
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/L

#1721 fix 3.1 api doc link
  server/config.yaml
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/XS

#1724 Fix issue: Not found error appears when querying CR on the CRD page
  src/utils/object.mapper.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1726 chore: Fix delete tip locale
  locales/en/base.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1697 fix: fix the environment variables and bitbucket owner value in pipeline
  src/components/Forms/Pipelines/RepoSelect/BitBucketForm/index.jsx
  src/components/Modals/Pipelines/PipelineEdit/index.jsx
  src/pages/devops/components/Modals/JenkinsEdit/index.jsx
  src/pages/devops/containers/Pipelines/Detail/TaskStatus/index.jsx
  src/stores/devops/pipelines.js
  src/stores/devops/scm.js
Labels: approved, area/devops, dco-signoff: yes, lgtm, size/M

#1719 fix: Fix the start time of the total meter data
  src/components/Modals/Bill/Details/Cluster/index.jsx
  src/components/Modals/Bill/Details/index.jsx
  src/components/Modals/Bill/components/SideCard/index.jsx
  src/stores/meter/base.js
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#1728 Few UI Updates
  locales/en/alerting.js
  locales/en/base.js
  locales/en/devops.js
  locales/en/grayrelease.js
  locales/en/ingress.js
  locales/es/base.js
  locales/tc/base.js
  locales/zh/base.js
  src/components/Forms/Pipelines/ParamsInput/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/S

#1731 fix: fix the color of progress
  src/components/Forms/ImageBuilder/B2IForm/BinaryFileUploader/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1693 Reviewed UI text related to roles and added conditional statements.
  locales/en/base.js
  locales/en/role.js
  src/components/Modals/EditAuthorization/CheckItem.jsx
  src/components/Modals/RoleCreate/index.jsx
  src/components/Modals/RoleDelete/index.jsx
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/L
