Repository kubesphere/console, pull requests merged in 2021-01, with the labels that each got.

#1410 refactor: Refactor ingress rule editor
  package.json
  src/components/Forms/Route/RouteRules/RuleForm/ClusterSelect/index.scss
  src/components/Forms/Route/RouteRules/RuleList/Item.jsx
  src/components/Forms/Route/RouteRules/RuleList/index.jsx
  src/components/Forms/Route/RouteRules/RuleList/index.scss
  src/components/Forms/Route/RouteRules/index.jsx
  src/pages/fedprojects/containers/Applications/Detail/AppIngresses/Ingresses/IngressCard/index.jsx
  src/pages/fedprojects/containers/Routes/Detail/ResourceStatus/Item/index.jsx
  src/pages/projects/components/Cards/Ingresses/Item.jsx
  src/pages/projects/components/Modals/CreateApp/BaseInfo/index.jsx
  src/pages/projects/components/Modals/CreateApp/Routes/RuleForm/ClusterSelect/index.jsx
  src/pages/projects/components/Modals/CreateApp/Routes/RuleForm/ClusterSelect/index.scss
  src/pages/projects/components/Modals/CreateApp/Routes/RuleForm/index.jsx
  src/pages/projects/components/Modals/CreateApp/Routes/RuleList/Item.jsx
  src/pages/projects/components/Modals/CreateApp/Routes/RuleList/index.jsx
  src/pages/projects/components/Modals/CreateApp/Routes/RuleList/index.scss
  src/pages/projects/components/Modals/CreateApp/Routes/index.jsx
  src/pages/projects/components/Modals/CreateApp/Services/index.jsx
  src/pages/projects/components/Modals/CreateApp/Steps/index.jsx
  src/pages/projects/components/Modals/CreateApp/Steps/index.scss
  src/pages/projects/components/Modals/CreateApp/index.jsx
  src/pages/projects/components/Modals/RouteRulesEdit/index.jsx
  src/pages/projects/containers/Routes/Detail/ResourceStatus/Rule.jsx
  src/pages/projects/containers/Routes/Detail/ResourceStatus/index.jsx
  yarn.lock
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/XXL

#1411 fix: Fix missing rule clusters info
  src/components/Forms/Route/RouteRules/RuleList/Item.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1412 feature: add auto deploy
  .github/workflows/deploy-backend-daily.yaml
  .github/workflows/deploy-backend.yml
  .github/workflows/deploy-backend/install.sh
  .github/workflows/deploy-backend/kubesphere.tf
  .github/workflows/deploy-backend/var.tf
  .github/workflows/deploy-pr-close.yml
  .github/workflows/deploy-pr.yml
Labels: approved, dco-signoff: yes, lgtm, size/L

#1377 feat:workspace-group
  server/config.yaml
  src/actions/group.js
  src/assets/add-grey.svg
  src/components/Inputs/ArrayInput/Item.jsx
  src/components/Inputs/ArrayInput/index.jsx
  src/components/Tree/Tree.jsx
  src/components/Tree/TreeNode.jsx
  src/components/Tree/contextTypes.js
  src/components/Tree/index.js
  src/components/Tree/style.scss
  src/components/Tree/treeUtils.js
  src/locales/en/app.js
  src/locales/en/base.js
  src/locales/en/group.js
  src/locales/en/role.js
  src/locales/en/workspace.js
  src/locales/es/app.js
  src/locales/es/base.js
  src/locales/es/group.js
  src/locales/es/role.js
  src/locales/es/workspace.js
  src/locales/tc/app.js
  src/locales/tc/base.js
  src/locales/tc/group.js
  src/locales/tc/role.js
  src/locales/tc/workspace.js
  src/locales/zh/app.js
  src/locales/zh/base.js
  src/locales/zh/group.js
  src/locales/zh/role.js
  src/locales/zh/workspace.js
  src/pages/workspaces/components/Modals/EditGroup/Department/index.jsx
  src/pages/workspaces/components/Modals/EditGroup/Department/index.scss
  src/pages/workspaces/components/Modals/EditGroup/Detail/Card/index.jsx
  src/pages/workspaces/components/Modals/EditGroup/Detail/Card/index.scss
  src/pages/workspaces/components/Modals/EditGroup/Detail/Form/DevopsSelect.jsx
  src/pages/workspaces/components/Modals/EditGroup/Detail/Form/ProjectSelect.jsx
  src/pages/workspaces/components/Modals/EditGroup/Detail/Form/index.jsx
  src/pages/workspaces/components/Modals/EditGroup/Detail/Form/index.scss
  src/pages/workspaces/components/Modals/EditGroup/Detail/index.jsx
  src/pages/workspaces/components/Modals/EditGroup/Detail/index.scss
  src/pages/workspaces/components/Modals/EditGroup/index.jsx
  src/pages/workspaces/components/Modals/EditGroup/index.scss
  src/pages/workspaces/containers/Groups/GroupTree/index.jsx
  src/pages/workspaces/containers/Groups/GroupTree/index.scss
  src/pages/workspaces/containers/Groups/GroupUser/User.jsx
  src/pages/workspaces/containers/Groups/GroupUser/index.jsx
  src/pages/workspaces/containers/Groups/GroupUser/index.scss
  src/pages/workspaces/containers/Groups/index.jsx
  src/pages/workspaces/containers/Groups/index.scss
  src/pages/workspaces/routes/index.js
  src/scss/variables.scss
  src/stores/group.js
  src/stores/user.js
  src/utils/constants.js
  src/utils/form.templates.js
  src/utils/group.js
  src/utils/object.mapper.js
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#1415 fix: Fix secrets link in cluster
  src/pages/clusters/containers/ConfigMaps/index.jsx
  src/pages/clusters/containers/Secrets/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1416 fix: Remove view monitor in application detail
  src/pages/projects/components/Cards/ServiceMonitors/Item.jsx
  src/pages/projects/components/Cards/ServiceMonitors/index.scss
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1417 fix: Fix add component error in application detail
  src/pages/projects/containers/Applications/CRDAppDetail/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1419 refactor: Remove captcha logic
  package.json
  scripts/webpack.server.js
  server/components/boot.js
  server/controllers/session.js
  server/controllers/view.js
  server/routes.js
  server/store/index.js
  src/core/containers/Login/Captcha.jsx
  src/core/containers/Login/index.jsx
  src/core/containers/Login/index.scss
  yarn.lock
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/L

#1420 fix: Fix ippool cluster module
  server/config.yaml
  src/components/Forms/Service/AdvanceSettings/index.jsx
  src/components/Forms/Workload/AdvanceSettings/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#1418 Change Batch Run to Run for consistent reason
  src/actions/pipeline.js
  src/locales/en/pipeline.js
  src/locales/es/pipeline.js
  src/locales/tc/pipeline.js
  src/locales/zh/pipeline.js
  src/pages/devops/containers/Pipelines/PipelinesList/index.jsx
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/M

#1423 fix: Fix app worklaod info
  src/actions/application.js
  src/pages/clusters/containers/Workload/DaemonSets/index.jsx
  src/pages/projects/components/Cards/Services/Item.jsx
  src/pages/projects/components/Cards/Workloads/Item.jsx
  src/pages/projects/components/Cards/Workloads/index.jsx
  src/pages/projects/components/Modals/ServiceMonitor/index.jsx
  src/pages/projects/containers/Services/Detail/ResourceStatus/index.jsx
  src/stores/application/crd.js
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/L

#1424 improvement: set os disk size
  .github/workflows/deploy-backend/kubesphere.tf
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/XS

#1425 feat: Add GitLab server and repo list API
  src/components/Forms/Pipelines/RepoSelect/GitLabForm/index.jsx
  src/stores/devops/scm.js
Labels: approved, dco-signoff: yes, lgtm, size/M

#1429 optimization: Reconnect websocket when the terminal disconnects unexpectedly
  src/components/Terminal/terminal.jsx
  src/utils/socket.client.js
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/M

#1430 feat: Support add route for application
  locales/en/ingress.js
  locales/es/ingress.js
  locales/tc/ingress.js
  locales/zh/application.js
  locales/zh/ingress.js
  package.json
  src/actions/application.js
  src/actions/openpitrix.js
  src/components/Base/Modal/index.scss
  src/components/Base/Modal/index.test.js
  src/components/Base/Modal/modal.jsx
  src/components/Base/Steps/index.jsx
  src/components/Base/Steps/index.scss
  src/components/Base/Text/index.jsx
  src/components/Base/Text/index.scss
  src/components/Clusters/ClusterWrapper/index.scss
  src/components/Forms/Cluster/BaseInfo/index.jsx
  src/components/Forms/CronJob/BaseInfo/index.jsx
  src/components/Forms/Route/RouteRules/RuleForm/index.jsx
  src/components/Forms/Route/RouteRules/index.jsx
  src/components/Forms/Secret/SecretSettings/index.jsx
  src/components/Graph/Detail/index.jsx
  src/components/Inputs/CustomSelect/index.jsx
  src/components/Inputs/CustomSelect/index.scss
  src/components/Inputs/CustomSelect/index.test.js
  src/components/Inputs/RulePath/index.jsx
  src/components/Inputs/SelectInput/index.jsx
  src/components/Inputs/SelectInput/index.scss
  src/components/KubeTools/index.scss
  src/pages/clusters/components/Modals/EditBasicInfo/index.jsx
  src/pages/fedprojects/containers/Applications/Detail/index.jsx
  src/pages/projects/components/Modals/AppEdit/index.jsx
  src/pages/projects/components/Modals/CreateApp/Routes/RuleForm/index.jsx
  src/pages/projects/components/Modals/CreateApp/Routes/RuleList/index.jsx
  src/pages/projects/components/Modals/CreateApp/Routes/index.jsx
  src/pages/projects/components/Modals/CreateApp/Services/index.jsx
  src/pages/projects/components/Modals/CreateApp/Steps/index.scss
  src/pages/projects/components/Modals/CreateApp/index.jsx
  src/pages/projects/components/Modals/CreateAppService/index.jsx
  src/pages/projects/components/Modals/CreateAppService/index.scss
  src/pages/projects/containers/Applications/CRDAppDetail/index.jsx
  src/scss/custom.scss
  yarn.lock
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XL

#1435 fix: Auto-refresh Pipeline running page
  src/components/Forms/Pipelines/AdvanceSettings/index.jsx
  src/components/Forms/Pipelines/AdvanceSettings/index.scss
  src/components/Modals/Pipelines/ScanRepositoryLogs/index.jsx
  src/pages/devops/components/PipelineStatus/card.jsx
  src/pages/devops/components/PipelineStatus/card.scss
  src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Artifacts/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Branch/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Layout/runs.jsx
  src/pages/devops/containers/Pipelines/Detail/PipelineLogDialog/index.jsx
  src/stores/devops/scm.js
Labels: approved, dco-signoff: yes, lgtm, size/L

#1436 chore: Modify the pipeline display and repeated rendering of components
  locales/en/pipeline.js
  locales/es/pipeline.js
  locales/tc/pipeline.js
  locales/zh/pipeline.js
  src/components/Forms/Pipelines/BaseInfo/index.jsx
  src/components/Modals/Pipelines/PipelineEdit/index.jsx
  src/components/Modals/Pipelines/PipelineEdit/index.scss
  src/pages/devops/components/Pipeline/Card/index.jsx
  src/pages/devops/components/Pipeline/Card/index.scss
  src/pages/devops/components/Pipeline/Edges/index.jsx
  src/pages/devops/components/Pipeline/PipelineTemplate/index.jsx
  src/pages/devops/components/Pipeline/Sider/index.jsx
  src/pages/devops/components/Pipeline/StepsEditor/StepCard.jsx
  src/pages/devops/components/Pipeline/StepsEditor/StepContainer.jsx
  src/pages/devops/components/Pipeline/StepsEditor/index.jsx
  src/pages/devops/components/Pipeline/nodesRender.jsx
  src/pages/devops/components/PipelineStatus/card.scss
  src/pages/devops/containers/Pipelines/Detail/PipeLine/index.jsx
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/XL

#1439 feat: The pipeline Log show more Message about error or queued
  src/pages/devops/containers/Pipelines/Detail/PipelineLogDialog/index.jsx
  src/pages/devops/containers/Pipelines/Detail/PipelineLogDialog/logItem.jsx
  src/pages/devops/containers/Pipelines/Detail/TaskStatus/index.jsx
Labels: approved, area/devops, dco-signoff: yes, lgtm, size/M

#1438 fix: Auto-refresh running page of pipeline branch
  locales/en/base.js
  locales/es/base.js
  src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Branch/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Commit/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Layout/branch.jsx
  src/pages/devops/containers/Pipelines/Detail/PullRequest/index.jsx
Labels: approved, area/devops, dco-signoff: yes, lgtm, size/L

#1422 feat: service account
  locales/en/serviceaccounts.js
  locales/es/serviceaccounts.js
  locales/tc/serviceaccounts.js
  locales/zh/serviceaccounts.js
  server/config.yaml
  src/actions/serviceaccount.js
  src/components/Forms/ServiceAccount/BaseInfo/index.jsx
  src/components/Forms/ServiceAccount/BaseInfo/index.scss
  src/components/Inputs/RoleSelect/index.jsx
  src/components/Inputs/RoleSelect/index.scss
  src/components/Inputs/index.js
  src/components/Modals/EditServiceAccount/index.jsx
  src/components/Modals/EditServiceAccount/index.scss
  src/components/Modals/ModifyServiceAccountRole/index.jsx
  src/components/Modals/ModifyServiceAccountRole/index.scss
  src/configs/steps/serviceaccounts.js
  src/pages/clusters/containers/ServiceAccounts/index.jsx
  src/pages/clusters/routes/detail.js
  src/pages/clusters/routes/index.js
  src/pages/projects/containers/ServiceAccounts/Detail/ServiceAccountDetail/Secret.jsx
  src/pages/projects/containers/ServiceAccounts/Detail/ServiceAccountDetail/index.jsx
  src/pages/projects/containers/ServiceAccounts/Detail/ServiceAccountDetail/index.scss
  src/pages/projects/containers/ServiceAccounts/Detail/index.jsx
  src/pages/projects/containers/ServiceAccounts/Detail/routes.js
  src/pages/projects/containers/ServiceAccounts/index.jsx
  src/pages/projects/routes/detail.js
  src/pages/projects/routes/index.js
  src/stores/serviceAccount.js
  src/utils/constants.js
  src/utils/form.templates.js
  src/utils/object.mapper.js
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#1441 Delete Chinese guillemets
  src/pages/apps/components/Modals/AppCreate/index.jsx
  src/pages/apps/components/Modals/HelmUpload/index.jsx
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/XS

#1442 fix: Fix topology error link
  src/pages/projects/containers/Services/Topology/Detail/Childrens/index.jsx
  src/pages/projects/containers/Services/Topology/Detail/Table/index.scss
  src/pages/projects/containers/Services/Topology/Detail/index.jsx
  src/pages/projects/containers/Services/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#1443 fix: Fix hpa memory metric value
  src/pages/projects/components/Cards/HPA/index.jsx
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#1451 Update Traditional Chinese translations
  locales/tc/application.js
  locales/tc/cluster.js
Labels: approved, dco-signoff: yes, lgtm, size/L

#1448 fix: fixup dirbranch error and improve display name
  src/components/Forms/Pipelines/ParamsFormModal/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/S

#1454 Update Traditional Chinese translations
  locales/tc/login.js
Labels: approved, dco-signoff: yes, lgtm, size/M

#1447 chore: Add Multi-Branch does not support batch operation
  locales/en/pipeline.js
  locales/es/pipeline.js
  locales/tc/pipeline.js
  locales/zh/pipeline.js
  src/components/Forms/Pipelines/RepoSelect/GitLabForm/index.jsx
  src/pages/devops/containers/Pipelines/PipelinesList/index.jsx
Labels: approved, dco-signoff: yes, lgtm, size/M

#1456 Update Traditional Chinese translations
  locales/tc/service.monitor.js
Labels: approved, dco-signoff: yes, lgtm, size/S
