Repository kubesphere/console, pull requests merged in 2022-11, with the labels that each got.

#3922 docs: Update UI text
  locales/en/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
Labels: lgtm, approved, kind/documentation, release-note-none

#3927 docs: Update UI text of cluster management
  locales/en/l10n-clusterManagement-clusters.js
  locales/en/l10n-clusterManagement-overview.js
  src/pages/clusters/components/StatusReason/index.jsx
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#3931 docs: Update UI text
  locales/en/l10n-clusterManagement-monitoring&Alerting-clusterStatus.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3938 docs: Update UI text
  locales/en/l10n-clusterManagement-clusters.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3943 docs: Update UI text
  locales/ar/l10n-clusterManagement-monitoring&Alerting-applicationResources.js
Labels: lgtm, approved

#3945 docs: Update UI text of rule groups
  locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
  src/configs/alerting/metrics/node.js
  src/configs/alerting/metrics/pod.js
  src/configs/alerting/metrics/workload.js
Labels: lgtm, approved, size/M, kind/documentation, release-note-none

#3948 docs: Update UI text
  locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3951 docs: Update UI text of rule groups
  locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
  src/configs/alerting/metrics/node.js
Labels: lgtm, approved, release-note-none, release-notes-none

#3953 docs: Update UI text of rule groups
  locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3955 docs: Update UI text of rule groups
  locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3957 docs: Update UI text of rule groups
  locales/en/l10n-clusterManagement-monitoring&Alerting-alertingMessages.js
  locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-details.js
  locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
  src/components/Forms/AlertingPolicy/BaseInfo/index.jsx
  src/pages/projects/containers/Alerting/Messages/index.jsx
  src/pages/projects/containers/Alerting/Policies/Detail/AlertMessages/index.jsx
  src/pages/projects/containers/Alerting/Policies/Detail/AlertRules/RuleItem.jsx
  src/pages/projects/containers/Alerting/Policies/Detail/index.jsx
  src/pages/projects/containers/Alerting/Policies/index.jsx
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#3960 docs: Update UI text of rule groups
  locales/ar/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3962 docs: Update UI text
  locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
Labels: size/XS, approved, kind/documentation, release-note-none

#3965 docs: Update UI text of rule groups
  locales/en/l10n-toolbox-auditLogSearch-details.js
Labels: size/XS, approved, kind/documentation, release-note-none

#3969 docs: Update UI text of FeiShu
  locales/en/l10n-platformSettings-notificationManagement-notificationChannels.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3971 docs: Update UI text of notification management
  locales/en/l10n-platformSettings-notificationManagement-notificationChannels.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3973 docs: Update UI text of notification management
  locales/en/l10n-platformSettings-notificationManagement-notificationChannels.js
Labels: lgtm, approved, kind/documentation, release-note-none

#3978 docs: Update UI text
  src/components/Forms/Cluster/BaseInfo/index.jsx
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3980 docs: Update UI text
  locales/en/l10n-appStore-details.js
  src/components/Forms/AppDeploy/BasicInfo/index.jsx
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3984 docs: Update UI text
  locales/en/idleComponents.js
  locales/en/l10n-accessControl-workspaces-list.js
  locales/en/l10n-clusterManagement-monitoring&Alerting-customMonitoring.js
  locales/en/l10n-clusterManagement-overview.js
  locales/en/l10n-clusterManagement-storage-storageClasses-list.js
  locales/en/l10n-projects-applicationWorkloads-apps-composedApps-list.js
  locales/en/l10n-projects-grayscaleRelease.js
  src/actions/application.js
  src/components/Cards/Containers/Item.jsx
  src/components/Cards/Volumes/Item.jsx
  src/components/Forms/Cluster/AdvanceSettings/index.jsx
  src/components/Forms/Cluster/BaseInfo/index.jsx
  src/components/Forms/Cluster/ClusterSettings/KubernetesParams/index.jsx
  src/components/Forms/Cluster/ClusterSettings/NetworkParams/index.jsx
  src/components/Forms/Cluster/ClusterSettings/index.jsx
  src/components/Forms/Cluster/NodeList/index.jsx
  src/components/Forms/Cluster/Providers/index.jsx
  src/components/Forms/Notification/FeiShuForm/index.jsx
  src/components/Forms/Service/BaseInfo/index.jsx
  src/components/Modals/CustomMonitoring/components/TitleInput/index.jsx
  src/pages/clusters/components/Cards/Monitoring/ETCDNodes/item.jsx
  src/pages/clusters/containers/Gateway/Components/Pods/index.jsx
  src/pages/clusters/containers/KubeConfig/index.jsx
  src/pages/clusters/containers/Monitor/Cluster/Overview/index.jsx
  src/pages/clusters/containers/Overview/Dashboard/KubernetesStatus/index.jsx
  src/pages/console/components/Cards/Workspace/index.jsx
  src/pages/console/containers/ContainerTerminal/index.jsx
  src/pages/devops/components/Modals/JenkinsEdit/index.jsx
  src/pages/projects/components/Cards/ContainerTemplate/Item.jsx
  src/pages/projects/components/Cards/Lifecycle/index.jsx
  src/pages/projects/components/Modals/KubeConfig/index.jsx
  src/pages/projects/components/Modals/ModifyMember/index.jsx
  src/pages/projects/components/Modals/TracingDetail/SpanDetail/index.jsx
  src/pages/projects/components/Modals/TracingDetail/SpanGraph/TimeRange.jsx
  src/pages/projects/containers/Pods/Detail/ScheduleInfo/index.jsx
  src/pages/projects/containers/Services/Detail/Ports/index.jsx
  src/pages/settings/components/Modals/GithubOAuth/index.jsx
  src/pages/settings/components/Modals/OAuth/index.jsx
  src/pages/settings/containers/ThirdPartyLogin/index.jsx
  src/pages/workspaces/components/Modals/EditGroup/Detail/Card/index.jsx
  src/pages/workspaces/components/Modals/WorkspaceCreate/BaseInfo/index.jsx
Labels: size/L, lgtm, approved, kind/documentation, release-note-none

#3987 docs: Update UI text
  locales/en/l10n-clusterManagement-nodes-clusterNodes-list.js
  locales/en/l10n-logIn.js
  src/actions/toolbox.js
  src/core/index.js
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#3990 feat: change helm valuesFiles Input component to ArrayInput
  src/actions/fluxcd.js
  src/components/Forms/CD/FluxCD/Advance/index.jsx
Labels: lgtm, approved, size/S, area/devops, kind/feature, ok-to-test, release-note-none

#3986 fix: Change Default GitOpsEngine from fluxcd to argocd
  server/services/session.js
Labels: size/XS, lgtm, approved, area/devops, ok-to-test, release-note-none

#3996 docs: Update UI text
  locales/en/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3991 feat: change helm values Input component to ArrayInput and ObjectInput
  src/actions/fluxcd.js
  src/components/Forms/CD/FluxCD/Advance/index.jsx
Labels: lgtm, approved, size/M, area/devops, kind/feature, ok-to-test, release-note-none

#3982 fix: npm start command failed to run on window
  package.json
Labels: size/XS, lgtm, approved, kind/bug, ok-to-test, release-note-none

#3992 feat: Add helm valuesFrom
  src/actions/fluxcd.js
  src/components/Forms/CD/FluxCD/Advance/index.jsx
Labels: size/L, lgtm, approved, area/devops, kind/feature, ok-to-test, release-note-none

#3993 chore: Add Crowdin UI string for FluxCD App
  locales/en/l10n-devopsProjects-continuousDeployments-list.js
  src/components/Forms/CD/FluxCD/Advance/index.jsx
Labels: lgtm, approved, size/S, area/devops, ok-to-test, release-note-none

#4000 docs: Update UI text of cluster removal
  locales/en/l10n-clusterManagement-clusters.js
  src/components/Forms/Notification/BaseForm/ConditionSelect/index.jsx
Labels: lgtm, approved, kind/documentation, release-note-none

#4002 docs: Update UI text
  locales/en/l10n-clusterManagement-clusters.js
Labels: lgtm, approved, kind/documentation, release-note-none

#4003 docs: Update UI text
  locales/en/l10n-platformSettings-notificationManagement-notificationChannels.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none
