Repository kubesphere/console, pull requests merged in 2022-09, with the labels that each got.

#3639 fix: Update openelb style
  src/pages/projects/components/Modals/ServiceGatewaySetting/index.scss
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3644 docs: Update UI text
  locales/ar/monitoring.js
  locales/ar/role.js
  locales/ar/storage.js
  locales/ar/workload.js
  locales/en/l10n-clusterManagement-applicationWorkloads-deployments-list.js
  locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
  locales/en/l10n-clusterManagement-projects-list.js
  locales/en/l10n-projects-projectSettings-basicInformation.js
  locales/en/l10n-workspaces-workspaceSettings-workspaceMembers-list.js
  locales/en/monitoring.js
  locales/en/role.js
  locales/en/storage.js
  locales/en/workload.js
  locales/es/monitoring.js
  locales/es/role.js
  locales/es/storage.js
  locales/es/workload.js
  locales/fr/monitoring.js
  locales/fr/role.js
  locales/fr/storage.js
  locales/fr/workload.js
  locales/hi/monitoring.js
  locales/hi/role.js
  locales/hi/storage.js
  locales/hi/workload.js
  locales/ko/monitoring.js
  locales/ko/role.js
  locales/ko/storage.js
  locales/ko/workload.js
  locales/lt/monitoring.js
  locales/lt/role.js
  locales/lt/storage.js
  locales/lt/workload.js
  locales/pl/monitoring.js
  locales/pl/role.js
  locales/pl/storage.js
  locales/pl/workload.js
  locales/tc/monitoring.js
  locales/tc/role.js
  locales/tc/storage.js
  locales/tc/workload.js
  locales/tr/monitoring.js
  locales/tr/role.js
  locales/tr/storage.js
  locales/tr/workload.js
  locales/zh/monitoring.js
  locales/zh/role.js
  locales/zh/storage.js
  locales/zh/workload.js
  src/actions/member.js
  src/components/Forms/Workload/VolumeSettings/MountConfig/index.jsx
  src/components/Modals/ProjectCreate/index.jsx
Labels: lgtm, approved, size/M, kind/documentation, release-note-none

#3652 docs: Remove redundant locale entries
  locales/ar/base.js
  locales/ar/configmap.js
  locales/ar/crd.js
  locales/ar/ingress.js
  locales/en/base.js
  locales/en/configmap.js
  locales/en/crd.js
  locales/en/ingress.js
  locales/en/l10n-clusterManagement-applicationWorkloads-deployments-list.js
  locales/en/l10n-clusterManagement-crds-details.js
  locales/en/l10n-clusterManagement-crds-list.js
  locales/en/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
  locales/en/secret.js
  locales/es/configmap.js
  locales/es/crd.js
  locales/es/ingress.js
  locales/fr/base.js
  locales/fr/configmap.js
  locales/fr/crd.js
  locales/fr/ingress.js
  locales/hi/base.js
  locales/hi/configmap.js
  locales/hi/crd.js
  locales/hi/ingress.js
  locales/ko/base.js
  locales/ko/configmap.js
  locales/ko/crd.js
  locales/ko/ingress.js
  locales/lt/base.js
  locales/lt/configmap.js
  locales/lt/crd.js
  locales/lt/ingress.js
  locales/pl/base.js
  locales/pl/configmap.js
  locales/pl/crd.js
  locales/pl/ingress.js
  locales/tc/configmap.js
  locales/tc/crd.js
  locales/tc/ingress.js
  locales/tr/base.js
  locales/tr/configmap.js
  locales/tr/crd.js
  locales/tr/ingress.js
  locales/zh/configmap.js
  locales/zh/crd.js
  locales/zh/ingress.js
  locales/zh/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
  src/components/Forms/AlertingPolicy/NotificationRule/index.jsx
  src/components/Inputs/EnvironmentInput/index.jsx
  src/components/Tables/Base/index.jsx
  src/pages/clusters/containers/Gateway/Detail/GatewayLog/index.jsx
  src/pages/projects/containers/Alerting/Policies/index.jsx
Labels: lgtm, approved, size/XXL, kind/documentation, release-note-none

#3660 fix: The list ofconfigmap is not displayed correctly
  src/pages/clusters/containers/ConfigMaps/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3659 fix: There is a delete button for project management permissions to view the details of grayscale publishing tasks
  src/pages/projects/components/Modals/GrayReleaseDetail/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3509 refactor: Reuse the git repository selector on the Pipeline and CD page
  locales/en/l10n-devopsProjects-pipeline-details.js
  locales/en/l10n-devopsProjects-pipeline-list.js
  src/actions/codeRepo.js
  src/actions/pipeline.js
  src/components/CodeRepoSelector/index.jsx
  src/components/CodeRepoSelector/index.scss
  src/components/Forms/CD/BaseInfo/index.jsx
  src/components/Forms/Pipelines/BaseInfo/index.jsx
  src/components/Forms/Pipelines/BaseInfo/index.scss
  src/components/Forms/Pipelines/RepoSelect/GitLabForm/index.jsx
  src/components/Forms/Pipelines/RepoSelect/subForm.jsx
  src/components/Modals/CodeRepoCreate/index.jsx
  src/components/Modals/Create/Form/index.jsx
  src/pages/devops/containers/CodeRepo/CRList/index.jsx
  src/pages/devops/containers/Pipelines/PipelinesList/index.jsx
  src/stores/devops/scm.js
  src/utils/devops.js
Labels: lgtm, approved, size/XL, area/console, area/devops, kind/feature, release-note-none

#3672 feat: Update the unbundling cluster confirmation box
  locales/en/l10n-clusterManagement-clusters.js
  src/actions/cluster.js
  src/assets/ksLogo.svg
  src/assets/unbindCluster.svg
  src/pages/clusters/components/Modals/UnbindCluster/SliderConfirm/index.jsx
  src/pages/clusters/components/Modals/UnbindCluster/SliderConfirm/index.scss
  src/pages/clusters/components/Modals/UnbindCluster/index.jsx
  src/pages/clusters/components/Modals/UnbindCluster/index.scss
Labels: lgtm, approved, size/XL, kind/feature, release-note-none, kind/require-ui-text-review

#3675 docs: Remove redundant locale entries
  locales/en/idle-components.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3678 fix: An error is displayed after deleting the container
  src/components/Forms/Workload/ContainerSettings/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3680 fix: Statefulsets and daemonsets do not show rveision record in app d…
  src/pages/projects/components/Cards/Workloads/Item.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3681 docs: Update UI text
  locales/en/l10n-clusterManagement-applicationWorkloads-deployments-details.js
  locales/en/l10n-clusterManagement-clusterSettings-basicInformation.js
  locales/en/l10n-clusterManagement-clusters.js
  locales/en/l10n-projects-grayscaleRelease.js
  locales/en/l10n-workspaces-workspaceSettings-basicInformation.js
  src/actions/cluster.js
  src/components/Modals/Delete/index.jsx
  src/pages/access/containers/Accounts/index.jsx
  src/pages/clusters/components/Modals/UnbindCluster/index.jsx
  src/pages/clusters/containers/BaseInfo/index.jsx
  src/pages/clusters/containers/Clusters/index.jsx
Labels: lgtm, approved, size/M, kind/documentation, release-note-none

#3682 fix: Update PatchWorkspaceTemplate PatchType to JsonPathType
  src/pages/clusters/actions/cluster.js
Labels: lgtm, approved, size/M, release-note-none

#3689 fix: Update workspaceapi params
  src/pages/clusters/actions/cluster.js
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3691 docs: Update UI text of platform roles
  locales/en/l10n-accessControl-platformRoles-list.js
  locales/en/l10n-clusterManagement-overview.js
  locales/en/l10n-workspaces-workspaceSettings-workspaceRoles-list.js
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#3688 fix: misbehaving when editing the same name service
  src/components/Forms/Service/BaseInfo/index.jsx
  src/pages/projects/components/Modals/CreateApp/Services/index.jsx
  src/pages/projects/components/Modals/CreateAppService/index.jsx
Labels: lgtm, approved, size/S, kind/bug, kind/feature, ok-to-test, release-note

#3697 docs: Update UI text of notification settings
  locales/en/l10n-platformSettings-notificationManagement-notificationChannels.js
  locales/en/pipeline.js
  server/config.yaml
  src/components/Forms/Notification/BaseForm/ConditionSelect/index.jsx
  src/components/Forms/Notification/DingTalkForm/index.jsx
  src/components/Forms/Notification/FeiShuForm/index.jsx
  src/pages/settings/components/Cards/Banner/index.jsx
Labels: lgtm, approved, size/M, kind/documentation, release-note-none

#3665 fix: Optimize the description of the application.
  src/components/Forms/Service/AdvanceSettings/index.jsx
  src/components/Forms/Service/BaseInfo/index.jsx
  src/components/Forms/Workload/ContainerSettings/index.jsx
  src/pages/projects/containers/Services/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3698 fix: Update workspaceapi params structure
  src/pages/clusters/actions/cluster.js
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#3704 docs: Cherry pick commit 87904dc5698c0c251aaf2808ece4bde4d15c3b5c to release-3.3
  locales/en/l10n-platformSettings-notificationManagement-notificationChannels.js
  locales/en/pipeline.js
  server/config.yaml
  src/components/Forms/Notification/BaseForm/ConditionSelect/index.jsx
  src/components/Forms/Notification/DingTalkForm/index.jsx
  src/pages/settings/components/Cards/Banner/index.jsx
Labels: lgtm, approved, size/M, kind/documentation, release-note-none

#3703 docs: Update UI text of notification channels
  locales/ar/l10n-platformSettings-notificationManagement-notificationConfiguration.js
  locales/en/l10n-platformSettings-notificationManagement-notificationChannels.js
  locales/en/l10n-workspaces-devopsProjects-list.js
  locales/es/l10n-platformSettings-notificationManagement-notificationConfiguration.js
  locales/fr/l10n-platformSettings-notificationManagement-notificationConfiguration.js
  locales/hi/l10n-platformSettings-notificationManagement-notificationConfiguration.js
  locales/ko/l10n-platformSettings-notificationManagement-notificationConfiguration.js
  locales/lt/l10n-platformSettings-notificationManagement-notificationConfiguration.js
  locales/pl/l10n-platformSettings-notificationManagement-notificationConfiguration.js
  locales/tc/l10n-platformSettings-notificationManagement-notificationConfiguration.js
  locales/tr/l10n-platformSettings-notificationManagement-notificationConfiguration.js
  locales/zh/l10n-platformSettings-notificationManagement-notificationConfiguration.js
  src/components/Forms/Notification/DingTalkForm/KeyWords.jsx
  src/components/Forms/Notification/DingTalkForm/index.jsx
  src/components/Forms/Notification/FeiShuForm/index.jsx
  src/components/Forms/Notification/SlackForm/Item.jsx
  src/components/Forms/Notification/SlackForm/index.jsx
  src/components/Forms/Notification/WeComForm/Item.jsx
  src/components/Forms/Notification/WeComForm/index.jsx
  src/components/Forms/Notification/WebhookForm/index.jsx
  src/pages/settings/containers/Notification/DingTalk/index.jsx
  src/pages/settings/containers/Notification/FeiShu/index.jsx
Labels: lgtm, approved, size/XXL, kind/documentation, release-note-none

#3708 docs: Remove redundant locale entries
  locales/ar/pipeline.js
  locales/es/pipeline.js
  locales/fr/pipeline.js
  locales/hi/pipeline.js
  locales/ko/pipeline.js
  locales/lt/pipeline.js
  locales/pl/pipeline.js
  locales/tc/pipeline.js
  locales/tr/pipeline.js
  locales/zh/pipeline.js
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#3712 docs: Update UI text of notification channels
  locales/en/l10n-appStoreManagement-apps-details.js
  locales/en/l10n-platformSettings-notificationManagement-notificationChannels.js
  src/components/Forms/Notification/BaseForm/index.jsx
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3711 fix: Update workspace api params structure
  src/pages/clusters/actions/cluster.js
Labels: size/XS, lgtm, approved, kind/api-change, release-note-none

#3715 Update UI text of notification channels
  locales/en/l10n-platformSettings-notificationManagement-notificationChannels.js
  src/pages/apps/containers/StoreManage/index.jsx
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3719 docs: Cherry pick locale files from master
  locales/ar/l10n-appStoreManagement-apps-details.js
  locales/ar/l10n-platformSettings-notificationManagement-notificationChannels.js
  locales/es/l10n-appStoreManagement-apps-details.js
  locales/es/l10n-platformSettings-notificationManagement-notificationChannels.js
  locales/fr/l10n-appStoreManagement-apps-details.js
  locales/fr/l10n-platformSettings-notificationManagement-notificationChannels.js
  locales/hi/l10n-appStoreManagement-apps-details.js
  locales/hi/l10n-platformSettings-notificationManagement-notificationChannels.js
  locales/ko/l10n-appStoreManagement-apps-details.js
  locales/ko/l10n-platformSettings-notificationManagement-notificationChannels.js
  locales/lt/l10n-appStoreManagement-apps-details.js
  locales/lt/l10n-platformSettings-notificationManagement-notificationChannels.js
  locales/pl/l10n-appStoreManagement-apps-details.js
  locales/pl/l10n-platformSettings-notificationManagement-notificationChannels.js
  locales/tc/l10n-appStoreManagement-apps-details.js
  locales/tc/l10n-platformSettings-notificationManagement-notificationChannels.js
  locales/tr/l10n-appStoreManagement-apps-details.js
  locales/tr/l10n-platformSettings-notificationManagement-notificationChannels.js
  locales/zh/l10n-appStoreManagement-apps-details.js
  locales/zh/l10n-platformSettings-notificationManagement-notificationChannels.js
  locales/zh/l10n-workspaces-devopsProjects-list.js
Labels: size/L, lgtm, approved, kind/documentation, release-note-none

#3723 docs: Cherry pick locale files from master.
  locales/zh/l10n-platformSettings-notificationManagement-notificationChannels.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3724 docs: Update UI text of access control
  locales/ar/l10n-accessControl-platformRoles-list.js
  locales/en/l10n-accessControl-platformRoles-list.js
  locales/es/l10n-accessControl-platformRoles-list.js
  locales/fr/l10n-accessControl-platformRoles-list.js
  locales/hi/l10n-accessControl-platformRoles-list.js
  locales/ko/l10n-accessControl-platformRoles-list.js
  locales/lt/l10n-accessControl-platformRoles-list.js
  locales/pl/l10n-accessControl-platformRoles-list.js
  locales/tc/l10n-accessControl-platformRoles-list.js
  locales/tr/l10n-accessControl-platformRoles-list.js
  locales/zh/l10n-accessControl-platformRoles-list.js
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#3730 fix: Create service error
  src/components/Forms/Service/BaseInfo/index.jsx
  src/components/Forms/Workload/ContainerSettings/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3734 fix: Role 'platform-regular' should not access cluster manager
  server/services/session.js
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3739 docs: Fix UI text bugs
  locales/en/idle-components.js
  locales/en/l10n-clusterManagement-clusterSettings-clusterRoles-list.js
  locales/en/l10n-clusterManagement-overview.js
  locales/en/l10n-devopsProjects-devopsProjectSettings-devopsProjectRoles-list.js
  locales/en/l10n-devopsProjects-pipeline-list.js
  locales/en/l10n-projects-projectSettings-projectRoles-list.js
  locales/en/l10n-toobox-auditLogSearch-list.js
  locales/en/l10n-toobox-containerLogSearch-list.js
  locales/en/l10n-toobox-resourceEventSearch-list.js
  locales/en/l10n-workspaces-workspaceSettings-workspaceMembers-list.js
  locales/en/l10n-workspaces-workspaceSettings-workspaceRoles-list.js
  server/config.yaml
  src/components/Forms/Route/RouteRules/RuleForm/index.jsx
  src/components/Modals/AuditingSearch/Auditing/Home/index.jsx
  src/components/Modals/EventSearch/Event/Home/index.jsx
  src/components/Modals/LogSearch/Logging/Home/index.jsx
  src/pages/clusters/components/Modals/UnbindCluster/index.jsx
  src/pages/devops/containers/CodeRepo/CRList/index.jsx
  src/pages/projects/components/Modals/CreateApp/Routes/RuleForm/index.jsx
  src/pages/projects/components/WorkloadStatus/index.jsx
  src/pages/workspaces/containers/DevOps/index.jsx
Labels: lgtm, approved, size/M, kind/documentation, release-note-none

#3744 docs: Update UI text of workloads
  locales/en/l10n-clusterManagement-applicationWorkloads-deployments-list.js
  locales/en/l10n-clusterManagement-monitoring&Alerting-applicationResources.js
  locales/en/l10n-projects-applicationWorkloads-daemonsets-list.js
  src/pages/clusters/containers/Workload/DaemonSets/index.jsx
  src/pages/clusters/containers/Workload/Deployments/index.jsx
  src/pages/clusters/containers/Workload/StatefulSets/index.jsx
  src/pages/fedprojects/containers/Deployments/index.jsx
  src/pages/fedprojects/containers/StatefulSets/index.jsx
  src/pages/projects/containers/DaemonSets/index.jsx
  src/pages/projects/containers/Deployments/index.jsx
  src/pages/projects/containers/StatefulSets/index.jsx
Labels: lgtm, approved, size/M, kind/documentation, release-note-none

#3740 fix: Proxy connected clusters should not have an update kubeconfig button
  src/components/Base/List/index.scss
  src/pages/clusters/containers/BaseInfo/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3750 docs: Fix UI text bugs
  locales/en/l10n-clusterManagement-clusterSettings-gatewaySettings-details.js
  locales/en/l10n-projects-applicationWorkloads-apps-composedApps-details.js
  src/pages/projects/components/Cards/Replica/index.jsx
  src/pages/projects/components/Cards/Workloads/Item.jsx
  src/pages/projects/containers/Applications/CRDApps.jsx
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#3759 fix: Update notification api version
  src/pages/settings/components/Cards/Banner/index.jsx
  src/stores/notification/base.js
Labels: size/XS, lgtm, approved, release-note-none

#3752 fix: Add app label
  src/components/Forms/Service/BaseInfo/index.jsx
  src/components/Forms/Workload/ContainerSettings/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3760 fix: Update api version
  src/stores/cluster/index.js
Labels: size/XS, lgtm, approved, release-note-none

#3764 fix: Role 'platform-self-provisioner' should not be edited.
  server/config.yaml
Labels: size/XS, lgtm, approved, release-note-none

#3766 fix: Display app name
  src/pages/projects/containers/Services/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3767 fix: Delete config field
  server/config.yaml
Labels: size/XS, lgtm, approved, release-note-none

#3738 fix: fix lastValue return err in workspace overview page
  src/components/Charts/Area/MediumArea/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, ok-to-test, release-note-none

#3757 fix: fix save secret value err when value is chinese
  src/actions/cluster.js
  src/components/Forms/Secret/SecretSettings/DataForm/index.jsx
Labels: size/XS, lgtm, approved, ok-to-test, release-note

#3772 chore: Update the kube-design version
  package.json
  src/components/Forms/KafkaForm/Settings/index.jsx
  yarn.lock
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3778 fix: In a multi-cluster environment, users without cluster permission…
  src/components/Forms/CD/Advance/Placement/index.jsx
  src/stores/cd.js
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3780 docs: Update UI text
  locales/en/idleComponents.js
  locales/en/l10n-clusterManagement-applicationWorkloads-services-list.js
  locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
  locales/en/l10n-clusterManagement-monitoring&Alerting-clusterStatus.js
  src/pages/clusters/containers/Nodes/Detail/Monitoring/index.jsx
  src/pages/clusters/containers/Workload/Services/index.jsx
  src/pages/projects/containers/Services/index.jsx
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#3768 fix: Show '-' when duration is negative
  src/pages/devops/containers/Pipelines/Detail/PipelineLogDialog/logItem.jsx
Labels: size/XS, lgtm, approved, area/devops, kind/bug, ok-to-test, release-note-none

#3787 docs: Update UI text of access control
  locales/en/l10n-accessControl-platformRoles-list.js
  locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-details.js
  locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
  src/components/Forms/AlertingPolicy/BaseInfo/index.jsx
  src/pages/projects/containers/Alerting/Messages/index.jsx
  src/pages/projects/containers/Alerting/Policies/Detail/index.jsx
  src/pages/projects/containers/Alerting/Policies/index.jsx
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#3785 fix: User can't click permissions field when editing workspace role
  src/components/Modals/EditAuthorization/CheckItem.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3792 fix: Update workspace update structure
  src/actions/resource.edit.js
  src/pages/workspaces/containers/BaseInfo/index.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#3794 fix: Fix the service address in log collection form
  locales/en/l10n-clusterManagement-clusterSettings-logReceivers-list.js
  src/components/Forms/KafkaForm/Settings/BrokersInput/index.jsx
  src/components/Forms/KafkaForm/Settings/index.jsx
  src/components/Modals/LogCollectionCreate/index.jsx
Labels: lgtm, approved, kind/bug, release-note-none, kind/require-ui-text-review

#3795 fix: Workspace shows error in resource consumption statistics.
  locales/en/l10n-toobox-resourceConsumptionStatistics-workspaceResourceConsumption.js
  src/components/Modals/Bill/components/SideCard/item.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3796 fix: Pods status display is incorrect
  src/utils/status.js
Labels: lgtm, approved, size/S, kind/bug, release-note-none
