Repository kubesphere/console, pull requests merged in 2022-06, with the labels that each got.

#3332 Update UI text of 'App Templates'
  locales/en/l10n-workspaces-appManagement-appRepositories-list.js
  locales/en/l10n-workspaces-appManagement-appTemplates-details.js
  locales/pl/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
  locales/pl/l10n-workspaces-appManagement-appRepositories-list.js
  src/pages/apps/components/Forms/AppBaseEdit/index.jsx
  src/pages/workspaces/containers/Repos/index.jsx
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#3338 fix: In member clusters below v3.3.0, some functions should be disabled and prompt to upgrade
  server/config.yaml
  src/pages/clusters/containers/Storage/StorageClasses/Detail/index.jsx
  src/pages/clusters/containers/Storage/VolumeSnapshots/Snapshots/index.jsx
  src/pages/projects/containers/Volumes/Detail/index.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#3343 fix: Optimize the UI
  package.json
  src/pages/clusters/containers/Storage/VolumeSnapshotClasses/Detail/VolumeSnapshot/index.jsx
  src/pages/clusters/containers/Storage/VolumeSnapshotClasses/Detail/VolumeSnapshot/index.scss
  src/pages/devops/containers/CD/CDList/index.jsx
  yarn.lock
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#3346 fix: Service Account can not use in member-cluster
  src/core/global.js
  src/pages/clusters/containers/Base/List/index.jsx
  src/pages/clusters/containers/layout.jsx
  src/stores/cluster/index.js
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#3345 fix: Remove the limit of cpu use in hpa
  src/pages/projects/components/Modals/HPA/index.jsx
  src/pages/projects/containers/Services/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3344 fix: Fix the select not open in select image
  server/services/session.js
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/DropdownContent.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/Select/index.jsx
  src/components/Inputs/EnvironmentInput/ConfigOrSecret/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3348 fix: Create a snapshot of the storage volume, the page is not refreshed
  src/actions/volume.js
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3339 fix: Fix Add the cluster in code repo API
  src/actions/cd.js
  src/actions/codeRepo.js
  src/components/Forms/CD/Advance/Placement/index.jsx
  src/components/Forms/CD/BaseInfo/index.jsx
  src/components/Modals/DevOpsAllowList/CodeRepoSelect.jsx
  src/components/Modals/DevOpsAllowList/index.jsx
  src/components/Modals/ProjectSelect/Card/index.jsx
  src/pages/devops/containers/Base/List/index.jsx
  src/pages/devops/containers/BaseInfo/index.jsx
  src/pages/devops/containers/CD/CDList/index.jsx
  src/pages/devops/containers/CD/detail/SyncStatus/index.jsx
  src/pages/devops/containers/CD/detail/index.jsx
  src/pages/devops/containers/CodeRepo/CRList/index.jsx
  src/pages/devops/containers/layout.jsx
  src/stores/cd.js
  src/stores/codeRepo.js
  src/stores/devops.js
Labels: size/L, lgtm, approved, area/devops, kind/bug, release-note-none

#3351 fix: Project list data not incorrect
  src/pages/clusters/components/Modals/Accessor/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3352 fix: Edit the workload resources not refresh
  src/components/Cards/Monitoring/Controller/TimeSelector/Range/Custom.jsx
  src/components/Forms/Workload/ContainerSettings/Affinity/index.jsx
  src/components/Forms/Workload/ContainerSettings/UpdateStrategy/index.jsx
  src/pages/projects/containers/DaemonSets/Detail/index.jsx
  src/pages/projects/containers/StatefulSets/Detail/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3353 fix: The mounted path of specific keys should be the relative path for multi-cluster deployment
  locales/en/l10n-multiclusterProjects-applicationWorkloads-deployments-details.js
  locales/zh/l10n-multiclusterProjects-applicationWorkloads-deployments-details.js
  src/components/Forms/Workload/VolumeSettings/MountConfig/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3356 fix: The relative path does not recognize '../'
  locales/en/l10n-multiclusterProjects-applicationWorkloads-deployments-details.js
  locales/zh/l10n-multiclusterProjects-applicationWorkloads-deployments-details.js
  src/components/Forms/Workload/VolumeSettings/MountConfig/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none, kind/require-ui-text-review

#3359 Update UI text of roles, permissions, and application workloads
  locales/en/base.js
  locales/en/l10n-multiclusterProjects-applicationWorkloads-deployments-details.js
  locales/en/l10n-workspaces-workspaceSettings-workspaceRoles-list.js
  locales/zh/l10n-multiclusterProjects-applicationWorkloads-deployments-details.js
  src/components/Forms/Workload/VolumeSettings/MountConfig/index.jsx
  src/components/Modals/EditAuthorization/CheckItem.jsx
  src/pages/workspaces/containers/Members/index.jsx
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#3363 fix: Alert message overflow out of box
  src/scss/base.scss
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3373 fix: Disallow input value with space filed
  src/components/Modals/StorageclassAutoresizer/TailItemInput/index.jsx
  src/components/Modals/StorageclassAutoresizer/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3370 fix: Storageclass name incorrect when creating a volume from a snapshot
  src/pages/clusters/containers/Storage/VolumeSnapshotClasses/Detail/VolumeSnapshot/index.jsx
  src/pages/clusters/containers/Storage/VolumeSnapshots/Snapshots/index.jsx
  src/utils/constants.js
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3372 fix: Member clusters below v3.3.0 should not support automatic expansion
  src/pages/clusters/containers/Storage/StorageClasses/Detail/index.jsx
  src/pages/projects/containers/Volumes/Detail/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3375 fix: Fix some bug about CD and service
  src/components/Cards/Containers/Item.jsx
  src/components/Inputs/EnvironmentInput/ArrowModal/index.jsx
  src/pages/devops/containers/CD/CDList/index.jsx
  src/pages/devops/containers/CD/Components/ChartCard/index.jsx
  src/pages/devops/containers/CD/Components/StatusText/index.jsx
  src/pages/devops/containers/CD/detail/index.jsx
  src/pages/projects/components/Cards/ContainerTemplate/Item.jsx
  src/pages/projects/containers/Services/index.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#3377 fix: Unable to delete the last character of env variable key
  src/components/Inputs/EnvironmentInput/Item.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3378 fix: Fix the repo url is incorrect when edit
  src/actions/codeRepo.js
  src/components/Modals/StorageclassAutoresizer/Slider/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3379 opt: Unable to delete the last character of env variable key
  src/components/Inputs/EnvironmentInput/Item.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3380 docs: Update UI text of 'Projects' and 'Clusters'
  locales/en/l10n-projects-overview.js
  src/pages/projects/containers/Overview/Applications/index.jsx
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3387 docs: Update UI text of 'Volume Snapshots'
  locales/en/l10n-clusterManagement-storage-volumeSnapshots-details.js
  locales/en/l10n-clusterManagement-storage-volumeSnapshots-list.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3389 docs: Update UI text of 'Volume Snapshots'
  locales/en/l10n-clusterManagement-storage-volumeSnapshots-details.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3388 fix: Fix the update time is '-' when it is empty
  src/pages/devops/containers/CD/CDList/index.jsx
  src/pages/devops/containers/CD/detail/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3390 fix: Users can't just only edit container port
  src/components/Inputs/ContainerPort/index.jsx
  src/components/Inputs/ContainerPort/index.test.js
  src/components/Inputs/ContainerServicePort/index.jsx
  src/components/Inputs/ContainerServicePort/index.test.js
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#3392 fix: Fix the data is incorre when twice update the cluster kubeconfig
  src/actions/cluster.js
  src/components/Forms/Secret/SecretSettings/DataForm/index.jsx
Labels: lgtm, approved, size/S, kind/bug, do-not-merge/release-note-label-needed

#3393 fix: Can't connect to kubectl due to the url
  src/components/Modals/ContianerTerminal/index.jsx
  src/components/Modals/KubeCtl/index.jsx
  src/components/Terminal/index.jsx
  src/components/Terminal/terminal.jsx
  src/stores/terminal.js
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#3395 fix: Batch reference modal's position incorrect
  src/components/Inputs/EnvironmentInput/ArrowModal/index.jsx
  src/components/Inputs/EnvironmentInput/ConfigOrSecret/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3396 fix: Kubectl terminal shell text error
  src/utils/socket.client.js
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3397 docs: Fix bugs of UI text
  locales/en/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
  locales/en/l10n-devopsProjects-continuousDeployments-list.js
  src/pages/devops/containers/CD/CDList/index.jsx
  src/pages/projects/components/Modals/AppTemplateEdit/index.jsx
  src/utils/constants.js
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#3386 fix: Fix harbor and dockerhub api formget to post
  server/config.yaml
  server/controllers/api.js
  server/controllers/session.js
  server/libs/request.js
  server/routes.js
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/DropdownContent.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
  src/core/containers/Login/index.jsx
  src/stores/container.js
  src/utils/index.js
Labels: size/L, lgtm, approved, kind/bug, release-note-none

#3404 docs: Update UI text of 'Auto Expansion'
  locales/ar/pipeline.js
  locales/en/l10n-clusterManagement-storage-storageClasses-details.js
  locales/en/pipeline.js
  locales/es/pipeline.js
  locales/fr/pipeline.js
  locales/hi/pipeline.js
  locales/ko/pipeline.js
  locales/lt/pipeline.js
  locales/pl/pipeline.js
  locales/tc/pipeline.js
  locales/tr/pipeline.js
  locales/zh/pipeline.js
  src/pages/clusters/containers/Storage/StorageClasses/Detail/Volumes/index.jsx
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#3407 fix: Storage class editing automatic extension maximum value does not take effect
  server/views/blank_markdown.html
  src/components/Modals/StorageclassAutoresizer/index.jsx
  src/pages/projects/containers/Services/Topology/Service/index.jsx
  src/pages/projects/containers/Volumes/Detail/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3413 fix: The kubectl url of member cluster's node incorrect
  src/components/Modals/KubeCtl/index.jsx
  src/pages/clusters/containers/Nodes/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3414 fix: The kubectl url of member edge node incorrect
  src/pages/clusters/containers/EdgeNodes/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none
