Repository kubesphere/console, pull requests merged in 2022-01, with the labels that each got.

#2889 fix: Devops are not shown in grey disabled mode.
  src/components/Modals/ProjectSelect/Card/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#2894 fix: Can't enter PV detail page in member cluster
  src/stores/pv.js
Labels: size/XS, lgtm, approved, kind/bug, release-note

#2895 fix: Delete gpu field when creating workload
  src/actions/application.js
  src/actions/federated.js
  src/actions/workload.js
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
  src/components/Forms/Workload/ContainerSettings/index.jsx
  src/pages/fedprojects/components/ContainerSetting/index.jsx
  src/utils/constants.js
  src/utils/index.js
Labels: size/L, lgtm, approved, kind/bug, release-note

#2888 feat: Add shell access to nodes
  src/components/Modals/KubeCtl/index.jsx
  src/pages/clusters/containers/EdgeNodes/index.jsx
  src/pages/clusters/containers/Nodes/index.jsx
  src/pages/terminal/index.jsx
  src/stores/terminal.js
Labels: lgtm, approved, size/M, kind/feature, ok-to-test, release-note-none

#2897 fix: Error occurs on the console when the time range is not set.
  locales/ar/l10n-clusterManagement-monitoring&Alerting-clusterStatus.js
  locales/en/l10n-clusterManagement-monitoring&Alerting-clusterStatus.js
  locales/es/l10n-clusterManagement-monitoring&Alerting-clusterStatus.js
  locales/fr/l10n-clusterManagement-monitoring&Alerting-clusterStatus.js
  locales/hi/l10n-clusterManagement-monitoring&Alerting-clusterStatus.js
  locales/lt/l10n-clusterManagement-monitoring&Alerting-clusterStatus.js
  locales/pl/l10n-clusterManagement-monitoring&Alerting-clusterStatus.js
  locales/tc/l10n-clusterManagement-monitoring&Alerting-clusterStatus.js
  locales/zh/l10n-clusterManagement-monitoring&Alerting-clusterStatus.js
  src/components/Cards/Monitoring/Controller/TimeSelector/Range/Custom.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#2900 fix: Fix the data of gateway not have the key of metric.ingress
  src/pages/clusters/containers/Gateway/Detail/Monitoring/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#2901 fix: Invalid API request of listing s2ibuildertemplates in multi-cluster environment
  src/components/Forms/ImageBuilder/B2IForm/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note

#2905 fix: Verify devops project name input
  src/components/Modals/DevOpsCreate/index.jsx
  src/stores/base.js
Labels: lgtm, approved, size/S, area/devops, kind/bug, release-note-none

#2911 fix: User can't edit resource limit for workload during create deloyment
  src/components/Inputs/ResourceLimit/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#2908 fix: Block users from going to the next step when the metadata validation fails
  src/components/Forms/Workload/ContainerSettings/Metadata/index.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note

#2896 fix: Modify the mouse display mode。
  src/components/Tables/Visible/index.scss
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#2907 fix: Block users submit updates when environment variable verification fails
  src/components/Forms/Workload/ContainerSettings/ContainerForm/Environments/index.jsx
  src/components/Inputs/ArrayInput/Item.jsx
  src/components/Inputs/ArrayInput/index.jsx
  src/components/Inputs/EnvironmentInput/Item.jsx
  src/components/Inputs/EnvironmentInput/index.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note

#2913 fix: Fix the page block by search image without permission
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#2903 fix: Webhook token and auth should be required fields
  locales/en/l10n-platformSettings-notificationManagement-notificationConfiguration.js
  src/components/Forms/Notification/WebhookForm/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note, kind/require-ui-text-review

#2916 fix: In the composed app's details page, users cannot customize the time interval for the traffic monitoring
  src/components/Graph/index.jsx
  src/pages/projects/containers/Applications/CRDAppDetail/TrafficManangement/index.jsx
  src/pages/projects/containers/Applications/CRDAppDetail/TrafficManangement/index.scss
  src/stores/application/crd.js
Labels: size/L, lgtm, approved, kind/bug, release-note

#2915 chore: Change the edge node api
  src/stores/edgenode.js
Labels: size/XS, lgtm, approved, release-note-none

#2926 fix: Invalid API request of persistentvolumeclaims in member cluster environment
  src/pages/clusters/containers/Storage/PV/detail/ResourceStatus/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note

#2928 fix: Wecom receiver should be required
  src/components/Forms/Notification/WeComForm/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note

#2927 fix: Fix The TCP traffic data in traffic monitoring is empty
  src/components/Graph/Detail/Monitors/ServiceMonitor.jsx
  src/components/Graph/Detail/Monitors/WorkloadMonitor.jsx
  src/stores/application/crd.js
Labels: size/L, lgtm, approved, kind/bug, release-note

#2931 fix: Delete the livenessProbe that it is empty
  src/components/Forms/Workload/ContainerSettings/ContainerForm/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note
