Repository kubesphere/console, pull requests merged in 2022-04, with the labels that each got.

#3038 feat: Add the status and operation of cluster KubeConfig expired
  locales/en/l10n-clusterManagement-clusters.js
  locales/zh/l10n-clusterManagement-clusters.js
  src/actions/cluster.js
  src/components/Clusters/ClusterTitle/index.jsx
  src/components/Clusters/ClusterTitle/index.scss
  src/components/EditMode/index.jsx
  src/components/Forms/Cluster/Configuration/index.jsx
  src/components/Forms/Cluster/KubeConfig/index.jsx
  src/components/Forms/Cluster/KubeConfig/index.scss
  src/pages/clusters/components/Cards/Cluster/index.jsx
  src/pages/clusters/components/Cards/Cluster/index.scss
  src/pages/clusters/containers/Clusters/index.jsx
  src/stores/cluster/index.js
  src/utils/index.js
  src/utils/object.mapper.js
Labels: size/L, lgtm, approved, kind/feature, release-note

#3044 feat: Support load the entire configmap as environment variables
  locales/en/l10n-projects-applicationWorkloads-deployments-details.js
  locales/zh/l10n-projects-applicationWorkloads-deployments-details.js
  src/components/Forms/Workload/VolumeSettings/index.jsx
  src/components/Inputs/EnvironmentInput/ArrowModal/index.jsx
  src/components/Inputs/EnvironmentInput/ArrowModal/index.scss
  src/components/Inputs/EnvironmentInput/ConfigOrSecret/index.jsx
  src/components/Inputs/EnvironmentInput/ConfigOrSecret/index.scss
  src/components/Inputs/EnvironmentInput/Item.jsx
  src/components/Inputs/EnvironmentInput/index.jsx
  src/components/Inputs/EnvironmentInput/index.scss
  src/components/Inputs/EnvironmentInput/index.test.js
Labels: lgtm, approved, size/XL, kind/feature, release-note, kind/require-ui-text-review

#3043 feat: Add CD step in visualization pipeline
  locales/en/l10n-devopsProjects-cd-list.js
  src/pages/devops/components/Pipeline/StepModals/cd.jsx
  src/pages/devops/components/Pipeline/StepModals/index.js
  src/pages/devops/components/Pipeline/StepModals/index.scss
  src/pages/devops/components/Pipeline/StepsSelector/index.jsx
  src/pages/devops/components/Pipeline/store.js
  src/utils/constants.js
Labels: size/L, lgtm, approved, area/devops, kind/feature, tide/merge-method-squash, release-note

#3049 Optimize HTTP status code
  server/controllers/session.js
Labels: lgtm, approved, size/S, kind/cleanup, release-note-none

#3031 fix: Disable management function in accounts and workspaces manage page when user login in a member cluster
  server/controllers/view.js
  server/services/session.js
  src/pages/workspaces/containers/BaseInfo/index.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note

#3041 feat: Add code repo page
  locales/en/l10n-devopsProjects-codeRepo-list.js
  package.json
  server/config.yaml
  src/actions/codeRepo.js
  src/components/Forms/Pipelines/RepoSelect/BitBucketForm/index.jsx
  src/components/Forms/Pipelines/RepoSelect/GitLabForm/index.jsx
  src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx
  src/components/Forms/Pipelines/RepoSelect/subForm.jsx
  src/components/Modals/CodeRepoCreate/index.jsx
  src/components/Modals/CodeRepoCreate/index.scss
  src/components/Tables/Base/index.jsx
  src/pages/devops/containers/CodeRepo/CRList/index.jsx
  src/pages/devops/containers/CodeRepo/CRList/index.scss
  src/pages/devops/routes/index.js
  src/stores/codeRepo.js
  src/utils/constants.js
  src/utils/form.templates.js
  src/utils/object.mapper.js
  yarn.lock
Labels: lgtm, approved, size/XL, area/devops, kind/feature, tide/merge-method-squash, release-note, kind/require-ui-text-review

#3062 feat: Add prompt to enable audit log
  locales/en/l10n-toobox-auditLogSearch-list.js
  locales/zh/l10n-toobox-auditLogSearch-list.js
  src/components/Modals/AuditingSearch/Auditing/Home/index.jsx
  src/components/Modals/AuditingSearch/Auditing/Home/index.scss
Labels: lgtm, approved, kind/feature, release-note, kind/require-ui-text-review

#3060 feat: Add the cd allowlist in devops base info
  locales/en/l10n-devopsProjects-devopsProjectSettings-basinInformation.js
  locales/zh/l10n-devopsProjects-devopsProjectSettings-basinInformation.js
  package.json
  src/actions/devops.js
  src/components/Modals/DevOpsAllowList/Destinations.jsx
  src/components/Modals/DevOpsAllowList/index.jsx
  src/components/Modals/DevOpsAllowList/index.scss
  src/pages/devops/containers/BaseInfo/index.jsx
  src/pages/devops/containers/BaseInfo/index.scss
  src/stores/devops.js
  src/utils/constants.js
  src/utils/object.mapper.js
  yarn.lock
Labels: lgtm, approved, size/XL, area/devops, kind/feature, release-note-none, kind/require-ui-text-review

#3061 feat: Add the cluster member and cluster role
  locales/en/l10n-clusterManagement-member-list.js
  locales/en/l10n-clusterManagement-role-list.js
  locales/zh/l10n-clusterManagement-member-list.js
  locales/zh/l10n-clusterManagement-role-list.js
  server/config.yaml
  src/pages/clusters/containers/Roles/index.jsx
Labels: size/L, lgtm, approved, release-note

#3063 feat: Add disk usage per hard disk
  locales/en/l10n-clusterManagement-monitoring&Alerting-clusterStatus.js
  locales/zh/l10n-clusterManagement-monitoring&Alerting-clusterStatus.js
  src/pages/clusters/containers/Nodes/Detail/Monitoring/index.jsx
Labels: size/L, lgtm, approved, kind/feature, release-note, kind/require-ui-text-review

#3064 fix: Get cluster role error
  server/services/session.js
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3056 feat: Add PVC autoresizer manage function
  locales/en/l10n-clusterManagement-storage-storageClasses-details.js
  locales/zh/l10n-clusterManagement-storage-storageClasses-details.js
  src/actions/storageclass.js
  src/assets/autoscaling.svg
  src/assets/chart.svg
  src/assets/history_duotone.svg
  src/assets/storageclass_autoresizer.svg
  src/components/Base/Text/index.jsx
  src/components/Modals/StorageclassAutoresizer/Slider/index.jsx
  src/components/Modals/StorageclassAutoresizer/Slider/index.scss
  src/components/Modals/StorageclassAutoresizer/TailItemInput/index.jsx
  src/components/Modals/StorageclassAutoresizer/TailItemInput/index.scss
  src/components/Modals/StorageclassAutoresizer/index.jsx
  src/components/Modals/StorageclassAutoresizer/index.scss
  src/core/containers/Base/Detail/BaseInfo/BtnGroup/index.jsx
  src/pages/clusters/containers/Storage/StorageClasses/Detail/Volumes/index.jsx
  src/pages/clusters/containers/Storage/StorageClasses/Detail/Volumes/index.scss
  src/pages/clusters/containers/Storage/StorageClasses/Detail/index.jsx
Labels: lgtm, approved, size/XXL, kind/feature, release-note, kind/require-ui-text-review

#3065 fix: Update kube-design version
  package.json
  yarn.lock
Labels: lgtm, approved, size/S, kind/bug, release-note

#3029 Update UI text of 'Cluster Management'
  locales/en/base.js
  locales/en/l10n-clusterManagement-applicationWorkloads-pods-details.js
  locales/en/l10n-clusterManagement-applicationWorkloads-routes-list.js
  locales/en/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
  locales/en/l10n-projects-applicationWorkloads-jobs-list.js
  locales/en/l10n-projects-applicationWorkloads-pods-details.js
  src/components/Cards/Containers/Item.jsx
  src/components/Cards/Containers/Ports/index.jsx
  src/components/Forms/Secret/SecretSettings/index.jsx
  src/pages/clusters/containers/Workload/Jobs/index.jsx
  src/pages/projects/containers/Pods/Containers/Detail.jsx
  src/pages/projects/containers/Pods/Containers/Monitoring.jsx
  src/pages/projects/containers/Pods/Detail/Monitoring.jsx
  src/pages/projects/containers/Services/Detail/index.jsx
Labels: lgtm, approved, size/M, kind/documentation, release-note-none

#3052 feat: Add snapshot class management page
  locales/en/l10n-clusterManagement-storage-volumeSnapshotClasses-list.js
  locales/zh/l10n-clusterManagement-storage-volumeSnapshotClasses-list.js
  server/config.yaml
  src/actions/volume.js
  src/components/Forms/VolumeSnapshot/SnapshotClassSettings/index.jsx
  src/configs/steps/volume.snapshot.class.js
  src/pages/clusters/containers/Storage/VolumeSnapshotClasses/Detail/VolumeSnapshot/index.jsx
  src/pages/clusters/containers/Storage/VolumeSnapshotClasses/Detail/VolumeSnapshot/index.scss
  src/pages/clusters/containers/Storage/VolumeSnapshotClasses/Detail/index.jsx
  src/pages/clusters/containers/Storage/VolumeSnapshotClasses/Detail/routes.js
  src/pages/clusters/containers/Storage/VolumeSnapshotClasses/index.jsx
  src/pages/clusters/containers/Storage/VolumeSnapshots/index.jsx
  src/pages/clusters/routes/detail.js
  src/pages/clusters/routes/index.js
  src/utils/constants.js
  src/utils/form.templates.js
  src/utils/object.mapper.js
Labels: lgtm, approved, size/XL, kind/feature, release-note, kind/require-ui-text-review

#3067 feat: Relate code repo with cd and allowlist
  src/actions/cd.js
  src/components/Forms/CD/Advance/Placement/index.jsx
  src/components/Forms/CD/BaseInfo/index.jsx
  src/components/Forms/CD/BaseInfo/index.scss
  src/components/Modals/DevOpsAllowList/Destinations.jsx
  src/components/Modals/DevOpsAllowList/index.jsx
  src/pages/devops/containers/BaseInfo/index.jsx
  src/pages/devops/containers/CD/Components/Destination/index.jsx
  src/pages/devops/containers/CodeRepo/CRList/index.jsx
  src/utils/index.js
Labels: size/L, lgtm, approved, area/devops, kind/feature, release-note-none

#3069 feat: Support storageclass access control
  locales/en/l10n-clusterManagement-storage-storageClasses-details.js
  locales/zh/l10n-clusterManagement-storage-storageClasses-details.js
  src/actions/storageclass.js
  src/assets/storageclass-tree.svg
  src/pages/clusters/components/Modals/Accessor/index.jsx
  src/pages/clusters/components/Modals/Accessor/index.scss
  src/pages/clusters/containers/Storage/StorageClasses/Detail/index.jsx
  src/pages/clusters/containers/Storage/StorageClasses/index.jsx
  src/stores/accessor.js
  src/utils/constants.js
  src/utils/form.templates.js
  src/utils/index.test.js
Labels: lgtm, approved, size/XL, kind/feature, release-note, kind/require-ui-text-review

#3054 fix: Fix cronjob status display err in detail page
  src/pages/projects/containers/CronJobs/Detail/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, ok-to-test, release-note

#3080 fix: No description for routes item in cluster management page
  src/pages/clusters/containers/Workload/Routes/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3082 fix: Container terminal doesn't change when switching to another container
  src/components/Modals/ContianerTerminal/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note

#3070 fix: Can't connect to the cluster which kubesphere version below v3.3
  server/services/session.js
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3083 fix: Environment variable display is occluded
  src/components/Cards/Containers/EnvVariables/index.scss
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3087 fix: Environment variables do not support key names containing hyphens (-) and periods (.)
  src/components/Inputs/EnvironmentInput/Item.jsx
  src/utils/constants.js
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3089 fix: Remove the Version field on the Revision Records tab page
  src/pages/projects/containers/Deployments/Detail/RevisionControl/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note

#3091 fix: Update PVC autoresizer text
  locales/en/l10n-clusterManagement-storage-storageClasses-details.js
  locales/zh/l10n-clusterManagement-storage-storageClasses-details.js
  src/components/Modals/StorageclassAutoresizer/index.jsx
  src/pages/clusters/containers/Storage/StorageClasses/Detail/Volumes/index.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note-none, kind/require-ui-text-review

#3110 fix: Remove 'update kubeconfig' and 'unbind cluster' button in host cluster card
  src/pages/clusters/containers/Clusters/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3111 fix: Create OpenLB gateway, the page shows error
  src/pages/clusters/containers/Gateway/Components/GatewayCard/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3092 fix: StorageClass accessor manage URL error
  src/pages/clusters/containers/Storage/StorageClasses/Detail/index.jsx
  src/stores/base.js
  src/stores/validateWebhookCF.js
  src/utils/constants.js
Labels: size/L, lgtm, approved, kind/bug, release-note-none

#3113 Update UI text of 'Cluster Management'
  locales/ar/l10n-clusterManagement-storage-volumeSnapshots-list.js
  locales/en/l10n-clusterManagement-storage-volumeSnapshots-list.js
  locales/en/l10n-projects-applicationWorkloads-services-details.js
  src/pages/projects/components/Modals/ServiceMonitor/Authorization/index.jsx
  src/pages/projects/components/Modals/ServiceMonitor/Endpoint/index.jsx
  src/pages/projects/components/Modals/ServiceMonitor/index.jsx
Labels: lgtm, approved, size/M, kind/documentation, release-note-none

#3117 fix: Service topology map container monitoring's data doesn't change with the data request
  src/pages/projects/containers/Services/Topology/Detail/Containers/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note

#3120 fix: Fix reload status of CD every 4 seconds
  src/pages/devops/containers/CD/detail/SyncStatus/index.jsx
Labels: lgtm, approved, size/S, area/devops, kind/bug, release-note

#3125 Update the URL of npm mirror
  README.md
Labels: size/XS, lgtm, approved, kind/cleanup, release-note-none

#3126 Update UI text of 'Storage Classes'
  locales/ar/l10n-clusterManagement-monitoring&Alerting-customMonitoring.js
  locales/en/l10n-clusterManagement-storage-storageClasses-details.js
  locales/en/l10n-clusterManagement-storage-volumeSnapshots-list.js
  src/components/Forms/Dashboard/BaseInfo/index.jsx
  src/components/Modals/StorageclassAutoresizer/index.jsx
  src/components/Modals/VolumeFunctionManage/index.jsx
  src/pages/clusters/components/Modals/Accessor/index.jsx
  src/pages/clusters/containers/Storage/StorageClasses/Detail/Volumes/index.jsx
  src/pages/clusters/containers/Storage/StorageClasses/Detail/index.jsx
  src/pages/clusters/containers/Storage/VolumeSnapshots/index.jsx
Labels: size/L, lgtm, approved, kind/documentation, release-note-none

#3129 Update UI text of 'Storage Classes'
  locales/en/l10n-clusterManagement-storage-storageClasses-details.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3127 fix: Fix the empty value when upload the file in cluster kubeconfig
  src/components/EditMode/index.jsx
  src/components/Forms/Cluster/KubeConfig/index.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#3122 fix: Incorrect URL of a git repository
  src/actions/codeRepo.js
Labels: lgtm, approved, size/S, area/devops, kind/bug, release-note-none

#3128 fix: Failed to enable automatic restart of workloads
  locales/en/l10n-clusterManagement-storage-storageClasses-details.js
  locales/zh/l10n-clusterManagement-storage-storageClasses-details.js
  src/components/Modals/StorageclassAutoresizer/TailItemInput/index.jsx
  src/components/Modals/StorageclassAutoresizer/index.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#3130 fix: Support select a CSI plugin when creating a volume snapshot class
  src/actions/volume.js
  src/components/Forms/VolumeSnapshot/SnapshotClassSettings/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3131 Update UI text of 'Continuous Deployment Allowlist'
  locales/en/l10n-devopsProjects-devopsProjectSettings-basinInformation.js
  src/components/Modals/DevOpsAllowList/Destinations.jsx
  src/components/Modals/DevOpsAllowList/index.jsx
  src/pages/devops/containers/BaseInfo/index.jsx
Labels: lgtm, approved, size/M, area/devops, kind/documentation, release-note-none

#3121 feat: Add CD and Code Repo role
  locales/en/l10n-devopsProjects-devopsProjectSettings-devopsProjectRoles-list.js
  server/config.yaml
  src/components/Modals/EditAuthorization/constants.js
  src/pages/devops/containers/CD/CDList/index.jsx
  src/pages/devops/containers/CodeRepo/CRList/index.jsx
  src/pages/devops/routes/index.js
Labels: lgtm, approved, size/M, area/devops, kind/feature, release-note, kind/require-ui-text-review

#3134 Update UI text of 'Set Auto Expansion'
  locales/en/l10n-clusterManagement-storage-storageClasses-details.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3132 Update UI text of 'DevOps Project Roles'
  locales/en/l10n-devopsProjects-devopsProjectSettings-devopsProjectRoles-list.js
Labels: lgtm, approved, size/S, area/devops, kind/documentation, release-note-none

#3133 fix: Hide the volume template card in statefulsets setting modal
  src/actions/federated.js
  src/actions/workload.js
  src/components/Forms/Workload/VolumeSettings/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3138 fix: Storageclass's accessor should in dsiabled status by default
  src/utils/form.templates.js
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3142 fix: Update storageclass expansion text
  src/components/Modals/StorageclassAutoresizer/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3143 fix: Storageclass autoresizer function should be disabled when it volume expansion funciton is disabled
  src/pages/clusters/containers/Storage/StorageClasses/Detail/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3145 fix: Fix the data is residual when after is created the custom monitor
  src/components/Forms/Dashboard/BaseInfo/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note

#3147 fix: Backend is lack of accessor crd will create 404 warning
  locales/en/l10n-clusterManagement-storage-storageClasses-details.js
  src/actions/storageclass.js
  src/pages/clusters/components/Modals/Accessor/index.jsx
  src/pages/clusters/containers/Storage/StorageClasses/Detail/index.jsx
  src/stores/base.js
Labels: lgtm, approved, size/M, kind/bug, release-note-none, kind/require-ui-text-review

#3149 fix: Storage type permission setting error
  src/pages/clusters/components/Modals/Accessor/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3148 fix: Fix the code repo issues about edit and create time
  src/actions/codeRepo.js
  src/components/Modals/CodeRepoCreate/index.jsx
  src/pages/devops/containers/CodeRepo/CRList/index.jsx
Labels: lgtm, approved, size/M, area/devops, kind/bug, release-note-none

#3152 fix: Do not check the locales folder
  .eslintignore
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3155 fix: The character length limit for aliases does not work
  src/components/Forms/CD/BaseInfo/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3153 fix: Fix the annotations in gateway modal
  src/pages/projects/components/Modals/GatewaySetting/index.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#3164 fix: Bars of a custom monitoring dashboard exceed the boundary
  src/components/Modals/CustomMonitoring/components/Graph/Compose/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note

#3163 Support creates a role that can only trigger a Pipeline
  src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Layout/branch.jsx
Labels: size/XS, lgtm, approved, area/devops, kind/feature, release-note

#3162 feat: Optimize CD delete modal
  locales/en/l10n-devopsProjects-continuousDeployments-list.js
  src/actions/cd.js
  src/components/Modals/CDDelete/index.jsx
  src/components/Modals/CDDelete/index.scss
  src/pages/devops/containers/CD/CDList/index.jsx
  src/pages/devops/containers/CD/detail/index.jsx
  src/stores/cd.js
Labels: size/L, lgtm, approved, area/devops, kind/feature, release-note, kind/require-ui-text-review

#3124 Fix the image tag when build it with make command
  .gitpod.yml
  Makefile
Labels: size/XS, lgtm, approved, kind/cleanup, release-note-none

#3168 fix: Fix the location in CD create modal
  src/components/Forms/CD/Advance/Placement/index.jsx
  src/components/Modals/DevOpsAllowList/index.jsx
  src/stores/cd.js
  src/utils/index.js
Labels: size/L, lgtm, approved, area/devops, kind/bug, release-note-none

#3175 fix: User still can create a snapshot while selected volume's storageclass has been deleted
  src/pages/projects/components/Modals/ResourceSnapshot/index.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#3173 fix: User still can create a volume from a snapshot after its snapshot class has been deleted
  src/pages/projects/containers/VolumeSnapshots/Detail/index.jsx
  src/stores/volumeSnapshotClasses.js
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#3177 fix: User still can click the delete button when the snapshot in deleting status
  src/pages/clusters/containers/Storage/VolumeSnapshots/Snapshots/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3170 Update UI text of 'Continuous Deployment'
  locales/ar/alerting.js
  locales/en/alerting.js
  locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-details.js
  locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
  locales/en/l10n-clusterManagement-nodes-clusterNodes-list.js
  locales/en/l10n-clusterManagement-storage-storageClasses-details.js
  locales/en/l10n-devopsProjects-continuousDeployments-list.js
  locales/es/alerting.js
  locales/fr/alerting.js
  locales/hi/alerting.js
  locales/lt/alerting.js
  locales/pl/alerting.js
  locales/tc/alerting.js
  locales/tr/alerting.js
  locales/zh/alerting.js
  locales/zh/l10n-clusterManagement-monitoring&Alerting-alertingMessages.js
  src/components/Cards/RankTable/NodeTable/index.jsx
  src/components/Forms/Cluster/NodeList/AddNode.jsx
  src/pages/clusters/containers/Nodes/Detail/index.jsx
  src/pages/clusters/containers/Nodes/index.jsx
  src/pages/clusters/containers/Overview/Dashboard/ClusterNodes/NodesTop5/index.jsx
  src/pages/projects/containers/Alerting/Messages/index.jsx
  src/pages/projects/containers/Alerting/Policies/Detail/AlertMessages/index.jsx
  src/pages/projects/containers/Alerting/Policies/Detail/AlertRules/RuleItem.jsx
  src/pages/projects/containers/Alerting/Policies/Detail/AlertRules/index.jsx
  src/pages/projects/containers/Alerting/Policies/Detail/routes.js
  src/utils/index.js
  src/utils/index.test.js
Labels: size/L, lgtm, approved, kind/documentation, release-note-none

#3178 fix: Delete a storageclass with 404 warning
  src/actions/storageclass.js
  src/stores/accessor.js
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3171 fix: Fix redirect when logging in with OAuth
  server/controllers/session.js
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3176 fix: Fix display of value of code repository
  locales/en/l10n-devopsProjects-continuousDeployments-details.js
  src/components/Forms/CD/BaseInfo/index.jsx
  src/components/Forms/CD/BaseInfo/index.scss
  src/pages/devops/containers/CD/detail/SyncStatus/index.jsx
Labels: lgtm, approved, size/S, area/devops, kind/bug, release-note-none, kind/require-ui-text-review

#3180 fix: Storageclass name incrrect when creating a volume from a snapshot
  src/components/Forms/Volume/VolumeSettings/SnapshotForm/index.jsx
  src/pages/projects/containers/VolumeSnapshots/Detail/index.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note

#3188 fix: Remove auto generate in create route modal
  locales/en/l10n-projects-applicationWorkloads-routes-details.js
  locales/zh/l10n-projects-applicationWorkloads-routes-details.js
  src/components/Forms/Route/RouteRules/RuleForm/index.jsx
Labels: size/L, lgtm, approved, kind/feature, release-note-none, kind/require-ui-text-review

#3181 fix: Fix the filter of health status and sync status in CD page
  src/pages/devops/containers/CD/Components/ChartCard/index.jsx
Labels: size/XS, lgtm, approved, area/devops, kind/bug, release-note-none

#3186 fix: Error select environment variable
  src/components/Inputs/EnvironmentInput/Item.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#3190 chore: Add export index file in ko
  locales/ko/alerting.js
  locales/ko/app.js
  locales/ko/app_repo.js
  locales/ko/app_store.js
  locales/ko/app_template.js
  locales/ko/application.js
  locales/ko/base.js
  locales/ko/cluster.js
  locales/ko/component.js
  locales/ko/configmap.js
  locales/ko/crd.js
  locales/ko/dashboard.js
  locales/ko/devops.js
  locales/ko/gateway.js
  locales/ko/grayrelease.js
  locales/ko/group.js
  locales/ko/idle-components.js
  locales/ko/index.js
  locales/ko/ingress.js
  locales/ko/ippool.js
  locales/ko/lego.js
  locales/ko/logging.js
  locales/ko/login.js
  locales/ko/meter.js
  locales/ko/monitoring.js
  locales/ko/network.js
  locales/ko/nodes.js
  locales/ko/notification.js
  locales/ko/pipeline.js
  locales/ko/project.js
  locales/ko/ranking.js
  locales/ko/role.js
  locales/ko/s2i.js
  locales/ko/scheduleDeployment.js
  locales/ko/secret.js
  locales/ko/service.js
  locales/ko/service.monitor.js
  locales/ko/serviceaccounts.js
  locales/ko/settings.js
  locales/ko/sort_rank.js
  locales/ko/storage.js
  locales/ko/terminal.js
  locales/ko/user.js
  locales/ko/version.js
  locales/ko/workload.js
  locales/ko/workspace.js
Labels: lgtm, approved, size/XXL, kind/documentation, release-note-none

#3193 fix: Get support gpu list from apiserver
  server/config.yaml
  server/controllers/view.js
  server/services/session.js
Labels: lgtm, approved, size/M, kind/bug, do-not-merge/release-note-label-needed

#3195 fix: Add time select in fedproject applications traffic
  src/components/Graph/Card/index.jsx
  src/components/Graph/Card/index.scss
  src/pages/fedprojects/containers/Applications/Detail/TrafficManangement/index.jsx
  src/pages/fedprojects/containers/Applications/Detail/TrafficManangement/index.scss
Labels: size/L, lgtm, approved, kind/bug, release-note-none

#3196 fix: Remove the auto route in app deploy modal
  src/pages/projects/components/Modals/CreateApp/Routes/RuleForm/index.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#3189 fix: Update edge node component name
  server/config.yaml
Labels: size/XS, lgtm, approved, kind/bug, release-note

#3198 feat: Add options of prune propagation policy in cd modal
  src/components/Forms/CD/Advance/index.jsx
  src/components/Modals/SyncModal/index.jsx
  src/utils/constants.js
  src/utils/object.mapper.js
Labels: lgtm, approved, size/M, area/devops, kind/feature, release-note-none, kind/require-ui-text-review

#3197 fix: Fix environment variables duplicate key name
  src/components/Inputs/ArrayInput/Item.jsx
  src/components/Inputs/ArrayInput/index.jsx
  src/components/Inputs/EnvironmentInput/Item.jsx
  src/components/Inputs/EnvironmentInput/index.jsx
Labels: size/L, lgtm, approved, kind/bug, release-note-none

#3201 Update UI text of 'Cluster Management'
  locales/en/l10n-clusterManagement-network-networkPolicies-details.js
  locales/en/l10n-clusterManagement-network-podIpPools-details.js
  locales/en/l10n-clusterManagement-storage-volumes-list.js
  src/pages/clusters/containers/Network/IPPools/Detail/index.jsx
  src/pages/clusters/containers/Storage/PV/index.jsx
  src/pages/clusters/containers/Storage/VolumeSnapshots/routes.js
  src/pages/clusters/containers/Storage/Volumes/Volume/index.jsx
  src/pages/projects/containers/Network/Policies/Detail/Viewer/index.jsx
  src/pages/projects/containers/Network/Policies/Detail/routes.js
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#3202 feat: Support the grafana dashboard at the namespace
  src/components/Forms/Dashboard/BaseInfo/index.jsx
  src/stores/dashboard.js
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3206 fix: Fix the cluster expiredDay less than 0
  src/pages/clusters/components/Cards/Cluster/index.jsx
  src/utils/index.js
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3207 fix: Failed to edit the volume for the container again when creating a deployment
  src/components/Forms/Workload/VolumeSettings/AddVolume/index.jsx
Labels: lgtm, approved, size/S, release-note-none

#3212 Update UI text of 'Workloads'
  locales/en/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
  locales/en/l10n-multiclusterProjects-applicationWorkloads-statefulsets-list.js
  locales/en/l10n-projects-applicationWorkloads-deployments-list.js
  src/components/Forms/Workload/VolumeSettings/AddExistVolumes/index.jsx
  src/pages/projects/components/Modals/ResourceSnapshot/index.jsx
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#3215 Update UI text of 'Volume Snapshots'
  locales/en/l10n-clusterManagement-storage-volumeSnapshots-list.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3213 fix: Fix not show probe tooltip when it has data
  src/components/Cards/Containers/Item.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/index.jsx
  src/pages/projects/components/Cards/ContainerTemplate/Item.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3219 fix: The end ip address of calico should be the broadcast address
  src/pages/clusters/containers/Network/IPPools/Detail/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3221 fix: Mask field does not need to be displayed
  src/pages/clusters/containers/Network/IPPools/Detail/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3216 fix: Fix no sync options in the manual method
  src/actions/cd.js
Labels: size/XS, lgtm, approved, area/devops, kind/bug, release-note-none

#3223 Update UI text of 'Storage'
  locales/en/l10n-clusterManagement-storage-storageClasses-details.js
  locales/en/l10n-clusterManagement-storage-volumes-list.js
  src/components/Modals/VolumeFunctionManage/index.jsx
  src/pages/clusters/containers/Storage/PV/detail/ResourceStatus/index.jsx
  src/pages/clusters/containers/Storage/StorageClasses/Detail/index.jsx
  src/pages/clusters/containers/Storage/StorageClasses/index.jsx
  src/pages/projects/containers/Volumes/Detail/ResourceStatus/index.jsx
Labels: lgtm, approved, size/S, kind/documentation, release-note-none
