Repository kubesphere/console, pull requests merged in 2022-02, with the labels that each got.

#2940 feat: Add the life management of container in workload
  locales/ar/l10n-clusterManagement-applicationWorkloads-daemonsets-list.js
  locales/ar/l10n-clusterManagement-applicationWorkloads-pods-details.js
  locales/ar/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
  locales/en/l10n-clusterManagement-applicationWorkloads-pods-details.js
  locales/en/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
  locales/en/workload.js
  locales/es/base.js
  locales/es/l10n-clusterManagement-applicationWorkloads-pods-details.js
  locales/es/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
  locales/es/s2i.js
  locales/es/workload.js
  locales/fr/l10n-clusterManagement-applicationWorkloads-pods-details.js
  locales/fr/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
  locales/hi/l10n-clusterManagement-applicationWorkloads-pods-details.js
  locales/hi/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
  locales/lt/l10n-clusterManagement-applicationWorkloads-pods-details.js
  locales/lt/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
  locales/pl/l10n-clusterManagement-applicationWorkloads-pods-details.js
  locales/pl/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
  locales/tc/base.js
  locales/tc/l10n-clusterManagement-applicationWorkloads-pods-details.js
  locales/tc/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
  locales/tc/s2i.js
  locales/tr/l10n-clusterManagement-applicationWorkloads-pods-details.js
  locales/tr/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
  locales/zh/base.js
  locales/zh/l10n-clusterManagement-applicationWorkloads-pods-details.js
  locales/zh/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
  locales/zh/s2i.js
  src/components/Cards/Containers/Item.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/LifeManagement/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/LifeManagement/index.scss
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ProbeForm/ProbeConfig.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ProbeForm/ProbeSection.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ProbeForm/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ProbeForm/index.scss
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ProbeInput/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ProbeInput/index.scss
  src/components/Forms/Workload/ContainerSettings/ContainerForm/index.jsx
  src/pages/projects/components/Cards/ContainerTemplate/Item.jsx
  src/pages/projects/components/Cards/Lifecycle/index.jsx
  src/pages/projects/components/Cards/Lifecycle/index.scss
  src/pages/projects/containers/Pods/Containers/ResourceStatus.jsx
Labels: lgtm, approved, size/XXL, kind/feature, release-note, kind/require-ui-text-review

#2944 docs: Minor Update in Localization Guide
  docs/join-the-kubesphere-localization-project.md
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#2955 fix: Modify the user password to at least 8 characters
  locales/ar/l10n-accessControl-users-list.js
  locales/ar/user.js
  locales/en/l10n-accessControl-users-list.js
  locales/en/user.js
  locales/es/l10n-accessControl-users-list.js
  locales/es/user.js
  locales/fr/l10n-accessControl-users-list.js
  locales/fr/user.js
  locales/hi/l10n-accessControl-users-list.js
  locales/hi/user.js
  locales/lt/l10n-accessControl-users-list.js
  locales/lt/user.js
  locales/pl/l10n-accessControl-users-list.js
  locales/pl/user.js
  locales/tc/l10n-accessControl-users-list.js
  locales/tc/user.js
  locales/tr/l10n-accessControl-users-list.js
  locales/tr/user.js
  locales/zh/l10n-accessControl-users-list.js
  locales/zh/user.js
  src/utils/constants.js
Labels: lgtm, approved, kind/bug, release-note, kind/require-ui-text-review

#2947 fix: Fix the pods not updated after modifying the config of workload in fedProject
  src/components/Cards/Pods/index.jsx
  src/components/Modals/KubeCtl/index.jsx
  src/pages/terminal/index.jsx
  src/stores/federated.js
Labels: lgtm, approved, size/M, kind/bug, release-note

#2952 fix: Fix websocket connection recreate unexpected
  src/utils/socket.client.js
Labels: lgtm, approved, size/S, kind/bug, release-note

#2954 fix: Can't access terminal on pods
  locales/en/terminal.js
  locales/zh/terminal.js
  src/stores/terminal.js
Labels: lgtm, approved, size/S, kind/bug, release-note
