Repository kubesphere/console, pull requests merged in 2022-03, with the labels that each got.

#2956 fix: Update Traditional Chinese translations in workspaceRoles-list
  locales/tc/l10n-workspaces-workspaceSettings-workspaceRoles-list.js
Labels: lgtm, approved, size/S, kind/documentation, ok-to-test, do-not-merge/release-note-label-needed

#2938 update https://registry.npm.taobao.org to https://registry.npmmirror.com
  build/Dockerfile
Labels: size/XS, lgtm, approved, ok-to-test, do-not-merge/release-note-label-needed

#2964 fix: Update kubeSphere backend version judgement logic
  src/pages/clusters/containers/Storage/Volumes/Volume/index.jsx
  src/pages/clusters/containers/Storage/Volumes/index.jsx
  src/pages/projects/containers/Volumes/index.jsx
  src/stores/base.js
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#2970 Change UI text 'master' to 'control plane'.
  locales/en/l10n-clusterManagement-nodes-clusterNodes-list.js
  src/pages/clusters/containers/Nodes/Detail/index.jsx
  src/pages/clusters/containers/Nodes/index.jsx
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#2972 Update node health status UI text.
  locales/en/l10n-clusterManagement-nodes-clusterNodes-details.js
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#2963 feat: Refactor the pipeline template modal
  locales/en/l10n-devopsProjects-pipeline-list.js
  locales/zh/l10n-devopsProjects-pipeline-list.js
  src/actions/pipeline.js
  src/assets/pipeline-temp-empty.svg
  src/components/Forms/Pipelines/PipelineTemplate/index.jsx
  src/components/Forms/Pipelines/PipelineTemplate/index.scss
  src/components/Forms/Pipelines/PipelineTemplateParams/index.jsx
  src/components/Forms/Pipelines/PipelineTemplateParams/index.scss
  src/components/Forms/Pipelines/PipelineTemplateParams/params.jsx
  src/components/Modals/Create/Form/index.jsx
  src/components/Modals/Pipelines/PipelineEdit/index.jsx
  src/configs/steps/pipelines.js
  src/pages/devops/components/Modals/JenkinsEdit/index.jsx
  src/pages/devops/components/Pipeline/PipelineTemplate/index.jsx
  src/pages/devops/components/Pipeline/PipelineTemplate/index.scss
  src/pages/devops/components/Pipeline/PipelineTemplate/templePipeline.js
  src/pages/devops/components/Pipeline/Sider/index.jsx
  src/pages/devops/components/Pipeline/StepsEditor/index.jsx
  src/pages/devops/containers/Pipelines/Detail/PipeLine/index.jsx
  src/stores/devops/pipelines.js
Labels: lgtm, approved, size/XL, area/devops, kind/api-change, kind/feature, tide/merge-method-squash, release-note, kind/require-ui-text-review

#2978 Update UI text of Cluster Management.
  locales/en/base.js
  locales/en/l10n-clusterManagement-nodes-clusterNodes-details.js
  locales/en/l10n-clusterManagement-nodes-clusterNodes-list.js
  locales/en/l10n-clusterManagement-projects-list.js
  locales/en/l10n-clusterManagement-systemComponents-details.js
  locales/en/l10n-clusterManagement-systemComponents-list.js
  locales/en/project.js
  src/pages/clusters/containers/EdgeNodes/index.jsx
  src/pages/clusters/containers/Nodes/index.jsx
  src/pages/clusters/containers/Projects/index.jsx
  src/pages/clusters/containers/ServiceComponents/Card/index.jsx
  src/pages/clusters/containers/ServiceComponents/Detail/index.jsx
  src/pages/clusters/containers/ServiceComponents/Detail/routes.js
  src/pages/clusters/containers/ServiceComponents/index.jsx
Labels: lgtm, approved, size/M, kind/documentation, release-note-none

#2993 feat: Integrate OpenELB in KubeSphere for exposing the LoadBalancer type of service.
  src/pages/projects/components/Modals/GatewaySetting/contants.js
  src/pages/projects/components/Modals/GatewaySetting/index.jsx
Labels: lgtm, approved, size/S, kind/feature, release-note

#2994 Update UI text of Cluster Management.
  locales/en/l10n-clusterManagement-monitoring&Alerting-clusterStatus.js
  locales/en/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
  locales/en/l10n-projects-overview.js
  locales/en/pipeline.js
  src/components/Forms/Workload/ContainerSettings/ContainerForm/LifeManagement/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ProbeInput/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerList/QuotaCheck.jsx
  src/components/Inputs/ResourceLimit/index.jsx
  src/components/Modals/QuotaEdit/index.jsx
  src/pages/clusters/containers/Monitor/Cluster/Monitor/PhysicalResource/index.jsx
  src/pages/clusters/containers/Nodes/Detail/Monitoring/index.jsx
  src/pages/projects/components/Cards/Lifecycle/index.jsx
  src/pages/projects/components/WorkloadStatus/index.jsx
Labels: lgtm, approved, size/M, kind/documentation, release-note-none

#2996 docs: Fix grammar mistakes and typos.
  locales/ar/l10n-projects-configuration-serviceAccounts-details.js
  locales/en/l10n-projects-applicationWorkloads-routes-details.js
  locales/en/l10n-projects-configuration-serviceAccounts-details.js
  locales/fr/l10n-projects-configuration-serviceAccounts-details.js
  locales/hi/l10n-projects-configuration-serviceAccounts-details.js
  locales/lt/l10n-projects-configuration-serviceAccounts-details.js
  locales/pl/l10n-projects-configuration-serviceAccounts-details.js
  locales/tr/l10n-projects-configuration-serviceAccounts-details.js
  locales/zh/l10n-projects-applicationWorkloads-routes-details.js
  src/pages/fedprojects/containers/Routes/Detail/ResourceStatus/Rule/index.jsx
  src/pages/projects/containers/Routes/Detail/ResourceStatus/Rule.jsx
Labels: lgtm, approved, size/M, kind/documentation, release-note-none

#2997 docs: Fix an improper description on a tab.
  src/pages/projects/containers/ServiceAccounts/Detail/routes.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#2999 fix: Node num incorrect
  src/stores/node.js
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3001 fix: Remove role select function for service account edit modal.
  src/components/Modals/EditServiceAccount/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3005 Make required field determine whether the parameter is required
  src/components/Forms/Pipelines/PipelineTemplateParams/params.jsx
Labels: size/XS, lgtm, approved, area/devops, kind/optimization, release-note-none

#3006 Remove default value of label field when agent type is kubernetes
  src/pages/devops/components/Pipeline/Sider/index.jsx
Labels: size/XS, lgtm, approved, area/devops, kind/optimization, release-note

#3002 fix: Update terminal prompt.
  src/components/Modals/KubeCtl/index.jsx
  src/components/Modals/KubeCtl/index.scss
  src/components/Terminal/index.jsx
  src/components/Terminal/terminal.jsx
  src/pages/clusters/containers/Nodes/index.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note

#3007 Change the artifact download link on the Pipeline run page
  src/pages/devops/containers/Pipelines/Detail/Artifacts/index.jsx
  src/stores/devops/run.js
Labels: lgtm, approved, size/M, area/devops, kind/feature, release-note-none

#2992 fix: Remove the **Schedulable** field in cluster node details and edge node details
  src/pages/clusters/containers/EdgeNodes/Detail/index.jsx
  src/pages/clusters/containers/Nodes/Detail/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3004 fix: Optimize the UI of deleting a cluster, workspace, and project.
  locales/en/l10n-clusterManagement-clusterSettings-basicInformation.js
  locales/zh/l10n-clusterManagement-clusterSettings-basicInformation.js
  src/actions/cluster.js
  src/components/Modals/Delete/index.jsx
  src/pages/clusters/containers/BaseInfo/ManageButton/index.jsx
  src/pages/clusters/containers/BaseInfo/ManageButton/index.scss
  src/pages/clusters/containers/BaseInfo/index.jsx
  src/pages/clusters/containers/BaseInfo/index.scss
  src/pages/fedprojects/containers/BaseInfo/ProjectInfo/index.jsx
  src/pages/projects/containers/BaseInfo/ProjectInfo/index.jsx
  src/pages/projects/containers/BaseInfo/ProjectInfo/index.scss
  src/pages/workspaces/containers/BaseInfo/index.jsx
  src/pages/workspaces/containers/BaseInfo/index.scss
Labels: size/L, lgtm, approved, kind/bug, release-note

#3008 docs: Update UI text.
  locales/zh/l10n-clusterManagement-storage-storageClasses-list.js
  src/pages/clusters/containers/Storage/PV/detail/ResourceStatus/index.jsx
  src/pages/clusters/containers/Storage/PV/index.jsx
Labels: lgtm, approved, size/M, kind/documentation, release-note-none

#3010 Update UI text of 'Cluster Management'.
  locales/en/l10n-clusterManagement-applicationWorkloads-pods-list.js
  locales/en/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
  src/components/Forms/Workload/ContainerSettings/ContainerForm/SecurityContext/Capabilities/index.jsx
  src/pages/projects/containers/Pods/index.jsx
  src/utils/constants.js
Labels: lgtm, approved, size/M, kind/documentation, release-note-none

#3013 docs: Fix incorrectly displayed UI text.
  locales/ar/l10n-clusterManagement-storage-volumeSnapshots-list.js
  locales/en/l10n-clusterManagement-storage-volumeSnapshots-list.js
  locales/es/l10n-clusterManagement-storage-volumeSnapshots-list.js
  locales/fr/l10n-clusterManagement-storage-volumeSnapshots-list.js
  locales/hi/l10n-clusterManagement-storage-volumeSnapshots-list.js
  locales/lt/l10n-clusterManagement-storage-volumeSnapshots-list.js
  locales/pl/l10n-clusterManagement-storage-volumeSnapshots-list.js
  locales/tc/l10n-clusterManagement-storage-volumeSnapshots-list.js
  locales/tr/l10n-clusterManagement-storage-volumeSnapshots-list.js
  locales/zh/l10n-clusterManagement-storage-volumeSnapshots-list.js
Labels: lgtm, approved, size/M, kind/documentation, release-note-none

#3011 fix: Fix value of the private dockerhub repository in the container
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
  src/components/Tables/Base/index.scss
Labels: lgtm, approved, size/M, release-note

#2991 fix: Fix workspace role table not show aliasName
  src/pages/workspaces/containers/Roles/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, ok-to-test, release-note

#3014 feat: Add account enalbe or disable function
  src/components/HOCs/withTableActions.js
  src/components/Tables/Base/index.jsx
  src/pages/access/containers/Accounts/index.jsx
  src/stores/user.js
Labels: size/L, lgtm, approved, kind/feature, release-note

#3012 feat: Add Event tabs in pipeline run record
  src/pages/devops/containers/Pipelines/Detail/Events/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Layout/runs.jsx
  src/pages/devops/containers/Pipelines/Detail/index.js
  src/pages/devops/containers/Pipelines/Detail/routes.js
  src/stores/devops/run.js
Labels: lgtm, approved, size/M, area/devops, kind/feature, tide/merge-method-squash, release-note

#3019 chore: Add the missing icon for syncfailed on the ArgoCD status list page
  src/assets/cd/syncfailed.svg
  src/pages/devops/containers/CD/Components/StatusText/index.scss
  src/pages/devops/containers/CD/detail/index.jsx
Labels: lgtm, approved, size/M, area/devops, release-note-none

#3024 fix: User can enter detail page when a volume in terminating status.
  src/pages/clusters/containers/Storage/PV/index.jsx
  src/pages/clusters/containers/Storage/Volumes/Volume/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3025 fix: Can't create snapshot from volume detail page
  src/pages/projects/components/Modals/ResourceSnapshot/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3026 fix: Update volume inUse judgment condition
  src/utils/object.mapper.js
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3021 fix: Pvc list ui problem
  src/pages/clusters/containers/Storage/Volumes/Volume/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3022 feat: Add cd summary data in cd page
  locales/en/l10n-devopsProjects-cd-list.js
  src/actions/cd.js
  src/components/Forms/CD/BaseInfo/index.jsx
  src/pages/devops/containers/CD/CDList/index.jsx
  src/stores/cd.js
Labels: lgtm, approved, size/M, area/devops, kind/feature, release-note-none, kind/require-ui-text-review

#3027 docs: Update UI text.
  locales/en/l10n-clusterManagement-storage-storageClasses-list.js
  src/components/Forms/StorageClass/StorageClassSettings/index.jsx
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3037 fix: Update parameters's key to lowercase
  src/components/Forms/StorageClass/StorageClassSettings/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3035 docs: Update UI text.
  locales/en/l10n-clusterManagement-storage-storageClasses-list.js
  locales/zh/l10n-clusterManagement-storage-storageClasses-list.js
  src/utils/constants.js
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#3030 Fix the default cluster name of the argo app destination
  src/stores/cd.js
Labels: size/XS, lgtm, approved, area/devops, kind/bug, release-note-none

#2943 feat: Avoid use the secret value in the DevOps scm verify API.
  src/components/Forms/Pipelines/RepoSelect/BitBucketForm/index.jsx
  src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx
  src/stores/devops.js
  src/stores/devops/scm.js
Labels: lgtm, approved, size/M, area/devops, kind/feature, tide/merge-method-squash, release-note-none

#3036 fix: The volumeBindingMode of the created storageClass is always 'Immediate'
  src/components/Forms/StorageClass/StorageClassSettings/index.jsx
  src/utils/form.templates.js
Labels: size/XS, lgtm, approved, kind/bug, release-note

#3039 fix: Fix the icon of pipeline template
  src/assets/pipeline/ci-en.svg
  src/assets/pipeline/ci-temple-en.svg
  src/assets/pipeline/ci-zh.svg
  src/assets/pipeline/cicd-en.svg
  src/assets/pipeline/cicd-temple-en.svg
  src/assets/pipeline/cicd-zh.svg
  src/assets/pipeline/custom.svg
  src/assets/pipeline/golang.svg
  src/assets/pipeline/maven.svg
  src/assets/pipeline/nodejs.svg
  src/pages/devops/components/Pipeline/PipelineTemplate/index.jsx
  src/pages/devops/components/Pipeline/PipelineTemplate/index.scss
  src/stores/devops/pipelines.js
Labels: size/L, lgtm, approved, area/devops, release-note-none

#3028 fix: Modify the sync api
  src/actions/cd.js
  src/assets/cd/syncfailed.svg
  src/components/Modals/SyncModal/index.jsx
  src/pages/devops/containers/CD/CDList/index.jsx
  src/pages/devops/containers/CD/Components/StatusText/index.scss
  src/pages/devops/containers/CD/detail/index.jsx
  src/stores/cd.js
Labels: size/L, lgtm, approved, area/devops, kind/api-change, release-note-none
