Repository kubesphere/console, pull requests merged in 2022-10, with the labels that each got.

#3800 fix: Update app name
  src/pages/projects/containers/Services/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3801 fix: the update time is always the latest time on the service detail page
  src/pages/projects/containers/Services/Detail/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, ok-to-test, release-note

#3804 docs: Update UI text
  locales/en/l10n-clusterManagement-applicationWorkloads-services-list.js
  locales/en/l10n-clusterManagement-clusterSettings-logReceivers-list.js
  locales/en/l10n-toolbox-auditLogSearch-details.js
  locales/en/l10n-toolbox-auditLogSearch-list.js
  locales/en/l10n-toolbox-containerLogSearch-details.js
  locales/en/l10n-toolbox-containerLogSearch-list.js
  locales/en/l10n-toolbox-kubeconfig.js
  locales/en/l10n-toolbox-kubectl.js
  locales/en/l10n-toolbox-list.js
  locales/en/l10n-toolbox-resourceConsumptionStatistics-clusterResourceConsumption.js
  locales/en/l10n-toolbox-resourceConsumptionStatistics-workspaceResourceConsumption.js
  locales/en/l10n-toolbox-resourceConsumptionStatistics.js
  locales/en/l10n-toolbox-resourceEventSearch-details.js
  locales/en/l10n-toolbox-resourceEventSearch-list.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3807 docs: Update localization guide
  docs/join-the-kubesphere-localization-project.md
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#3813 docs: Update UI text.
  locales/en/l10n-clusterManagement-monitoring&Alerting-applicationResources.js
  locales/en/l10n-clusterManagement-monitoring&Alerting-clusterStatus.js
  locales/en/l10n-multiclusterProjects-configuration-configmaps-list.js
  locales/en/l10n-workspaces-overview-usageRanking.js
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#3815 docs: Update UI text.
  locales/en/l10n-clusterManagement-monitoring&Alerting-applicationResources.js
  locales/en/l10n-workspaces-overview-usageRanking.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3816 docs: Update UI text
  locales/en/l10n-clusterManagement-overview.js
  locales/en/l10n-devopsProjects-pipeline-details.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3810 feat: add revision record on the workload item when type is statefulsets or daemonsets
  src/pages/projects/components/Cards/Workloads/Item.jsx
Labels: lgtm, approved, size/M, kind/feature, ok-to-test, release-note

#3822 docs: Update UI text
  locales/en/l10n-projects-projectSettings-basicInformation.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3825 docs: Update UI text
  locales/en/l10n-clusterManagement-applicationWorkloads-deployments-details.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3823 fix: Remove slider in resource quota and can set value to 0
  src/components/Inputs/ResourceLimit/index.jsx
  src/utils/index.js
Labels: lgtm, approved, size/M, kind/bug, release-note

#3832 Feat: Add support page
  locales/en/l10n-technical-support.js
  src/assets/slack_duotone.svg
  src/assets/support-backup.svg
  src/assets/support-cluster-inspection.svg
  src/assets/support-ks-cloud.svg
  src/assets/support-ks.svg
  src/assets/support-kse-cluster.svg
  src/assets/support-kse-light.svg
  src/assets/support-kse-security.svg
  src/assets/support-kse.svg
  src/assets/support-light-cluster.svg
  src/assets/support-open-about-bg.svg
  src/assets/support-ticket-about-bg.svg
  src/assets/topic_circle_duotone.svg
  src/components/Layout/LoginInfo/index.jsx
  src/pages/console/containers/Support/index.jsx
  src/pages/console/containers/Support/index.scss
  src/pages/console/routes/index.js
Labels: lgtm, approved, size/XXL, kind/feature, release-note

#3834 docs: Update UI text
  locales/en/l10n-clusterManagement-applicationWorkloads-pods-details.js
  locales/en/l10n-projects-projectSettings-basicInformation.js
  src/pages/projects/containers/Pods/Containers/Detail.jsx
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#3841 docs: Update UI text of technical support
  locales/ar/l10n-technical-support.js
  locales/en/l10n-technical-support.js
  locales/en/l10n-technicalSupport.js
  locales/es/l10n-technical-support.js
  locales/fr/l10n-technical-support.js
  locales/hi/l10n-technical-support.js
  locales/ko/l10n-technical-support.js
  locales/lt/l10n-technical-support.js
  locales/pl/l10n-technical-support.js
  locales/tc/l10n-technical-support.js
  locales/tr/l10n-technical-support.js
  locales/zh/l10n-technical-support.js
  src/pages/console/containers/Support/index.jsx
Labels: lgtm, approved, size/XL, kind/documentation, release-note-none

#3721 feat: Change the kind from 'argo-project' to 'argocd'
  src/actions/cd.js
  src/utils/form.templates.js
Labels: size/XS, lgtm, approved, area/devops, kind/design, ok-to-test, release-note-none

#3844 docs: Change alerting message to alert
  locales/en/l10n-clusterManagement-monitoring&Alerting-alertingMessages.js
  locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
  locales/en/l10n-platformSettings-notificationManagement-notificationChannels.js
  locales/en/l10n-projects-monitoring&Alerting-alertingPolicies-list.js
  locales/en/l10n-projects-projectSettings-projectRoles-list.js
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#3846 fix: Fixed the cluster list was incorrectly displayed due to roles
  src/pages/clusters/containers/Visibility/index.jsx
  src/pages/workspaces/components/Modals/WorkspaceCreate/ClusterSettings/ClusterSelect/index.jsx
  src/stores/cluster/index.js
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#3849 docs: Update UI text
  locales/en/l10n-clusterManagement-clusters.js
  src/components/Forms/Cluster/Configuration/index.jsx
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3860 [release-3.3]fix: Support the value is 0 in resource quotas (#3856)
  package.json
  src/components/Inputs/ResourceLimit/index.jsx
  yarn.lock
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3864 fix: Get detail when pipeline run and add kubeconfigFile credential
  src/components/Inputs/ResourceLimit/index.jsx
  src/pages/devops/components/Pipeline/Sider/index.jsx
  src/pages/devops/components/Pipeline/StepModals/withCredentials.jsx
  src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Layout/branch.jsx
  src/pages/devops/containers/Pipelines/Detail/PipeLine/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3868 docs: Update UI text
  locales/ar/l10n-projects-projectSettings-basicInformation.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3871 docs: Update UI text
  locales/zh/l10n-projects-projectSettings-basicInformation.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3873 docs: Update UI text
  locales/en/l10n-projects-projectSettings-basicInformation.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3876 docs: Update UI text
  locales/ar/l10n-projects-applicationWorkloads-deployments-list.js
  src/components/Forms/Workload/VolumeSettings/AddVolumeTemplate/index.jsx
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3882 docs: Update UI text
  locales/en/l10n-clusterManagement-monitoring&Alerting-alertingMessages.js
  locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
  src/pages/projects/containers/Alerting/Messages/index.jsx
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#3887 fix: Fixed the CPU value of the container details that is displayed incorrectly because it has units.
  src/pages/projects/containers/Pods/Containers/Detail.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3889 fix: Fix the value encoded of the secret displayed incorrectly on the detail page
  src/pages/fedprojects/containers/Secrets/Detail/SecretDetail/index.jsx
  src/pages/projects/containers/Secrets/Detail/SecretDetail/index.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note

#3894 docs: Update UI text
  locales/en/idleComponents.js
  locales/en/l10n-clusterManagement-nodes-edgeNodes-list.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3897 fix: Fix visibility and edit cluster button in cluster displayed incorrectly
  src/pages/clusters/actions/cluster.js
  src/pages/clusters/components/Modals/ClusterVisibility/index.jsx
  src/pages/clusters/containers/BaseInfo/index.jsx
  src/pages/clusters/containers/Visibility/index.jsx
  src/stores/workspace.js
Labels: size/L, lgtm, approved, kind/bug, release-note-none

#3902 fix: Update slack channel address
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3903 chore: Optimize the width of the table's item list and the switch but…
  src/components/Base/Switch/index.scss
  src/components/Forms/CD/FluxCD/Advance/index.jsx
  src/pages/clusters/components/ResourceTable/ProjectSelect/index.scss
  src/pages/devops/containers/BaseInfo/index.jsx
  src/pages/devops/containers/BaseInfo/index.scss
  src/pages/projects/containers/Network/Policies/IsolateInfo/index.jsx
  src/pages/projects/containers/Network/Policies/IsolateInfo/index.scss
  src/pages/workspaces/components/ResourceTable/ClusterSelect/index.scss
Labels: size/L, lgtm, approved, kind/design, release-note-none

#3906 fix: Remove cluster in cluster visibility
  src/pages/clusters/containers/BaseInfo/index.jsx
  src/stores/workspace.js
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3908 [release-3.3]chore: Optimize the width of the table's item list and the switch but…
  src/components/Base/Switch/index.scss
  src/pages/clusters/components/ResourceTable/ProjectSelect/index.scss
  src/pages/devops/containers/BaseInfo/index.jsx
  src/pages/devops/containers/BaseInfo/index.scss
  src/pages/projects/containers/Network/Policies/IsolateInfo/index.jsx
  src/pages/projects/containers/Network/Policies/IsolateInfo/index.scss
  src/pages/workspaces/components/ResourceTable/ClusterSelect/index.scss
Labels: size/L, approved, kind/design, release-note-none

#3910 docs: Update UI text
  locales/en/l10n-logIn.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3913 docs: Modify the link in suport page
  server/config.yaml
  src/pages/console/containers/Support/index.jsx
  src/pages/console/containers/Support/index.scss
Labels: lgtm, approved, size/M, kind/documentation, release-note-none

#3917 docs: Update UI text of alerts and rule groups
  locales/en/l10n-accessControl-users-list.js
  locales/en/l10n-clusterManagement-monitoring&Alerting-alertingMessages.js
  locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-details.js
  locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
  locales/en/l10n-platformSettings-notificationManagement-notificationChannels.js
  locales/en/l10n-projects-monitoring&Alerting-alertingPolicies-details.js
  locales/en/l10n-projects-monitoring&Alerting-alertingPolicies-list.js
  locales/en/l10n-projects-projectSettings-projectRoles-list.js
  src/pages/projects/containers/Alerting/Policies/index.jsx
Labels: lgtm, approved, size/M, kind/documentation, release-note-none
