Repository kubesphere/console, pull requests merged in 2022-07, with the labels that each got.

#3416 fix: Form can't save when creating a workload
  src/components/Forms/Workload/VolumeSettings/MountConfig/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3420 fix: Path parsing error in windows environment
  scripts/checkRepeat.js
Labels: size/XS, lgtm, approved, kind/bug, ok-to-test, release-note-none

#3427 fix: Render wrong form item while multiple branch
  src/components/Forms/Pipelines/ParamsFormModal/index.jsx
Labels: size/XS, lgtm, approved, area/devops, kind/bug, release-note-none

#3411 Setting the hostpath is required when mounting the hostpath storage volume to an application
  locales/ar/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
  locales/en/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
  locales/es/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
  locales/fr/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
  locales/hi/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
  locales/ko/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
  locales/lt/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
  locales/pl/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
  locales/tc/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
  locales/tr/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
  locales/zh/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
  src/components/Forms/Workload/VolumeSettings/AddHostPath/index.jsx
Labels: lgtm, approved, size/S, kind/bug, ok-to-test, release-note

#3426 fix: canary release is invalid, when multiple operating systems are selected
  src/components/Forms/GrayRelease/PolicyConfig/Canary/OSSelect/index.jsx
  src/pages/projects/components/Modals/GrayReleaseDetail/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, ok-to-test, release-note

#3430 fix:the associated hpa hasn't been deleted when use the command line to delete the deployment
  src/pages/projects/components/Modals/HPA/index.jsx
Labels: lgtm, approved, size/S, kind/bug, ok-to-test, release-note-none

#3425 fix: Fix the valide of referer url
  server/libs/utils.js
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3433 fix: docs in pipeline page 404 not found
  server/config.yaml
Labels: size/XS, lgtm, approved, area/devops, kind/documentation, ok-to-test, release-note

#3434 fix: Wrong "volumeBindingMode" params when I add PVC
  src/components/Forms/StorageClass/StorageClassSettings/index.jsx
  src/pages/clusters/containers/Storage/StorageClasses/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3435 feat: Support for modifying the number of data per page of table
  locales/en/l10n-clusterManagement-applicationWorkloads-deployments-list.js
  src/components/Tables/Base/Pagination/index.jsx
  src/components/Tables/Base/Pagination/index.scss
  src/components/Tables/Base/index.jsx
  src/components/Tables/Base/index.scss
  src/utils/constants.js
Labels: size/L, lgtm, approved, kind/feature, release-note

#3436 docs: Update UI text of creation/update time
  locales/en/l10n-clusterManagement-nodes-clusterNodes-details.js
  locales/en/l10n-projects-applicationWorkloads-apps-templateBasedApps-details.js
  src/components/Cards/Pods/Item.jsx
  src/components/Tables/Base/index.jsx
  src/pages/clusters/containers/Gateway/Components/Pods/Item.jsx
  src/pages/projects/components/Cards/Workloads/Item.jsx
  src/pages/projects/containers/Services/index.jsx
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#3432 docs: modify git commit command line and add signature reference documentation
  docs/development-workflow.md
Labels: size/XS, lgtm, approved, kind/documentation, ok-to-test, release-note-none

#3440 fix: Optimize the 'Application governance' parameter on the app details page
  src/pages/projects/components/Cards/Services/Item.jsx
  src/pages/projects/containers/Applications/CRDAppDetail/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3444 fix: Display the type of each workload on the app details page
  src/pages/projects/components/Cards/Workloads/Item.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3443 fix: Remove the 'App' field on the composed app details page
  src/pages/projects/containers/Applications/CRDAppDetail/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3452 feat: Support batch stop workloads
  locales/en/l10n-projects-applicationWorkloads-daemonsets-list.js
  locales/en/l10n-projects-applicationWorkloads-statefulsets-list.js
  src/pages/clusters/containers/Workload/DaemonSets/index.jsx
  src/pages/clusters/containers/Workload/StatefulSets/index.jsx
  src/pages/fedprojects/containers/Deployments/index.jsx
  src/pages/fedprojects/containers/StatefulSets/index.jsx
  src/pages/projects/containers/DaemonSets/index.jsx
  src/pages/projects/containers/Deployments/index.jsx
  src/pages/projects/containers/StatefulSets/index.jsx
  src/stores/federated.js
  src/stores/workload/index.js
Labels: size/L, lgtm, approved, kind/feature, release-note, kind/require-ui-text-review

#3456 fix: Missing openelb annotation hint when creating service of type loadbalancer
  locales/en/l10n-clusterManagement-applicationWorkloads-services-list.js
  src/components/Forms/Service/AdvanceSettings/InternetAccess/index.jsx
  src/components/Forms/Service/AdvanceSettings/InternetAccess/index.scss
  src/components/Forms/Service/AdvanceSettings/index.jsx
  src/stores/openelb.js
Labels: size/L, lgtm, approved, kind/bug, release-note, kind/require-ui-text-review

#3450 refactor: Avoid using API tojson and tojenkinsfile
  locales/en/l10n-devopsProjects-pipeline-details.js
  src/actions/pipeline.js
  src/pages/devops/components/Modals/JenkinsEdit/index.jsx
  src/pages/devops/components/Pipeline/Sider/index.jsx
  src/pages/devops/components/Pipeline/store.js
  src/pages/devops/containers/Pipelines/Detail/PipeLine/index.jsx
  src/pages/devops/containers/Pipelines/Detail/PipeLine/index.scss
  src/stores/devops/pipelines.js
Labels: size/L, lgtm, approved, area/devops, kind/api-change, release-note-none

#3458 fix: Update OpenELB check url
  src/stores/openelb.js
Labels: size/XS, lgtm, approved, release-note-none

#3459 fix: Add monitoring items to the custom monitoring panel, and the monitoring indicators display errors
  src/components/Base/Cascader/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3442 fix: incorrect parameters were created by glusterfs storageclass
  src/components/Forms/StorageClass/StorageClassSettings/index.jsx
  src/utils/constants.js
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3457 fix: Status icon not show in multi-cluster deployment
  src/pages/fedprojects/components/ClusterWorkloadStatus/Cluster.jsx
  src/pages/fedprojects/components/ClusterWorkloadStatus/ScheduleCluster.jsx
  src/pages/fedprojects/components/ClusterWorkloadStatus/index.scss
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3461 docs: Update UI text
  locales/en/l10n-clusterManagement-applicationWorkloads-deployments-list.js
  locales/en/l10n-projects-applicationWorkloads-apps-templateBasedApps-details.js
  locales/en/l10n-projects-applicationWorkloads-apps-templateBasedApps-list.js
  src/components/Tables/Base/Pagination/index.jsx
  src/pages/projects/containers/Applications/OPApps.jsx
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#3455 fix: Fix the External services cause the "Services" page to crash
  package.json
  src/pages/projects/containers/Services/index.jsx
  src/pages/workspaces/containers/Repos/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note

#3467 fix: The gidMax and gidMin in the storage class GlusterFs are not format checked
  locales/en/l10n-clusterManagement-storage-storageClasses-list.js
  src/components/Forms/StorageClass/StorageClassSettings/TailInput.jsx
  src/components/Forms/StorageClass/StorageClassSettings/index.jsx
  src/components/Inputs/TailIUnitInput/index.jsx
Labels: lgtm, approved, size/M, kind/require-ui-text-review

#3468 fix: For single-cluster environments, the 'Update kubeconfig' button should be canceled.
  src/pages/clusters/containers/BaseInfo/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3464 feat: Support to edit continuous deployments settings
  src/actions/cd.js
  src/components/Forms/CD/Advance/Parameter/HelmForm/index.jsx
  src/components/Forms/CD/Advance/Parameter/ImagesInput/index.jsx
  src/components/Forms/CD/Advance/Parameter/KustomizeForm/index.jsx
  src/components/Forms/CD/Advance/Parameter/index.jsx
  src/components/Forms/CD/Advance/Placement/index.jsx
  src/components/Forms/CD/Advance/index.jsx
  src/components/Modals/CDAdvanceEdit/index.jsx
  src/pages/devops/containers/CD/CDList/index.jsx
  src/pages/devops/containers/CD/detail/index.jsx
Labels: size/L, lgtm, approved, area/devops, kind/feature, release-note

#3460 fix: Fix the key is not display in LoadBalancer
  src/pages/projects/components/Modals/CreateApp/index.jsx
  src/pages/projects/components/Modals/GatewaySetting/index.jsx
  src/pages/projects/components/Modals/ServiceGatewaySetting/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note

#3448 fix: When accessing an edge node, the page is blank and no content is displayed
  src/utils/object.mapper.js
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3470 docs: Update UI text.
  locales/en/l10n-clusterManagement-configuration-secrets-list.js
  locales/en/l10n-toobox-resourceConsumptionStatistics.js
  src/pages/projects/components/Cards/ImageRunRecord/Item/index.jsx
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#3462 feat: Add reminder to sync locales files in command before compiling
  package.json
  scripts/checkLocales.js
  scripts/locale-plugin.js
Labels: lgtm, approved, size/M, kind/feature, release-note-none

#3471 fix: Modify the route of the dashboard when another role login in.
  src/components/Forms/Notification/FeiShuForm/index.jsx
  src/pages/console/containers/Dashboard/index.jsx
  src/pages/settings/containers/Notification/DingTalk/index.jsx
  src/pages/settings/containers/Notification/FeiShu/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none
