Repository kubesphere/console, pull requests merged in 2022-08, with the labels that each got.

#3472 docs: Change 'grayscale release job' to 'grayscale release task'
  locales/en/l10n-projects-applicationWorkloads-apps-composedApps-details.js
  locales/en/l10n-projects-grayscaleRelease.js
  locales/en/l10n-projects-projectSettings-projectRoles-list.js
  src/components/Forms/GrayRelease/Components/Card/index.jsx
  src/pages/projects/components/Modals/GrayReleaseDetail/Edit/index.jsx
  src/pages/projects/components/Modals/GrayReleaseDetail/index.jsx
  src/pages/projects/containers/Applications/CRDAppDetail/GrayRelease/index.jsx
  src/pages/projects/containers/GrayRelease/Categories/index.jsx
  src/pages/projects/containers/GrayRelease/Jobs/index.jsx
  src/pages/projects/routes/grayrelease.js
Labels: lgtm, approved, size/M, kind/documentation, release-note-none

#3474 docs: Update UI text of log search
  locales/en/l10n-accessControl-workspaces-list.js
  locales/en/l10n-toobox-auditLogSearch-list.js
  locales/en/l10n-toobox-containerLogSearch-list.js
  locales/en/l10n-toobox-resourceEventSearch-list.js
  src/components/Modals/AuditingSearch/index.jsx
  src/components/Modals/Bill/Details/Cluster/index.jsx
  src/components/Modals/EventSearch/index.jsx
  src/components/Modals/LogSearch/index.jsx
  src/pages/workspaces/components/ResourceTable/index.jsx
  src/pages/workspaces/containers/BaseInfo/index.jsx
  src/pages/workspaces/containers/Clusters/index.jsx
  src/pages/workspaces/containers/Overview/Clusters/index.jsx
  src/pages/workspaces/containers/Overview/ResourceUsage/index.jsx
  src/pages/workspaces/containers/Overview/UsageRanking/index.jsx
Labels: lgtm, approved, size/M, kind/documentation, release-note-none

#3488 docs: Update UI text of grayscale release
  locales/ar/l10n-projects-grayscaleRelease.js
  locales/en/l10n-projects-applicationWorkloads-apps-composedApps-details.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3489 fix: When you do not select key or path to save, there is no prompt information on the page.
  src/components/Forms/Workload/VolumeSettings/MountConfig/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3490 fix: Replace atob for encod encryption in login
  src/core/containers/Login/index.jsx
  src/utils/index.js
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3511 fix: Update delete text for storageclass
  locales/en/l10n-clusterManagement-storage-storageClasses-list.js
  server/services/session.js
  src/actions/storageclass.js
Labels: lgtm, approved, size/S, kind/bug, release-note-none, kind/require-ui-text-review

#3522 fix: Display volume template info in statefulsets setting modal
  src/components/Forms/Workload/VolumeSettings/VolumeTemplateList/Card.jsx
  src/components/Forms/Workload/VolumeSettings/VolumeTemplateList/index.jsx
  src/components/Forms/Workload/VolumeSettings/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3523 docs: Update UI text of image builders
  locales/en/l10n-projects-imageBuilders-details.js
  locales/en/l10n-projects-imageBuilders-list.js
  src/pages/projects/containers/ImageBuilder/Detail/index.jsx
  src/pages/projects/containers/ImageBuilder/index.jsx
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#3529 Fix bug of UI text
  src/pages/projects/containers/ImageBuilder/index.jsx
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3525 docs: Update UI text for release 3.3.1
  locales/en/l10n-clusterManagement-applicationWorkloads-services-list.js
  locales/en/l10n-clusterManagement-storage-storageClasses-list.js
  locales/en/l10n-devopsProjects-pipeline-details.js
  locales/en/l10n-platformSettings-notificationManagement-notificationConfiguration.js
  locales/en/l10n-projects-applicationWorkloads-daemonsets-list.js
  src/pages/clusters/containers/Workload/DaemonSets/index.jsx
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#3532 docs: Cherry pick UI text to release-3.3.
  locales/en/l10n-clusterManagement-applicationWorkloads-deployments-list.js
  locales/en/l10n-clusterManagement-applicationWorkloads-services-list.js
  locales/en/l10n-clusterManagement-storage-storageClasses-list.js
  locales/en/l10n-devopsProjects-pipeline-details.js
  locales/en/l10n-platformSettings-notificationManagement-notificationConfiguration.js
  locales/en/l10n-projects-applicationWorkloads-apps-templateBasedApps-details.js
  locales/en/l10n-projects-applicationWorkloads-apps-templateBasedApps-list.js
  locales/en/l10n-projects-applicationWorkloads-daemonsets-list.js
  src/components/Tables/Base/Pagination/index.jsx
  src/pages/clusters/containers/Workload/DaemonSets/index.jsx
  src/pages/projects/containers/Applications/OPApps.jsx
Labels: lgtm, approved, size/M, kind/documentation, release-note-none

#3524 fix: Add empty message in image builder create modal
  locales/en/l10n-projects-imageBuilders-list.js
  src/components/Forms/ImageBuilder/LanguageSelect/index.jsx
Labels: lgtm, approved, size/S, area/devops, kind/bug, release-note, kind/require-ui-text-review

#3535 docs: Fix bug of UI text
  src/pages/projects/components/Cards/ImageBuilderLastRun/index.jsx
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3539 docs: Update UI text of project deletion
  locales/en/l10n-projects-projectSettings-basicInformation.js
  src/pages/projects/containers/BaseInfo/index.jsx
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3451 fix: application's updatetime always is current time
  src/utils/object.mapper.js
Labels: lgtm, approved, size/S, kind/bug, ok-to-test, release-note

#3473 fix: traffic allocation fails after taking over traffic in the canary release modal.
  src/pages/projects/components/Modals/GrayReleaseDetail/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, ok-to-test, release-note

#3512 refactor: Replace the labelsData api with the nodelabels api
  src/pages/devops/components/Pipeline/index.jsx
  src/pages/devops/components/Pipeline/store.js
Labels: lgtm, approved, size/M, area/console, release-note-none

#3513 fix: Avoid the being deleting Pipelines on the list page
  src/stores/devops/pipelines.js
Labels: size/XS, lgtm, approved, area/devops, kind/bug, release-note-none

#3545 fix: Modify the cluster module key of edge node
  src/components/Forms/Service/AdvanceSettings/NodeSchedule/NodeSelect/index.jsx
  src/components/Forms/Workload/AdvanceSettings/NodeSchedule/NodeSelect/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note

#3550 [release-3.3] fix: Update OpenELB check url
  src/stores/openelb.js
Labels: size/XS, approved, release-note

#3551 [release-3.3]fix: Fix the External services cause the "Services" page to crash
  package.json
  src/pages/projects/containers/Services/index.jsx
  src/pages/workspaces/containers/Repos/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3549 fix: Modify the api of get cluster list in different user login
  src/components/Modals/ContianerTerminal/index.jsx
  src/pages/clusters/containers/Clusters/index.jsx
  src/pages/workspaces/components/Modals/WorkspaceCreate/ClusterSettings/ClusterSelect/index.jsx
  src/pages/workspaces/components/Modals/WorkspaceSelect/index.jsx
  src/pages/workspaces/containers/Projects/index.jsx
  src/stores/cluster/index.js
Labels: lgtm, approved, size/M, kind/bug, release-note

#3553 fix: User with cluster view role, view storage class details error
  src/pages/clusters/containers/Storage/StorageClasses/Detail/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3547 fix: Fix ingress monitoring data time unit
  src/pages/clusters/containers/Gateway/Components/MonitoringOverview/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note

#3543 fix: misbehaving when editing or deleting an image of the same name
  locales/ar/l10n-projects-applicationWorkloads-deployments-list.js
  locales/en/l10n-projects-applicationWorkloads-deployments-list.js
  locales/es/l10n-projects-applicationWorkloads-deployments-list.js
  locales/fr/l10n-projects-applicationWorkloads-deployments-list.js
  locales/hi/l10n-projects-applicationWorkloads-deployments-list.js
  locales/ko/l10n-projects-applicationWorkloads-deployments-list.js
  locales/lt/l10n-projects-applicationWorkloads-deployments-list.js
  locales/pl/l10n-projects-applicationWorkloads-deployments-list.js
  locales/tc/l10n-projects-applicationWorkloads-deployments-list.js
  locales/tr/l10n-projects-applicationWorkloads-deployments-list.js
  locales/zh/l10n-projects-applicationWorkloads-deployments-list.js
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/index.jsx
  src/components/Forms/Workload/ContainerSettings/index.jsx
Labels: lgtm, approved, size/M, area/console, kind/bug, kind/feature, ok-to-test, release-note

#3554 fix: inaccurate container missing validation hints
  locales/ar/l10n-projects-applicationWorkloads-deployments-list.js
  locales/en/l10n-projects-applicationWorkloads-deployments-list.js
  locales/es/l10n-projects-applicationWorkloads-deployments-list.js
  locales/fr/l10n-projects-applicationWorkloads-deployments-list.js
  locales/hi/l10n-projects-applicationWorkloads-deployments-list.js
  locales/ko/l10n-projects-applicationWorkloads-deployments-list.js
  locales/lt/l10n-projects-applicationWorkloads-deployments-list.js
  locales/pl/l10n-projects-applicationWorkloads-deployments-list.js
  locales/tc/l10n-projects-applicationWorkloads-deployments-list.js
  locales/tr/l10n-projects-applicationWorkloads-deployments-list.js
  locales/zh/l10n-projects-applicationWorkloads-deployments-list.js
Labels: lgtm, approved, size/S, kind/bug, ok-to-test, release-note

#3558 feat: Support CD directory recurse
  locales/en/l10n-devopsProjects-continuousDeployments-list.js
  src/components/Forms/CD/Advance/index.jsx
  src/components/Forms/CD/Advance/index.scss
Labels: lgtm, approved, size/S, area/devops, kind/feature, release-note

#3562 fix: Give the cluster view role when a list of clusters can be obtained
  server/services/session.js
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3408 fix: Support the logs wrapping
  src/components/Cards/ContainerLog/index.scss
Labels: size/XS, lgtm, approved, ok-to-test, release-note-none

#3573 fix: Table pgaesize scroll style
  src/components/Tables/Base/Pagination/index.jsx
  src/components/Tables/Base/Pagination/index.scss
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3564 fix: OAuth login state error
  server/controllers/session.js
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3578 fix: Missing openelb annotation hint when editing service of type loadbalancer
  src/pages/projects/components/Modals/ServiceGatewaySetting/index.jsx
  src/pages/projects/components/Modals/ServiceGatewaySetting/index.scss
Labels: size/L, lgtm, approved, release-note-none

#3580 fix: Get snapshotclass api warning
  src/actions/volume.js
  src/pages/projects/containers/Volumes/Detail/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3579 fix: When you do not select key or path to save, you cant save it
  locales/en/workload.js
  src/components/Forms/Workload/VolumeSettings/MountConfig/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none, kind/require-ui-text-review

#3581 fix: Fix the limit not change in pagination
  src/stores/devops/pipelines.js
  src/stores/devops/run.js
Labels: lgtm, approved, size/M, area/devops, kind/bug, release-note-none

#3587 fix: App review list page settings pagination fault
  src/components/Base/Image/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3593 docs: Update UI text of 'Add Cluster'
  locales/ar/cluster.js
  locales/ar/idle-components.js
  locales/ar/l10n-clusterManagement-clusters.js
  locales/en/cluster.js
  locales/en/idle-components.js
  locales/en/l10n-clusterManagement-clusters.js
  locales/es/cluster.js
  locales/es/idle-components.js
  locales/es/l10n-clusterManagement-clusters.js
  locales/fr/cluster.js
  locales/fr/idle-components.js
  locales/fr/l10n-clusterManagement-clusters.js
  locales/hi/cluster.js
  locales/hi/idle-components.js
  locales/hi/l10n-clusterManagement-clusters.js
  locales/ko/cluster.js
  locales/ko/idle-components.js
  locales/ko/l10n-clusterManagement-clusters.js
  locales/lt/cluster.js
  locales/lt/idle-components.js
  locales/lt/l10n-clusterManagement-clusters.js
  locales/pl/cluster.js
  locales/pl/idle-components.js
  locales/pl/l10n-clusterManagement-clusters.js
  locales/tc/cluster.js
  locales/tc/idle-components.js
  locales/tc/l10n-clusterManagement-clusters.js
  locales/tr/cluster.js
  locales/tr/idle-components.js
  locales/tr/l10n-clusterManagement-clusters.js
  locales/zh/cluster.js
  locales/zh/idle-components.js
  locales/zh/l10n-clusterManagement-clusters.js
  src/components/Forms/Cluster/BaseInfo/index.jsx
  src/components/Forms/Cluster/Configuration/index.jsx
  src/configs/steps/clusters.js
Labels: lgtm, approved, size/M, kind/documentation, release-note-none

#3592 feat: Support load pipeline steps by api
  src/pages/devops/components/Pipeline/StepModals/application.jsx
  src/pages/devops/components/Pipeline/StepModals/archiveArtifacts.jsx
  src/pages/devops/components/Pipeline/StepModals/cd.jsx
  src/pages/devops/components/Pipeline/StepModals/checkout.jsx
  src/pages/devops/components/Pipeline/StepModals/cleanWs.jsx
  src/pages/devops/components/Pipeline/StepModals/container.jsx
  src/pages/devops/components/Pipeline/StepModals/credential.jsx
  src/pages/devops/components/Pipeline/StepModals/dir.jsx
  src/pages/devops/components/Pipeline/StepModals/echo.jsx
  src/pages/devops/components/Pipeline/StepModals/git.jsx
  src/pages/devops/components/Pipeline/StepModals/index.js
  src/pages/devops/components/Pipeline/StepModals/input.jsx
  src/pages/devops/components/Pipeline/StepModals/kubernetesDeploy.jsx
  src/pages/devops/components/Pipeline/StepModals/mail.jsx
  src/pages/devops/components/Pipeline/StepModals/params.jsx
  src/pages/devops/components/Pipeline/StepModals/pipeline.jsx
  src/pages/devops/components/Pipeline/StepModals/script.jsx
  src/pages/devops/components/Pipeline/StepModals/shell.jsx
  src/pages/devops/components/Pipeline/StepModals/sonarqube.jsx
  src/pages/devops/components/Pipeline/StepModals/timeout.jsx
  src/pages/devops/components/Pipeline/StepModals/waitForQualityGate.jsx
  src/pages/devops/components/Pipeline/StepModals/withCredentials.jsx
  src/pages/devops/components/Pipeline/StepsEditor/StepCard.jsx
  src/pages/devops/components/Pipeline/StepsEditor/index.jsx
  src/pages/devops/components/Pipeline/StepsSelector/index.jsx
  src/pages/devops/components/Pipeline/StepsSelector/index.scss
  src/pages/devops/components/Pipeline/store.js
  src/utils/constants.js
  src/utils/devops.js
Labels: lgtm, approved, size/XXL, area/devops, kind/feature, release-note

#3597 fix: Fix the query param of role template in role detail page
  src/pages/access/containers/Roles/Detail/AuthorizationList/index.jsx
  src/pages/clusters/containers/Roles/index.jsx
  src/stores/role.js
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#3577 fix: failed to create routing rules in ipv6 and ipv4 dual-stack environment
  src/utils/object.mapper.js
Labels: size/XS, lgtm, approved, kind/bug, ok-to-test, release-note

#3602 fix: Fix router data is incorrect after canceling editing
  src/components/Inputs/RulePath/index.jsx
  src/pages/projects/components/Modals/CreateApp/Routes/RuleList/index.jsx
  src/pages/projects/components/Modals/CreateApp/Routes/index.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#3603 fix: Fix the word is blocked in bill page
  src/components/Modals/Bill/components/TimeSelect/index.jsx
  src/components/Modals/Bill/components/TimeSelect/index.scss
Labels: size/L, lgtm, approved, kind/bug, release-note-none

#3591 optimization the image building of KubeSphere/console
  build/Dockerfile.dapper
  hack/docker_build_multiarch.sh
Labels: lgtm, approved, size/M, needs-ok-to-test, release-note

#3612 docs: Update UI text of cluster management
  locales/en/l10n-clusterManagement-clusters.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3616 docs: Update UI text of cluster management
  locales/en/l10n-projects-applicationWorkloads-daemonsets-list.js
  locales/en/l10n-projects-applicationWorkloads-deployments-list.js
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3619 docs: Update UI text of daemonsets
  locales/en/l10n-projects-applicationWorkloads-daemonsets-list.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3617 fix: Fix some issues about image search and edit cluster config
  src/components/Forms/AppDeploy/AppConfig/SchemaForm/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/index.jsx
  src/pages/clusters/containers/Clusters/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3627 Update owners
  OWNERS
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3626 docs: Update UI text of 'Log Receivers'
  locales/en/l10n-clusterManagement-clusterSettings-logReceivers-details.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3632 fix: Fix the initial container is incorrect when deleting the volume
  src/components/Forms/Workload/VolumeSettings/VolumeList/index.jsx
  src/components/Forms/Workload/VolumeSettings/VolumeTemplateList/index.jsx
Labels: size/XS, lgtm, approved, release-note-none

#3635 fix: generate random string to replace numberic name
  src/pages/devops/components/Pipeline/store.js
Labels: size/XS, lgtm, approved, area/devops, kind/bug, release-note-none
