Repository kubesphere/console, pull requests merged in 2022-05, with the labels that each got.

#3226 Update UI text of 'Continuous Deployments'
  locales/en/l10n-devopsProjects-continuousDeployments-list.js
  src/pages/devops/containers/CD/CDList/index.jsx
  src/utils/constants.js
Labels: lgtm, approved, size/S, area/devops, kind/documentation, release-note-none

#3211 fix: When creating a CD task, selecting ‘replace resource' did not take effect
  src/components/Forms/CD/Advance/index.jsx
Labels: lgtm, approved, size/S, area/devops, kind/bug, release-note-none

#3232 Add Patrick-LuoYu to the approver list
  OWNERS
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3233 fix: Optimize the ui
  src/actions/pipeline.js
  src/components/Forms/Pipelines/PipelineTemplate/index.scss
  src/components/Forms/Pipelines/PipelineTemplateParams/index.jsx
  src/components/Forms/Pipelines/PipelineTemplateParams/index.scss
  src/pages/devops/components/Pipeline/PipelineTemplate/index.scss
  src/pages/devops/containers/CD/Components/ChartCard/index.jsx
  src/pages/devops/containers/CD/Components/ChartCard/index.scss
  src/pages/devops/containers/Pipelines/Detail/PipeLine/index.jsx
Labels: lgtm, approved, size/M, kind/design, release-note-none

#3234 fix: Update button list style
  src/pages/clusters/components/Cards/Cluster/index.jsx
  src/pages/clusters/components/Cards/Cluster/index.scss
  src/pages/clusters/containers/BaseInfo/index.jsx
Labels: lgtm, approved, size/M, kind/design, release-note-none

#3222 feat: Add more repos and orgs in Github
  server/config.yaml
  src/components/Base/ScrollLoad/index.jsx
  src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx
  src/components/Forms/Pipelines/RepoSelect/GithubForm/index.scss
  src/stores/devops/scm.js
Labels: size/L, lgtm, approved, area/devops, kind/feature, release-note

#3167 perf: Add throttle for Slider components
  src/components/Inputs/ResourceLimit/Slider.jsx
Labels: lgtm, approved, size/S, ok-to-test, release-note-none

#3237 Fix bug in account item actions
  src/pages/access/containers/Accounts/index.jsx
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3224 feat: Add enabled or disabled of allow list in devops base info
  locales/en/l10n-devopsProjects-devopsProjectSettings-basinInformation.js
  src/pages/devops/containers/BaseInfo/index.jsx
  src/pages/devops/containers/BaseInfo/index.scss
Labels: size/L, lgtm, approved, area/devops, kind/feature, release-note-none, kind/require-ui-text-review

#3242 fix: Container information is blocked
  src/pages/projects/components/StatusReason/index.scss
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3243 fix: Can not cancel Post-Start or Pre-Stop alone
  src/components/Forms/Workload/ContainerSettings/ContainerForm/LifeManagement/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ProbeInput/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3245 Update UI text of 'Storage'
  locales/en/l10n-clusterManagement-storage-persistentVolumes-details.js
  locales/en/l10n-clusterManagement-storage-persistentVolumes-list.js
  locales/en/l10n-clusterManagement-storage-volumeSnapshotContent-list.js
  src/pages/clusters/containers/Members/index.jsx
  src/pages/clusters/containers/Storage/PV/detail/index.jsx
  src/pages/clusters/containers/Storage/VolumeSnapshots/SnapshotContent/Detail/index.jsx
  src/pages/clusters/containers/Storage/VolumeSnapshots/SnapshotContent/index.jsx
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#3246 fix: The created time of service in Service Topology is error
  src/pages/projects/containers/Services/Topology/Detail/BaseInfo/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3248 Update UI text of 'DevOps Projects'
  locales/en/l10n-clusterManagement-applicationWorkloads-deployments-list.js
  locales/en/l10n-devopsProjects-devopsProjectSettings-basinInformation.js
  locales/en/workload.js
  src/pages/devops/containers/BaseInfo/index.jsx
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#3240 fix: Modify the api of get bitbucket org
  src/components/Forms/Pipelines/RepoSelect/BitBucketForm/index.jsx
  src/stores/devops/scm.js
Labels: size/L, lgtm, approved, area/devops, kind/api-change, release-note-none

#3252 fix: Add all in repo and placement in allowlist
  server/config.yaml
  src/actions/codeRepo.js
  src/components/Forms/Pipelines/RepoSelect/BitBucketForm/index.jsx
  src/components/Modals/DevOpsAllowList/Destinations.jsx
  src/components/Modals/DevOpsAllowList/index.jsx
  src/pages/devops/containers/CodeRepo/CRList/index.jsx
  src/pages/devops/containers/Pipelines/PipelinesList/index.jsx
  src/stores/devops/pipelines.js
  src/stores/project.js
Labels: size/L, lgtm, approved, area/devops, kind/bug, release-note-none

#3257 fix: Update storagecontent table icon when list data is empty
  src/pages/clusters/containers/Storage/VolumeSnapshots/index.jsx
  src/utils/constants.js
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3258 fix: Update key name for service topology detail item
  src/pages/projects/containers/Services/Topology/Detail/BaseInfo/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3263 fix: Fix the display error in allowlist
  src/actions/devops.js
  src/components/Modals/DevOpsAllowList/Destinations.jsx
  src/components/Modals/DevOpsAllowList/index.jsx
  src/pages/devops/containers/BaseInfo/index.jsx
Labels: size/L, lgtm, approved, area/devops, kind/bug, release-note-none

#3264 feat: Support state parameter in OAuth URL
  server/controllers/session.js
Labels: lgtm, approved, size/S, kind/feature, release-note-none

#3266 Update UI text of 'Persistent Volume Claims'
  locales/en/l10n-clusterManagement-storage-persistentVolumeClaims-list.js
  src/actions/volume.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3276 fix: Wrong name of containers in service details in Service Topology
  src/pages/projects/containers/Services/Topology/Detail/Containers/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3270 Remove redundant locale files
  locales/ar/l10n-clusterManagement-storage-volumes-details.js
  locales/ar/l10n-clusterManagement-storage-volumes-list.js
  locales/es/l10n-clusterManagement-storage-volumes-details.js
  locales/es/l10n-clusterManagement-storage-volumes-list.js
  locales/fr/l10n-clusterManagement-storage-volumes-details.js
  locales/fr/l10n-clusterManagement-storage-volumes-list.js
  locales/hi/l10n-clusterManagement-storage-volumes-details.js
  locales/hi/l10n-clusterManagement-storage-volumes-list.js
  locales/ko/l10n-clusterManagement-storage-volumes-details.js
  locales/ko/l10n-clusterManagement-storage-volumes-list.js
  locales/ko/workload.js
  locales/lt/l10n-clusterManagement-storage-volumes-details.js
  locales/lt/l10n-clusterManagement-storage-volumes-list.js
  locales/pl/l10n-clusterManagement-storage-volumes-details.js
  locales/pl/l10n-clusterManagement-storage-volumes-list.js
  locales/tc/l10n-clusterManagement-storage-volumes-details.js
  locales/tc/l10n-clusterManagement-storage-volumes-list.js
  locales/tr/l10n-clusterManagement-storage-volumes-details.js
  locales/tr/l10n-clusterManagement-storage-volumes-list.js
  locales/zh/l10n-clusterManagement-storage-volumes-details.js
  locales/zh/l10n-clusterManagement-storage-volumes-list.js
Labels: lgtm, approved, size/XL, kind/documentation, release-note-none

#3274 fix: Optimize the index path in devops by role
  src/pages/devops/containers/Base/List/index.jsx
  src/pages/devops/routes/index.js
Labels: lgtm, approved, size/M, area/devops, kind/bug, release-note-none

#3278 The sonarqube test bug for v3.3.0-alpha.x
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/Select/index.jsx
  src/components/Forms/Workload/ContainerSettings/index.scss
  src/components/Graph/Card/index.scss
  src/pages/clusters/containers/Overview/Initializing/KubeKeyCluster/Logs/index.scss
  src/pages/fedprojects/components/ClusterWorkloadStatus/index.scss
  src/pages/projects/components/Cards/ImageRunRecord/Item/index.scss
  src/scss/markdown.scss
  src/scss/mixins.scss
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3281 Update UI text of 'Cluster Management'
  locales/en/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
  locales/en/l10n-projects-projectSettings-gatewaySettings-list.js
  locales/ko/l10n-clusterManagement-applicationWorkloads-pods-details.js
  src/actions/gateways.js
  src/components/Cards/Volumes/index.jsx
  src/pages/clusters/containers/Gateway/Components/ProjectGatewayList/index.jsx
  src/pages/clusters/containers/Gateway/index.jsx
  src/pages/clusters/containers/Storage/StorageClasses/Detail/routes.js
  src/pages/projects/containers/Pods/Containers/ResourceStatus.jsx
Labels: lgtm, approved, size/M, kind/documentation, release-note-none

#3279 fix: Worker node statistics error
  src/pages/clusters/containers/Nodes/index.jsx
  src/stores/node.js
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3273 fix: Compatible with version 3.2 of Devops
  server/config.yaml
  src/actions/codeRepo.js
  src/components/Forms/Pipelines/RepoSelect/BitBucketForm/index.jsx
  src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx
  src/pages/devops/containers/BaseInfo/index.jsx
  src/stores/devops/scm.js
Labels: size/L, lgtm, approved, area/devops, kind/bug, release-note-none

#3282 fix: No workspace created in host cluster on the console page of member cluster
  src/stores/workspace.js
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3285 Update UI text of 'Alerting Policies'
  locales/en/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
  locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-details.js
  locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
  src/components/Forms/AlertingPolicy/AlertingRule/index.jsx
  src/pages/projects/containers/Alerting/Policies/Detail/AlertRules/RuleItem.jsx
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#3286 fix: Update button width
  src/pages/clusters/containers/BaseInfo/index.jsx
  src/pages/clusters/containers/BaseInfo/index.scss
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3287 Update UI text of 'Cluster Management'
  locales/en/l10n-clusterManagement-applicationWorkloads-pods-details.js
  locales/en/l10n-clusterManagement-clusters.js
  locales/ko/l10n-clusterManagement-applicationWorkloads-pods-details.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3289 fix: Deleting a workspace does not select any resources from it
  src/pages/workspaces/components/Modals/WorkspaceDelete/index.jsx
Labels: size/XS, lgtm, approved, release-note-none

#3283 fix: Fix code repository option show
  server/services/session.js
  src/actions/cd.js
  src/components/Forms/CD/BaseInfo/index.jsx
  src/components/Modals/DevOpsAllowList/CodeRepoSelect.jsx
  src/components/Modals/DevOpsAllowList/index.jsx
Labels: size/L, lgtm, approved, area/devops, release-note-none

#3291 fix: Update cluster role
  server/services/session.js
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3292 fix: Can't connect to conatiner's kubectl
  src/components/Modals/ContianerTerminal/index.jsx
  src/stores/terminal.js
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3296 feat: Add cluster view permission when user add one cluster
  server/services/session.js
Labels: lgtm, approved, size/S, kind/bug, release-note

#3293 fix: Fix the permission of gateway view
  src/pages/clusters/containers/Gateway/Components/GatewayCard/index.jsx
  src/pages/fedprojects/containers/Gateway/Access/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3297 fix: Fix workspace api error due to error cluster role
  server/services/session.js
Labels: size/XS, lgtm, approved, kind/bug, do-not-merge/release-note-label-needed

#3303 fix: Remove devops id in devops list
  src/pages/workspaces/containers/DevOps/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3301 Update UI text of 'App Templates' and 'App Review'
  locales/ar/app.js
  locales/en/app.js
  locales/en/l10n-appStoreManagement-appReview-details.js
  locales/en/l10n-appStoreManagement-appReview-list.js
  locales/en/l10n-appStoreManagement-apps-details.js
  locales/en/l10n-appStoreManagement-apps-list.js
  locales/en/l10n-clusterManagement-applicationWorkloads-deployments-list.js
  locales/en/l10n-workspaces-appManagement-appTemplates-details.js
  locales/en/l10n-workspaces-appManagement-appTemplates-list.js
  locales/es/app.js
  locales/fr/app.js
  locales/hi/app.js
  locales/ko/app.js
  locales/lt/app.js
  locales/pl/app.js
  locales/tc/app.js
  locales/tr/app.js
  locales/zh/app.js
  server/config.yaml
  src/components/Layout/LoginInfo/index.jsx
  src/configs/openpitrix/version.js
  src/pages/apps/components/Lists/VersionList/Item.jsx
  src/pages/apps/components/Modals/AppReview/index.jsx
  src/pages/apps/containers/Reviews/index.jsx
  src/pages/apps/containers/StoreManage/Detail/AuditRecord/index.jsx
  src/pages/apps/containers/StoreManage/Detail/index.jsx
  src/pages/apps/containers/StoreManage/Detail/routes.js
  src/pages/workspaces/containers/Apps/Detail/routes.js
  src/utils/app.js
Labels: size/L, lgtm, approved, kind/documentation, release-note-none

#3305 fix: Fix the workspace show error in app review list
  src/components/Base/Image/index.jsx
  src/pages/apps/containers/Reviews/index.jsx
Labels: lgtm, approved, size/S, kind/bug, do-not-merge/release-note-label-needed

#3302 Fix UI description in volume snapshot class
  locales/en/l10n-clusterManagement-storage-volumeSnapshotClasses-list.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3310 fix: Optimize the 'Service Type' and 'External Access' columns of the service list for project
  src/pages/projects/containers/Services/index.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#3312 fix: Fix the permission of user in cluster page
  src/pages/clusters/containers/Gateway/Components/GatewayCard/index.jsx
  src/pages/clusters/containers/Gateway/Components/GatewayEmpty/index.jsx
  src/pages/clusters/containers/Visibility/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#3308 docs: Update UI text of 'App Templates'
  locales/en/l10n-workspaces-appManagement-appTemplates-details.js
  src/configs/openpitrix/version.js
  src/pages/apps/components/Modals/VersionSubmit/index.jsx
  src/utils/app.js
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#3306 docs: Remove the 'App ID' and 'Category' parameters of app template
  locales/en/l10n-appStoreManagement-appReview-list.js
  src/pages/workspaces/containers/Apps/Detail/index.jsx
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#3314 docs: Update UI text of 'App Templates'
  locales/ar/app.js
  locales/en/app.js
  locales/en/l10n-appStore-list.js
  locales/es/app.js
  locales/fr/app.js
  locales/hi/app.js
  locales/ko/app.js
  locales/lt/app.js
  locales/pl/app.js
  locales/tc/app.js
  locales/tr/app.js
  locales/zh/app.js
  src/pages/apps/components/Forms/AppBaseEdit/index.jsx
  src/pages/apps/components/Modals/CategoryAdjust/index.jsx
  src/pages/apps/containers/Categories/Cates/Item.jsx
  src/pages/apps/containers/Home/index.jsx
  src/pages/workspaces/containers/Apps/Detail/index.jsx
Labels: size/L, lgtm, approved, kind/documentation, release-note-none

#3316 docs: Update UI text of permissions
  locales/ar/app.js
  locales/ar/base.js
  locales/ar/role.js
  locales/en/app.js
  locales/en/base.js
  locales/en/l10n-accessControl-platformRoles-list.js
  locales/en/l10n-clusterManagement-clusterSettings-clusterRoles-details.js
  locales/en/l10n-clusterManagement-clusterSettings-clusterRoles-list.js
  locales/en/l10n-devopsProjects-devopsProjectSettings-devopsProjectRoles-details.js
  locales/en/l10n-devopsProjects-devopsProjectSettings-devopsProjectRoles-list.js
  locales/en/l10n-platform.js
  locales/en/l10n-projects-projectSettings-projectRoles-list.js
  locales/en/l10n-workspaces-workspaceSettings-departmentManagement.js
  locales/en/l10n-workspaces-workspaceSettings-workspaceRoles-list.js
  locales/en/role.js
  locales/es/app.js
  locales/es/base.js
  locales/es/role.js
  locales/fr/app.js
  locales/fr/base.js
  locales/fr/role.js
  locales/hi/app.js
  locales/hi/base.js
  locales/hi/role.js
  locales/ko/app.js
  locales/ko/base.js
  locales/ko/role.js
  locales/lt/app.js
  locales/lt/base.js
  locales/lt/role.js
  locales/pl/app.js
  locales/pl/base.js
  locales/pl/role.js
  locales/tc/app.js
  locales/tc/base.js
  locales/tc/role.js
  locales/tr/app.js
  locales/tr/base.js
  locales/tr/role.js
  locales/zh/app.js
  locales/zh/base.js
  locales/zh/role.js
  server/config.yaml
  src/components/Cards/RuleList/index.jsx
  src/components/Cards/RuleList/index.scss
  src/components/Modals/EditAuthorization/CheckItem.jsx
  src/components/Modals/EditAuthorization/index.jsx
  src/components/Modals/RoleCreate/index.jsx
  src/pages/clusters/components/Modals/ClusterSelect/index.jsx
  src/pages/clusters/containers/Clusters/index.jsx
  src/pages/workspaces/containers/Groups/index.jsx
Labels: size/L, lgtm, approved, kind/documentation, release-note-none

#3317 fix: Optimize the css style of webkit-box-orient
  src/pages/devops/components/Pipeline/PipelineTemplate/index.jsx
  src/scss/mixins.scss
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#3318 docs: Update UI text of permissions.
  locales/en/l10n-devopsProjects-devopsProjectSettings-devopsProjectRoles-list.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#3321 docs: Remove redundant locale files.
  locales/ar/l10n-appStoreManagement-appRelease-details.js
  locales/ar/l10n-appStoreManagement-appRelease-list.js
  locales/ar/l10n-clusterManagement-role-list.js
  locales/es/l10n-appStoreManagement-appRelease-details.js
  locales/es/l10n-appStoreManagement-appRelease-list.js
  locales/es/l10n-clusterManagement-role-list.js
  locales/fr/l10n-appStoreManagement-appRelease-details.js
  locales/fr/l10n-appStoreManagement-appRelease-list.js
  locales/fr/l10n-clusterManagement-role-list.js
  locales/hi/l10n-appStoreManagement-appRelease-details.js
  locales/hi/l10n-appStoreManagement-appRelease-list.js
  locales/hi/l10n-clusterManagement-role-list.js
  locales/ko/l10n-appStoreManagement-appRelease-details.js
  locales/ko/l10n-appStoreManagement-appRelease-list.js
  locales/ko/l10n-clusterManagement-role-list.js
  locales/lt/l10n-appStoreManagement-appRelease-details.js
  locales/lt/l10n-appStoreManagement-appRelease-list.js
  locales/lt/l10n-clusterManagement-role-list.js
  locales/pl/l10n-appStoreManagement-appRelease-details.js
  locales/pl/l10n-appStoreManagement-appRelease-list.js
  locales/pl/l10n-clusterManagement-role-list.js
  locales/tc/l10n-appStoreManagement-appRelease-details.js
  locales/tc/l10n-appStoreManagement-appRelease-list.js
  locales/tc/l10n-clusterManagement-role-list.js
  locales/tr/l10n-appStoreManagement-appRelease-details.js
  locales/tr/l10n-appStoreManagement-appRelease-list.js
  locales/tr/l10n-clusterManagement-role-list.js
  locales/zh/l10n-appStoreManagement-appRelease-details.js
  locales/zh/l10n-appStoreManagement-appRelease-list.js
  locales/zh/l10n-clusterManagement-role-list.js
Labels: lgtm, approved, size/XXL, kind/documentation, release-note-none

#3323 fix: Fix the error that the user name is Chinese when logging in by oath
  server/controllers/session.js
  server/controllers/view.js
  server/libs/utils.js
Labels: lgtm, approved, size/M, kind/bug, release-note-none
