Repository kubesphere/console, pull requests merged in 2023-10, with the labels that each got.

#3866 fix:Updating crd resource on ks-console page loses status information
  src/stores/crd.resource.js
  src/utils/object.mapper.js
Labels: lgtm, approved, size/S, kind/bug, needs-ok-to-test, release-note

#3415 fix: Appdeploy schemaform support select
  src/components/Forms/AppDeploy/AppConfig/SchemaForm/index.jsx
Labels: size/XS, lgtm, approved, kind/feature, ok-to-test, release-note-none

#4102 fix: support to run in ARM64 environment
  build/Dockerfile
  build/Dockerfile.dapper
Labels: size/XS, lgtm, approved, kind/bug, ok-to-test, release-note

#4201 doc: Fix a Chinese alias
  locales/zh/l10n-clusterManagement-nodes-clusterNodes-details.js
Labels: size/XS, lgtm, approved, kind/bug, ok-to-test, release-note

#4206 fix: Fix pipeline shell command can't save
  src/components/Base/CodeEditor/index.jsx
  src/pages/devops/components/Pipeline/StepModals/params.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#4207 fix: No termination seconds in multi project (#1001)
  src/components/EditForms/Workload/TerminationSeconds/index.jsx
  src/components/Forms/Workload/ContainerSettings/TerminationSeconds/index.jsx
  src/pages/fedprojects/components/ConfigTemplate/config.js
  src/pages/projects/components/Modals/ConfigTemplate/config.js
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#4209 fix: fix project gateway not display in cluster
  src/pages/clusters/containers/Gateway/Components/ProjectGatewayList/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note

#4210 style: Update dashboard history card style
  src/pages/console/containers/Dashboard/Admin/History/Card.jsx
  src/pages/console/containers/Dashboard/Admin/History/index.jsx
  src/pages/console/containers/Dashboard/Admin/History/index.scss
Labels: lgtm, approved, size/M, kind/bug, release-note

#4211 fix: Count table body height for filter button's dropdown content
  src/components/Tables/Base/CustomColumns/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note

#4213 fix: Fix the type of number when entering the routing rule path
  src/components/Inputs/RulePath/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note

#4214 fix: Fix the status of schedule in pod schedule page
  src/pages/projects/containers/Pods/Detail/ScheduleInfo/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note

#4215 feat: Pipeline detail add code repo attr
  src/pages/devops/containers/Pipelines/Detail/Layout/pipeline.jsx
  src/utils/devOpsRepos.js
Labels: lgtm, approved, size/M, kind/bug, release-note

#4216 fix: Set disabled when cluster is not ready or not install devops
  src/pages/workspaces/containers/DevOps/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#4217 fix: Fix parameters defined in pipeline not passed to jenkins
  src/components/Forms/Pipelines/ParamsFormModal/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#4218 fix: [devops 3.4.1] fix devops pipeline run log (#1772)
  server/proxy.js
  src/pages/devops/containers/Pipelines/Detail/PipelineLogDialog/FullLogs/index.jsx
  src/pages/devops/containers/Pipelines/Detail/PipelineLogDialog/index.scss
  src/pages/devops/containers/Pipelines/Detail/TaskStatus/index.jsx
  src/pages/devops/containers/layout.jsx
  src/stores/devops/run.js
  src/utils/request.js
Labels: size/L, lgtm, approved, kind/bug, release-note-none

#4219 fix: notify message before run pipeline
  src/actions/pipeline.js
  src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#4220 fix: Add link at pipeline run log list to detail page
  src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#4222 fix: Remove kubeconfig type when create credential
  src/components/Modals/CredentialCreate/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#4223 fix: Fix the text description of deleting expired branches in a multi-branch pipeline setup is inaccurate.
  locales/en/l10n-devopsProjects-pipeline-list.js
  locales/tc/l10n-devopsProjects-pipeline-list.js
  locales/zh/l10n-devopsProjects-pipeline-list.js
Labels: lgtm, approved, size/M, kind/documentation, release-note-none

#4224 fix: Fix deploy the app by template not get the detail
  src/pages/apps/components/Modals/AppDeploy/index.jsx
  src/stores/openpitrix/base.js
Labels: lgtm, approved, size/S, kind/bug, release-note

#4221 fix: Fix devops pipeline too large run logs
  locales/en/l10n-devopsProjects-pipeline-details.js
  locales/es/l10n-devopsProjects-pipeline-details.js
  locales/tc/l10n-devopsProjects-pipeline-details.js
  locales/zh/l10n-devopsProjects-pipeline-details.js
  src/pages/devops/components/Pipeline/StepModals/params.jsx
  src/pages/devops/containers/Pipelines/Detail/PipelineLogDialog/FullLogs/index.jsx
  src/pages/devops/containers/Pipelines/Detail/PipelineLogDialog/Timer.jsx
  src/pages/devops/containers/Pipelines/Detail/PipelineLogDialog/index.jsx
  src/stores/devops/log.js
  src/stores/devops/run.js
Labels: size/L, lgtm, approved, kind/bug, release-note-none

#4225 fix: Optimize the tag input to automatically fill in the value when it loses focus
  package.json
  src/components/Forms/Notification/BaseForm/ConditionSelect/index.jsx
  src/components/Inputs/TagInput/autosuggest.jsx
  src/components/Inputs/TagInput/index.scss
  yarn.lock
Labels: lgtm, approved, size/M, kind/bug, release-note

#4186 doc: Fix Storage Class translation mistakes
  locales/ar/l10n-clusterManagement-storage-storageClasses-list.js
  locales/de/l10n-clusterManagement-storage-storageClasses-list.js
  locales/en/l10n-clusterManagement-storage-storageClasses-list.js
  locales/es/l10n-clusterManagement-storage-storageClasses-list.js
  locales/fr/l10n-clusterManagement-storage-storageClasses-list.js
  locales/hi/l10n-clusterManagement-storage-storageClasses-list.js
  locales/ko/l10n-clusterManagement-storage-storageClasses-list.js
  locales/lt/l10n-clusterManagement-storage-storageClasses-list.js
  locales/pl/l10n-clusterManagement-storage-storageClasses-list.js
  locales/pt/l10n-clusterManagement-storage-storageClasses-list.js
  locales/tc/l10n-clusterManagement-storage-storageClasses-list.js
  locales/tr/l10n-clusterManagement-storage-storageClasses-list.js
  locales/zh/l10n-clusterManagement-storage-storageClasses-list.js
Labels: lgtm, approved, size/M, kind/bug, ok-to-test, release-note

#4226 dos: fix some words in mistakes
  locales/ar/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
  locales/ar/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
  locales/de/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
  locales/de/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
  locales/en/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
  locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
  locales/es/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
  locales/es/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
  locales/fr/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
  locales/fr/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
  locales/hi/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
  locales/hi/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
  locales/ko/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
  locales/ko/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
  locales/lt/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
  locales/lt/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
  locales/pl/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
  locales/pl/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
  locales/pt/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
  locales/pt/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
  locales/tc/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
  locales/tc/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
  locales/tr/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
  locales/tr/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
  locales/zh/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
  locales/zh/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
  locales/zh/l10n-clusterManagement-storage-storageClasses-list.js
Labels: lgtm, approved, size/XL, kind/documentation, release-note-none

#4227 fix: The 0 in pvc autosizer input can not be deleted
  src/components/Base/Slider/index.jsx
  src/components/Base/Slider/index.scss
  src/components/Base/index.js
  src/components/Inputs/UnitSlider/index.jsx
Labels: size/L, lgtm, approved, kind/bug, release-note

#4228 fix: fix the tag version of image after the tag is selected
  server/controllers/api.js
  server/libs/request.js
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/DropdownContent.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/index.scss
  src/components/Forms/Workload/ContainerSettings/ContainerForm/index.jsx
  src/pages/fedprojects/components/ContainerImage/index.jsx
  src/stores/container.js
Labels: size/L, lgtm, approved, release-note

#4229 feat: add github action
  .github/workflows/main.yaml
  .github/workflows/manually.yaml
  .github/workflows/nightly-builds.yaml
Labels: size/L, lgtm, approved, kind/feature, release-note

#4232 fix(action): change image-registry and tag retrieval method
  .github/workflows/main.yaml
  .github/workflows/manually.yaml
  .github/workflows/nightly-builds.yaml
  .github/workflows/release.yml
Labels: size/L, kind/bug, release-note

#4235 fix(action): change main runtime.
  .github/workflows/main.yaml
Labels: size/XS, kind/bug, release-note

#4234 fix: Fix error in AppStore
  src/pages/apps/containers/Home/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, ok-to-test, release-note-none

#4238 fix: fix the window have scroller when it have hpa card
  src/pages/projects/components/Cards/HPA/index.jsx
  src/pages/projects/components/Cards/HPA/index.scss
  src/utils/index.js
Labels: lgtm, approved, size/M, kind/bug, release-note

#4240 fix: fix the devops page is block
  src/pages/workspaces/containers/DevOps/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none
