Repository kubesphere/console, pull requests merged in 2023-01, with the labels that each got.

#4019 fix: Fix some resources not belong current workspace
  src/components/Inputs/ProjectSelect/index.jsx
  src/components/Modals/Network/Policies/index.jsx
  src/components/Modals/Network/Policies/index.scss
Labels: lgtm, approved, size/S, kind/bug, release-note

#4021 fix:Fix issue 4658, when deleting a service, validate associated pods
  src/pages/projects/components/Modals/ServiceDelete/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note

#4024 fix: Display optimization in code repository
  src/components/Forms/Pipelines/RepoSelect/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#4029 fix:Fix ks-devops issue 859, add link for aborted status pipelinerun
  src/pages/devops/containers/Pipelines/Detail/Activity/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note

#4032 fix:Fix issue 3079, remove work node statistics, node list add role filter
  src/pages/clusters/containers/Nodes/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note

#4031 fix: Fix the delete button not display in gray release detail page
  src/pages/projects/components/Modals/GrayReleaseDetail/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note

#4036 fix:Fix devops artifacts download link
  src/pages/devops/containers/Pipelines/Detail/Artifacts/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note

#4037 fix: Fix the governance is not changed when creating the sample bookinfo application
  src/pages/projects/components/Modals/CreateApp/index.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note

#4044 fix: Add translation entries
  locales/en/l10n-projects-applicationWorkloads-services-details.js
  src/components/Forms/Workload/VolumeSettings/VolumeList/Card.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#4045 fix: Fix edit Persistent Volume Claims storage type error in federation project
  src/actions/volume.js
  src/components/Forms/Volume/VolumeSettings/FormTemplate.jsx
  src/components/Forms/Volume/VolumeSettings/index.jsx
  src/pages/fedprojects/components/VolumeSetting/VolumeSettingForm.jsx
  src/pages/fedprojects/containers/Volumes/Detail/index.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note

#4027 fix: Fix image pull secrets deleted by edit page
  src/components/EditForms/Workload/PodTemplate/index.jsx
  src/components/Forms/Workload/ClusterDiffSettings/ContainersMapper/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
  src/components/Forms/Workload/ContainerSettings/index.jsx
  src/components/Inputs/ContainerPort/index.jsx
  src/pages/fedprojects/components/ContainerImage/index.jsx
Labels: size/L, lgtm, approved, kind/bug, release-note

#4050 fix: Gateway does not automatically refresh after a Resource Status change
  src/pages/clusters/containers/Gateway/Components/Pods/index.jsx
  src/pages/clusters/containers/Gateway/Detail/ResourceStatus/index.jsx
  src/stores/gateway.js
Labels: size/L, lgtm, approved, kind/bug, release-note

#4051 fix spelling
  locales/en/l10n-projects-applicationWorkloads-services-details.js
Labels: size/XS, lgtm, approved, release-note-none

#4055 docs: change route to ingress
  locales/en/l10n-clusterManagement-applicationWorkloads-routes-list.js
  locales/en/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
  locales/en/l10n-clusterManagement-monitoring&Alerting-applicationResources.js
  locales/en/l10n-multiclusterProjects-applicationWorkloads-apps-list.js
  locales/en/l10n-multiclusterProjects-applicationWorkloads-routes-list.js
  locales/en/l10n-projects-applicationWorkloads-apps-composedApps-details.js
  locales/en/l10n-projects-applicationWorkloads-apps-composedApps-list.js
  locales/en/l10n-projects-overview.js
  locales/en/l10n-projects-projectSettings-basicInformation.js
  locales/en/l10n-projects-projectSettings-gatewaySettings-list.js
Labels: lgtm, approved, size/M, release-note

#4054 fix: Fix the username and password is empty in secret detail
  package.json
  src/pages/projects/containers/Secrets/Detail/SecretDetail/index.jsx
  yarn.lock
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#4059 style: Fix the style of clusters with too long names
  src/components/Clusters/ClusterTitle/index.scss
Labels: size/XS, lgtm, approved, kind/bug, release-note

#4060 [release-3.3]docs: change route to ingress (#4055)
  locales/en/l10n-clusterManagement-applicationWorkloads-routes-list.js
  locales/en/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
  locales/en/l10n-clusterManagement-monitoring&Alerting-applicationResources.js
  locales/en/l10n-multiclusterProjects-applicationWorkloads-apps-list.js
  locales/en/l10n-multiclusterProjects-applicationWorkloads-routes-list.js
  locales/en/l10n-projects-applicationWorkloads-apps-composedApps-details.js
  locales/en/l10n-projects-applicationWorkloads-apps-composedApps-list.js
  locales/en/l10n-projects-overview.js
  locales/en/l10n-projects-projectSettings-basicInformation.js
  locales/en/l10n-projects-projectSettings-gatewaySettings-list.js
Labels: lgtm, approved, size/M, kind/documentation, release-note-none

#4063 fix: Change the pod status filter options in page
  src/pages/devops/containers/CD/detail/routes.js
  src/stores/cd.js
  src/utils/constants.js
Labels: lgtm, approved, size/S, kind/bug, release-note

#4065 [release-3.3]fix: Change the pod status filter options in page (#4063)
  src/stores/cd.js
  src/utils/constants.js
Labels: size/XS, approved, kind/bug, release-note

#4066 fix: Fedrate service's pod replicas can not auto refres
  src/pages/fedprojects/containers/Services/Detail/ResourceStatus/index.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#4068 change cluster to workspace
  locales/en/l10n-projects-projectSettings-networkIsolation.js
Labels: lgtm, approved, size/S, release-note-none

#4071 fix: Change the Failed to Error in Pod status filter in pod page
  src/utils/constants.js
Labels: size/XS, lgtm, approved, kind/bug, release-note

#4069 fix:Fix issue 872, add more information for continuous deployment parameters
  locales/en/l10n-devopsProjects-continuousDeployments-list.js
  src/components/Forms/CD/Advance/CodeRepoSetting.jsx
  src/components/Forms/CD/Advance/Placement/index.scss
  src/components/Forms/CD/Advance/SyncSetting.jsx
  src/components/Forms/CD/Advance/index.scss
  src/components/Forms/CD/BaseInfo/index.jsx
  src/configs/steps/cd.js
Labels: size/L, lgtm, approved, kind/bug, release-note

#4074 fix:Fix issue 872, add more information for continuous deployment parameters
  locales/en/l10n-devopsProjects-continuousDeployments-list.js
  src/components/Forms/CD/Advance/CodeRepoSetting.jsx
  src/components/Forms/CD/Advance/Placement/index.scss
  src/components/Forms/CD/Advance/SyncSetting.jsx
  src/components/Forms/CD/Advance/index.scss
  src/components/Forms/CD/BaseInfo/index.jsx
  src/configs/steps/cd.js
Labels: size/L, lgtm, approved, kind/bug, release-note

#4075 Fix the problem that after logging in with OAuth login, you cannot re…
  server/controllers/session.js
Labels: size/XS, lgtm, approved, kind/bug, ok-to-test, release-note-none

#4081 docs: Add the index.js in de and pt
  locales/de/index.js
  locales/pt/index.js
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#4077 fix: System-workspace cluster field shows 'all' for multi-cluster
  locales/en/l10n-accessControl-workspaces-list.js
  src/components/Clusters/ClusterWrapper/index.jsx
  src/pages/access/containers/Workspaces/index.jsx
  src/pages/workspaces/components/Modals/WorkspaceSelect/Card/index.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note

#4085 fix: Fix the image not match when created service by jar/war
  src/components/Forms/ImageBuilder/B2IForm/BinaryFileUploader/index.scss
  src/components/Forms/Service/ContainerSetting/index.jsx
  src/stores/service.js
Labels: lgtm, approved, size/M, kind/bug, release-note
