Repository kubesphere/console, pull requests merged in 2023-04, with the labels that each got.

#4106 fix: Missing translation
  locales/zh/l10n-devopsProjects-continuousDeployments-list.js
  locales/zh/l10n-devopsProjects-pipeline-list.js
  locales/zh/l10n-projects-projectSettings-gatewaySettings-list.js
Labels: lgtm, approved, size/S, release-note-none

#4108 feat: Add log receiver translate filed
  locales/ar/l10n-clusterManagement-clusterSettings-logReceivers-list.js
Labels: size/XS, lgtm, approved, release-note-none

#4109 feat: Add devops pipeline custom pipeline modal locales
  locales/en/l10-project-devops-pipeline-detail.js
Labels: lgtm, approved, size/M, kind/bug, release-note

#4111 doc: change the file name of the devops detail language
  locales/en/l10n-project-devops-pipeline-detail.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#4112 doc: merge devops pipeline detail locales
  locales/en/l10n-devopsProjects-pipeline-details.js
  locales/en/l10n-project-devops-pipeline-detail.js
Labels: size/L, lgtm, approved, kind/documentation, release-note-none

#4113 Fix: fix alias desc
  locales/en/l10n-clusterManagement-projects-list.js
Labels: size/XS, lgtm, approved, release-note-none

#4117 Fix: fix alias desc
  locales/en/l10n-clusterManagement-projects-list.js
Labels: size/XS, lgtm, approved, release-note-none

#4119 fix: Update gateway modal text
  locales/en/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#4120 fix: LOG_RECEIVER field not be translated
  locales/en/l10n-clusterManagement-clusterSettings-logReceivers-details.js
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#4121 Fix: fix typo
  locales/en/l10n-clusterManagement-clusterSettings-gatewaySettings-list.js
Labels: size/XS, lgtm, approved, release-note-none
