Repository kubesphere/console, pull requests merged in 2023-09, with the labels that each got.

#4187 feat: Cherry pick LADP
  locales/en/l10n-logIn.js
  locales/zh/l10n-logIn.js
  server/controllers/session.js
  server/routes.js
  server/services/session.js
  src/core/containers/Login/index.jsx
  src/core/containers/Login/index.scss
  src/stores/root.js
Labels: size/L, lgtm, approved, kind/bug, release-note-none

#4188 fix: Fix error in applications template page (#5873)
  src/stores/openpitrix/base.js
Labels: size/XS, lgtm, approved, kind/bug, needs-ok-to-test, release-note-none

#4190 fix: Update k8s api version
  src/utils/constants.js
  src/utils/form.templates.js
  src/utils/workload.js
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#4192 Fix Api Documentation Link
  locales/ar/l10n-help.js
  locales/en/l10n-help.js
  locales/es/l10n-help.js
  locales/fr/l10n-help.js
  locales/hi/l10n-help.js
  locales/lt/l10n-help.js
  locales/pl/l10n-help.js
  locales/pt/l10n-help.js
  locales/tc/l10n-help.js
  locales/tr/l10n-help.js
Labels: lgtm, approved, size/S, needs-ok-to-test, release-note

#4195 doc: fix the poc description
  locales/ar/l10n-multiclusterProjects-persistentVolumeClaims-details.js
  locales/en/l10n-multiclusterProjects-persistentVolumeClaims-details.js
  locales/es/l10n-multiclusterProjects-persistentVolumeClaims-details.js
  locales/fr/l10n-multiclusterProjects-persistentVolumeClaims-details.js
  locales/hi/l10n-multiclusterProjects-persistentVolumeClaims-details.js
  locales/pl/l10n-multiclusterProjects-persistentVolumeClaims-details.js
  locales/pt/l10n-multiclusterProjects-persistentVolumeClaims-details.js
  locales/zh/l10n-multiclusterProjects-persistentVolumeClaims-details.js
Labels: lgtm, approved, size/M, kind/documentation, release-note

#4180 style: fix incorrect style for IsolateInfo and RuleInfo of Network Policy panel
  src/pages/projects/containers/Network/Policies/IsolateInfo/index.scss
  src/pages/projects/containers/Network/Policies/RuleInfo/index.scss
Labels: lgtm, approved, size/S, kind/bug, ok-to-test, release-note
