Repository kubesphere/console, pull requests merged in 2023-03, with the labels that each got.

#4091 feat: Replace code repository component in continuous deployments
  locales/en/l10n-devopsProjects-continuousDeployments-list.js
  src/components/Base/TypeSelect/index.jsx
  src/components/CodeRepoSelector/index.jsx
Labels: lgtm, approved, size/M, kind/feature, release-note

#4090 fix: Add jenkins validate field, fixed jenkins file validate status
  src/pages/devops/containers/Pipelines/Detail/PipeLine/index.jsx
  src/utils/object.mapper.js
Labels: lgtm, approved, size/M, kind/bug, release-note

#4094 fixed: Add pipeline activity list id then id is empty
  src/stores/devops/pipelines.js
Labels: lgtm, approved, size/S, kind/bug, release-note

#4095 fixed: Fixed devops issue 847, add number lint when edit pipeline gurations
  locales/en/l10n-devopsProjects-pipeline-list.js
  src/actions/pipeline.js
  src/components/Forms/Pipelines/AdvanceSettings/index.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note

#4096 feat: Avoid using API tojson and tojenkinsfile
  src/actions/pipeline.js
  src/components/Forms/Pipelines/PipelineTemplateParams/index.jsx
  src/components/Forms/Pipelines/PipelineTemplateParams/index.scss
  src/pages/devops/containers/Pipelines/Detail/PipeLine/index.jsx
  src/stores/devops/pipelines.js
Labels: size/L, lgtm, approved, kind/feature, release-note

#4097 feat: Optimize user experience for multi branch pipeline
  locales/en/l10n-devopsProjects-pipeline-list.js
  src/components/Forms/Pipelines/BaseInfo/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Layout/pipeline.jsx
  src/pages/devops/containers/Pipelines/PipelinesList/index.jsx
  src/stores/devops/pipelines.js
  src/utils/object.mapper.js
Labels: size/L, lgtm, approved, kind/feature, release-note

#4098 doc: Add the project gateway empty desc
  locales/en/l10n-projects-projectSettings-gatewaySettings-list.js
Labels: lgtm, approved, size/S, kind/documentation, release-note-none

#4099 fix: When 'jenkinsfile.edit.mode' is json, show the pipeline
  src/pages/devops/containers/Pipelines/Detail/PipeLine/index.jsx
  src/utils/object.mapper.js
Labels: lgtm, approved, size/S, kind/bug, release-note
