Repository kubesphere/console, pull requests merged in 2023-07, with the labels that each got.

#4155 fix: Fix devops cd application form field (#1479)
  src/pages/devops/components/Pipeline/StepModals/application.jsx
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#4157 fix: Remove multi-branch API request from non-multi-branch pipeline run record page. (#1439)
  src/pages/devops/containers/Pipelines/Detail/Layout/runs.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#4156 feat: Refactor image search
  server/controllers/api.js
  src/components/Cards/Pods/Item.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/DropdownContent.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/ImageTagRadioList/ImageTagRadio.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/ImageTagRadioList/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/ImageTagRadioList/index.scss
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/index.scss
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/Ports/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/Ports/index.scss
  src/components/Forms/Workload/ContainerSettings/ContainerForm/index.jsx
  src/components/Forms/Workload/ContainerSettings/index.jsx
  src/pages/fedprojects/components/ClusterDiffSettings/index.jsx
  src/pages/fedprojects/components/ContainerImage/index.jsx
  src/stores/container.js
Labels: lgtm, approved, size/XL, kind/feature, release-note

#4158 fix: Fix the error when downloading pipeline logs. (#1441)
  src/pages/devops/containers/Pipelines/Detail/PipelineLogDialog/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#4159 fix: Fix devops bugs
  src/actions/cd.js
  src/components/Base/TypeSelect/index.jsx
  src/components/Forms/CD/Advance/CodeRepoSetting.jsx
  src/components/Modals/CredentialCreate/index.jsx
  src/pages/devops/containers/CD/CDList/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#4160 fix: Fix the data is error in gateway page
  src/components/Clusters/ClusterWrapper/index.jsx
  src/pages/observability/containers/Observability/components/ResourceRankModal/RankTable/ProjectOrDevopsName.jsx
  src/pages/settings/containers/layout.jsx
  src/stores/gateway.js
Labels: size/L, lgtm, approved, kind/bug, release-note-none

#4161 fix: fix create multi branch pipeline git source field
  src/utils/devOpsRepos.js
Labels: lgtm, approved, kind/bug, release-note-none

#4164 fix: Filter cd deployment location clusters options by host cluster name
  src/components/Forms/CD/Advance/Placement/index.jsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none
