Repository kubesphere/console, pull requests merged in 2023-11, with the labels that each got.

#4245 revert: recovery kubeconfig type when create credential
  src/components/Modals/CredentialCreate/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#4244 feat: update zh document link in config.yaml
  server/config.yaml
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#4248 Revert "fix: Fix the text description of deleting expired branches in a multi-branch pipeline setup is inaccurate."
  locales/en/l10n-devopsProjects-pipeline-list.js
  locales/tc/l10n-devopsProjects-pipeline-list.js
  locales/zh/l10n-devopsProjects-pipeline-list.js
Labels: lgtm, approved, size/M, release-note-none

#4249 fix: HPA api response 404
  server/services/session.js
  src/stores/workload/hpa.js
  src/utils/constants.js
  src/utils/workload.js
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#4252 fix: remove the how to modify platform info in base info
  src/pages/settings/containers/BaseInfo/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none
