Repository kubesphere/console, pull requests merged in 2023-06, with the labels that each got.

#4131 fix: Delete manager filed in workspace base info page
  src/pages/workspaces/containers/BaseInfo/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#4132 fix: The 'Cluster Gateway' page keeps loading and reports an error 'evaluating e.ip.includes'
  src/utils/object.mapper.js
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#4135 fix: Devops: Request to reuse the git repository selector on the eline edit (create) page
  locales/en/l10n-devopsProjects-pipeline-details.js
  src/actions/codeRepo.js
  src/actions/pipeline.js
  src/components/Base/TypeSelect/index.jsx
  src/components/Base/TypeSelect/index.scss
  src/components/CodeRepoSelector/index.jsx
  src/components/Forms/Pipelines/BaseInfo/index.jsx
  src/components/Forms/Pipelines/RepoSelect/index.jsx
  src/components/Modals/CodeRepoCreate/index.jsx
  src/components/Modals/Pipelines/Base/index.jsx
  src/components/Modals/Pipelines/PipelineEdit/index.jsx
  src/pages/devops/components/Pipeline/Sider/index.jsx
  src/pages/devops/components/Pipeline/StepModals/FromCodeRepository.jsx
  src/pages/devops/components/Pipeline/StepModals/params.jsx
  src/pages/devops/components/Pipeline/StepModals/reaction.js
  src/pages/devops/components/Pipeline/StepsEditor/StepsEditor.jsx
  src/pages/devops/components/Pipeline/StepsSelector/index.jsx
  src/pages/devops/components/Pipeline/index.jsx
  src/pages/devops/containers/Pipelines/Detail/Layout/pipeline.jsx
  src/pages/devops/containers/Pipelines/Detail/PipeLine/index.jsx
  src/pages/devops/version
  src/stores/devops/scm.js
  src/utils/devOpsRepos.js
  src/utils/devops.js
  src/utils/object.mapper.js
Labels: lgtm, approved, size/XL, kind/bug, release-note-none

#4136 fix: Fix devops locales
  locales/en/l10n-devopsProjects-pipeline-details.js
Labels: size/XS, lgtm, approved, kind/documentation, release-note-none

#4137 meraged the kse v3.4.0 into ks-3.4.0
  locales/en/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
  package.json
  server/controllers/view.js
  src/actions/secret.js
  src/components/EditForms/Workload/TerminationSeconds/index.jsx
  src/components/Forms/AppDeploy/AppConfig/SchemaForm/index.jsx
  src/components/Forms/Secret/SecretSettings/ImagerRegistry/index.jsx
  src/components/Forms/Secret/SecretSettings/ImagerRegistry/index.scss
  src/components/Forms/Secret/SecretSettings/index.jsx
  src/components/Forms/Workload/AdvanceSettings/Metadata/index.jsx
  src/components/Forms/Workload/AdvanceSettings/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/DropdownContent.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/Select/index.jsx
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/ImageInput/Select/index.scss
  src/components/Forms/Workload/ContainerSettings/ContainerForm/ContainerSetting/index.jsx
  src/components/Forms/Workload/ContainerSettings/TerminationSeconds/index.jsx
  src/components/Forms/Workload/ContainerSettings/index.jsx
  src/components/HOCs/withDefaultSecrets.js
  src/components/Inputs/ResourceLimit/index.jsx
  src/components/Modals/AuditingSearch/Auditing/Detail/MetadataModal/index.scss
  src/components/Modals/AuditingSearch/Auditing/Detail/index.scss
  src/components/Modals/AuditingSearch/Auditing/Home/index.jsx
  src/components/Modals/EventSearch/Event/Detail/index.scss
  src/components/Modals/QuotaEdit/index.jsx
  src/components/Modals/SetDefaultSecretClass/index.jsx
  src/components/Modals/SetDefaultSecretClass/index.scss
  src/pages/clusters/containers/Gateway/Detail/ResourceStatus/index.jsx
  src/pages/clusters/containers/Secrets/index.jsx
  src/pages/clusters/containers/Secrets/index.scss
  src/pages/projects/components/Modals/ConfigTemplate/config.js
  src/pages/projects/components/Modals/GatewaySetting/index.jsx
  src/pages/projects/components/Modals/GrayReleaseDetail/Component/Item.jsx
  src/pages/projects/containers/Secrets/Detail/index.jsx
  src/stores/gateway.js
  src/stores/secret.js
  src/utils/object.mapper.js
Labels: lgtm, approved, size/XL, kind/bug, release-note-none

#4139 fix: fix translation
  locales/en/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
Labels: lgtm, approved, size/S, release-note-none

#4138 fix: Remove cluster gateway in project gateway list
  src/pages/clusters/containers/Gateway/Components/ProjectGatewayList/index.jsx
  src/pages/clusters/containers/Gateway/index.jsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#4143 fix: Fix notification form field
  src/pages/settings/containers/Notification/Slack/index.jsx
  src/pages/settings/containers/Notification/Webhook/index.jsx
  src/stores/notification/base.js
  src/stores/notification/verify.js
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#4142 fix: Update rule group list page and create modal
  locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-details.js
  locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
  locales/zh/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-details.js
  locales/zh/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
  src/actions/alerting.js
  src/assets/bell_gear_duotone.svg
  src/assets/computing-setting.svg
  src/assets/monitor.svg
  src/components/Cards/Banner/index.jsx
  src/components/Forms/AlertingPolicy/AlertingRule/CustomRule/index.jsx
  src/components/Forms/AlertingPolicy/AlertingRule/MonitoringTarget/NodeSelect.jsx
  src/components/Forms/AlertingPolicy/AlertingRule/MonitoringTarget/WorkloadSelect.jsx
  src/components/Forms/AlertingPolicy/AlertingRule/MonitoringTarget/index.jsx
  src/components/Forms/AlertingPolicy/AlertingRule/QueryMonitor/index.jsx
  src/components/Forms/AlertingPolicy/AlertingRule/RuleInput/index.jsx
  src/components/Forms/AlertingPolicy/AlertingRule/RuleInput/index.scss
  src/components/Forms/AlertingPolicy/AlertingRule/index.jsx
  src/components/Forms/AlertingPolicy/AlertingRule/index.scss
  src/components/Forms/AlertingPolicy/AlertingRules/index.jsx
  src/components/Forms/AlertingPolicy/BaseInfo/index.jsx
  src/components/Forms/AlertingPolicy/NotificationRule/index.jsx
  src/components/Forms/AlertingPolicy/NotificationRule/index.scss
  src/configs/alerting/metrics/node.js
  src/configs/alerting/metrics/rule.config.js
  src/configs/alerting/metrics/workload.js
  src/configs/steps/alerting.policy.js
  src/pages/projects/containers/Alerting/Policies/AlertingStatus/index.jsx
  src/pages/projects/containers/Alerting/Policies/AlertingStatus/index.scss
  src/pages/projects/containers/Alerting/Policies/Detail/AlertMessages/index.jsx
  src/pages/projects/containers/Alerting/Policies/Detail/AlertMessages/index.scss
  src/pages/projects/containers/Alerting/Policies/Detail/AlertRules/Monitoring.jsx
  src/pages/projects/containers/Alerting/Policies/Detail/AlertRules/Notification.jsx
  src/pages/projects/containers/Alerting/Policies/Detail/AlertRules/Query.jsx
  src/pages/projects/containers/Alerting/Policies/Detail/AlertRules/RuleItem.jsx
  src/pages/projects/containers/Alerting/Policies/Detail/AlertRules/RuleList/Item.jsx
  src/pages/projects/containers/Alerting/Policies/Detail/AlertRules/RuleList/index.jsx
  src/pages/projects/containers/Alerting/Policies/Detail/AlertRules/RuleList/index.scss
  src/pages/projects/containers/Alerting/Policies/Detail/AlertRules/index.jsx
  src/pages/projects/containers/Alerting/Policies/Detail/Health/index.jsx
  src/pages/projects/containers/Alerting/Policies/Detail/index.jsx
  src/pages/projects/containers/Alerting/Policies/Detail/index.scss
  src/pages/projects/containers/Alerting/Policies/index.jsx
  src/pages/projects/containers/Alerting/Policies/index.scss
  src/stores/alerting/policy.js
  src/utils/constants.js
  src/utils/form.templates.js
  src/utils/object.mapper.js
Labels: lgtm, approved, size/XXL, release-note

#4145 fix: Add edit basic info modal for rule group
  locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
  locales/zh/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
  src/actions/alerting.js
  src/pages/projects/containers/Alerting/Policies/Detail/index.jsx
  src/pages/projects/containers/Alerting/Policies/index.jsx
Labels: size/L, lgtm, approved, release-note-none

#4146 fix: Add rule group edit form
  locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
  locales/zh/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
  src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/CustomRule/CustomExpr/MetircQueryInput/index.jsx
  src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/CustomRule/CustomExpr/MetircQueryInput/index.scss
  src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/CustomRule/CustomExpr/index.jsx
  src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/CustomRule/index.jsx
  src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/CustomRule/index.scss
  src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/TemplateRule/MonitoringTarget/NodeSelect.jsx
  src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/TemplateRule/MonitoringTarget/WorkloadSelect.jsx
  src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/TemplateRule/MonitoringTarget/index.jsx
  src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/TemplateRule/MonitoringTarget/index.scss
  src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/TemplateRule/NodeRule.jsx
  src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/TemplateRule/NodeSelector/index.jsx
  src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/TemplateRule/RuleInput/index.jsx
  src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/TemplateRule/RuleInput/index.scss
  src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/TemplateRule/WorkloadRule.jsx
  src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/TemplateRule/index.jsx
  src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/TemplateRule/index.scss
  src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/index.jsx
  src/components/Forms/AlertingPolicy/AlertingRules/AddRuleForm/index.scss
  src/components/Forms/AlertingPolicy/AlertingRules/RuleList/Card/index.jsx
  src/components/Forms/AlertingPolicy/AlertingRules/RuleList/Card/index.scss
  src/components/Forms/AlertingPolicy/AlertingRules/RuleList/index.jsx
  src/components/Forms/AlertingPolicy/AlertingRules/RuleList/index.scss
  src/components/Forms/AlertingPolicy/AlertingRules/index.jsx
Labels: lgtm, approved, size/XXL, release-note-none

#4147 fix: Add rule monitor modal
  src/actions/alerting.js
  src/components/Modals/Monitoring/AlertMonitoring/index.jsx
  src/components/Modals/Monitoring/AlertMonitoring/index.scss
Labels: size/L, lgtm, approved, release-note-none

#4148 fix: Add rule reset modal
  locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-details.js
  locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
  locales/zh/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-details.js
  locales/zh/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
  src/actions/alerting.js
  src/pages/projects/components/Modals/AlertingConfirm/index.jsx
  src/pages/projects/components/Modals/AlertingConfirm/index.scss
  src/pages/projects/containers/Alerting/Messages/index.jsx
Labels: size/L, lgtm, approved, release-note-none, kind/require-ui-text-review

#4149 feat: add devops locale
  locales/en/l10n-devopsProjects-pipeline-details.js
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#4151 fix: Fix devops and pipiline check api (#1430)
  src/components/Forms/Pipelines/BaseInfo/index.jsx
  src/pages/devops/version
  src/stores/devops.js
  src/stores/devops/pipelines.js
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#4144 docs: Add the USE_IMAGE_DEFAULT_PORTS word
  locales/en/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
  yarn.lock
Labels: size/L, lgtm, approved, kind/documentation, release-note-none, kind/require-ui-text-review

#4152 Update: update alerts
  locales/en/l10n-clusterManagement-baseicInformation.js
  locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-details.js
  locales/en/l10n-clusterManagement-monitoring&Alerting-alertingPolicies-list.js
Labels: size/XS, lgtm, approved, release-note-none
