Repository kubesphere/console, pull requests merged in 2024-10, with the labels that each got.

#4321 Correct and clarify potentially misleading terms in the license file
  LICENSE
Labels: size/XS, lgtm, approved, release-note-none

#4322 fix: displaying readme of markdown format in appTemplate
  packages/shared/src/components/Apps/Applications/DetailInfo/AppTemplate/index.tsx
Labels: size/XS, lgtm, approved, kind/bug, needs-ok-to-test, release-note

#4324 chore: remove system.min.js in codes
  .prettierignore
  packages/bootstrap/assets/system.min.js
  server/views/index.html
Labels: size/XS, lgtm, approved, release-note-none

#4323 ci: update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: lgtm, approved, release-note-none

#4326 chore: bump ESLint dependencies
  .github/PULL_REQUEST_TEMPLATE.md
  package.json
  yarn.lock
Labels: lgtm, approved, size/M, release-note-none
