Repository kubesphere/console, pull requests merged in 2024-12, with the labels that each got.

#4350 fix:correct spelling mistake
  server/proxy.js
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#4354 chore: validate email when editing basic information
  locales/en/l10n-logIn.js
  locales/es/l10n-logIn.js
  locales/tc/l10n-logIn.js
  locales/zh/l10n-logIn.js
  packages/console/src/pages/access/containers/Accounts/components/UserCreateModal/index.tsx
  packages/console/src/pages/access/containers/Accounts/components/UserEditModal/index.tsx
  packages/core/src/components/Layouts/Header/UserSetting/BasicInfo/index.tsx
Labels: lgtm, approved, size/S, kind/bug, release-note

#4357 feat:Support loading styles declared by extended components
  server/controllers/view.js
  server/services/extension.js
  server/views/index.html
Labels: size/XS, lgtm, approved, kind/feature, needs-ok-to-test, release-note

#4361 Update bookinfo version to 1.17.0
  server/sample/bookinfo.yaml
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#4359 feat: add version in image
  build/Dockerfile
  hack/docker_build_multiarch.sh
  hack/update-licenses.sh
  hack/version.sh
Labels: lgtm, approved, size/M, kind/feature, release-note

#4364 style: format files
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/workflows/codeql-analysis.yml
  .github/workflows/issue_comment_webhook.yml
  .github/workflows/manually.yaml
  .github/workflows/nightly-builds.yml
  .github/workflows/release-drafter.yml
  CONTRIBUTING.md
  README.md
  cypress/fixtures/clusterroles.json
  docs/development-workflow.md
  docs/join-the-kubesphere-localization-project.md
  packages/console/tsconfig.json
  packages/shared/src/components/Apps/Applications/DetailInfo/AppTemplate/index.tsx
  packages/shared/tsconfig.json
  server/sample/bookinfo.yaml
Labels: size/L, lgtm, approved, release-note-none

#4369 ci: v3dist does not require CodeQL
  .github/workflows/codeql-analysis.yml
Labels: size/XS, lgtm, approved, release-note-none

#4375 fix(secret): update error handling in validateImageRegistrySecret to use response data
  packages/console/src/pages/clusters/components/SecretSettings/ImagerRegistry/index.tsx
  packages/console/src/pages/clusters/components/SecretSettings/ImagerRegistry/styles.ts
  packages/shared/src/stores/secret.ts
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#4377 fix: Fix the z-index of monitorController modal
  packages/shared/src/components/Base/Card/MonitorController/Modal/index.tsx
  packages/shared/src/components/TimeSelector/CustomRange.tsx
  packages/shared/src/components/TimeSelector/index.tsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#4379 chore: remove useless WorkspaceSelectorModal in packages/console
  packages/console/src/pages/workspaces/components/Modals/WorkspaceSelectorModal/index.tsx
  packages/console/src/pages/workspaces/components/Modals/WorkspaceSelectorModal/styles.ts
  packages/console/src/pages/workspaces/components/Modals/index.ts
Labels: size/L, lgtm, approved, kind/cleanup, release-note-none

#4381 fix: missing page param in useFetchProjectsByTypeInfiniteQuery
  packages/shared/src/components/ProjectLayout/ProjectsSelectorModal/hooks.ts
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#4383 fix: Update global variable handling in views to use decodeURIComponent
  server/controllers/view.js
  server/views/consolev3.html
  server/views/index.html
  server/views/terminal.html
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#4387 fix: add name rules when create yaml app
  packages/shared/src/components/Apps/AppCreate/CreateYamlApp/index.tsx
  packages/shared/src/constants/patterns.ts
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#4384 fix: Fix delete workspace with deleting project on workspace baseinfo page
  packages/console/src/pages/access/containers/Workspaces/index.tsx
  packages/shared/src/stores/workspace.ts
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#4394 fix: synchronize alias pattern with ksc
  packages/shared/src/constants/patterns.ts
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#4386 fix: fix missing introduction and image in app template
  packages/shared/src/components/Apps/AppInformation/AppInfo/index.tsx
  packages/shared/src/components/Apps/AppInformation/index.tsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#4404 feat: Add KubeSphere App Store usage guide
  locales/en/ent-appStore-list.js
  locales/es/ent-appStore-list.js
  locales/tc/ent-appStore-list.js
  locales/zh/ent-appStore-list.js
  packages/shared/src/components/Apps/AppsDashBoard/Card.tsx
  packages/shared/src/components/Apps/AppsDashBoard/UseGuide.tsx
  packages/shared/src/components/Apps/AppsDashBoard/index.tsx
Labels: size/L, lgtm, approved, release-note-none
