Repository kubesphere/console, pull requests merged in 2024-09, with the labels that each got.

#4281 Update OWNERS
  OWNERS
Labels: size/XS, release-note-none

#4282 fix: sync image to aliyuns repo
  .github/workflows/release.yml
  hack/docker_build_multiarch.sh
Labels: lgtm, approved, size/M, kind/documentation, release-note-none

#4280 fix: resourceStatus get podNums
  src/pages/projects/containers/Deployments/Detail/ResourceStatus/index.jsx
  yarn.lock
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#4295 ci: add workflow_dispatch trigger to main.yaml
  .github/workflows/main.yaml
Labels: size/XS, lgtm, approved, release-note-none

#4294 ci: add .github/workflows/sync-to-kse.yml
  .github/workflows/sync-to-kse.yml
Labels: lgtm, approved, size/M, release-note-none

#4296 fix: set initial value of isRemoteExtensionLoading to true
  packages/core/src/Pages.tsx
Labels: size/XS, lgtm, approved, release-note-none

#4297 ci: update .github/workflows/sync-to-kse.yml
  .github/workflows/sync-to-kse.yml
Labels: size/XS, lgtm, approved, release-note-none

#4298 ci: fix TARGET_BRANCH in .github/workflows/sync-to-kse.yml
  .github/workflows/sync-to-kse.yml
Labels: size/XS, lgtm, approved, release-note-none

#4299 fix: Fix devops bugs
  locales/en/custom.js
  locales/es/custom.js
  locales/tc/custom.js
  locales/zh/custom.js
  packages/console/src/pages/workspaces/containers/Devops/ClusterSelect.tsx
  packages/console/src/pages/workspaces/containers/Devops/index.tsx
  packages/core/src/components/GlobalStyles/index.tsx
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#4301 ci: add setup for Git in sync-to-kse.yml workflow
  .github/workflows/sync-to-kse.yml
Labels: lgtm, approved, release-note-none

#4303 fix: fix the issue of checking licenses in ks
  packages/bootstrap/webpack/webpack.base.conf.js
  packages/shared/src/components/Layouts/NavMenu/NavItem/index.tsx
  packages/shared/src/constants/env.ts
Labels: lgtm, approved, size/S, release-note-none

#4304 build: add KUBESPHERE_EDITION constant to config files
  packages/bootstrap/webpack/config.js
  packages/bootstrap/webpack/webpack.base.conf.js
  packages/bootstrap/webpack/webpack.dll.conf.js
Labels: lgtm, approved, size/S, release-note-none

#4305 sync images to huaweicloud
  .github/workflows/release.yml
Labels: size/S, kind/cleanup, release-note

#4306 fix: resourceStatus get podNums (#4280)
  src/pages/projects/containers/Deployments/Detail/ResourceStatus/index.jsx
  yarn.lock
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#4308 feat: Add KUBESPHERE_EDITION constants to globals config
  packages/core/src/run.tsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#4311 chore: remove useless API
  server/controllers/view.js
  server/services/session.js
Labels: lgtm, approved, size/M, kind/cleanup, release-note-none

#4312 chore: disable kapis/config.kubesphere.io/v1alpha2/configs/marketplace
  packages/core/src/stores/marketplace.ts
Labels: size/XS, lgtm, approved, kind/cleanup, release-note-none

#4307 add oci protocol to share/UrlInput
  packages/shared/src/components/UrlInput/index.tsx
Labels: size/XS, lgtm, approved, kind/feature, needs-ok-to-test, release-note

#4314 chore: improve page error messages
  server/controllers/view.js
Labels: size/XS, lgtm, approved, release-note-none

#4316 enhancement: application text adjust
  locales/en/l10n-projects-applicationWorkloads-apps-templateBasedApps-list.js
  locales/tc/l10n-projects-applicationWorkloads-apps-templateBasedApps-list.js
  locales/zh/l10n-projects-applicationWorkloads-apps-templateBasedApps-list.js
  packages/shared/src/components/Apps/Applications/index.tsx
Labels: lgtm, approved, size/S, release-note-none

#4317 fix: Filter clusters by status of ready in kubectl modal
  packages/shared/src/components/Modals/KubeCtl/index.tsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#4320 ci: remove aliyuncs image registry
  .github/workflows/release.yml
Labels: lgtm, approved
