Repository kubesphere/console, pull requests merged in 2024-11, with the labels that each got.

#4328 fix: role and member users issues in clusters / workspaces / projects
  packages/console/src/pages/clusters/containers/ClusterSetting/Members/index.tsx
  packages/console/src/pages/projects/containers/Members/index.tsx
  packages/console/src/pages/workspaces/containers/Members/index.tsx
  packages/shared/src/components/Roles/AuthorizedUsers/index.tsx
  packages/shared/src/components/index.ts
  packages/shared/src/stores/user.ts
  packages/shared/src/utils/table/hooks/useUrlSearchParamsStatus.ts
Labels: size/L, lgtm, approved, kind/bug, release-note-none

#4333 fix: remove workspace support remove projects
  locales/en/l10n-clusterManagement-clusterSettings-clusterVisibility.js
  locales/es/l10n-clusterManagement-clusterSettings-clusterVisibility.js
  locales/tc/l10n-clusterManagement-clusterSettings-clusterVisibility.js
  locales/zh/l10n-clusterManagement-clusterSettings-clusterVisibility.js
  packages/console/src/pages/access/containers/Workspaces/index.tsx
  packages/console/src/pages/access/containers/Workspaces/styles.ts
  packages/shared/src/components/Modals/DeleteConfirm/DeleteConfirm.tsx
  packages/shared/src/stores/workspace.ts
Labels: size/L, lgtm, approved, kind/bug, release-note

#4337 fix: v3Notify show error
  packages/core/src/components/Layouts/BaseLayout/index.tsx
Labels: size/XS, lgtm, approved, release-note

#4340 fix: clear authAuthorizeUrl cookie when redirecting to login
  server/controllers/session.js
  server/proxy.js
Labels: size/XS, lgtm, approved, kind/bug, release-note-none
