Repository kubesphere/console, pull requests merged in 2025-03, with the labels that each got.

#4495 fix: update username field handling in login confirmation
  packages/core/src/containers/Session/LoginConfirm/index.tsx
  server/services/session.js
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#4498 fix: refactor page router
  packages/core/package.json
  packages/core/src/Pages.tsx
Labels: size/L, lgtm, approved, kind/bug, release-note-none

#4500 fix: Fix page router
  packages/core/src/Pages.tsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#4502 fix: Fix wujie version
  packages/console/package.json
  packages/shared/package.json
  yarn.lock
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#4504 feat: add id to headings in Markdown component
  packages/shared/package.json
  packages/shared/src/components/Markdown/Markdown.tsx
  yarn.lock
Labels: lgtm, approved, size/M, kind/feature, release-note-none

#4506 feat: add customizable text for create button in DataTable component
  packages/shared/src/components/DataTable/TableEmpty/CreateButton.tsx
  packages/shared/src/components/DataTable/TableEmpty/index.tsx
Labels: lgtm, approved, size/S, release-note-none

#4512 refactor: improve pagination handling with new utility functions
  packages/shared/src/stores/base.ts
  packages/shared/src/stores/store.ts
  packages/shared/src/utils/request.helper.ts
Labels: lgtm, approved, size/M, release-note-none

#4514 chore: update node-fetch to version 2.6.7
  server/package.json
  yarn.lock
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#4519 chore: update qs package to version 6.10.3
  package.json
  yarn.lock
Labels: size/L, lgtm, approved, release-note-none

#4518 refactor: enhance pagination handling to calculate total page count and item count more effectively
  packages/shared/src/stores/base.ts
  packages/shared/src/stores/store.ts
  packages/shared/src/utils/request.helper.ts
Labels: lgtm, approved, size/M, release-note-none

#4522 fix: Adjust the workspace assignment logic in PlacementConfigForm to ensure the correct retrieval of patchWorkspaces names
  packages/shared/src/components/Apps/AppForms/AppBaseInfoForm/PlacementForm/ConfigForm/index.tsx
Labels: size/XS, lgtm, approved

#4531 ci: delete .github/workflows/codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: lgtm, approved, size/M, release-note-none

#4533 feat: implement error handling for 403 Forbidden responses and restructure session routes
  locales/en/l10n-errors.js
  locales/es/l10n-errors.js
  locales/tc/l10n-errors.js
  locales/zh/l10n-errors.js
  packages/bootstrap/assets/403.svg
  packages/bootstrap/assets/404.svg
  packages/core/src/Pages.tsx
  packages/core/src/components/Layouts/BaseLayout/index.tsx
  packages/core/src/containers/Errors/403/index.tsx
  packages/core/src/containers/Errors/403/styles.tsx
  packages/core/src/containers/Errors/routes.tsx
  packages/core/src/containers/Session/routes.tsx
  packages/core/src/utils/emitter.tsx
  packages/shared/src/constants/index.ts
  packages/shared/src/constants/pages.ts
  packages/shared/src/types/globals.ts
  packages/shared/src/utils/request.helper.ts
  packages/shared/src/utils/request.ts
Labels: size/L, lgtm, approved, release-note-none

#4539 fix: improve readability
  locales/en/l10n-errors.js
  locales/es/l10n-errors.js
  locales/tc/l10n-errors.js
  locales/zh/l10n-errors.js
Labels: size/XS, lgtm, approved, release-note-none

#4540 refactor: optimize imports in emitter utility by removing unused imports and adjusting import statements
  packages/core/src/utils/emitter.tsx
Labels: size/XS, lgtm, approved, release-note-none

#4544 fix: Update fetch storage class list api
  packages/console/src/components/EditQuotas/StorageResourceQuota/index.tsx
  packages/console/src/pages/clusters/stores/storageClass.ts
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#4546 refactor: replace 403 error page with ErrorLayout component for improved structure and maintainability
  packages/core/src/containers/Errors/403/index.tsx
  packages/core/src/containers/Errors/components/ErrorLayout/index.tsx
  packages/core/src/containers/Errors/components/ErrorLayout/styles.tsx
Labels: lgtm, approved, size/M, release-note-none

#4548 feat: add 404 error page
  locales/en/l10n-errors.js
  locales/es/l10n-errors.js
  locales/tc/l10n-errors.js
  locales/zh/l10n-errors.js
  packages/core/src/Pages.tsx
  packages/core/src/containers/Errors/404/index.tsx
Labels: lgtm, approved, size/M, release-note-none
