Repository kubesphere/console, pull requests merged in 2025-04, with the labels that each got.

#4552 refactor: replace ExtensionStatusState enum with EXTENSION_STATUS_STATE_MAP for improved consistency and readability
  packages/core/src/constants/extension.ts
  packages/core/src/containers/Extensions/Management/actions/index.ts
  packages/core/src/stores/extension.ts
Labels: lgtm, approved, size/M, release-note-none

#4558 refactor: rename and enhance UI state utility functions for clarity and consistency
  packages/shared/src/utils/uiState.ts
Labels: lgtm, approved, size/M, release-note-none

#4560 fix: rename refetch function for clarity in extension store
  packages/core/src/stores/extension.ts
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#4562 fix(app): app template fetch error
  packages/shared/src/hooks/useList/index.ts
Labels: size/XS, lgtm, approved

#4567 fix: Filter clusters by role binding existence in KubeConfig and KubeCtl modals
  packages/shared/src/components/Modals/KubeConfig/index.tsx
  packages/shared/src/components/Modals/KubeCtl/index.tsx
  packages/shared/src/stores/cluster/index.ts
Labels: size/XS, lgtm, approved, kind/bug, release-note-none
