Repository kubesphere/console, pull requests merged in 2025-05, with the labels that each got.

#4572 feat: export Button component from Base index for improved accessibility
  packages/shared/src/components/Base/Button/Copy/index.tsx
  packages/shared/src/components/Base/Button/Copy/styles.ts
  packages/shared/src/components/Base/Button/index.ts
  packages/shared/src/components/Base/index.ts
Labels: size/L, lgtm, approved, release-note-none

#4574 feat: enhance resource quota handling and add unit conversion utility
  packages/console/src/components/EditQuotas/utils.ts
Labels: lgtm, approved, size/M

#4578 fix: refetch project table after updating quotas
  packages/console/src/pages/workspaces/containers/Projects/index.tsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#4587 ci: reorganize lint scripts in package.json for clarity
  package.json
Labels: lgtm, approved, size/S, release-note-none

#4589 ci: update OWNERS
  OWNERS
Labels: size/XS, lgtm, approved

#4591 ci: update Node.js setup to use .nvmrc and enable yarn caching
  .github/workflows/kubed-bump.yml
  .github/workflows/license-headers.yml
  .github/workflows/lock-file-update.yml
  .github/workflows/npm-release-canary.yml
  .github/workflows/npm-release-next.yml
  .github/workflows/npm-release.yml
Labels: lgtm, approved, size/S, release-note-none

#4596 ci: enhance nvm setup in husky hooks for better Node.js version management
  .husky/post-checkout
  .husky/post-merge
Labels: lgtm, approved, size/S, release-note-none
