Repository kubesphere/console, pull requests merged in 2025-02, with the labels that each got.

#4465 refactor(container): replace Docker Hub and Harbor image search Node.js API with backend API
  server/controllers/api.js
  server/libs/request.base.js
  server/libs/request.js
  server/package.json
  server/routes.js
  yarn.lock
Labels: size/L, lgtm, approved, release-note-none

#4471 fix: Change cluster overview and base-info auth
  server/configs/config.yaml
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#4473 feat: Add notifications for job re-run operation
  locales/en/l10n-projects-applicationWorkloads-jobs-list.js
  locales/es/l10n-projects-applicationWorkloads-jobs-list.js
  locales/tc/l10n-projects-applicationWorkloads-jobs-list.js
  locales/zh/l10n-projects-applicationWorkloads-jobs-list.js
  packages/console/src/pages/clusters/containers/ApplicationWorkloads/Jobs/Job/index.tsx
  packages/console/src/pages/clusters/containers/Workload/Jobs/index.tsx
  packages/console/src/pages/projects/containers/ApplicationWorkloads/Jobs/Job/Detail/index.tsx
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#4475 fix: pod remove ownerkind parameter
  packages/shared/src/components/PodsCard/utils.ts
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#4476 feat: Add notifications for job re-run operation
  locales/en/l10n-projects-applicationWorkloads-jobs-list.js
  locales/es/l10n-projects-applicationWorkloads-jobs-list.js
  locales/tc/l10n-projects-applicationWorkloads-jobs-list.js
  locales/zh/l10n-projects-applicationWorkloads-jobs-list.js
  packages/console/src/pages/clusters/containers/ApplicationWorkloads/Jobs/Job/index.tsx
  packages/console/src/pages/clusters/containers/Workload/Jobs/index.tsx
  packages/console/src/pages/projects/containers/ApplicationWorkloads/Jobs/Job/Detail/index.tsx
Labels: lgtm, approved, size/M

#4481 refactor: optimize the WebSocket of InstallPlan on the extension detail page
  packages/core/src/containers/Extensions/Management/Detail/index.tsx
Labels: lgtm, approved, size/M, kind/bug, release-note-none

#4483 feat: Add new localization strings for login confirmation screen
  locales/en/l10n-logIn.js
  locales/es/l10n-logIn.js
  locales/tc/l10n-logIn.js
  locales/zh/l10n-logIn.js
  packages/core/src/containers/Session/LoginConfirm/index.tsx
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#4486 refactor: Simplify OAuth login redirect handling
  server/controllers/session.js
Labels: size/XS, lgtm, approved

#4352 fix: solve client api request that can't handle 302 redirects
  server/middlewares/checkToken.js
  server/middlewares/proxy.js
Labels: size/XS, lgtm, approved, kind/bug, needs-ok-to-test, release-note

#4342 adjust app-releases button permission
  packages/shared/src/components/Apps/Applications/DetailInfo/index.tsx
Labels: size/XS, lgtm, approved, kind/bug, needs-ok-to-test, release-note
