Repository kubesphere/console, pull requests merged in 2025-01, with the labels that each got.

#4406 fix: add rule on app category name to match backend rule
  locales/en/l10n-appStoreManagement-appCategories-list.js
  locales/es/l10n-appStoreManagement-appCategories-list.js
  locales/tc/l10n-appStoreManagement-appCategories-list.js
  locales/zh/l10n-appStoreManagement-appCategories-list.js
  packages/shared/src/constants/patterns.ts
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#4407 feat: add formdata version of creating helm app
  packages/shared/src/components/Apps/AppCreate/CreateHelmApp/index.tsx
  packages/shared/src/components/Apps/AppCreate/index.tsx
  packages/shared/src/components/Apps/PackageUpload/index.tsx
  packages/shared/src/stores/openpitrix/app.ts
  packages/shared/src/stores/openpitrix/files.ts
  packages/shared/src/stores/openpitrix/version.ts
  packages/shared/src/utils/apps.ts
Labels: size/L, lgtm, approved, kind/feature, release-note-none

#4411 fix: remove footer display option from LoginHistory component
  packages/console/src/pages/access/containers/Accounts/Detail/components/LoginHistory/index.tsx
Labels: size/XS, lgtm, approved, release-note-none

#4415 chore: sync codes
  packages/core/src/containers/Extensions/Management/components/ResetDefaultConfigTip/ResetDefaultConfigConfirmModal.tsx
  packages/shared/src/components/Modals/Confirm/ConfirmModal.constants.ts
  packages/shared/src/components/Modals/Confirm/ConfirmModal.helpers.tsx
  packages/shared/src/components/Modals/Confirm/ConfirmModal.styles.ts
  packages/shared/src/components/Modals/Confirm/ConfirmModal.tsx
  packages/shared/src/components/Modals/Confirm/ConfirmModal.types.ts
  packages/shared/src/components/Modals/Confirm/index.ts
  packages/shared/src/components/index.ts
Labels: size/L, lgtm, approved, release-note-none

#4419 refactor: refactor extensions management using DataTable
  packages/core/package.json
  packages/core/src/components/GlobalStyles/index.tsx
  packages/core/src/containers/Extensions/Management/components/Extensions/Extensions.styles.ts
  packages/core/src/containers/Extensions/Management/components/Extensions/Extensions.tsx
  packages/core/src/containers/Extensions/Management/components/Extensions/ExtensionsEmpty.styles.ts
  packages/core/src/containers/Extensions/Management/components/Extensions/ExtensionsEmpty.tsx
  packages/core/src/containers/Extensions/Management/constants/index.ts
  packages/core/src/containers/Extensions/components/ExtensionsEmpty/ExtensionsEmpty.tsx
Labels: size/L, lgtm, approved, release-note-none

#4423 feat: enhance useUrlSearchParamsStatus hook with reset pageIndex when columnFilters has changed
  packages/shared/src/utils/table/hooks/useUrlSearchParamsStatus.ts
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#4428 refactor: the WebSocket logic in the details page of the expansion center
  packages/core/src/containers/Extensions/Management/Detail/index.tsx
  packages/core/src/stores/extension.ts
Labels: lgtm, approved, size/M, release-note-none

#4430 chore: update version api url (#5539)
  server/services/session.js
Labels: size/XS, lgtm, approved, release-note-none

#4439 fix: the description of the role uses data from the API
  packages/shared/src/stores/role.ts
Labels: lgtm, approved, size/S, kind/bug, release-note-none

#4442 fix(app): add version name ordering in app version lists
  packages/shared/src/components/Apps/AppForms/AppBaseInfoForm/BasicInfoForm/index.tsx
  packages/shared/src/components/Apps/AppVersionSelector/index.tsx
Labels: lgtm, approved, size/S, release-note-none

#4438 fix: temporary fix for PropertiesInput focus loss problem
  packages/shared/src/components/Inputs/PropertiesInput/index.tsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#4441 fix: add create yaml app description input max length
  packages/shared/src/components/Apps/AppCreate/CreateYamlApp/index.tsx
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#4448 fix: Update fillEmptyMetrics rules
  packages/shared/src/utils/monitoring.ts
Labels: size/XS, lgtm, approved, kind/bug, release-note-none

#4446 fix: Fix the edit manager permission on create workspace
  packages/console/src/pages/workspaces/components/WorkspaceBasicInfoForm/WorkspaceBasicInfoForm.styles.ts
  packages/console/src/pages/workspaces/components/WorkspaceBasicInfoForm/WorkspaceManagerField.tsx
Labels: lgtm, approved, size/S

#4453 fix(UseGuid): update Card and UseGuide components layout
  packages/shared/src/components/Apps/AppsDashBoard/Card.tsx
  packages/shared/src/components/Apps/AppsDashBoard/UseGuide.tsx
Labels: lgtm, approved

#4454 fix(node): update logout handling to redirect instead of returning URL by OIDC
  server/controllers/session.js
Labels: size/XS, lgtm, approved, release-note-none

#4458 chore: improve npm scripts
  package.json
Labels: size/XS, lgtm, approved, release-note-none
